- runtime/include/tt/runtime/detail/ttnn.h
**Implemented**
- Simple patch to build runtime and avoid errors building with clang-17
> Patch applied to ignore pessimizing-move and build runtime successfully

- runtime/lib/ttnn/program.cpp
This code change introduces a TTNN::Add operation switch within the TTNN program handling. It appears this functionality was missed during the initial project setup. This will enable us to execute the end-to-end demo for add op.
Solves https://github.com/tenstorrent/tt-mlir/issues/126
> Adding a support for ttnn::add op in a runtime

- include/ttmlir/Dialect/TTNN/Transforms/TTNNToSerializedBinary.h
- lib/Dialect/TTNN/Transforms/CMakeLists.txt
- lib/Dialect/TTNN/Transforms/TTNNToSerializedBinary.cpp
Exposing flatbuffer generation API from tt-mlir lib. Aligning things with how we plan to generate plain C++, TTNNToCpp, hence this change consists of:
- Renaming SerialzedBinary.cpp -> TTNNToSerializedBinary.cpp
- Creating API function in a new header file: TTNNToSerializedBinary.h(`std::shared_ptr<void> emitTTNNAsFlatbuffer(...)`)
- Implementing API function at the end of  TTNNToSerializedBinary.cpp:
```
std::shared_ptr<void> emitTTNNAsFlatbuffer(OwningOpRef<ModuleOp> &moduleOp) {
auto pm = PassManager::on<ModuleOp>(moduleOp.get().getContext());
auto pass = createTTNNSerializeToBinary();
Pass* basePass = pass.get();
pm.addPass(std::move(pass));
// Run the pass manager.
if (failed(pm.run(moduleOp.get())))
{
return nullptr;
}
auto *derivedPass= …
```
> Workarounding flatbuffer generation API

- .github/check-spdx.yaml
- .pre-commit-config.yaml
- include/ttmlir-c/Dialects.h
**Implemented**:
- Added SPDX config to `pre-commit`. No more failed builds with a small incremental update! 
- License configuration file stored in `.github/check-spdx.yaml`
> Added pre-commit hook to check for SPDX, applies if missing

- .github/actions/build_toolchain/action.yml
- .github/workflows/build.yml
- env/CMakeLists.txt
- moved ttmlir-toolchain build to separate action
- build ttmlir-toolchain only if files in env/ are changed or there is no cache
- Add ccache to build
- Ccache folder will be cached between pipeline runs
- Moved dependency versions to variables
Note:
Github can access the cache from "parent" branches, but not the other way around. This means that we will sometimes get one more full build, for example if we make a change in a branch to update the flatbuffer version we will have full build for branch, and again full build for main after merging. This is just how Github works
Closes: #36
Closes: #51
> Improve CI build time

- docs/src/adding-an-op.md
- include/ttmlir/CMakeLists.txt
- include/ttmlir/Conversion/CMakeLists.txt
- include/ttmlir/Conversion/Passes.h
- include/ttmlir/Conversion/Passes.td
- include/ttmlir/Conversion/TTNNToEmitC/TTNNToEmitC.h
- include/ttmlir/Dialect/TTNN/Passes.td
- lib/CMakeLists.txt
- lib/Conversion/CMakeLists.txt
- lib/Conversion/PassDetail.h
- lib/Conversion/TTNNToEmitC/CMakeLists.txt
- lib/Conversion/TTNNToEmitC/PopulatePatterns.h
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Conversion/TTNNToEmitC/TypeConverter.h
- lib/Dialect/TTNN/Transforms/CMakeLists.txt
- lib/Dialect/TTNN/Transforms/TTNNToCpp.cpp
- lib/Dialect/TTNN/Transforms/TTNNToSerializedBinary.cpp
- lib/RegisterAll.cpp
- tools/ttmlir-opt/CMakeLists.txt
Details:
- Convert TTNN to EmitC dialect via dialect conversion API (#94)
- Structure set following [torch-mlir](https://github.com/llvm/torch-mlir/tree/main) approach
- `TTNNToCpp.cpp` stills exists as I didn't want to break existing tests/pipelines (used to embed cpp into flatbuffer), but it should be removed in the near future
To run, we first generate an IR in EmitC dialect, dump it to disk, and read back with `ttmlir-translate` tool to covert to actual cpp code:
```bash
./build/bin/ttmlir-opt --ttir-layout --ttnn-open-device --convert-ttir-to-ttnn --convert-ttnn-to-emitc test/ttmlir/Dialect/TTNN/simple_multiply.mlir -o c.mlir
./build/bin/ttmlir-translate -mlir-to-cpp c.mlir -allow-unregistered-dialect
```
TODO: Add these commands to docs (#147)
> Change ttnn->emitc transform to use dialect conversion API

- docs/src/SUMMARY.md
- docs/src/ttmlir-translate.md
- Add `ttmlir-translate` docs with cpp gen example (#147)
> Add `ttmlir-translate` docs and cpp gen example

- lib/Dialect/TTIR/Transforms/Passes.cpp
- test/ttmlir/Dialect/TTNN/multiple_add_with_loc.mlir
- Fix scenario where more than one result is returned from func::FuncOp.
- Add test with multiple returns and with some location data to start POC work on leveraging it.
> [GridSetPass] Fix handling of FuncOp with multiple results.

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Target/TTNN/program.fbs
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTIR/Transforms/Passes.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Dialect/TTNN/Transforms/Passes.cpp
- lib/Dialect/TTNN/Transforms/TTNNToSerializedBinary.cpp
- runtime/include/tt/runtime/detail/ttnn.h
- runtime/lib/ttnn/program.cpp
- test/ttmlir/Dialect/TTNN/softmax/simple_softmax.mlir
- test/ttmlir/Dialect/TTNN/softmax/softmax_negative_1.mlir
- test/ttmlir/Dialect/TTNN/softmax/softmax_negative_2.mlir
- Added e2e support for softmax op in MLIR.
- Added simple positive and negative test cases for softmax op.
Solves: https://github.com/tenstorrent/tt-mlir/issues/80 and https://github.com/tenstorrent/tt-mlir/issues/81
> Adding softmax op in MLIR e2e

- runtime/CMakeLists.txt
- runtime/test/CMakeLists.txt
- runtime/test/ttnn/CMakeLists.txt
- runtime/test/ttnn/hello_test.cc
- runtime/test/ttnn/test_subtract.cpp
- third_party/CMakeLists.txt
#102 
Added a prototype of runtime gtest infra. Parent `CMakeLists.txt` under `runtime/test` defines a function that can be used to add tests. Subdirectories include `runtime/test/ttmetal` and `runtime/test/ttnn`. `runtime/test` is guarded by a cmake flag `-DTTMLIR_ENABLE_RUNTIME_TESTS`, and will only be built if `-DTTMLIR_ENABLE_RUNTIME_TESTS=ON`.
Added an example test `test_subtract.cpp` under `runtime/test/ttnn`. Currently using an environment variable to receive the flatbuffer path which isn't the most ideal, any suggestions are appreciated to improve the flow. Presumably we could have some directory that contains flatbuffers for these tests, and update/regenerate these flatbuffers once the compiler version is newer.
To run all tests:
```
cd build/runtime/test …
```
> Runtime gtest infrastructure

- include/ttmlir/Dialect/TTIR/Analysis/GridAnalysis.h
- include/ttmlir/Dialect/TTIR/Analysis/TTIRAnalysis.h
- include/ttmlir/Dialect/TTIR/Passes.td
- include/ttmlir/Dialect/TTNN/Passes.h
- lib/Dialect/TTIR/Analysis/GridAnalysis.cpp
- lib/Dialect/TTIR/Transforms/Passes.cpp
- lib/Dialect/TTNN/Transforms/Passes.cpp
- test/ttmlir/Dialect/TTNN/multiple_add_with_loc_grid_override.mlir
Introduce per of grid size overrides. Extend analysis with basic override support. POC for:
- Pass level overrides
- Per op overrides
- Location info usage
- Non-scalar option type with custom parser for llvm command line support
https://github.com/tenstorrent/tt-mlir/issues/208
> [Optimizer] Per op grid overrides.

- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- python/TTModule.cpp
Initial implementation of stride calculation from the logical shape and the `LayoutAttr`. The strides of the tensors are stored in the Flatbuffer and are used by FE to allocate the tensors.
Needed for E2E scenario (issues: #19 #68)
> [tensor-layout] implements LayoutAttr::getStride()

- docs/CMakeLists.txt
- docs/src/build.md
It looks like the `cp -r` command behaves differently on linux vs macOS.
`cp -r dir/ new_dir/` will copy contents of the `dir/` into `new_dir/` on macOS, but on Linux, it will copy the directory, so you would end up with `new_dir/dir/`.
Hence, changing the command to be:
`cp -r dir/* new_dir/` which works the same on both platforms.
Updating the docs for building docs as well.
> [docs] fix build on linux

- docs/src/adding-an-op.md
- include/ttmlir/Conversion/Passes.h
- include/ttmlir/Conversion/Passes.td
- include/ttmlir/Conversion/TTIRToTTNN/TTIRToTTNN.h
- include/ttmlir/Dialect/TTNN/Transforms/Passes.td
- lib/Conversion/CMakeLists.txt
- lib/Conversion/PassDetail.h
- lib/Conversion/TTIRToTTNN/CMakeLists.txt
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTIRToTTNN/TTIRToTTNNPass.cpp
- lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
- lib/Dialect/TTNN/Transforms/CMakeLists.txt
- lib/Dialect/TTNN/Transforms/Passes.cpp
Details:
* Refactor ttir -> ttnn pass to use the dialect conversion API (#177)
* Structure following [llvm conversion passes](https://github.com/llvm/llvm-project/tree/main/mlir/lib/Conversion)
This leaves the repo in an inconsistent state since the current ttnn->emitc conversion pass follows torch-mlir structure.
Next steps:
* Refactor common conversion pass files from torch approach to llvm
* Refactor ttnn -> emitc to llvm approach
* Add tests
> Change ttir -> ttnn to use dialect conversion API

- include/ttmlir/Dialect/TTIR/IR/TTIROpsInterfaces.td
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Dialect/TTIR/Transforms/Passes.cpp
Align TTIR dialect base op interface naming with other major dialects. Walking TTIR ops within OpModule example:
`    module_op->walk([&](TTIROp op) {
op->dump();
});`
> [Misc] Rename TTIR op interface to TTIROp.

- include/ttmlir/Conversion/Passes.h
- include/ttmlir/Conversion/Passes.td
- include/ttmlir/Conversion/TosaToTTIR/TosaToTTIR.h
- include/ttmlir/Dialect/TTIR/Transforms/Passes.td
- lib/CMakeLists.txt
- lib/Conversion/CMakeLists.txt
- lib/Conversion/PassDetail.h
- lib/Conversion/TTIRToTTNN/TTIRToTTNNPass.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Conversion/TosaToTTIR/CMakeLists.txt
- lib/Conversion/TosaToTTIR/TosaToTTIR.cpp
- lib/Dialect/TTIR/Transforms/Passes.cpp
- lib/Dialect/TTNN/Transforms/CMakeLists.txt
- test/ttmlir/Dialect/TTIR/tosa_to_ttir_multiply.mlir
- tools/ttmlir-opt/CMakeLists.txt
Fixes #178
Added conversion lib that implements conversion from TOSA to TTIR. Did not add new coverage of TOSA ops, it still supports only add, mul, sub, geq ops. Type conversion is still a no-op.
Removed old conversion.
Added MLIRTTConversions lib that links all conversion libs and is linked against TTMLIR.
> Change TOSA->TTIR to use dialect conversion API

- lib/Conversion/TTIRToTTNN/CMakeLists.txt
- lib/Conversion/TTNNToEmitC/CMakeLists.txt
- lib/Conversion/TosaToTTIR/CMakeLists.txt
We should only ever link against `MLIR`, `LLVM`, or `MLIR-C`, any other libs with a suffix will match against a static MLIR library and can lead to weird linker errors like the Mac build was seeing.
FYI @mmanzoorTT, audit your branch for places where we might be accidentally linking against a static library, because the error message looked nearly identical to the one you're seeing on your llvm upgrade branch:
```
LLVM ERROR: can't create Attribute 'mlir::DenseArrayAttr' because storage uniquer isn't initialized: the dialect was likely not loaded, or the attribute wasn't added with addAttributes<...>() in the Dialect::initialize() method.          
```
> Fix mac build; link against MLIR dylib

- .github/actions/build-toolchain/action.yml
- .github/workflows/build.yml
Fixes CI build errors to do with stale ccache files against mismatched macOS SDK 
e.g. error:
```
/Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/include/c++/v1/__memory/unique_ptr.h:191:3: error: non-static data member cannot be constexpr; did you intend to make it const?
_LIBCPP_CONSTEXPR unique_ptr(nullptr_t) _NOEXCEPT : __ptr_(__value_init_tag(), __value_init_tag()) {}
^
/Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/include/c++/v1/__config:612:31: note: expanded from macro '_LIBCPP_CONSTEXPR'
```
> embed sdk in ccache

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- test/ttmlir/Dialect/TTNN/softmax/simple_softmax.mlir
- test/ttmlir/Dialect/TTNN/softmax/softmax_negative_1.mlir
- test/ttmlir/Dialect/TTNN/softmax/softmax_negative_2.mlir
Softmax op is updated to use a signed version of the I32 attribute to support positive and negative dimension attributes.
Solves: https://github.com/tenstorrent/tt-mlir/issues/240
> Update Softmax op to use signed version of I32 attribute for dimension

- runtime/tools/python/ttrt/common/api.py
If there's a host side crash or exception there is some device cleanup / shutdown that doesn't automatically happen and will leave the device in a hung state for the next run.
This change registers an atexit handler so that in most situations a host side crash will not result in a hung device.
> Always close backend device before program exit

- env/CMakeLists.txt
- include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
- lib/CAPI/CMakeLists.txt
- lib/CAPI/TTAttrs.cpp
- lib/CAPI/TTKernelTypes.cpp
- lib/CAPI/TTTypes.cpp
- lib/Conversion/TosaToTTIR/TosaToTTIR.cpp
- lib/Dialect/TT/IR/TTDialect.cpp
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- lib/Dialect/TTIR/Analysis/LegalGridAnalysis.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTIR/Transforms/Passes.cpp
- lib/Dialect/TTKernel/IR/TTKernelOps.cpp
- lib/Dialect/TTMetal/IR/TTMetalOps.cpp
- lib/Dialect/TTMetal/Transforms/KernelsToCpp.cpp
- lib/Dialect/TTMetal/Transforms/Passes.cpp
- lib/Dialect/TTMetal/Transforms/SerializeToBinary.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Dialect/TTNN/Transforms/Passes.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- python/CMakeLists.txt
- python/TTKernelModule.cpp
- python/TTModule.cpp
1. Update LLVM version to match xla
2. Add required patches for xla
3. Modify the deprecated calls
> Update LLVM to match xla

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Target/TTNN/program.fbs
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Dialect/TTIR/Transforms/Passes.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/lib/ttnn/program.cpp
- test/ttmlir/Dialect/TTNN/simple_avg.mlir
Solves #243. Implement avg reduction through TTIR, TTNN dialects and generate flat buffers. Add mapping between dialects for avg op.Add simple_avg.mlir test.
> Implement reduction avg op end to end

- runtime/include/tt/runtime/detail/ttnn.h
- runtime/include/ttnn/runtime/utils.h
- runtime/lib/binary.cpp
- runtime/lib/ttnn/CMakeLists.txt
- runtime/lib/ttnn/program.cpp
- runtime/lib/ttnn/runtime.cpp
- runtime/lib/ttnn/utils.h
#92 
Make toMemoryConfigOp more general, update to use ttnn apis instead of low level metal APIs.
> Refactor toMemoryConfigOp

- include/ttmlir/Target/TTMetal/binary.fbs
- lib/Dialect/TTMetal/Transforms/SerializeToBinary.cpp
- runtime/include/tt/runtime/detail/ttmetal.h
- runtime/lib/binary.cpp
- runtime/lib/runtime.cpp
- runtime/lib/ttmetal/command_queue.cpp
- runtime/lib/ttmetal/runtime.cpp
- runtime/lib/ttnn/runtime.cpp
- runtime/tools/python/ttrt/common/api.py
- runtime/tools/python/ttrt/runtime/__init__.py
- runtime/tools/python/ttrt/runtime/module.cpp
- Make inputs per-device (multi-device inputs still need to be worked out)
- Create common functions for creating metal Buffers and CoreRange from flatbuffer types
- Implement wait API + events, update ttrt to use it
- Bug fix logical_grid_size -> compute_with_storage_grid_size, the latter accurately gives post-harvested shape
- Automatically move inputs / outputs during submit
> Additional fixes to metal runtime bootstrap #290

- include/ttmlir/Dialect/TT/IR/TTOpsTypes.h
- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTIR/IR/TTIROpsInterfaces.td
- include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
- include/ttmlir/Utils.h
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTIR/Transforms/Passes.cpp
- lib/Dialect/TTMetal/Transforms/Passes.cpp
- lib/Dialect/TTMetal/Transforms/SerializeToBinary.cpp
- test/ttmlir/Dialect/TTIR/test_allocate.mlir
- test/ttmlir/Dialect/TTMetal/simple_multiply.mlir
- test/ttmlir/Dialect/TTMetal/to_layout.mlir
- Enforce the Noc/DRAM/PCIE alignment requirements taken from the system
descriptor on the allocator.
- Annotate function arguments with new attribute "argument_allocations"
with info about where inputs are allocated.
> Feed HW alignment requirements from system desc into allocator

- runtime/include/tt/runtime/detail/ttnn.h
- runtime/tools/python/ttrt/__init__.py
- runtime/tools/python/ttrt/common/api.py
- New tensor initialization functions, for certain kinds of tests it's useful to initialize with a range of values vs random.  In the future we could add more like uniform distribution.
- Some tests, like for data movement, can be implemented to perform a trivial golden check where the input exactly matches the output. Add an identity flag which does this check.
> ttrt add support for initialization function + ident check

- include/ttmlir/Dialect/TT/IR/TTOpsTypes.h
- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- lib/CAPI/TTTypes.cpp
- lib/Dialect/TT/IR/TTDialect.cpp
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- lib/Dialect/TTIR/Transforms/Passes.cpp
- python/TTModule.cpp
- test/python/tensor_layout.py
Previously it was:
!tt.tile<32 x 32, bfp8_b>
There was an awkward space between the `x` because of the way we can legally write the assembly syntax.
Now it uses the same DimensionList custom parser as all other shape types so we have:
!tt.tile<32x32, bfp8_b>
> Change !tt.tile shape encoding to be consistent with other shape

- runtime/include/tt/runtime/types.h
- runtime/lib/runtime.cpp
- runtime/lib/ttmetal/runtime.cpp
- runtime/lib/ttnn/runtime.cpp
Runtime data structures now require an associated runtime when created, which will be strictly checked when the type-erased data pointer is casted.
> Prohibit runtime mixing

- include/ttmlir/Dialect/TTKernel/IR/TTKernelOpsTypes.td
- include/ttmlir/Target/Common/types.fbs
- lib/Dialect/TTMetal/Transforms/SerializeToBinary.cpp
- runtime/lib/ttmetal/command_queue.cpp
These attributes are needed by ttnn generic and direct to metal
> Add page_size and num_buffers attributes to CBDesc

- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Target/TTNN/program.fbs
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/lib/ttnn/program.cpp
- runtime/lib/ttnn/utils.h
- test/ttmlir/Dialect/TTNN/simple_ge.mlir
- test/ttmlir/Dialect/TTNN/simple_mean.mlir
- test/ttmlir/Dialect/TTNN/simple_multiply.mlir
- test/ttmlir/Dialect/TTNN/simple_relu.mlir
- test/ttmlir/Dialect/TTNN/simple_subtract.mlir
- test/ttmlir/Dialect/TTNN/simple_sum.mlir
- test/ttmlir/Dialect/TTNN/softmax/simple_softmax.mlir
- test/ttmlir/Dialect/TTNN/ttir_to_ttnn_pipeline.mlir
- test/ttmlir/Dialect/TTNN/ttir_to_ttnn_pipeline_custom_opt.mlir
- test/ttmlir/Silicon/TTNN/simple_eltwise.mlir
- test/ttmlir/Silicon/TTNN/simple_ge.mlir
- test/ttmlir/Silicon/TTNN/simple_multiply.mlir
- test/ttmlir/Silicon/TTNN/simple_relu.mlir
- test/ttmlir/Silicon/TTNN/simple_subtract.mlir
- test/ttmlir/Silicon/TTNN/simple_sum.mlir
- Add `ttnn.emptyOp` to match TTNN lib API
- Update tests to expect `ttnn.empty()` instead of `ttnn.full()` when converting from `tensor.empty()`
Resolves #373
> Add ttnn.emptyOp

- test/CMakeLists.txt
- Fixes issue where `cmake --build build -- check-ttmlir` would fail on a clean build, as `ttmlir-translate` wouldn't be compiled
> Add ttmlir-translate to check-ttmlir target

- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Target/Common/types.fbs
- include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
- lib/CAPI/TTAttrs.cpp
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- python/TTModule.cpp
- runtime/lib/common/system_desc.cpp
- test/ttmlir/Dialect/TTIR/test_allocate.mlir
- test/ttmlir/Dialect/TTNN/simple_mean.mlir
Closes #264
First TTMLIR PR finally, hooray.
from commit desc:
- Originally was going to have logical to phyical cores by type, but after some discussion, storing physical cores only, by type under ChipDesc
- Create TT_CoreCoordAttr layer w/ Y,X members to make printing nicer and in the format [(1, 2), (2, 3)] for 2 core coordinates.
Tested with below commands:
```
% ttrt query --save-artifacts --system-desc // Looked at system desc, looks good
%  ./build/bin/ttmlir-opt --ttir-to-ttnn-backend-pipeline --ttir-load-system-desc="path=./ttrt-artifacts/system_desc.ttsys" test/ttmlir/Dialect/TTNN/simple_subtract.mlir
#l1_ = #tt.memory_space<l1>
#system = #tt.memory_space<system>
#layout = #tt.layout<(d0, d1) -> (d0, d1), undef, <1x1>, memref<64x128xf32, #system>>
#layout1 = #tt.layout<(d0, d1) …
```
> Update SystemDesc's ChipDesc to have Worker, Dram, Eth physical core list

- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Dialect/TTKernel/IR/TTKernelOpsTypes.td
- lib/Dialect/TT/IR/TTOpsTypes.cpp
Until we have system desc slicing #113, by default the compiler will only construct a `DeviceAttr` that observes the first chip on the system to enable running on n300.
Once we have system desc slicing, we can change it back, and the user will have to explicitly generate a system desc that partitions out a single device.
> Workaround multi-device system descs by only observing the first device

- include/ttmlir/Dialect/TT/IR/TTOpsEnums.td
- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- lib/Dialect/TTNN/Transforms/Passes.cpp
#380 #388
Handle NONE type chip capability, dump chip channel when translating flatbuffer to mlir
> Fix for n300 system descriptor

- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
Closes #411 - sorry for (not so obvious) breakage that would affect users on N150 machines.
Make SystemDesc's eth and eth_inactive core list optional
- Empty eth core list happens on N150, this solves MLIR parser issue introduced on 8/15 commit d187e56
- Removes ", eth = []" entirely from MLIR when list is empty, took inspiration from chipChannels existing optional param.
==
Testing:
-  Solved issue for me locally on N300 (when I hacked eth and eth_inactive to become empty).  I left worker and dram cores as not optional.
Folks who are blocked by this plz cherry-pick b7c920d562 and recompile and regenerate systemdesc for your N150 (`ttrt query --save-artifacts`)
> Make SystemDesc's eth and eth_inactive core list optional (solves N150 MLIR parsing fail introduced today)

- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTIR/Transforms/Passes.td
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTIR/Transforms/Passes.cpp
- test/ttmlir/Dialect/TTIR/split_compound_layout.mlir
This graph pass breaks up compound to_layout ops into constituent pieces. In TTIR, to_layout can do any of the following all at once:
- Change dataformat (including to/from tile or different tile types)
- Change memory space
- Change linear affine map
- Change grid shape
Going to TTMetal dialect, we need a pass that breaks these compound to_layout ops into successive to_layout ops such that each one only does a single task. There will be opportunity in the future to merge back particular patterns, but that's an optimization for a follow on change.
> Split compound layout pass #356

- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
Removing commas from `assemblyFormat` so that the parsing of multiple optional groups works.
It seems that there isn't great support for this kind of parsing in mlir...
> fix parsing of `ChipPhysicalCoresAttr`

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Target/TTNN/program.fbs
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/lib/ttnn/program.cpp
- test/ttmlir/Dialect/TTNN/transpose/simple_transpose.mlir
- test/ttmlir/Dialect/TTNN/transpose/simple_transpose_8x16_reverse_dims.mlir
- test/ttmlir/Dialect/TTNN/transpose/simple_transpose_8x8.mlir
- test/ttmlir/Dialect/TTNN/transpose/simple_transpose_negative_dims.mlir
Renamed params in transpose op from (..., dimension1, dimension2) to (..., dimension0, dimension1) to make integration with tt-forge streamlined and to make naming in-line with PyTorch (https://pytorch.org/docs/stable/generated/torch.transpose.html)
https://github.com/tenstorrent/tt-forge/pull/41
> Renamed params in transpose op

- docs/src/ttmlir-translate.md
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitCPass.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- test/ttmlir/Dialect/TTNN/eltwise/operand_broadcasts.mlir
- tools/ttnn-standalone/ttnn-standalone.cpp
- `ttnn.to_memory_config` was implemented as a DPS op in TTNN dialect. However, actual `ttnn` implementation doesn't support this type of signature
- Fixed stale docs
- Opened #435 to follow up
> [TTNN Dialect] Convert ttnn.to_memory_config from DPS to non-DPS op

- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTIR/IR/TTIROpsInterfaces.td
- include/ttmlir/Dialect/TTIR/Transforms/Passes.td
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTIR/Transforms/Passes.cpp
- lib/Dialect/TTMetal/Transforms/Passes.cpp
- test/ttmlir/Dialect/TTMetal/simple_eltwise.mlir
Repurpose the existing --ttir-generic pass to pattern match against any ops that implement `GenericRegionOpInterface`.
Ops that implement the `GenericRegionOpInterface` must implement methods:
- `getIndexingMaps`: Return a pair of indexingMaps and iteratorTypes for the given GenericRegionOp.
- `buildGenericRegion`: Rewrite self into the generic region block using the arith and math dialects.
One of the other major differences in this change is to rewrite the generic region operands to be tensors with encoding `ShardLayout`. Previously they were just memrefs, but arith and math dialects cannot work with memref, tensor seemed like a sensible container, `ShardLayout` now holds the memref inside of it.
Here's an example of what this transformation does, given input:
```mlir
%1 = …
```
> Generic region pass

- include/ttmlir/Dialect/TT/IR/TTOpsEnums.td
- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- lib/Dialect/TTIR/Transforms/Passes.cpp
BufferAccess is a new attribute on BufferAttr that defines how tensor data is accessed by compute.  It currently can take 2 values:
- Alias: This buffer aliases a persistent Tensor L1 allocation directly. Implies that no datamovement occurs and the compute kernel just accesses the local allocation directly.
- Stream: This buffer is a temporary destination as a means to get remote data for local computation.  Remote data is most likely a tensor that is allocated in dram, but could also be data from a remote core.
> Add BufferAccess Attribute

- include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
- lib/Dialect/TTMetal/Transforms/KernelsToCpp.cpp
This also includes relevant setup HLK calls like:
- TileRegsAcquireOp
- TileRegsCommitOp
- TileRegsWaitOp
- TileRegsReleaseOp
- PackTileOp
- BinaryOpInitCommonOp
- AddTilesInitOp
- MulTilesInitOp
- AddTilesOp
- MulTilesOp
Also added support for lowering SCF through the ttkernel emitc flow.
> Add eltwise add_tiles and mul_tiles ttkernel dialect

- lib/Dialect/TTMetal/Transforms/Passes.cpp
Until now compiler would create single tilize block call with total amount of tiles needed to be generated. LLK actually needs to work on a single row of tiles at the time in order to know how much to stride.
This fix changes lowering to TTMetal dialect and creates correct number of tilize/untilize calls. In between them it pops/pushes from/to given CBs.
With SCF dialect we'll be able to insert loops, but for now these calls will be unrolled.
> Fix tilizing in tt-metal backend

- runtime/lib/ttnn/program.cpp
There seems to be an issue with implementation of `ttnn::empty()` for `TILE` layout in cases where the tensor needs to be padded.
Switching to `ROW_MAJOR` as a workaround - since we are anyhow not properly using tensors created via empty.
> [runtime] setting ROW_MAJOR layout for empty op

- lib/Dialect/TT/IR/TTOpsTypes.cpp
- test/python/tensor_layout.py
This commit adds a fix to support 1d tensors:
- Handle special case where the collapse interval distance is 0
- Support grid rank > shape rank by backfilling 0's
> Support 1d tensors #461 #471

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Target/TTNN/program.fbs
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/include/tt/runtime/detail/ttnn.h
- runtime/lib/ttnn/program.cpp
- test/ttmlir/Dialect/TTNN/embedding/embedding_1d_tensor.mlir
- test/ttmlir/Dialect/TTNN/embedding/embedding_non_tile.mlir
- test/ttmlir/Dialect/TTNN/embedding/simple_embedding.mlir
- Adds embedding op
- Added 3 tests:
- `simple_embedding.mlir` is marked `UNSUPPORTED`
- Metalium's implementation seems to behave a little different than pytorch's - there's some extra dimensions getting added somewhere, so a tensor that's supposed to be `[32, 32]` turns into `[32, 1, 1, 32]`; this causes an assert which expects a tile divisible dim(-2) since default layout is TILE
- `embedding_non_tile.mlir` is marked `UNSUPPORTED`
- tensor with non-tile aligned dims, currently failing in ttrt (ttnn) as we're not handling layouts correctly
- `embedding_1d_tensor.mlir` is marked `XFAIL`
- seems to fail due to a bug in MLIR, opened #471 to track
> Add embedding op

- test/ttmlir/Dialect/TTNN/embedding/embedding_1d_tensor.mlir
- On PR #473 I have added a test for embedding op, marked with XFAIL
- A fix (PR #478) was merged to main before I merged
- My tests still showed as passing on the PR, and I hadn't seen that #478 was already in (yay Friday merges!)
- Reproed error locally, fixed, confirmed it's good
> Remove XFAIL for now-passing test

- python/Passes.cpp
- runtime/tools/python/ttrt/binary/__init__.py
- runtime/tools/python/ttrt/binary/module.cpp
- runtime/tools/python/ttrt/common/api.py
- runtime/tools/python/ttrt/common/util.py
- Added functionality with the magic of `py::capsule`
- Can now run the entire transformation from TTIR -> Flatbuffer -> Perf Modelling with only python calls.
- Fixed a small bug
> Added load_from_capsule functionality to TTRT and Python Bindings

- include/ttmlir-c/TTAttrs.h
- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Target/Common/types.fbs
- include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
- lib/CAPI/TTAttrs.cpp
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- python/TTModule.cpp
- runtime/lib/common/system_desc.cpp
Adds the following constants to chip descriptors:
- L1_UNRESERVED_BASE
- ERISC_L1_UNRESERVED_BASE
- DRAM_UNRESERVED_BASE
Each of these point to the end of the reserved section by fast dispatch for the respective memory space. Hence, it's where the unreserved section begins.
> ChipDesc constants for fast dispatch memory carve outs

- runtime/lib/ttnn/program.cpp
- test/ttmlir/Silicon/TTNN/simple_nop.mlir
Closes #426
- Discussed a bit offline, other more complicated solutions could exist including new ops, but this is simplest for now, and simplifies some future runtime refactoring that might occur.
- Added original testcase generated from XLA that exposed this and added CHECK attributes inline
> TTNN Runtime workaround to support NOP program (input returned as output)

- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Utils.h
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- lib/Dialect/TTMetal/Transforms/Passes.cpp
- test/ttmlir/Silicon/TTMetal/tiled_reblock.mlir
Fix #322
This commit adds support for data movement between tiled layouts. Few key pieces:
1. TiledLinearMap - original linear space map translated into tile space. Example:
```
// tensor: tensor<2x3x64x128xf32,
//		  #tt.layout<(d0, d1, d2, d3) -> (d0 * 192 + d1 * 64 + d2, d3),
//		  undef, <1x1>, memref<384x128xf32, #tt.memory_space<l1>>>> 
// scalar linear: (d0, d1, d2, d3) -> (d0 * 192 + d1 * 64 + d2, d3), 
// tile linear: (d0, d1, d2, d3) -> (d0 * 6 + d1 * 2 + d2 floordiv 32, d3 floordiv 32).
```
3. TiledShape - same as original except that dims are computed with TiledLinearMap. Given above example: 
```
// originalScalarShape: [384, 128]
// tiledShape: [12, 4]
```
5. postLinearIndexToVisitingIndex - cpp map that keeps mapping between tiled indexes and initial linear index. Then when …
> Support tiled data movement in TTMetal

- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- lib/Dialect/TTIR/Transforms/Passes.cpp
- test/ttmlir/Dialect/TTIR/test_layout.mlir
- test/ttmlir/Dialect/TTNN/eltwise/operand_broadcasts.mlir
- test/ttmlir/Dialect/TTNN/eltwise/unary/relu/simple_relu.mlir
- test/ttmlir/Dialect/TTNN/embedding/embedding_1d_tensor.mlir
- test/ttmlir/Dialect/TTNN/embedding/simple_embedding.mlir
- test/ttmlir/Dialect/TTNN/simple_concat.mlir
- test/ttmlir/Dialect/TTNN/simple_div.mlir
- test/ttmlir/Dialect/TTNN/simple_ge.mlir
- test/ttmlir/Dialect/TTNN/simple_matmul.mlir
- test/ttmlir/Dialect/TTNN/simple_mean.mlir
- test/ttmlir/Dialect/TTNN/simple_multiply.mlir
- test/ttmlir/Dialect/TTNN/simple_subtract.mlir
- test/ttmlir/Dialect/TTNN/simple_sum.mlir
- test/ttmlir/Dialect/TTNN/softmax/simple_softmax.mlir
- test/ttmlir/Dialect/TTNN/transpose/simple_transpose.mlir
- test/ttmlir/Dialect/TTNN/transpose/simple_transpose_8x16_reverse_dims.mlir
- test/ttmlir/Dialect/TTNN/transpose/simple_transpose_8x8.mlir
- test/ttmlir/Dialect/TTNN/transpose/simple_transpose_negative_dims.mlir
- test/ttmlir/Translate/TTNN/1d_tensor.mlir
Previously we were just creating tensor layout grids with rank 1 or 2 depending on the tensor's rank.  This however is incorrect, the tensor grid must be of the same rank as the device grid.
The fix is to use the device grid's rank in the layout type converter to ensure that by default a tensor layout gets a grid of equivalent rank.
> Create tensor grids with same rank as device grid bug fix #500

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTMetal/IR/TTMetalOps.td
- include/ttmlir/Utils.h
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTMetal/Transforms/Passes.cpp
The core of this change is generating a loop nest from arith on tensors, consider the following `ttir.generic` body:
```mlir
^bb0(%arg2: tensor<64x128xf32, #tt.buffer<memref<2x4x!tt.tile<32x32, f32>, #l1_>, alias>>, %arg3, %arg4):
%8 = arith.addf %arg2, %arg3 : tensor<64x128xf32, #tt.buffer<memref<2x4x!tt.tile<32x32, f32>, #l1_>, alias>>
"ttir.yield"(%8) : (tensor<64x128xf32, #tt.buffer<memref<2x4x!tt.tile<32x32, f32>, #l1_>, alias>>) -> ()
})
```
Into a loop nest using the scf dialect:
```mlir
"ttkernel.binary_op_init_common"(%arg2, %arg3, %arg4)
"ttkernel.add_tiles_init"(%arg2, %arg3)
%8 = scf.for %arg5 = %c0_i32 to %c2_i32 step %c1_i32 iter_args(%arg6 = %c0_i32) -> (i32)  : i32 {
%9 = scf.for %arg7 = %c0_i32 to %c4_i32 step %c1_i32 iter_args(%arg8 = %arg6) -> (i32)  : i32 { …
```
> Support lowering add and mul through ttir.generic metal backend

- runtime/include/tt/runtime/detail/ttmetal.h
- runtime/lib/common/system_desc.cpp
- runtime/lib/ttnn/program.cpp
- runtime/tools/python/setup.py
- test/ttmlir/Silicon/TTNN/simple_sum.mlir
- third_party/CMakeLists.txt
Regressions:
- https://github.com/tenstorrent/tt-mlir/issues/528
> Upgrade metal 516a8917fac17649abbc9052b680894b432b4de6

- .github/workflows/docker-build.yml
Set up and register new builder machines for Github CI. These machines perform build and lint tasks 2x faster than standard silicon runners. 
- install docker on bileder VMs
- register builder nodes as Github self-hosted runners
- add them to tt-mlir project
- tag them with "builder" label
- update CI workflow to use "builder" nodes
> Add builder nodes to tt-mlir CI

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- test/ttmlir/Dialect/TTNN/simple_squeeze.mlir
`squeeze` is implemented through `reshape`
Validate checks:
* that `dim` is valid int in range `[0, inputType.getRank() - 1]`
* that the dimension `dim` is `1` in the input tensor
* that the output tensor has at least one dimension
* that the rank of the output tensor is one less than the input tensor
* that the dimensions of the output tensor are the same as the input tensor except for dimension `dim`
> Adding `squeeze` op

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- test/ttmlir/Dialect/TTNN/simple_unsqueeze.mlir
Adding `unsqueeze` through `reshape`
Verifications checks:
* that `dim` is valid int in range `[0, inputType.getRank()]`
* that the dimension `dim` is `1` in the output tensor
* that the rank of the input tensor is one less than the output tensor
* that the dimensions of the output tensor are the same as the input tensor except for dimension `dim`
closes #490
> Adding `unsqueeze`  op

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Target/TTNN/program.fbs
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTIR/Transforms/Passes.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/include/tt/runtime/detail/ttnn.h
- runtime/lib/ttnn/program.cpp
- runtime/lib/ttnn/runtime.cpp
- test/ttmlir/Dialect/TTNN/simple_conv.mlir
Changes:
- Updated MLIR to latest main and added my changes
- TTIR, TTNN MLIR support
- TTNN runtime support
- ToMemoryConfig ops should not be placed on the input activations, weight, or bias of the conv2d op as the conv2d op transforms these tensors on host and then moves them to device on its own (hack here)
- Typecast on the output ToMemoryConfig doesn't work on host (hack here)
-  MaxPool2d op definitions in TTIR and TTNN
TTForge PR: https://github.com/tenstorrent/tt-forge-fe/pull/168
> E2E Conv2D Implementation

- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- test/ttmlir/Dialect/TTNN/simple_squeeze.mlir
Adding negative dim support for `squeeze`
For `unsqueeze` this is already added as part of #544 
closes #550
> Adding negative dim support for `squeeze`

- runtime/tools/python/CMakeLists.txt
- runtime/tools/python/ttrt/common/api.py
Before: Registering an atexit close device function on program termination
Now: try finally block to always close device after ttnn binaries are executed and ttmetal. Takes care of exceptions/unexpected situations
> #563: Enable mixed ttnn and ttm runtime in ttrt

- include/ttmlir/Dialect/TTIR/Transforms/Passes.td
- lib/Dialect/TTIR/Transforms/Passes.cpp
- lib/Dialect/TTMetal/Transforms/Passes.cpp
- lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
- test/ttmlir/Dialect/TTIR/test_grid_set.mlir
- test/ttmlir/Dialect/TTNN/multiple_add_with_loc.mlir
- test/ttmlir/Dialect/TTNN/multiple_add_with_loc_grid_override.mlir
- test/ttmlir/Dialect/TTNN/simple_matmul.mlir
- test/ttmlir/Dialect/TTNN/ttir_to_ttnn_pipeline.mlir
- test/ttmlir/Dialect/TTNN/ttir_to_ttnn_pipeline_custom_opt.mlir
This new option sets the default memory space for layout pass to prefer for operation operands, if they are not constrained. This differs from initMemorySpace which sets the expected graph input and output memory space.
Closes #555
> Add a new TTIR Layout pass option defaultMemorySpace

- runtime/include/tt/runtime/detail/ttmetal.h
- runtime/lib/ttmetal/command_queue.cpp
- test/ttmlir/Silicon/TTMetal/simple_eltwise.mlir
- test/ttmlir/Silicon/TTMetal/tiled_reblock.mlir
- test/ttmlir/Silicon/TTMetal/to_layout.mlir
- Prevent duplicate Buffers from being created inside CreateBufferCommand handler by checking for existence in buffers umap.
- Change to use buffers.erase() in DeallocateBufferCommand to actually remove the entry from buffers umap. Buffer will still be destroyed because it goes out of scope.
- Neither of these help with the original segfault in this ticket but these were found through visual observation.
> A pair of runtime::ttmetal CQExecutor buffer map improvements (#408)

- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Target/Common/types.fbs
- include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
- lib/CAPI/TTAttrs.cpp
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- python/TTModule.cpp
- runtime/lib/common/system_desc.cpp
Calculate the end of the DRAM region that is not usable by compiler.  This upper region of memory is where kernel programs get allocated to.  This calculation intends to estimate some conservative max number, but still needs a mechanism to enforce during runtime #539.
> Add system desc attribute dram_unreserved_end

- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
Currently, the ElementwiseBinaryOpConversionPattern class is used for both unary and binary type conversions from TTIR to TTNN because it is written generically. This can be confusing for code readers, hence renaming: `ElementwiseBinaryOpConversionPattern to ElementwiseOpConversionPattern`
Closes https://github.com/tenstorrent/tt-mlir/issues/577
> Renaming ElementwiseBinaryOpConversionPattern to ElementwiseOpConversionPattern

- runtime/include/tt/runtime/detail/ttmetal.h
- runtime/include/tt/runtime/detail/ttnn.h
- runtime/include/tt/runtime/runtime.h
- runtime/lib/runtime.cpp
- runtime/lib/ttmetal/runtime.cpp
- runtime/lib/ttnn/runtime.cpp
- runtime/tools/python/ttrt/common/api.py
- runtime/tools/python/ttrt/runtime/module.cpp
Plumb through deallocate_buffers API to clear metal allocator between programs.  Previously we were running OOM because of leaked buffers. Leaked buffers should largely be cleaned up after the allocate=false support is in #408.
It might still be needed even after #408 lands, because metal internally uses its allocator for some fast dispatch things, but we can revisit what policy to adopt.
> ttrt deallocate_buffers

- test/ttmlir/Silicon/TTMetal/simple_eltwise.mlir
- test/ttmlir/Silicon/TTMetal/tiled_reblock.mlir
- test/ttmlir/Silicon/TTMetal/to_layout.mlir
- tools/ttmlir-translate/CMakeLists.txt
- Needed after 5d60c17 today otherwise tests don't run on CI
> Update RUN cmds for 3x TTMetal tests to include "ttmlir-translate --ttmetal-to-flatbuffer" 

- docs/src/build.md
- docs/src/overview.md
- docs/src/specs/runtime-stitching.md
- test/ttmlir/Dialect/TTNN/multiple_add_with_loc.mlir
- test/ttmlir/Dialect/TTNN/multiple_add_with_loc_grid_override.mlir
We're getting PyBuda/Buda words in a few files in the TT-MLIR repo. This PR replaces the PyBuda\Buda with forge where appropriate.
> Renaming PyBuda\Buda occurances to Forge in TT-MLIR repo

- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
The original method of retrieving the bias:
```
llvm::dyn_cast_or_null<::mlir::RankedTensorType>(getBias().getType());
```
resulted in a segmentation fault because `getBias()` itself would return an incomplete object. Thus, `getBias().getType()` would attempt to dereference a `nullptr` at some point.
> Fixing logic for biasType retrieval in the event there is no bias input

- include/ttmlir/Dialect/TT/IR/TTOpsTypes.h
- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Dialect/TT/Utils/PhysicalCoreCoord.h
- include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
- include/ttmlir/Utils.h
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- lib/Dialect/TTIR/Transforms/Passes.cpp
- lib/Dialect/TTMetal/Transforms/Passes.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- python/TTModule.cpp
- test/python/device_attr.py
- test/ttmlir/Silicon/TTMetal/to_layout.mlir
This change adds support for the device dram memory space in metal
backend.  This required a few bits of refactoring including:
- `DeviceAttr` splits out worker grid from L1 map, they now respectively
map the physical compute cores and the physical L1 memory map.
- `DeviceAttr` gets a new map, `dramMap`, which maps a linear tensor
coordinate to a physical dram address.
- Change `projectOnto` to take an arbitrary affine map instead of a grid
attr.  This let's us pass in unique affine map for L1 or DRAM or Eth
(in the future) to the same interface.
- `PhysicalCoreCoordMapping` can now take an L1 grid or a DRAM grid.
- Giving explicit enum index names for the DeviceAttr affine map
results.
- Noc datamovement program can now be generated as reads or writes,
necessary for writing to DRAM since …
> Support dram memory space in metal direct

- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Dialect/TTIR/Transforms/Passes.td
- include/ttmlir/Utils.h
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- lib/Dialect/TTIR/Transforms/Passes.cpp
This change fixes a few bugs and makes a few cleanups to do with memory map and allocation:
- Create utility function replaceMemoryMapSymbolsWithShardShape instead of just being inline with projectOnto.  Size estimation needs this too.
- Fix bug in dram memory map which had one of the address calculation dims flipped.
- Create convenience function getTensorSizeBytes to calculate the memory footprint of the tensor depending on memory space.
- Fixup the allocator to use this new function getTensorSizeBytes instead of doing a simple shard calc.
Closes #613
> Fixup tensor size bytes for allocator

- runtime/lib/ttnn/program.cpp
- runtime/lib/ttnn/utils.h
closes #450 
Dynamically create memory configs in ToMemoryConfigOp instead of using default L1/DRAM_MEMORY_CONFIG. Derive and pass output memory config into ops accordingly.
> Dynamically create memory configs

- include/ttmlir/Dialect/TTIR/Analysis/LegalGridAnalysis.h
- lib/Dialect/TTIR/Analysis/LegalGridAnalysis.cpp
- lib/Dialect/TTIR/Analysis/OptimalTargetGridAnalysis.cpp
- lib/Dialect/TTIR/Transforms/Passes.cpp
- test/ttmlir/Dialect/TTIR/test_grid_set.mlir
- test/ttmlir/Dialect/TTNN/multiple_add_with_loc.mlir
- test/ttmlir/Dialect/TTNN/multiple_add_with_loc_grid_override.mlir
- test/ttmlir/Dialect/TTNN/ttir_to_ttnn_pipeline.mlir
- test/ttmlir/Silicon/TTNN/sharded/simple_eltwise_sharded.mlir
A first implementation of generating possible op configurations. Starting with generating a few sharded tensor layouts for now. Much of the details here are incomplete and this is meant to unblock further optimizer and runtime development.
Waiting on #541 in order to add appropriate TensorMemoryLayout before merge. 
Closes #572
> Add V0 tensor layout generation

- .github/Dockerfile.base
- .github/Dockerfile.ci
- .github/Dockerfile.ird
- .github/workflows/build-and-test.yml
- .github/workflows/build-image.yml
- .github/workflows/docker-build.yml
- .github/workflows/on-pr.yml
- .github/workflows/pages.yml
- .github/workflows/pre-commit.yml
- .github/workflows/spdx.yml
- docs/src/internal-build.md
Split docker image builds into steps, so now we have base image containing only build dependencies, ci image that contains prebuilt toolchain and ird image that add dev tools and ssh to these images. Also adds GDB 14.2 to IRD images.
- added GDB 14.2 to IRD images
- replace image in workflows with new ci image
- update docs
- set job timeout to 30 minutes
- add "in-service" to runner selection
Closes: #481 
Closes: #593
> Multi stage docker build

- lib/Dialect/TTIR/Analysis/LegalGridAnalysis.cpp
When it doesn't make sense to change output layout just pass existing layout.
> Handle ops with fixed layout

- python/Passes.cpp
- runtime/tools/python/ttrt/binary/module.cpp
Closes #610 
**Implemented**
- Added `ttnn_to_flatbuffer_file` to pybind `ttmlir.passes` module.
- Simple bugfix for loading capsules into TTRT (Carried over from 1-line hotfix).
> Added ttnn_to_flatbuffer_file to directly dump module to file

- .github/workflows/build-and-test.yml
- .github/workflows/docker-build.yml
- python/CMakeLists.txt
- test/CMakeLists.txt
- tools/ttmlir-opt/CMakeLists.txt
- tools/ttmlir-translate/CMakeLists.txt
This change introduces a new cmake install component named Test. Where running cmake command:
cmake --install build --component Test
Will install all of the build artifacts necessary for testing.  This should cut down on the artifact size down to ~42 MB.
> Cut down on CI build artifacts

- include/ttmlir/Target/TTMetal/program.fbs
- lib/Target/TTMetal/TTMetalToFlatbuffer.cpp
- runtime/lib/ttmetal/command_queue.cpp
Closes #361 and Closes #267
- 2 types of runtime_args today: RuntimeArgTensorAddress, RuntimeArgSemaphoreAddress where runtime will resolve tensor address or semaphore id, and call metal APIs SetRuntimeArgs() and CreateSemaphore()
- Compiler support not included, so did some light testing with various dummy values for each type in flatbuffer via TTMetalToFlatbuffer.cpp changes, and tested assertions. For now, keep nullptr in .ttm for runtime_args and runtime_args_types
> Runtime support for RuntimeArgs on KernelDesc (Tensor Addr + Semaphores) 

- lib/Dialect/TTIR/Transforms/Passes.cpp
Fix traversal order of TTIRLayout pass, default is bottom up. Reduces number of ToLayout ops inserted as operands are transformed first allowing their layout to be reused.
Closes #653
> Fix TTIRLayout pass generating unnecessary ToLayoutOps

- runtime/lib/ttnn/program.cpp
> runtime support for full op

- cmake/modules/LintTools.cmake
- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTIR/Transforms/Passes.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Target/TTNN/program.fbs
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTIR/Transforms/Passes.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/lib/ttnn/program.cpp
- test/ttmlir/Dialect/TTNN/simple_maxpool2d.mlir
- Bringup MaxPool2d: TTIR->Pass to add reshapes on input/output -> TTNN -> Flatbuffer -> runtime
- Working for shapes where H, W, and C are tile-dim aligned, and C is a power of 2
> E2E MaxPool2d Bringup

- include/ttmlir/Conversion/StableHLOToTTIR/StableHLOToTTIR.h
- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/dot_general_op.mlir
This conversion only works for cases that can be directly converted for ttir.matmul op in order to support the case in MNIST examples. 
It will be enhanced further as other required ops are supported e.g. permute and broadcast_in_dim.
> Add an preliminary conversion for stablehlo.dot_general op

- docs/src/specs/device.md
- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Dialect/TTIR/Transforms/Passes.td
- include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
- include/ttmlir/Utils.h
- lib/Dialect/TT/IR/TTDialect.cpp
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- lib/Dialect/TTIR/Transforms/Passes.cpp
- lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- python/TTModule.cpp
- test/lit.cfg.py
- test/python/device_attr.py
- test/ttmlir/Silicon/TTNN/multi_device.mlir
- Updated the device spec to outline new meshShape attribute usage and lowering to TTNN.
- Add meshShape to DeviceAttr which drives interpretation of multi-device device and tensor grids.
- Add pass and pipeline option "mesh-shape" for providing a mesh shape to the device attribute creation.
- Make device and system_desc attributes as alias attributes, i.e. hoisted in mlir printing.
- Add llvm lit config features based on provided system_desc
- Update `test/python/device_attr.py` to match spec
- Add simple test marked as XFAIL for now
> Multi-chip spec update, add meshShape to DeviceAttr

- runtime/include/tt/runtime/detail/ttmetal.h
Closes #408 - by removing a temporary hack now that tt-metal uplift has happened to include proper fix. Confirmed tests still passing and segfault avoided by allocate=false change. See 408 for details.
> Metal Runtime use Buffer allocate=false in createBufferFromTensorRef(), remove temp hack #408

- include/ttmlir/Dialect/TTIR/Analysis/DFShardingPolicy.h
- include/ttmlir/Dialect/TTIR/Analysis/Edge.h
- include/ttmlir/Dialect/TTIR/Analysis/OpConfigAnalysis.h
- include/ttmlir/Dialect/TTIR/Analysis/ShardChainConfig.h
- include/ttmlir/Dialect/TTIR/Analysis/ShardSolver.h
- include/ttmlir/Dialect/TTIR/Analysis/ShardingAnalysis.h
- include/ttmlir/Dialect/TTIR/Transforms/Passes.td
- include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
- lib/Dialect/TTIR/Analysis/CMakeLists.txt
- lib/Dialect/TTIR/Analysis/DFShardingPolicy.cpp
- lib/Dialect/TTIR/Analysis/OpConfigAnalysis.cpp
- lib/Dialect/TTIR/Analysis/ShardChainConfig.cpp
- lib/Dialect/TTIR/Analysis/ShardSolver.cpp
- lib/Dialect/TTIR/Analysis/ShardingAnalysis.cpp
- lib/Dialect/TTIR/Transforms/Passes.cpp
- lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
- test/ttmlir/Dialect/TTNN/mnist_sharding.mlir
First iteration of DF sharding policy v0 per Optimizer design spec.
Implemented so far:
Core of DF Sharding policy, Shard chan config, Shard spec and Shard solver.
Scheduler integration into DFSp and corresponding transformation via MLIR op reordering.
Base analysis for reshard generation.
Lots of work remains to be done and is pending, this is current snapshot before moving on. Sharding pass option added to pass and TTNN pipeline, will remain in default off until code is more stable(under construction).
TTNN Op constraints are already big issue(sharding ones for start) and prevent MNIST model running E2E with current change.
More details: Issue related #570
> [Optimizer] DF sharding policy v0 - part 1.

- cmake/modules/BuildFlatbuffers.cmake
Update `*_bfbs_generated.h` on incremental builds.
> fix bfbs cmake tracking

- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Dialect/TTIR/Analysis/DFShardingPolicy.h
- include/ttmlir/Dialect/TTIR/Analysis/ShardChainConfig.h
- include/ttmlir/Dialect/TTIR/Analysis/ShardSolver.h
- include/ttmlir/Dialect/TTIR/Analysis/ShardingAnalysis.h
- include/ttmlir/Dialect/TTIR/Transforms/Passes.td
- include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- lib/Dialect/TTIR/Analysis/DFShardingPolicy.cpp
- lib/Dialect/TTIR/Analysis/ShardChainConfig.cpp
- lib/Dialect/TTIR/Analysis/ShardSolver.cpp
- lib/Dialect/TTIR/Analysis/ShardingAnalysis.cpp
- lib/Dialect/TTIR/Transforms/Passes.cpp
- lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
- test/ttmlir/Dialect/TTIR/test_grid_set.mlir
- test/ttmlir/Dialect/TTNN/ttir_to_ttnn_pipeline_custom_opt.mlir
- test/ttmlir/Silicon/TTNN/sharded/simple_eltwise_sharded.mlir
Follow-up change on DF sharding policy implementation:
- Resharding pass added.
- Handling of firstOp/chain start added.
- Updated L1 shard size calc to common API in DeviceAttr.
- Minor refactor(naming).
Closes #570.
> [Optimizer] DF sharding policy - part2.

- runtime/lib/ttnn/operations/pool/maxpool2d.cpp
Pre-shard maxpool2d input. To be left in place until shard configuration is modelled in the TTNN dialect.
> Pre-shard maxpool2d Input

- runtime/lib/ttnn/runtime.cpp
closes #697 
Enable async mode implicitly by default, there's no reason not to. Even for single device it can reduce the time the main thread blocks.
Close device will automatically reset the async work executor, so when the device is reopened the state is cleared and it will run in synchronous mode again.
> #697: Enable async mode by default in ttnn runtime

- include/ttmlir/Dialect/TTNN/IR/TTNNOpsAttrs.td
New dialect attribute MeshShape, just holds an [y, x] shape.
> Add new TTNN Dialect Attribute: MeshShape (#698)

- cmake/modules/CMakeLists.txt
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOpsAttrs.td
- include/ttmlir/Dialect/TTNN/Utils/Utils.h
- include/ttmlir/Target/TTNN/program.fbs
- include/ttmlir/Target/TTNN/utils.h
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitCPass.cpp
- lib/Dialect/TTNN/CMakeLists.txt
- lib/Dialect/TTNN/IR/CMakeLists.txt
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Dialect/TTNN/Utils/CMakeLists.txt
- lib/Dialect/TTNN/Utils/Utils.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/lib/ttnn/include/tt/runtime/ttnn/utils.h
- runtime/lib/ttnn/operations/creation/empty.cpp
- runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/utils.cpp
- runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/utils.h
- runtime/lib/ttnn/operations/layout/to_device.cpp
- test/ttmlir/Silicon/TTNN/sharded/simple_eltwise_sharded.mlir
- tools/ttnn-standalone/ttnn-precompiled.hpp
- tools/ttnn-standalone/ttnn-standalone.cpp
Introduce few changes to make emitted cpp code compileable. There's another small issue to tackle (#721) which I'll post the PR for soon.
Parameterize EmptyOp, pipe thru ttnn runtime, fix 2 tests that require height sharding.
If you want to play with this, you can run:
```
./build/bin/ttmlir-opt --ttir-load-system-desc --ttir-implicit-device --ttir-layout --convert-ttir-to-ttnn --convert-ttnn-to-emitc test/ttmlir/Dialect/TTNN/simple_multiply.mlir | ./build/bin/ttmlir-translate -mlir-to-cpp -allow-unregistered-dialect
```
which will generate:
```cpp
#include "ttnn-precompiled.hpp"
ttnn::Tensor forward(ttnn::Tensor v1, ttnn::Tensor v2) {
ttnn::Device* v3 = ttnn::DeviceGetter::getInstance();
ttnn::Tensor v4 = ttnn::to_layout(v1, ttnn::Layout::TILE, std::nullopt, std::nullopt, v3); …
```
> make emitted cpp code compileable

- .github/workflows/build-and-test.yml
- docs/src/ttrt.md
- runtime/lib/ttnn/runtime.cpp
- runtime/tools/python/ttrt/common/api.py
Before: We were missing device performance related data in the perf csv file.
Missing: 
An API call which explicity dumps the performance data. This is found in metal's conftest.py file. 
Some env flags needed to clear the L1 cache (otherwise l1 data corruption occurs)
Copying the perf device log csv file to generated logs in ttrt whls path (metal's internal scripts parse relative to TT_METAL_HOME path)
> #552: Fixed collecting device related performance data in ttrt

- include/ttmlir/Dialect/TT/IR/TTOpsTypes.h
- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOpsAttrs.td
Support printing shapes with named dims with a varg printer/parser:
let assemblyFormat = "custom<VargDimensionList>($y, $x)";
For e.g.:
3x4
> Create varg dimension assembly printer

- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Target/TTNN/program.fbs
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/lib/ttnn/operations/CMakeLists.txt
- runtime/lib/ttnn/operations/layout/from_device.cpp
- runtime/lib/ttnn/operations/layout/from_device.h
- runtime/lib/ttnn/program.cpp
- tools/ttnn-standalone/ttnn-standalone.cpp
Currently, we're calling to_memory_config to get tensor from device to host. This isn't correct, so we're changing to the approach used in ttnn lib, which is to call `FromDevice` + `ToLayout` ops, as can be seen in the `to_torch` method in `third_party/tt-metal/src/tt-metal/ttnn/ttnn/operations/core.py`:
```py
if ttnn.is_tensor_storage_on_device(tensor):
tensor = ttnn.from_device(tensor, cq_id=cq_id)
if tensor.layout != ttnn.ROW_MAJOR_LAYOUT:
tensor = tensor.to(ttnn.ROW_MAJOR_LAYOUT, device)
```
This PR updates the conversion of `ToLayout` op from TTIR to TTNN. It also adds the `FromDevice` op.
> Fix tensor read (device->host path)

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTIR/Transforms/Passes.td
- include/ttmlir/Dialect/TTMetal/IR/TTMetalOps.td
- include/ttmlir/Target/Common/types.fbs
- include/ttmlir/Target/TTMetal/command.fbs
- include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
- lib/Conversion/TTIRToTTMetal/TTIRToTTMetal.cpp
- lib/Dialect/TTIR/Transforms/Passes.cpp
- lib/Dialect/TTMetal/IR/TTMetalOps.cpp
- lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp
- lib/Target/TTMetal/TTMetalToFlatbuffer.cpp
- runtime/lib/ttmetal/command_queue.cpp
- test/ttmlir/Dialect/TTIR/constant_as_fill.mlir
- test/ttmlir/Silicon/TTMetal/simple_constant.mlir
- Introduce `ttir.fill` op
- Introduce pass the converts `ttir.constant` into an empty + fill
- Support lowering `ttir.fill` to `ttmetal.host_write`
The purpose of this change is to support lowering of `ttir.constant` into the ttmetal backend.  An issue that arises with `ttir.constant` is that the allocator pass only knows how to convert `ttir.empty`'s into `ttir.allocate`, and we probably don't want to support lowering `ttir.constant` in the same way because otherwise we'd have to store the constant value attribute on the `ttir.allocate` op which would be an awkward place to put it.  The best solution I could come up with is to create a `ttir.fill` op, which is essentially just a DPS version of `ttir.constant`, but now more naturally fits the allocation pass. Further, this also better …
> Introduce FillOp + lowering ttir.constant to ttmetal

- .github/workflows/build-and-test.yml
- runtime/lib/ttnn/operations/layout/from_device.cpp
Fixes main CI where all output tensors are 0
> Update output tensors in from device op

- docs/src/ttrt.md
- runtime/include/tt/runtime/detail/debug.h
- runtime/lib/common/debug.cpp
- runtime/lib/ttnn/operations/conv/conv2d.cpp
- runtime/lib/ttnn/operations/data_movement/transpose.cpp
- runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/utils.cpp
- runtime/lib/ttnn/operations/layout/to_memory_config.cpp
- runtime/lib/ttnn/operations/pool/maxpool2d.cpp
- runtime/lib/ttnn/runtime.cpp
- runtime/tools/python/test/test_run.py
- runtime/tools/python/ttrt/common/run.py
- test/ttmlir/Silicon/TTNN/simple_conv.mlir
- test/ttmlir/Silicon/TTNN/simple_maxpool2d.mlir
With async mode enabled, when querying metadata from ttnn tensors, we must use the get_* APIs. The normal APIs won't block on the worker thread, and so the metadata returned may not be correct.
When possible, we should query this metadata from the flatbuffer tensor descriptor instead of the ttnn tensor directly, as these get_ APIs do have a performance cost.
Added conv2d and maxpool to silicon tests. 
FYI @LPanosTT
> Async TTNN: Use fields from flatbuffer when possible, update APIs

- include/ttmlir/Bindings/Python/TTMLIRModule.h
- include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
- lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
- python/Passes.cpp
- python/ttmlir/passes.py
Closes #661, _depends_ on #714 (not really).
**Implemented**
- Path of least resistance, added `skip-ttnn-conversion` option to `TTIRtoTTNNPipeline` (TTNNPipelines.h)
- Skips adding conversion passes to the pipeline. Simple change. (TTNNPipelines.cpp)
> Split TTIRtoTTNNPipeline into thirds, add python bindings for these thirds.

- runtime/lib/ttmetal/command_queue.cpp
- test/ttmlir/Silicon/TTMetal/simple_constant.mlir
Data to write comes from src HostRef, which only supports ConstantData32 at the moment. Builds on refactoring changes from #758
> Add EnqueueWriteBuffer #269

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
- lib/Conversion/TTIRToTTMetal/TTIRToTTMetal.cpp
- lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- test/python/simple_kernel.py
- test/ttmlir/Silicon/TTMetal/simple_eltwise.mlir
Fixes https://github.com/tenstorrent/tt-mlir/issues/534.
Added TTIR_GenericElementwiseUnaryOp. Made TTIR_ExpOp inherit from it. Handled lowering to ttkernel.
- Refactored TTIRToTTMetalDispatchRewriter to include common building steps as well as some separate steps for unary and binary ops
- Deprecated AcquireDstOp and ReleaseDstOp in favor of up-to-date metal tile_regs_* API: acquire, commit, wait, release
Running `ttmlir-opt` on 
```mlir
func.func @exp(%arg0: tensor<64x128xf32>) -> tensor<64x128xf32> {
// CHECK: %[[C:.*]] = "ttmetal.alloc"[[C:.*]]
%0 = tensor.empty() : tensor<64x128xf32>
// CHECK: %[[C:.*]] = "ttmetal.dispatch"[[C:.*]]
%1 = "ttir.exp"(%arg0, %0) <{operandSegmentSizes = array<i32: 1, 1>, operand_constraints = [#any_device, #any_device]}> : (tensor<64x128xf32>, …
```
> [Metal Direct] Added support for ttir.exp op

- runtime/lib/ttmetal/command_queue.cpp
fixes #794 
New file name format (if kernel is distributed across 2 core ranges):
```
/tmp/ttmlir_multiply_%5_tensix__startY1_startX1-endY1_endX1__startY2_startX2-endY2_endX2.cpp
```
> Embed core ranges to kernel's filename

- include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
- test/ttmlir/Dialect/TTNN/mnist_sharding.mlir
- test/ttmlir/Dialect/TTNN/multiple_add_with_loc.mlir
- test/ttmlir/Dialect/TTNN/multiple_add_with_loc_layout_override.mlir
- test/ttmlir/Dialect/TTNN/ttir_to_ttnn_pipeline.mlir
Optimizer pass was enabled by default and some tests depend on it. We want to make it disabled by default, and make rest of the compiler independent of the optimizer. Independent means all components should work with and without optimizer, correctness of the output of the compiler doesn't depend on the optimizer.
Issue: https://github.com/tenstorrent/tt-mlir/issues/727
> [Optimizer] Disable optimizer pass by default

- include/ttmlir/Dialect/TTIR/Analysis/TTNNOPInterface.h
- lib/Dialect/TTIR/Analysis/CMakeLists.txt
- lib/Dialect/TTIR/Analysis/LegalGridAnalysis.cpp
- lib/Dialect/TTIR/Analysis/ShardSolver.cpp
- lib/Dialect/TTIR/Analysis/TTNNOpInterface.cpp
Extracted TTNN op interface to a separate file so it can be used by both LegalGridAnalysis and ShardSolver.
> Extract ttnn op interface to common file

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
- lib/Conversion/TTIRToTTMetal/TTIRToTTMetal.cpp
- lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTKernel/IR/TTKernelOps.cpp
- test/ttmlir/Silicon/TTMetal/simple_eltwise.mlir
Fixes #535 
Implement Div op for tt-metal backend.
Important notes for review
- Div op is implemented using recip + mul. Input 1 of the div is going to go through the recip using DST register, and then input 0 and recip input 1 are multiplied to get the div.
- To avoid intermediate buffers, input 1 CB is used to pack recip tiles of the original input 1. Then input 0 and input 1 are regularly used as inputs for multiply part
- More code is moved to convert compute init and convert compute functions, since the code that was outside of those functions was mostly for eltwise ops, and we need to do recip now as well, we cannot keep that code outside of functions
Generated kernel 
```cpp
#include <cstdint>
#include "compute_kernel_api/common.h"
#include "compute_kernel_api/tilize.h"
#include …
```
> [Metal Direct] Implement div op

- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/concat_op.mlir
Add concatenate end-to-end along with required conversion for stablehlo. 
Dimension is i64 for stablehlo, si32 for ttir/ttnn concat.
> Add StableHLO conversion for concatenate. [#751]

- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- runtime/lib/ttnn/operations/eltwise/binary.cpp
- test/ttmlir/Dialect/TTNN/simple_subtract_to_add.mlir
Canonicalize Eltwise binary ops by switching operands in case the `_rhs_` operand requires broadcast. 
Make SubtractOp commutative by converting it to combination of `NegOp` and `AddOp`: 
`SubtractOp(lhs, rhs) -> AddOp(lhs, NegOp(rhs)`
Fixes #815
> Canonicalize Eltwise binary ops for broadcast

- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/concat_op.mlir
Add operand constraints for all arguments, not just inputs.
> Fix concatOp StableHLO to TTIR Constraint [#864]

- include/ttmlir/Dialect/TT/IR/TTOpsEnums.td
- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Dialect/TT/Utils/PhysicalCoreCoord.h
- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTIR/Transforms/Passes.td
- include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
- include/ttmlir/Dialect/TTKernel/IR/TTKernelOpsEnums.td
- include/ttmlir/Dialect/TTKernel/IR/TTKernelOpsTypes.td
- lib/Conversion/TTIRToTTMetal/TTIRToTTMetal.cpp
- lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTIR/Transforms/Passes.cpp
- lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp
- runtime/lib/ttmetal/command_queue.cpp
- test/ttmlir/Silicon/TTMetal/simple_reduce.mlir
- test/ttmlir/Silicon/TTMetal/simple_reduce_1x1.mlir
Fixes #536 
Adding reduce op support in metal backend path.
```
#layout3 = #tt.layout<(d0, d1) -> (d0, d1), undef, <1x4>, memref<32x96xf32, #l1_>>
func.func @reduceH(%arg0: tensor<256x384xf32, #layout1>) -> tensor<32x384xf32, #layout3> {
%0 = tensor.empty() : tensor<32x384xf32, #layout3>
// CHECK: %[[C:.*]] = "ttmetal.dispatch"[[C:.*]]
%1 = "ttir.sum"(%arg0, %0) <{operandSegmentSizes = array<i32: 1, 1>,
dim_arg = [-2: i32],
keep_dim = true,
operand_constraints = [#any_device, #any_device, #any_device]}> :
(tensor<256x384xf32, #layout1>, tensor<32x384xf32, #layout3>) -> tensor<32x384xf32, #layout3>
return %1 : tensor<32x384xf32, #layout3>
}
```
Consider about reduce sum. It will be placed on 4 cores (to match `layout3` width). This will be lowered to dispatch op:
```
%4 = …
```
> [Metal Direct] Reduce op 

- .github/Dockerfile.ci
- .github/workflows/build-image.yml
Remove "Run clang-tidy" check from Docker build. It is also running a lint check on tt-metal code and failing, and we don't want this to block our Docker build.
Combine the docker build tag and latest tag steps in one to avoid building image twice
> Remove "Run clang-tidy" check from Docker build

- .github/workflows/build-and-test.yml
After Docker image update lint check started failing. It is now scanning tt-metal code and failed on different errors. Disabling linter checks until this problem is resolved
> Comment out lint check

- include/ttmlir/Target/Common/types.fbs
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/utils.cpp
// old desc
- Undo hardcoded tile layout in TTIR->TTNN
- Updated silicon tests to pass
- Dialect tests not updated here
// end old desc
- Override how layout (tile/rowmajor) is set in TTIR->TTNN path for conv/maxpool ops
- Pass shardshape to memoryconfig (this was relevant in previous iteration, but is still a good change, so leaving it in)
> Undo hardcoded tile layout in TTIR->TTNN

- .gitignore
- include/ttmlir/Utils.h
- python/CMakeLists.txt
- python/TTModule.cpp
- python/test_infra/ttir_builder.py
- test/python/test_ttir_ops.py
Fixes https://github.com/tenstorrent/tt-mlir/issues/853.
Set up test infrastructure for lowering ttir ops from Python.
- Created builder class providing API for creating TTIR ops and other helpers
- Created decorator function which makes it possible to create a MLIR module from decorated python function
- Created couple of tests to serve as examples
- Added support for tracking golden tensors for each op in MLIR graph
Note: Decorator `compile_as_mlir_module` from `python/test_infra/ttir_builder.py` is quite convoluted, but IMO it does provide an easy way to write tests. More importantly, it instantly returns MLIR `Module` which can be used in our pipelines to lower `ttir` to whatever. 
I devised it after reading docstring of `FuncOp.from_py_func` from …
> [Metal Direct] Set up test infrastructure for lowering ttir ops from Python.

- runtime/include/tt/runtime/detail/logger.h
- runtime/lib/CMakeLists.txt
- runtime/lib/binary.cpp
- runtime/lib/common/CMakeLists.txt
- runtime/lib/runtime.cpp
- runtime/lib/ttmetal/command_queue.cpp
- runtime/lib/ttnn/operations/context/get_device.cpp
- runtime/lib/ttnn/operations/eltwise/unary.cpp
- runtime/lib/ttnn/program.cpp
- runtime/lib/ttnn/runtime.cpp
Added 8 logging APIs in runtime in std::cout style. TTmetal fmt library pollutes runtime such that we cannot use any logger lib the uses libfmt, which is required for formatting strings as such `log_info("the value of x is {}", x);` :
- LOG_TRACE: traces the file/line in the log. Will not do anything if TT_RUNTIME_DEBUG is not enabled.
- LOG_DEBUG: debug log. Will not do anything if TT_RUNTIME_DEBUG is not enabled.
- LOG_INFO: info log.
- LOG_WARNING: warning log.
- LOG_ERROR: error log. This does not throw.
- LOG_FATAL: This will throw and print the stack trace.
- LOG_ASSERT: This will throw if the condition is not met. Will print the stack trace.
- DEBUG_ASSERT: Will throw and print stack trace if condition not met. Will not do anything if TT_RUNTIME_DEBUG is not enabled.
Sample code: …
> Implement runtime logger

- tools/ttnn-standalone/ttnn-standalone.cpp
- After recent metal uplift, update a few lines to make ttnn-standalone compile
- `Shape` -> `LegacyShape`
- `ttnn::empty` now expects pointer to `Device` instead of a ref
> fix ttnn-standalone after metal uplift

- .github/workflows/nightly-uplift.yml
- third_party/CMakeLists.txt
Auto uplift overview [CI-CD-Guide](https://github.com/tenstorrent/tt-forge-internal/wiki/CI-CD-Guide#uplift)
How to add PR automation to the project
In project settings
> Add workflow to auto create uplift PR

- lib/CMakeLists.txt
- lib/Conversion/StableHLOToTTIR/CMakeLists.txt
- lib/Conversion/TTIRToTTMetal/CMakeLists.txt
- lib/Conversion/TTIRToTTNN/CMakeLists.txt
- lib/Conversion/TTKernelToEmitC/CMakeLists.txt
- lib/Conversion/TTNNToEmitC/CMakeLists.txt
- lib/Conversion/TosaToTTIR/CMakeLists.txt
- lib/Dialect/TTNN/IR/CMakeLists.txt
- lib/RegisterAll.cpp
- lib/Scheduler/CMakeLists.txt
- lib/Target/TTNN/CMakeLists.txt
- python/CMakeLists.txt
- tools/ttmlir-opt/CMakeLists.txt
- tools/ttmlir-translate/CMakeLists.txt
We cannot mix static and dynamic linking when building targets because otherwise we can end up with multiple global constructors which MLIR isn't happy about.  We need to manually enforce that all cmake targets are statically linked, i.e. _don't_ use target `MLIR`, the only exception being the SharedLibrary target.
> Static link all targets and tools

- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/constant_op.mlir
Fixes #798 
Fixes https://github.com/tenstorrent/tt-xla/issues/5
> Fix issue #798 - Constant OP conversion doesn't convert scalar values

- include/ttmlir/RegisterAll.h
- lib/Dialect/TTIR/IR/TTIRDialect.cpp
- lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
- lib/RegisterAll.cpp
- python/Passes.cpp
- test/ttmlir/Dialect/TTNN/multiple_func.mlir
- tools/ttmlir-opt/ttmlir-opt.cpp
- Register FuncDialect Inliner interface
- Create and register TTIRDialect Inliner interface
- ~~Added pass that will make-private all functions which are called~~
- ~~The inliners will inline all functions - however it will leave those functions in the module if they are public even when they are dead code. Setting them to private ensures they are deleted from the module.~~
Since we are inlining all functions that are called, if the module has multiple distinct programs they will all remain afterward. This is because the topmost function in the call stack is the only non-dead-code function that doesn't get called.
Disabling the inliner pass is as simple as removing the added lines in `lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp`
If you wish to not register them altogether you'll have to …
> Inline all functions that are called.

- include/ttmlir/Bindings/Python/TTMLIRModule.h
- python/CMakeLists.txt
- python/TTIRModule.cpp
- python/TTMLIRModule.cpp
- python/ttmlir/dialects/ttir.py
- tools/scripts/parted.py
The script parted.py can be run like:
source env/activate
python tools/scripts/parted.py test/ttmlir/Dialect/TTNN/mnist_sharding.mlir
It will walk every op in the file and break it out into separated entry functions suitable for unit testing ops in isolation. It should largely be TTIR/TTNN dialect agnostic.
> Script for breaking up a model into isolated op tests

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOpsEnums.td
- include/ttmlir/Target/TTNN/program.fbs
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/include/tt/runtime/detail/ttnn.h
- runtime/lib/ttnn/operations/CMakeLists.txt
- runtime/lib/ttnn/operations/ccl/all_gather.cpp
- runtime/lib/ttnn/operations/ccl/all_gather.h
- runtime/lib/ttnn/program.cpp
- test/ttmlir/Dialect/TTNN/ccl/all_gather.mlir
- test/ttmlir/Dialect/TTNN/ccl/all_gather_negative.mlir
- test/ttmlir/Silicon/TTNN/ccl/all_gather.mlir
These ops are addead:
- all_gather
- reduce_scatter
Also add all_gather as a TTIR op
Closed #700
> Add CCL ops to TTNN dialect (#700)

- env/CMakeLists.txt
I have root caused LLDB hanging/crashing issue to be caused by "LLVMlib.so DW_TAG_member extends beyond the bounds error" which seems to be caused by a default C++ compiler on Ubuntu. 
Resolved by using Clang for compiling LLVM toolchain which aligns with how we build tt-mlir.
> [DebugExp] Set Clang as default llvm toolchain compiler.

- runtime/lib/ttnn/operations/creation/empty.cpp
- runtime/lib/ttnn/operations/creation/full.cpp
> #860: For creation ops, check if the output is borrowed from the user

- include/ttmlir/Conversion/Passes.h
- include/ttmlir/Conversion/Passes.td
- include/ttmlir/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.h
- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- lib/Conversion/CMakeLists.txt
- lib/Conversion/TTIRToTTIRDecomposition/CMakeLists.txt
- lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
- lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecompositionPass.cpp
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
- lib/SharedLib/CMakeLists.txt
- test/ttmlir/Dialect/TTIR/index/index_tests_negative.mlir
- test/ttmlir/Dialect/TTIR/index/index_tests_positive.mlir
- test/ttmlir/Dialect/TTIR/slice/slice_tests_negative.mlir
- test/ttmlir/Dialect/TTIR/slice/slice_tests_positive.mlir
- test/ttmlir/Silicon/TTNN/simple_index.mlir
- Create a  TTIR decomposition pass in mlir (see more here: https://github.com/tenstorrent/tt-mlir/issues/914)
- Implement an IndexOp that will be decomposed into a SliceOp. I chose not to use DRR in mlir for the decomposition of IndexOp since it involves modifying its attributes to adapt to SliceOp, and DRR is not very flexible in that regard. However, I plan to use DRR in the future for simpler decompositions.
> Introduce a TTIR decomposition pass

- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Dialect/TTNN/Transforms/Passes.td
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Dialect/TTNN/Analysis/DFShardingPolicy.cpp
- lib/Dialect/TTNN/Analysis/LegalGridAnalysis.cpp
- lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
- lib/Dialect/TTNN/Transforms/Optimizer.cpp
- lib/Dialect/TTNN/Transforms/Passes.cpp
- test/ttmlir/Dialect/TTNN/test_grid_set.mlir
Closes #1090 
As discussed in #840, we'll use ttnn.ToLayoutOp both prior to and after decomposition, however in ttnn backend this op will only be used for tilize/untilize. Once ttnn::to_layout is properly implemented to support all parameter combinations, we can simply remove the lowering pass and use this op directly for all cases.
> Remove ttnn::CompositeToLayoutOp, use ttnn::ToLayoutOp instead

- include/ttmlir/Dialect/TT/Utils/OverrideParams.h
- include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
- include/ttmlir/Dialect/TTNN/Transforms/Optimizer.h
- lib/Dialect/TTNN/Analysis/DFShardingPolicy.cpp
- lib/Dialect/TTNN/Transforms/Optimizer.cpp
- test/ttmlir/Dialect/TTNN/multiple_add_with_loc_input_layout_override.mlir
- test/ttmlir/Dialect/TTNN/test_override_reshard_edges.mlir
Reimplement Optimizer op memory reconfiguration/resharding after migration to TTNN dialect. 
Closes [#966](https://github.com/tenstorrent/tt-mlir/issues/966)
> [Optimizer] Fix mem reconfig/reshard.

- python/CMakeLists.txt
Change the link order to put extension libs last so the linker can find all necessary extension symbols for TTMLIRStatic target.
> Fix python tests in debug round 2

- lib/Dialect/TTNN/Transforms/Optimizer.cpp
- test/ttmlir/Dialect/TTNN/input_layout_loc_override.mlir
- test/ttmlir/Silicon/TTNN/sharded/mnist_sharding_tiled.mlir
Temp fix for discrepancy between MemoryConfigAttr and layout attribute of output tensor of generic version of ttnn.ToLayoutOp.
Remove op input overrides not needed anymore from Mnist sharding POC.
> [Optimizer] Fix ttnn.ToLayout mem config optimizer override.

- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPass.cpp
- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/binary/concat_op.mlir
- test/ttmlir/Conversion/StableHLOToTTIR/constant_op.mlir
* Convert integer scalars of different bit widths explicitly.
* Convert boolean values to bfloat16 due to unavailability of TTNN support.
* Convert 64-bit integers to 32-bit integers due to unavailability of TTNN
support.
> Update stablehlo.constant to TTIR conversion

- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Dialect/TTNN/Analysis/DFShardingPolicy.h
- lib/Dialect/TTNN/Analysis/DFShardingPolicy.cpp
- lib/Dialect/TTNN/Analysis/LegalGridAnalysis.cpp
- lib/Dialect/TTNN/Analysis/ShardSolver.cpp
- test/ttmlir/Dialect/TTNN/mnist_sharding.mlir
- test/ttmlir/Dialect/TTNN/multiple_add_with_loc_input_layout_override.mlir
- test/ttmlir/Dialect/TTNN/test_override_reshard_edges.mlir
- test/ttmlir/Silicon/TTNN/sharded/mnist_sharding_tiled.mlir
Add shard spec constraint within ShardSolver - match shard memory layout on input and output.
Fix height and width shard spec generation.
Add simple shard layout picker.
MNIST is now automatically sharded without overrides!
Closes [#1147](https://github.com/tenstorrent/tt-mlir/issues/1147)
> [Optimizer] Simple shard layout picker

- .github/workflows/macos-build.yml
- env/build_venv.sh
If the default python version is 3.13, build on OS X will fail, because torch 2.3.0 (specified in https://github.com/tenstorrent/tt-mlir/blob/main/test/python/requirements.txt) isn't available for python 3.13. This change should fix it.
> Specify python version (3.10)

- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Dialect/TTNN/Analysis/ShardSolver.h
- include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
- include/ttmlir/Dialect/TTNN/Transforms/Optimizer.h
- lib/Dialect/TTNN/Analysis/DFShardingPolicy.cpp
- lib/Dialect/TTNN/Analysis/LegalGridAnalysis.cpp
- lib/Dialect/TTNN/Analysis/ShardSolver.cpp
Enable resharding to be on by default when Optimizer and Memory layout analysis is enabled.
Reworked conditions for inserting resharding edge on first shard chain op. Assume it's not needed unless it is specified that targeted Op type requires it. Perform preprocessing also in case if resharding edge was passed in as override.
Closes [#1161](https://github.com/tenstorrent/tt-mlir/issues/1161)
> [Optimizer] Resharding ON by default.

- lib/Conversion/StableHLOToTTIR/ArithToStableHLOPass.cpp
- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPass.cpp
Fixes https://github.com/tenstorrent/tt-xla/issues/50.
> Marked func::CallOp as legal in StableHLOToTTIRPass and in ArithToStableHLOPass

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
- lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecompositionPass.cpp
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTIRToTTNN/TTIRToTTNNPass.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/get_dimension_size_op.mlir
- test/ttmlir/Dialect/TTNN/simple_get_dimension_size.mlir
- test/ttmlir/Silicon/TTNN/simple_eltwise.mlir
- Add end-to-end implementation of the get_dimension_size op in the HLODIalect
- It can be folded in the compiler, on the ttir level, producing a constant op
- Related to issue https://github.com/tenstorrent/tt-mlir/issues/1016
> Add support for get_dimension_size op

- include/ttmlir/Target/Common/Target.h
- include/ttmlir/Target/Common/types.fbs
- include/ttmlir/Target/TTNN/program.fbs
- include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- python/TTModule.cpp
- runtime/include/tt/runtime/detail/ttmetal.h
- runtime/include/tt/runtime/detail/ttnn.h
- runtime/include/tt/runtime/runtime.h
- runtime/include/tt/runtime/types.h
- runtime/include/tt/runtime/utils.h
- runtime/lib/runtime.cpp
- runtime/lib/ttnn/include/tt/runtime/ttnn/types.h
- runtime/lib/ttnn/include/tt/runtime/ttnn/utils.h
- runtime/lib/ttnn/operations/context/get_device.cpp
- runtime/lib/ttnn/operations/conv/conv2d.cpp
- runtime/lib/ttnn/operations/creation/empty.cpp
- runtime/lib/ttnn/operations/creation/full.cpp
- runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/utils.cpp
- runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/utils.h
- runtime/lib/ttnn/operations/layout/from_device.cpp
- runtime/lib/ttnn/operations/layout/to_device.cpp
- runtime/lib/ttnn/operations/layout/to_layout.cpp
- runtime/lib/ttnn/operations/layout/typecast.cpp
- runtime/lib/ttnn/operations/pool/maxpool2d.cpp
- runtime/lib/ttnn/program.cpp
- runtime/lib/ttnn/runtime.cpp
- runtime/tools/python/ttrt/runtime/__init__.py
- runtime/tools/python/ttrt/runtime/module.cpp
closes #696 
Added API overload for createTensor that allows for creating multi-device host tensors. 
Updated program context to use parentMesh/subMesh model instead of meshDeviceViews. When subMeshes go out of scope, if the parent is still alive, no devices will be closed.
Updated ops that explicitly require device to adapt to meshDevice accordingly.
As a POC, successfully ran a simple eltwise add op on both chips of n300 through ttrt on this branch: `jnie/multi_device_tensor_test`. Had to add a couple hacks in the mlir/flatbuffer translate, since compiler doesn't fully support multi chip attributes yet.
Current runtime caveats:
- Did not test conv2d/maxpool on multi device. These ops explicitly require the device so updated them to be able to accept  meshDevice as well, though I doubt …
> Runtime support for multi-chip tensors/ops

- runtime/tools/python/test/test_perf.py
- runtime/tools/python/ttrt/common/perf.py
The reason for this is running perf mode means the user definitely wants to see the perf result that got dumped (which happens by default) but this also dumps all the intermediate perf files generated (which is useful for users) eg. host.tracy file which can be uploaded into the GUI.
If we don't save by default, it becomes a game of trying to figure out what files not to copy into the artifacts dir (and the metal perf scripts will query the artifacts directory to do device side processing).
Closes this issue: https://github.com/tenstorrent/tt-mlir/issues/1200. (easier to just dump everything for perf than track when to dump/when not to.)
> #1200: Save all ttrt perf artifacts by default

- python/test_infra/test_ttir_ops_ttmetal.py
- python/test_infra/test_ttir_ops_ttnn.py
- python/test_infra/test_utils.py
This change moves grabbing the path for the `ttrt` generated system description from the env into decorators, so that it doesn't need to be passed into every invocation of the decorator. This is a simple cleanup change that does not change behavior.
> Cleanup system description discovery (#1184)

- docs/src/decomposing-an-op-in-ttir.md
- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
The code snippets were not rendered correctly so I fixed anchor names throughout the referenced files in the documentation
> Fix code references in op decomposition documentation

- runtime/tools/python/ttrt/common/run.py
- test/ttmlir/Silicon/TTNN/simple_add.mlir
- test/ttmlir/Silicon/TTNN/simple_eltwise.mlir
Currently we convert all integer types (int/uint) to uint since metal only supports uint. TTRT doesn't support creating uint tensors (it throws exeception).
> [Runtime][Minor fix] Support for creating uint typtes in ttrt

- python/test_infra/test_ttir_ops.py
- python/test_infra/test_utils.py
This change removes the necessity to specify the name of a test in the `compile_and_convert` decorator, using `__name__` of the decorated function to supply this instead. The option to override this choice still exists.
> Snoop `test_infra` Names (#1185)

- third_party/CMakeLists.txt
Here is another tt-metal uplift to get the next week (Nov1 -> Nov8) of changes. Much easier (an hour) than last time (2 weeks) of effort.   
This is targeting a tt-metal commit that was a recent conv2d fix (that I previously cherry-picked into current in-use metal branch.  This has benefit of us not pointing to a branch of metal, but a real (recent) origin/main metal version.
CI Runs for this uplift:
tt-mlir (passing): [link](https://github.com/tenstorrent/tt-mlir/actions/runs/11826552731)
tt-forge-fe (passing): [link](https://github.com/tenstorrent/tt-forge-fe/actions/runs/11827094308)
> Uplift third_party/tt-metal to 2024-11-08 (1d79aee)

- include/ttmlir/Dialect/TTNN/IR/CMakeLists.txt
- include/ttmlir/Dialect/TTNN/IR/TTNNBase.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOpModelInterface.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.h
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- lib/Dialect/TTNN/Analysis/ShardSolver.cpp
- lib/Dialect/TTNN/IR/CMakeLists.txt
- lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
renaming TTNNOpsBackendInterface => TTNN_OpModelInterface to avoid confusion with traditional meaning of compiler backends
> renaming TTNNOpsBackendInterface => TTNN_OpModelInterface

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Target/TTNN/program.fbs
- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/lib/ttnn/operations/eltwise/unary/unary_composite.cpp
- runtime/lib/ttnn/operations/eltwise/unary/unary_composite.h
- test/ttmlir/Conversion/StableHLOToTTIR/clamp_op.mlir
- test/ttmlir/Dialect/TTIR/clamp/clamp_tests_negative.mlir
- test/ttmlir/Dialect/TTNN/clamp/clamp_tests_negative.mlir
- test/ttmlir/Dialect/TTNN/simple_clamp.mlir
- test/ttmlir/Silicon/TTNN/perf_unit/test_perf_clamp.mlir
- test/ttmlir/Silicon/TTNN/simple_eltwise.mlir
* Add end-to-end implementation of the ops.
* Add stablehlo to ttir conversion for clamp op.
> Add support for clamp op

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- test/ttmlir/Dialect/TTNN/pooling/complex_pooling.mlir
- test/ttmlir/Dialect/TTNN/pooling/simple_pooling.mlir
- test/ttmlir/Silicon/TTNN/pooling/complex_pooling.mlir
- test/ttmlir/Silicon/TTNN/pooling/simple_pooling.mlir
The crash reported in this issue comes from the initialization of a tensor using `ttnn.full`. However, this `ttnn.full` call is actually dangling code and should be removed from the program entirely. 
Also fixed a bug where inputs with non-bf16 data formats wouldn't pattern match when converting from `stablehlo.reduce_window`. There is now a verification for `ttnn.max_pool2d` that will return an error if the input is not bf16.
Issue: https://github.com/tenstorrent/tt-xla/issues/64
> Erase reduce_window init values

- python/test_infra/test_utils.py
- python/test_infra/ttir_builder.py
This change embeds source file name and line number into the MLIR module generated during `test_infra` tests. The location refers to the decorated function, e.g. `test_add`
> Embed Loc Info From `test_infra` Tests (#1187)

- include/ttmlir-c/TTAttrs.h
- include/ttmlir/Bindings/Python/TTMLIRModule.h
- lib/CAPI/TTAttrs.cpp
- python/CMakeLists.txt
- python/TTModule.cpp
- python/TTNNModule.cpp
- Manually defined downcasting methods. Goal is to autogenerate these, should be decently easy to integrate with tblgen for the cpp methods, but difficult to throw into the pybind declaration itself. Was easier to do a short sighted fix where these methods are manually defined.
- Used `dyn_cast` instead of `cast` for a safer call signature. Failure will be defined through the function resulting in `None` instead of a full failure.
-
> Added maybe_downcast & hardened TT Attrs and Types to include better support

- docs/src/ttrt.md
- python/test_infra/ttir_builder.py
- runtime/include/tt/runtime/detail/debug.h
- runtime/include/tt/runtime/detail/ttmetal.h
- runtime/include/tt/runtime/detail/ttnn.h
- runtime/include/tt/runtime/runtime.h
- runtime/include/tt/runtime/types.h
- runtime/lib/binary.cpp
- runtime/lib/common/debug.cpp
- runtime/lib/runtime.cpp
- runtime/lib/ttmetal/runtime.cpp
- runtime/lib/ttnn/include/tt/runtime/ttnn/types.h
- runtime/lib/ttnn/program.cpp
- runtime/lib/ttnn/runtime.cpp
- runtime/tools/python/ttrt/binary/module.cpp
- runtime/tools/python/ttrt/common/golden.py
- runtime/tools/python/ttrt/common/run.py
- runtime/tools/python/ttrt/common/util.py
- runtime/tools/python/ttrt/runtime/__init__.py
- runtime/tools/python/ttrt/runtime/module.cpp
The goal of this PR is to introduce golden support in runtime. The design was taken into account that other runtimes can plug into MLIR runtime (ttrt is just one possible frontend for mlir runtime). The frontend building off MLIR runtime can register a "callback" function through python, which will return ProgramContext* and Operation* - to be run after every op is executed. The frontend can then call supporting APIs to return currently running data.
- golden information embedded into the flatbuffer as a golden_map
- key = loc() of the operation
- value = vector(float)
- ability to dump debug string from both Operation* and it's OpType*
- added Hook callback function to execute after every op
- python interface with C++ runtime can initialize a callback function that will return …
> #1190: Added runtime support for doing golden comparision for flatbuffers in ttrt

- .github/CODEOWNERS
- include/ttmlir/Dialect/TTNN/Analysis/ShardSolver.h
- lib/Dialect/TTNN/Analysis/DFShardingPolicy.cpp
- lib/Dialect/TTNN/Analysis/ShardSolver.cpp
- test/unittests/CMakeLists.txt
- test/unittests/Optimizer/CMakeLists.txt
- test/unittests/Optimizer/TestShardSolver.cpp
Replace trivial greedy approach which was producing potentially suboptimal solution. First heuristic used here is to maximize global core usage, but can easily be replaced with per OP performance API in future with target to minimize time spent in execution.
Introducing Optimizer unit tests, with ShardSolver and produceMaxCoreUsage as the first test.
Closes #1250.
> [Optimizer] Globally optimal shard config picker(numcores).

- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
- include/ttmlir/Dialect/TTKernel/IR/TTKernelOpsTypes.td
- lib/Conversion/TTIRToTTMetal/TTIRToTTMetal.cpp
- lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- lib/Dialect/TTIR/Transforms/Allocate.cpp
- lib/Target/TTMetal/TTMetalToFlatbuffer.cpp
- runtime/include/tt/runtime/detail/ttmetal.h
- runtime/lib/ttmetal/command_queue.cpp
- test/ttmlir/Conversion/TTKernelToEmitC/ttkernel.mlir
fixes #781 
When lowering reduce op, compiler will add additional CB that will represent scaler CB needed by LLK. ScalerCB is filled by constant according to type of reduce operation.
An idea is to leave preallocated space at the top of L1 memory for misc usage in kernels. Scaler CB should be placed inside of this region. Also, TTIR ops should not have context of scaler CB. It should appear only in TTKernel dialect as additional arg when lowering reduce operations.
ScalerCB is populated during kernel runtime, and that should be done in NOC thread since that thread can read zeros in a burst.
For example, loading scaler cb in data movement kernel looks like
```
::tt::CB v3 = ::tt::CB::c_in1;
::tt::CB v4 = v3;
int32_t v5 = 1065369472;
int32_t v6 = 1;
cb_reserve_back(v4, v6);
int32_t v7 = …
```
> [Direct Metal] Insert scaler CB in reduce kernels

- runtime/include/tt/runtime/detail/ttnn.h
- runtime/lib/ttnn/operations/data_movement/transpose.cpp
Previously, transpose was decomposed in runtime to permute. This PR transfers directly to ttnn::transpose. 
I ran transpose tests on forge with this change and everything seems fine. 
@vladimirjovanovicTT do you have some insight for why you added this decomposition? Was that a workaround due to some transpose case failing or transpose wan't implemented (less likely)?
> Use ttnn::transpose instead of runtime decomposing transpose

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
- test/ttmlir/Dialect/TTIR/convolution/convolution_tests_negative.mlir
- test/ttmlir/Dialect/TTNN/convolution/complex_conv_channel_first.mlir
- test/ttmlir/Silicon/TTNN/complex_conv_channel_first.mlir
The tt-xla conv2d tests are failing because the default padding attribute for `ttir.convolution` is not being generated properly. 
- All `DefaultValuedOptionalAttr`s for `ttir.convolution` are now mandatory.
- In conversion from stablehlo, if `stablehlo.convolution` is missing these attributes, we populate `ttir.convolution` with the default intended attribute for `stablehlo.convolution` as stated in the comments of `StablehloOps.td::StableHLO_ConvolutionOp`
> Do not use default values for ttir.convolution

- runtime/tools/python/setup.py
- test/ttmlir/Silicon/TTNN/simple_reductions.mlir
2 small changes independent from but related to tt-metal uplifts.  Was sitting on this for a bit un un-approved metal uplift PR, so spawning to it's own dedicated PR:
- remove dep on libfmt.so required to solve compile error with upcoming tt-metal uplifts
- new test to cover tt-metal bug caught by tt-forge-fe but not tt-mlir during my recent tt-metal uplift effort (https://github.com/tenstorrent/tt-metal/issues/15167)
> Pair of tt-metal uplift improvements (new test, remove dep on libfmt.so)

- include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
- lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
- test/ttmlir/Dialect/TTNN/pipelines/ttir_to_emitc_add.mlir
As outlined in the [EmitC spec](https://tenstorrent-my.sharepoint.com/:w:/r/personal/svuckovic_tenstorrent_com/Documents/EmitC%20Spec.docx?d=wca1db2049282411583a16ed46456814c&csf=1&web=1&e=eIJugr), adding a TTIR to EmitC pipeline. The pipeline runs the `--ttir-to-ttnn-backend-pipeline` under the hood, and then runs the `--convert-ttnn-to-emitc` pass. Its options also extend the `TTIRToEmitCPipelineOptions` struct.
So instead of running
```
./build/bin/ttmlir-opt --ttir-to-ttnn-backend-pipeline="system-desc-path=ttrt-artifacts/system_desc.ttsys" --convert-ttnn-to-emitc test/ttmlir/Silicon/TTNN/emitc/simple_add.mlir
```
One can now run
```
./build/bin/ttmlir-opt --ttir-to-emitc-pipeline="system-desc-path=ttrt-artifacts/system_desc.ttsys" test/ttmlir/Silicon/TTNN/emitc/simple_add.mlir
```
To …
> Add TTIR to EmitC pipeline

- runtime/tools/python/ttrt/binary/__init__.py
- runtime/tools/python/ttrt/binary/stats.py
- runtime/tools/python/ttrt/common/read.py
This commit adds new ttrt API `construct_op_stats_json` that can be used as a common method for all frontends to generate op test sweep data. The format isn't fully established, but this is just serving as the boilerplate to begin wiring up all of the pieces with frontends.
Example FE usage:
```python
import ttrt.binary
@op_test_harness("llama7b")
def test_softmax():
return torch.softmax(...)
def op_test_harness(model):
def wrapper(test_fn):
flatbuffer_binary = compile(test_fn)
stats = ttrt.binary.stats.construct_op_stats_json(
"forge-fe",
model,
flatbuffer_binary
)
aggregate_or_write_to_file(stats)
return wrapper
```
Example Op Data:
```json
{
"op_name": "ttnn.softmax",
"framework_op_name": "",
"dialect_op_name": "",
"ttir_op_name": "",
"inputs": [
{
"shape": [ 1, 10 ],
"data_type": …
```
> Bootstrap python hooks for collecting DB information for op tests

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
- lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecompositionPass.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/gather_op.mlir
- test/ttmlir/Dialect/TTNN/embedding/gather_to_embedding.mlir
- test/ttmlir/Dialect/TTNN/embedding/gather_to_embedding_negative.mlir
- test/ttmlir/Silicon/TTNN/embedding/gather_to_embedding.mlir
Gather op implemetation end-to-end.
SHLO GatherOp --> TTIR Gather Op --> TTIR Embedding Op (+ if needed, Reshape Op) --> TTNN Embedding Op (+ if needed, Reshape Op)
TTNN does not currently support Gather Op, but had Embedding Op support.
Given that Torch Embedding is lowered into SHLO Gather Op, and that most
Gather Ops in models are simple embeddings, Gather Op is lowered into
Embedding Op. If more sophisticated Gather Op implementations are
encountered, then Gather could be lowered into slice/ concat/ etc if
needed.
Gather Op checks certain criteria to ensure lowering into Embedding Op
in lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
- Output tensor shape: Multi-dimensional with last dimension as
embedding size/ hiddenDim
- Slice sizes: Must be [1, hiddenDim], where …
> Gather op implementation [#1015]

- third_party/CMakeLists.txt
This gets us another week (Nov8 -> Nov15) of tt-metal.  Using stable tt-metal [42035c1711](https://github.com/tenstorrent/tt-metal/commit/42035c171179b945d71d8a16390c30bf177cb575) from tt-metal main plus a cherry pick fix for an assertion fix (not yet on tt-metal main, but expected to go in soon).
CI Runs:
tt-mlir (Passing): [link](https://github.com/tenstorrent/tt-mlir/actions/runs/11862788450)
tt-forge-fe (Running) : [link](https://github.com/tenstorrent/tt-forge-fe/actions/runs/11863453098)
Would merge if approved and if tt-forge-fe is passing.
> Uplift third_party/tt-metal to 2024-11-15 (42035c1711 + cherry-pick fix)

- .gitignore
- Keeps getting autogenerated from UMD, seems handy to just ignore it.
> Add cluster_descriptor.yaml to gitignore

- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/gather_op.mlir
- test/ttmlir/Dialect/TTNN/embedding/gather_to_embedding.mlir
- test/ttmlir/Dialect/TTNN/embedding/gather_to_embedding_negative.mlir
- test/ttmlir/Silicon/StableHLO/gather_op.mlir
* Use updated operands during stableHLO to TTIR conversion
* Add check to ensure the input argument data type is bfloat16
* Add stablehlo runtime test for gather op
Fixes #1336
> Minor fixes for stablehlo.gather op

- .github/workflows/nightly-uplift.yml
Fixes missing SHA in title and description. Basically copied over from https://github.com/tenstorrent/tt-xla/blob/main/.github/workflows/nightly-uplift.yml. In tt-xla repo last successful nightly looks like [this](https://github.com/tenstorrent/tt-xla/pull/74).
> Small improvements to gh nightly uplift yaml

- docs/src/ttmlir-translate.md
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitCPass.cpp
- test/ttmlir/Silicon/TTNN/emitc/two_fns.mlir
- tools/ttnn-standalone/README.md
- tools/ttnn-standalone/ttnn-standalone.cpp
Running:
```
./build/bin/ttmlir-opt --ttir-to-ttnn-backend-pipeline="system-desc-path=ttrt-artifacts/system_desc.ttsys" --convert-ttnn-to-emitc test/ttmlir/Silicon/TTNN/emitc/simple_add.mlir > binary.mlir
./build/bin/ttmlir-translate --mlir-to-cpp binary.mlir
```
Produces an error:
```bash
binary.mlir:1:15: error: #"tt"<"device<workerGrid = #tt.grid<8x8, (d0, d1) -> (0, d0, d1)>, l1Map = (d0, d1)[s0, s1] -> (0, d0 floordiv s0, d1 floordiv s1, (d0 mod s0) * s1 + d1 mod s1), dramMap = (d0, d1)[s0, s1] -> (0, 0, ((((d0 floordiv s0) * 8 + d1 floordiv s1) * (s1 * s0) + (d0 mod s0) * s1 + d1 mod s1) floordiv 8192) mod 12, (((d0 floordiv s0) * 8 + d1 floordiv s1) * (s1 * s0) + (d0 mod s0) * s1 + d1 mod s1) floordiv 98304 + (((d0 floordiv s0) * 8 + d1 floordiv s1) * (s1 * s0) + (d0 mod s0) * s1 + …
```
> Fix unregistered dialects error message (ttmlir-translate)

- lib/Dialect/TTNN/IR/TTNNOps.cpp
Fixes #1360 
Logs with `error: 'ttnn.clamp' op input and output must have same shape.`
[distilbert_before.log](https://github.com/user-attachments/files/17841299/distilbert_before.log)
[bart_before.log](https://github.com/user-attachments/files/17841304/bart_before.log)
Logs after fix:
[distilbert_log.log](https://github.com/user-attachments/files/17841302/distilbert_log.log)
[bart_log.log](https://github.com/user-attachments/files/17841303/bart_log.log)
> Fix: input and output must have same shape for matching shapes

- python/TTModule.cpp
Nitpick fix PR to address minor issues discussed in previous PR.  Noted that this file has some `for (auto X` loops that should really be `for (const auto& X` to avoid unneeded copying.  Vectors in the lambda have same issue too.
> Cleanup some places where unneeded copies are created

- .github/workflows/issue-last-updated.yml
The existing workflow will only work if the issue ID is found in the first  100 ITEM_IDs.
These updates should enable pagination to occur through all the existing issues.
I attempt to use `items(last: 100, before: $cursor) {` 
under the assumption that it would be faster to find the latest issues, however this functionality wasn't working with the API when I was testing it locally.
I got this code to run locally and paginate through the issues as expected(code below so this workflow update is to add this to the `get_item_id_by_issue_id` section of the workflow.
Please let me know what feedback or if you think there is a better way to accomplish this. 
```
#!/bin/bash
GITHUB_TOKEN="YOUR_GITHUB_TOKEN"
PROJECT_ID="PVT_kwDOA9MHEM4AjeTl"  # Example Project ID
ISSUE_NODE_ID="I_kwDOMKpl8c6eFjOV" …
```
> adding pagination to find item ids

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Target/TTNN/program.fbs
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/lib/ttnn/operations/matmul/matmul.cpp
- runtime/lib/ttnn/operations/matmul/matmul.h
- runtime/lib/ttnn/program.cpp
- test/ttmlir/Dialect/TTIR/linear/linear_tests_negative.mlir
- test/ttmlir/Dialect/TTNN/linear/linear_tests_positive.mlir
- test/ttmlir/Dialect/TTNN/linear/simple_linear.mlir
- test/ttmlir/Silicon/TTNN/perf_unit/test_perf_linear.mlir
- test/ttmlir/Silicon/TTNN/simple_linear.mlir
Some remarks:
- Semantics of linear in [torch](https://pytorch.org/docs/stable/generated/torch.nn.Linear.html) and [ttnn](https://docs.tenstorrent.com/ttnn/latest/ttnn/ttnn/linear.html) are different, that's something to think about.
- verify() is mostly duplication of MatmulOp::verify(). I didn't want to refactor it, because it would ruin documentation that already exists for matmul and if in the future we decide change linear in TTIR, it would only make it worse. verify() should be stable for both ops, so duplication doesn't seem like a problem here.
Closes https://github.com/tenstorrent/tt-mlir/issues/925
> Added LinearOp support

- .gitignore
These flatbuffer files are generated as part of `test_infra`, and should not be comitted.
> Ignore `*.ttnn` & `*.ttm` Files

- include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
- lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
Add NoC multicast ops to `ttkernel` dialect.
The following ops are defined:
- `get_noc_multicast_addr`
- `noc_async_write_multicast_one_packet`
- `noc_async_write_multicast`
- `noc_async_write_multicast_loopback_src` 
TODO: 
- Add test case that utilizes these ops (likely matmul)
- `buildMulticastNocAsyncTx` utility similar to `buildNocAsyncTx`
> Add NoC Mcast Ops in D2M

- .github/workflows/produce_data.yml
Initial commit for collecting workflow data, SFTP upload is commented out until we can confirm that generated files are in the correct format.
We need to merge "workflow_run" workflow to test is first. 
In followup PR we will enable SFTP upload and collect test report files.
> Collect test reports

- include/ttmlir/Dialect/TT/IR/TTOpsEnums.td
- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/ccl_ops.mlir
- Overall Plan
As a first step of multi-device support plan, this PR allows to convert the MLIR outputs that target all_reduce op from JAX/OpenXLA(GSPMD)/PJRT. There will be following several PRs, which allow the computation flows from TTIR down to runtime. Detailed steps are as follows.
(1) Convert MLIRs from JAX/OpenXLA/PJRT to TTIR (this PR)
(2) Pass converted TTIR to TTNN MLIR and Flatbuffer format
(3) Parse TTNN flatbuffer and execute in TT Runtime
Although current version of code is targeting GSPMD partitioned MLIRs, our future plan mainly aims at supporting Shardy-based JAX/PJRT MLIRs.
- Implementation Details
In general, GSPMD partitioned MLIR has following computation pattern, 
A. Shard inputs for computation in multi-device
%0 = stablehlo.custom_call @Sharding(%arg0) …
> Enable conversion of all_reduce and GSPMD custom_op into TTIR dialect

- lib/Target/TTNN/TTNNToFlatbuffer.cpp
Concrete op types shouldn't be shadowed by template arguments when they are only ever going to be instantiated with concrete types with the same name anyway, it's confusing for no reason.
> Minor fix of TTNNToFlatbuffer createOps

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTIR/IR/TTIROpsInterfaces.h
- include/ttmlir/Dialect/TTIR/IR/TTIROpsInterfaces.td
- lib/Dialect/TTIR/IR/TTIROpsInterfaces.cpp
- test/ttmlir/Dialect/TTIR/ttir_broadcastable_negative.mlir
- test/ttmlir/Dialect/TTIR/ttir_noperands_negative.mlir
- Refactoring of ElementwiseOpInteface to better reflect intention, with a fix of broadcast shape calculation, considering that the operand that represents the destination shouldn't affect output shape.
- Check the number of operands for AttrSizedOperandSegments ops with simple traits.
- Minor refactoring of TTIR_GenericOp.
This addresses https://github.com/tenstorrent/tt-mlir/issues/1289, but I would leave it open to track further progress on similar traits and interfaces needed in the TTNN dialect.
> Additional verifications of TTIR dialect ops

- include/ttmlir/Dialect/TTNN/IR/TTNNOpsAttrs.td
- include/ttmlir/Dialect/TTNN/Utils/Utils.h
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Dialect/TTNN/IR/TTNNOpsAttrs.cpp
- lib/Dialect/TTNN/Transforms/Optimizer.cpp
- lib/Dialect/TTNN/Transforms/Passes.cpp
This PR adds couple convenience methods to TTNN tensor encoding attribute and also removes redundant utils functions.
Renaming/Adding some new functions...
* `getDataType` to get scalar data type:
* `memref<2x2x!tt.tile<32x32xf32>>` returns float data type
* `memref<128x128xi32>` returns int data type
* `getElementType` to get type from memref:
* `memref<2x2x!tt.tile<32x32xf32>>` returns TileType
* `memref<128x128xi32>` returns IntegerType
* `getLayout` - gets layout of encoding i.e Tile/RowMajor
* `getShardShape`:
* `memref<2x2x!tt.tile<32x32xf32>>` returns `(2, 2)`
* `memref<128x128xi32>` returns `(128, 128)`
* `getScalarShardShape`:
* `memref<2x2x!tt.tile<32x32xf32>>` returns `(64, 64)`
* `memref<128x128xi32>` returns `(128, 128)`
> Minor API fixes for TTNN encoding ettribute

- .github/workflows/nightly-uplift.yml
Dissable auto-merge for now until we are more confident  that uplift won't break the downstream projects
> Dissable uplift auto-merge

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Target/TTNN/program.fbs
- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/lib/ttnn/operations/eltwise/binary/binary_composite.cpp
- runtime/lib/ttnn/operations/eltwise/binary/binary_composite.h
- runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/eltwise/binary/utils.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/scatter_op.mlir
- test/ttmlir/Dialect/TTNN/simple_scatter.mlir
- test/ttmlir/Silicon/TTNN/simple_eltwise.mlir
As part of the effort to run stableHLO models on TT silicon, lowering scatter op through TTIR and TTNN dialects.
This op currently has limited functionality, but enough to pass the current models, primarily due to the current limitations in tt-metal:
- The op only supports one index, mimicking Torch's `select_scatter` op https://pytorch.org/docs/stable/generated/torch.select_scatter.html
- Furthermore, since we do not currently support any indexing on the tt-metal side (https://github.com/tenstorrent/tt-metal/issues/4294), it will ignore the ttir index variable and use index 0, as supported by tt-metal.
- The StableHLO scatter op also supports adding a custom function for merging the two tensor operands of the scatter. Since this is not supported in tt-metal, I have added the check to see …
> Add conversion for StableHLO scatter op to TTIR and TTNN dialect

- lib/Conversion/TTKernelToEmitC/CMakeLists.txt
- tools/CMakeLists.txt
- tools/ttmlir-lsp-server/CMakeLists.txt
- tools/ttmlir-lsp-server/ttmlir-lsp-server.cpp
This change introduces the tool `ttmlir-lsp-server`. It will fall under `build/bin`, and is built alongside the rest of the compiler via `cmake --build build`. This is a language server that should be used alongside your IDE/Text editor to give you IDE like features while editing `.mlir` files. For more info, please see [here](https://mlir.llvm.org/docs/Tools/MLIRLSP/#mlir-lsp-language-server--mlir-lsp-server)
Closes #1383
> Create `ttmlir-lsp-server` (#1383)

- include/ttmlir/Dialect/TTNN/IR/CMakeLists.txt
- include/ttmlir/Dialect/TTNN/IR/TTNNBase.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.h
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOpsAttrs.td
- include/ttmlir/Dialect/TTNN/IR/TTNNWorkaroundInterface.h
- include/ttmlir/Dialect/TTNN/IR/TTNNWorkaroundInterface.td
- include/ttmlir/Dialect/TTNN/IR/TTNNWorkarounds.h
- include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
- include/ttmlir/Dialect/TTNN/Transforms/Passes.td
- include/ttmlir/Dialect/TTNN/Utils/TransformUtils.h
- include/ttmlir/Dialect/TTNN/Utils/Utils.h
- include/ttmlir/Utils.h
- lib/Conversion/TTIRToTTNN/CMakeLists.txt
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Dialect/TTNN/IR/CMakeLists.txt
- lib/Dialect/TTNN/IR/TTNNOpsAttrs.cpp
- lib/Dialect/TTNN/IR/TTNNWorkaroundInterface.cpp
- lib/Dialect/TTNN/IR/TTNNWorkarounds.cpp
- lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
- lib/Dialect/TTNN/Transforms/CMakeLists.txt
- lib/Dialect/TTNN/Transforms/TTNNWorkarounds.cpp
- lib/Dialect/TTNN/Utils/CMakeLists.txt
- lib/Dialect/TTNN/Utils/TransformUtils.cpp
- lib/Dialect/TTNN/Utils/Utils.cpp
- test/ttmlir/Dialect/TTNN/Transforms/Workarounds/simple_workaround.mlir
This PR introduces the initial implementation of a workaround pass in the TTNN dialect. It establishes the foundation for handling operation-specific workarounds by defining interfaces and data structures and includes the initial logic for applying these workarounds. While the logic is disabled by default in this PR, future updates will gradually enable it in the compiler. Below is a summary of the changes:
- Introduced TTNNWorkaround classes to abstract the workarounds we can currently specify
- Introduced the TTNNWorkaroundInterface in the TTNN dialect
- Interface for now retrieves the operation operand workarounds mentioned above for:
- Tensor Layout
- Tensor Buffer Type
- Tensor Memory Layout
- For now, the interface provides default values. However, as a proof of concept, custom …
> Workaround pass - Initial implementation

- include/ttmlir/Dialect/TTIR/IR/TTIRBase.td
- include/ttmlir/Dialect/TTNN/IR/TTNNBase.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- test/ttmlir/Dialect/TTIR/test_remove_dead_values_pass.mlir
- test/ttmlir/Dialect/TTNN/test_remove_dead_values_pass.mlir
- Added MLIR's `Pure` attribute to all TTIR and TTNN ops since they are pure SSA ops.
- MLIR's built-in `RemoveDeadValues` pass can now trim dead code off of TTIR and TTNN modules effectively.
> Mark all TTIR and TTNN ops as pure

- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- test/ttmlir/Dialect/TTNN/ccl/all_gather.mlir
This fixes the incorrect conversion of the ttnn all_gather op. It should not use the output of an EmptyOp as the input to all_gather.
Testing with:
```bash
./build/bin/ttmlir-opt --ttir-to-ttnn-backend-pipeline test/ttmlir/Dialect/TTNN/ccl/all_gather.mlir
```
Before:
```mlir
func.func @forward(%arg0: tensor<1x1x32x32xbf16, #layout>) -> tensor<1x1x32x128xbf16, #layout1> {
%0 = "ttnn.get_device"() <{mesh_shape = #ttnn<mesh_shape 1x1>}> : () -> !tt.device<#device>
%1 = "ttnn.to_device"(%arg0, %0) <{memory_config = #ttnn.memory_config<<interleaved>, <dram>, <<1x1>>>}> : (tensor<1x1x32x32xbf16, #layout>, !tt.device<#device>) -> tensor<1x1x32x32xbf16, #layout2>
%2 = "ttnn.to_layout"(%1) <{layout = #ttnn.layout<tile>}> : (tensor<1x1x32x32xbf16, #layout2>) -> tensor<1x1x32x32xbf16, #layout2> …
```
> Fix TTIR to TTNN conversion for all gather

- lib/Conversion/TosaToTTIR/TosaToTTIRPatterns.cpp
- test/ttmlir/Conversion/TosaToTTIR/matmul_op.mlir
Adds conversion for [tosa.matmul](https://mlir.llvm.org/docs/Dialects/TOSA/#tosamatmul-mlirtosamatmulop)
closes #1416
> Add TOSA to TTIR conversion for matmul

- runtime/include/tt/runtime/detail/ttnn.h
- runtime/include/tt/runtime/runtime.h
- runtime/lib/runtime.cpp
- runtime/lib/ttnn/runtime.cpp
- runtime/test/python/ttnn/test_runtime_api.py
- runtime/tools/python/ttrt/runtime/module.cpp
Add `memcpy(void *, Tensor)` API
tt-xla stores the source runtime tensor but only a dest data pointer, thus this API will support this use-case and save the user the trouble of creating a runtime tensor just to copy the data into a pointer.
FYI @kmitrovicTT
> Add new memcpy API

- include/ttmlir/Dialect/TTNN/Transforms/Passes.td
- include/ttmlir/Dialect/TTNN/Utils/Utils.h
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Dialect/TTNN/Transforms/Passes.cpp
- lib/Dialect/TTNN/Utils/Utils.cpp
- test/ttmlir/Dialect/TTNN/Transforms/ttnn_create_input_gens_0.mlir
For each "forward" function that exists in the top-level module, this newly introduced pass `TTNNCreateInputGenerators` will create a function that generates input tensors. Additionally, the pass will create a "main" function that will call the input generators and the forward functions.
> Add pass to create input tensor generator functions for emitc path

- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
Issue https://github.com/tenstorrent/tt-mlir/issues/1471 was raised because the typecast operation translation from `ttir` to `ttnn` dialects failed due to the typecast operation in question being dead code. This PR removes this check. 
The code snippet in the issue will still fail on silicon because of the fact that full ops is not currently produced in TILE format and therefore typecast op cannot run the operand. See issue https://github.com/tenstorrent/tt-mlir/issues/850
Fixes https://github.com/tenstorrent/tt-mlir/issues/1471
> Removed dead code check for typecast

- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
- include/ttmlir/Dialect/TTNN/Transforms/Passes.td
- include/ttmlir/Target/TTNN/program.fbs
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
- lib/Dialect/TTNN/Transforms/TTNNWorkarounds.cpp
- lib/Dialect/TTNN/Utils/TransformUtils.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- test/ttmlir/Dialect/TTNN/Transforms/Workarounds/simple_workaround.mlir
- test/ttmlir/Dialect/TTNN/ccl/all_gather.mlir
- test/ttmlir/Dialect/TTNN/ccl/all_reduce.mlir
- test/ttmlir/Dialect/TTNN/ccl/all_reduce_negative.mlir
- test/ttmlir/Dialect/TTNN/ccl/mesh_shard.mlir
- Overall Plan
As a second step of multi-device support plan, this PR allows to lower all_reduce and mesh_shard ops to TTNN and flatbuffer format. 
1. Convert MLIRs from JAX/OpenXLA/PJRT to TTIR (merged)
2. Pass converted TTIR to TTNN MLIR and Flatbuffer format (this PR)
3. Parse TTNN flatbuffer and execute in TT Runtime
- Implementation Details
The all_reduce op lowering needs special handling in this PR.
Although all_reduce lowering is supposed to be one to one mapping from ttir all_reduce to ttnn all_reduce, the all_reduce ops are broken down into reduce_scatter and all_gather ops because current support of all_reduce in TTNN is not stable.
In addition, the reduce_scatter op in TTNN currently does not support two dimensional tensor correctly. As a temporary workaround, we insert …
> Enable lowering ttir all_reduce and mesh_shard to ttnn and flatbuffer

- .github/workflows/on-pr.yml
Trigger workflows in tt-forge-fe via the GitHub GH CLI when all tests pass and the source branch is uplift.
Start workflow with
- test group: push and
- SHA of the uplift branch
Relates to #214
> Trigger the downstream checks on uplift run

- CONTRIBUTING.md
- docs/src/SUMMARY.md
- docs/src/coding-guidelines.md
I am sharing the first draft of our coding style guidelines. I noticed several instances where we discussed different coding approaches. Having a single, agreed-upon document will provide us with clarity and help us avoid confusion about how to write our code.
The intention is to start with this document, and we can build upon it by adding additional guidelines as we see fit and agree upon them.
> Adding coding style guidelines into our docs

- include/ttmlir/Dialect/TTNN/Analysis/BFInterleavedPolicy.h
- lib/Dialect/TTNN/Analysis/BFInterleavedPolicy.cpp
Instead of analyzing greedily the next state based on only currently scheduleable ops, this extended version of the policy introduces the lookahead. It is only restricted to simple chains of ops (no fork nor join ops in the lookahead). This way, the policy will make a decision based on the larger picture of the graph and avoid falling into the non-global optimum. This is only true if we assume that the lookahead stops when 1) we reach fork or join node, or 2) forced to do DRAM spill due to the shortage of L1 memory.
> [Optimizer] L1 Interleaved policy that solves simple fork-joins with the extension of solving chains in parallel

- include/ttmlir/Conversion/TTNNToEmitC/Utils.h
- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Dialect/TTNN/Utils/Utils.h
- include/ttmlir/Target/TTNN/program.fbs
- include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTNNToEmitC/CMakeLists.txt
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Conversion/TTNNToEmitC/Utils.cpp
- lib/Dialect/TTNN/Utils/Utils.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/lib/ttnn/include/tt/runtime/ttnn/utils.h
- runtime/lib/ttnn/operations/CMakeLists.txt
- runtime/lib/ttnn/operations/creation/ones.cpp
- runtime/lib/ttnn/operations/creation/ones.h
- runtime/lib/ttnn/program.cpp
- runtime/lib/ttnn/runtime.cpp
- test/ttmlir/Conversion/TTNNToEmitC/ones.mlir
- test/ttmlir/Silicon/TTNN/ones.mlir
This PR adds support for `ttnn::ones()` op.
- A ttnn-to-emitc utils file has been added
- In `MLIRToFlatbuffer.h`, two `toFlatbufferOptional` method have been added to make the `TTNNToFlatbuffer.cpp` code cleaner, as all the optional stuff is abstracted away
- More streamlined conversion of the op in `TTNNToEmitC.cpp`, would like to try to apply this to other ops, and hopefully create a generic solution that would work for most ops without any special case handling
- In a similar manner, `run()` method in `runtime/lib/ttnn/operations/creation/ones.cpp` has been written so that it "mechanically" unpacks a flatbuffer and calls the appropriate ttnn method - it would be great if we could make this generic so that we don't need to manually handle each op
N̶o̶t̶e̶:̶ ̶t̶h̶e̶r̶e̶'̶s̶ ̶a̶ …
> Add ttnn::ones() op

- python/test_infra/ttir_builder.py
- runtime/include/tt/runtime/detail/debug.h
- runtime/tools/python/ttrt/binary/__init__.py
- runtime/tools/python/ttrt/binary/module.cpp
- runtime/tools/python/ttrt/common/golden.py
- runtime/tools/python/ttrt/common/run.py
- runtime/tools/python/ttrt/common/util.py
- runtime/tools/python/ttrt/runtime/__init__.py
- runtime/tools/python/ttrt/runtime/module.cpp
This change introduces a PyBound class `GoldenTensor` that reflects the same type from TTRT. This binding supports the following element types for a `GoldenTensor`:
- uint8
- uint16
- uint32
- float32
Closes #1294
> PyBind `GoldenTensor` w/ Integral Types (#1294)

- CMakeLists.txt
- lib/CMakeLists.txt
* Address sanitization build causes errors for python bindings and shared libs. Other MLIR based projects (IREE, Stablehlo) seem to have similar issues and just skip building these components for sanitization builds.
* Address sanitization can be enabled by setting '-DCMAKE_BUILD_TYPE=Asan -DTTMLIR_ENABLE_SHARED_LIB=OFF -DTTMLIR_ENABLE_BINDINGS_PYTHON=OFF' options with cmake command.
closes #1561
> Add checks for Asan build type

- tools/explorer/run.py
- Added `-p, --port` ,`-u, --url`, and `-q, --no-browser` arguments to control how tt-explorer is invoked.
- Added some simple help messages in `argparse`.
- PR closes #1543
> Added arguments to tt-explorer program

- test/ttmlir/Decomposition/TTIR/arange/arange_tests_positive.mlir
This test failed due to removal of TTIR operand_constraint (#1388).
> Fix lit test for ttir.arange decomposition

- include/ttmlir/Dialect/TTIR/IR/TTIRBase.td
- lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
- lib/Dialect/TTIR/IR/TTIRDialect.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- test/ttmlir/Dialect/TTIR/Decomposition/get_dimension_size_decomposition.mlir
`ConstantOp` in the TTIR dialect has a `ConstantLike` trait so constants can be materialized into `ttir.constant` operation. We already have one use case, where `GetDimensionSizeOp` is folded into `Attribute`, so instead of decomposition, a folding into `Attribute` and materialization into `ConstantOp` takes a more natural approach.
For all future use cases of `FooOpToConstantOp` conversions, instead of implementing pattern rewriting, it's enough to fold `FooOp` into `mlir::ElementsAttr`.
> TTIR constant materialization

- include/ttmlir/Dialect/TTNN/Analysis/ShardSolver.h
- lib/Dialect/TTNN/Analysis/ShardSolver.cpp
- test/unittests/Optimizer/TestShardSolver.cpp
Extend Shardsolver with support for passing in custom constraint check function. 
Integrate custom check function in unit tests so that they are not impacted with future implementation of proper E2E constraint check API.
Closes #1287.
> [Optimizer/Test] Add ability to pass in custom constraint check function.

- tools/explorer/CMakeLists.txt
- tools/explorer/test/run_tests.py
- tools/explorer/tt_adapter/src/tt_adapter/main.py
- tools/explorer/tt_adapter/src/tt_adapter/mlir.py
- tools/explorer/tt_adapter/src/tt_adapter/runner.py
Explorer execute command now spawns a new thread in which all model compile and execution is handled. Results are stored as state on the server and will be sent to the frontend with the next covert command.
Additionally:
* Use subprocesses for compile and to_flatbuffer in order for asserts to not kill the server
* Setup high level error messages for execution steps
* Send incremental logs to the frontend
> Move explorer execution to background

- runtime/include/tt/runtime/detail/ttmetal.h
- runtime/lib/ttmetal/runtime.cpp
- test/ttmlir/Silicon/TTMetal/perf_unit/test_perf_add.mlir
- test/ttmlir/Silicon/TTMetal/perf_unit/test_perf_div.mlir
- test/ttmlir/Silicon/TTMetal/perf_unit/test_perf_exp.mlir
- test/ttmlir/Silicon/TTMetal/perf_unit/test_perf_max.mlir
- test/ttmlir/Silicon/TTMetal/perf_unit/test_perf_multiply.mlir
This somehow got missed during the addition of TTNN perf reports - reported by Vlad.
> #1588: Enable metal device side profiler dumps

- lib/Dialect/TTNN/Transforms/Passes.cpp
- lib/Dialect/TTNN/Utils/TransformUtils.cpp
This PR introduces some changes https://github.com/tenstorrent/tt-mlir/pull/1566, but it seems that it doesn't fix the majority of failing tests. Both bugs are a result of dangling references of `ArrayRef` objects, because they receive temporary `SmallVector` objects.
I've rebased this branch on https://github.com/tenstorrent/tt-mlir/pull/1562, for the ability to build with ASAN flag.
Fixes https://github.com/tenstorrent/tt-mlir/issues/1565
> ASAN fix of failing tests

- tools/ttnn-standalone/CMakeLists.txt
Path for device api in metal changed, updated ttnn-standalone's cmake file.
> Fix ttnn-standalone build

- include/ttmlir/Dialect/TT/IR/TTOps.h
- include/ttmlir/Dialect/TT/IR/TTOps.td
- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Dialect/TTNN/Transforms/Passes.td
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitCPass.cpp
- lib/Dialect/TT/IR/TTOps.cpp
- lib/Dialect/TTNN/Transforms/Passes.cpp
- test/ttmlir/Dialect/TTNN/Transforms/ttnn_modify_signatures_for_dylib_0.mlir
This PR adds a `ModifySignaturesForDylib` pass to help with emitc dylib testing.
So called "forward" functions' signatures take general form of
```
func do_ml_math(tensor0, tensor1, ..., tensorN)
```
For emitc dylib testing path, there's value in having a generic signature for these "forward" functions - it makes loading the functions' symbols easier. The proposed solution, which the above-mentioned pass implements, is to canonicalize signatures to
```
func do_ml_math(vector<Tensor>)
```
This requires changing the signature of the `func.func` and the signature of the function's entry `Block` (more commentary in code).
Things to note:
- Wrapping MLIR's builtin TupleType
- This was added to TT dialect; there's no other dialect that makes more sense for this to live in, and adding a new …
> Add ModifySignaturesForDylib pass

- python/test_infra/test_utils.py
- python/test_infra/ttir_builder.py
- runtime/tools/python/ttrt/common/golden.py
- test/python/golden/test_ttir_ops.py
This change fixes a bug introduced by the previous attempt to use real file names into ops built via python bindings. The problem stemmed from using the `Location.file` constructor, instead of manually constructing a location string and using the `Location.name` constructor instead. This is a temporary fix, and in the future, pure locations shouldn't be used as op UUIDs as they can be inherited by their decomposed ops in some circumstances, thus making them non-unique.
> Fix golden location bug

- include/ttmlir/Bindings/Python/TTMLIRModule.h
- python/CMakeLists.txt
- python/TTMLIRModule.cpp
- python/Util.cpp
- python/ttmlir/util.py
- tools/explorer/tt_adapter/src/tt_adapter/mlir.py
- PR closes #1515 
- Creates a new `utils` module in `ttmlir` that provides utility functions
- Currently implemented
- `utils.debug_print_module` Prints module with Debug flag active (prints locs + other data)
- `utils.get_loc_name` Casts Loc to NameLoc if possible and returns the name
- `utils.get_loc_full` Casts Loc to FileLineColLoc if possible and returns full FileLineCol str.
- New namespace parsing method: If module doesn't have location info (loc is `-`) then a full location is passed into the namespace, otherwise the name is used.
> Created Utils module + Pybound Loc Functionality

- runtime/lib/ttnn/operations/creation/empty.cpp
- runtime/lib/ttnn/operations/creation/full.cpp
- runtime/lib/ttnn/runtime.cpp
- third_party/CMakeLists.txt
This PR uplifts the third_party/tt-metal to the bbce2c3359e128273a38e2afdcf5e346a0941858
- Update .cpmcache/magicenum/ hash on include path becuase tt-metal updated version
- drop the ::api from namespace distributed
> Uplift third_party/tt-metal to bbce2c3359e128273a38e2afdcf5e346a0941858 2024-12-17

- .github/workflows/on-pr.yml
Use PAT token GH_TOKEN to trigger workflow in downstream project
- use GH_TOKEN
- wait for build-and-test to finish
- move parameters to env
- print step summary
> Use GH_TOKEN to trigger workflow

- runtime/lib/ttnn/program.cpp
- runtime/lib/ttnn/runtime.cpp
The new submit API does not need to check for nops as it generically returns tensors based on global id, regardless of if it's an input tensor or not.
> Remove nop check

- include/ttmlir/Dialect/TTNN/Analysis/BFInterleavedPolicy.h
- include/ttmlir/Dialect/TTNN/IR/TTNNOpsAttrs.td
- include/ttmlir/Dialect/TTNN/Utils/Utils.h
- lib/Dialect/TTNN/Analysis/BFInterleavedPolicy.cpp
- lib/Dialect/TTNN/Analysis/GreedyL1InterleavedPolicy.cpp
- lib/Dialect/TTNN/Analysis/LegalLayoutAnalysis.cpp
- lib/Dialect/TTNN/IR/TTNNOpsAttrs.cpp
- lib/Dialect/TTNN/Utils/Utils.cpp
- test/ttmlir/Dialect/TTNN/optimizer/bf_interleaved_policy/all_dram_operands_l1_op.mlir
- test/ttmlir/Dialect/TTNN/optimizer/bf_interleaved_policy/all_l1_operands_dram_op.mlir
- test/ttmlir/Dialect/TTNN/optimizer/bf_interleaved_policy/fork_join_01.mlir
- test/ttmlir/Dialect/TTNN/optimizer/bf_interleaved_policy/fork_join_02.mlir
- test/ttmlir/Dialect/TTNN/optimizer/greedy_l1_interleaved_policy/simple_join_tests/dram_AB_l1_C.mlir
- test/ttmlir/Dialect/TTNN/optimizer/greedy_l1_interleaved_policy/simple_join_tests/dram_AC_l1_B.mlir
- test/ttmlir/Dialect/TTNN/optimizer/greedy_l1_interleaved_policy/simple_join_tests/dram_A_l1_BC.mlir
- test/ttmlir/Dialect/TTNN/optimizer/greedy_l1_interleaved_policy/simple_join_tests/dram_BC_l1_A.mlir
- test/ttmlir/Dialect/TTNN/optimizer/greedy_l1_interleaved_policy/simple_join_tests/dram_B_l1_AC.mlir
- test/ttmlir/Dialect/TTNN/optimizer/greedy_l1_interleaved_policy/simple_join_tests/dram_C_l1_AB.mlir
- test/ttmlir/Dialect/TTNN/optimizer/input_layout_loc_override.mlir
- test/unittests/Optimizer/TestGreedyL1InterleavedPolicy.cpp
This PR fixes the issue of incorrect `memRef` for L1 Interleaved layouts.
In the previous implementation of `TTNNLayoutAttr` we were modelling `memRef` as its memory layout is `BlockSharded`. By modelling everything as `BlockSharded` we hit the error of incorrect memory usage for tensors with the given layout.
For example, if we wanted to create a L1 Interleaved `TTNNLayout` of `tensor<1x1024xbf16>`, we would get a `memref<1x4x!tt.tile<32x32, bf16>, #l1_>`. This was incorrect since the whole tensor can be tiled into 32 tiles and if grid shape is `8x8` we could assign only one tile per grid unit. There is no need for 4 tiles to be placed in one grid unit.
This PR adds workaround for this issue by using different logic for calculating logical shard shape for L1 Interleaved layouts. This …
> Support for memRef of L1 Interleaved tensors (#1292)

- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
When serializing to FlatBuffer, we did not treat the embedding op as a DPS op. Instead, its output was treated as a separate tensor and assigned a different global ID than the DPS init, which later caused a data mismatch at runtime.
So in this example:
```
%3 = "ttnn.empty"(%0) <{dtype = #tt.supportedDataTypes<bf16>, layout = #ttnn.layout<tile>, memory_config = #ttnn.memory_config<#dram, <<1x100>>, <interleaved>>, shape = #ttnn.shape<1x12x3200>}> : (!tt.device<#device>) -> tensor<1x12x3200xbf16, #ttnn_layout5>
%4 = "ttnn.embedding"(%1, %2, %3) : (tensor<1x12xi32, #ttnn_layout3>, tensor<1x12x3200xbf16, #ttnn_layout5>, tensor<32000x3200xbf16, #ttnn_layout4>) -> tensor<1x12x3200xbf16, #ttnn_layout5>
%5 = "ttnn.from_device"(%4) : (tensor<1x12x3200xbf16, #ttnn_layout5>) -> …
```
> Fix embedding data missmatch

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/reverse_op.mlir
- test/ttmlir/Dialect/TTIR/reverse/reverse_tests_negative.mlir
- test/ttmlir/Dialect/TTIR/reverse/reverse_tests_positive.mlir
Fixes https://github.com/tenstorrent/tt-mlir/issues/1330. 
A part of the solution for for https://github.com/tenstorrent/tt-mlir/issues/1142 (need to add tt-torch and tt-xla tests in separate PRs) .
Not implemented end to end since this OP should not exists e2e but rather fitted inside transposed conv op.
> Added TTIR Reverse op and stablehlo -> ttir conversion

- .github/workflows/on-pr.yml
Use pull request sha when triggering downstream check (github.event.pull_request.head.sha) instead of github.sha. It seems that github.sha is pointing to temp merge that is created to run the PR workflow, and not the original commit.
> Fix for downstream check during uplift

- test/ttmlir/Silicon/TTNN/regression/reshape_5d.mlir
- third_party/CMakeLists.txt
This PR uplifts the third_party/tt-metal to 5d0a53211ef2bfbf5f45b9f632bf360a4519a7d8 + cherry-picks/reverts 2024-12-19 (Evening)
- for hang fix (https://github.com/tenstorrent/tt-metal/issues/16141) needed for tt-forge-fe ReshapeOp test hang (was xfail, assert before)
- Need to add new include path to find Tracy.hpp
- Uplift to tt-metal branch kmabee/metal-dec19-5d0a53211-with-patches to get something stable
- Add Unsupported reshape_5d.mlir test copied from tt-forge-fe ReshapeTest
> Uplift third_party/tt-metal to 5d0a53211ef2bfbf5f45b9f632bf360a4519a7d8 2024-12-19

- lib/Target/TTNN/TTNNToFlatbuffer.cpp
As described in https://github.com/tenstorrent/tt-mlir/pull/1633, I checked if any other operations has the same problem, and the embedding backward operation was the only one.
> Fix flatbuffer serialization for embedding backward op

- include/ttmlir/Conversion/TTNNToEmitC/Utils.h
- include/ttmlir/Dialect/TT/IR/TTOps.td
- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Dialect/TTNN/Transforms/Passes.td
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Conversion/TTNNToEmitC/Utils.cpp
- lib/Dialect/TT/IR/TTOps.cpp
- lib/Dialect/TTNN/Transforms/Passes.cpp
- test/ttmlir/Dialect/TTNN/Transforms/ttnn_modify_signatures_for_dylib_0.mlir
ModifySignaturesForDylib pass now packs return values into a tuple. It also hoists the `ttnn::GetDeviceOp` from function's body into its signature, as `DeviceType`.
`tt::TupleOp` was added to allow for creation of tuples.
There was a slightly tricky part in `TTNNToEmitC` pass when converting the new `tt::TupleOp` into a `std::vector`. EmitC doesn't provide any way to call a function (e.g. vector constructor) with an initializer list, nor does it allow calling of member functions (it is emitc after all, not emitcpp 😢) which would've been an avenue for `vec.push_back()`. Instead, I've used `emitc::VerbatimOp` to create a utility function at the top of the func's module. The utility function takes in a variadic number of tensors and packs them into a vector:
```C++
template <typename... T> …
```
> Improve ModifySignaturesForDylib pass

- test/ttmlir/Silicon/TTNN/regression/unsqueeze.mlir
- third_party/CMakeLists.txt
This PR uplifts the third_party/tt-metal to the 8ab8736293d4213be6dd9e7585a80c2acdcac855
Include a unsqueeze.mlir test from tt-forge-fe that was previously failing recently, but appears fixed now
> Uplift third_party/tt-metal to 8ab8736293d4213be6dd9e7585a80c2acdcac855 2024-12-20

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOpsAttrs.td
- include/ttmlir/Dialect/TTNN/Transforms/Workarounds/Decomposition/ReduceOpsRewritePattern.h
- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Dialect/TTNN/IR/TTNNOpsAttrs.cpp
- lib/Dialect/TTNN/Transforms/CMakeLists.txt
- lib/Dialect/TTNN/Transforms/Workarounds/Decomposition/ReduceOpsRewritePattern.cpp
- lib/Dialect/TTNN/Transforms/Workarounds/TTNNWorkarounds.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/reduce_add_op.mlir
- test/ttmlir/Conversion/StableHLOToTTIR/reduce_maximum_op.mlir
- test/ttmlir/Dialect/TTIR/reduce_ops/negative_invalid_dim_high.mlir
- test/ttmlir/Dialect/TTIR/reduce_ops/negative_invalid_dim_low.mlir
- test/ttmlir/Dialect/TTIR/reduce_ops/negative_repeating_dims.mlir
- test/ttmlir/Dialect/TTNN/reduction/max_op_negative.mlir
- test/ttmlir/Dialect/TTNN/reduction/mean_op_negative.mlir
- test/ttmlir/Dialect/TTNN/reduction/sum_op_negative.mlir
- test/ttmlir/Silicon/StableHLO/reduce_add_op.mlir
- test/ttmlir/Silicon/StableHLO/reduce_maximum_op.mlir
- test/ttmlir/Silicon/TTNN/simple_max.mlir
- test/ttmlir/Silicon/TTNN/simple_sum.mlir
This PR adds TTNN workarounds for these Metal issues:
- https://github.com/tenstorrent/tt-metal/issues/13361 - By decomposing `reduce(keepDim=false)` into `reduce(keepDim=true) + reshape`
- https://github.com/tenstorrent/tt-metal/issues/16118 - By annulling dimensions argument when all dims are being reduced
As part of this work I've also:
- Enabled conversion of `stablehlo.reduce` op with multiple reduce dimensions
- Added reduce ops verifiers in TTIR
- Added a separate function in TTNNWorkarounds to run rewrite patterns for decomposition and layout workarounds
- Added lots of unit tests for reduce ops to cover conversions and verifiers
- Added lots of silicon tests for reduce ops
Opened issue https://github.com/tenstorrent/tt-mlir/issues/1624 on myself to revert these workarounds once …
> Add Reduce ops workaround for keepDim=false

- lib/Dialect/TTIR/Pipelines/CMakeLists.txt
Change e748e713afe6556b988f3fcf2797a34e6a151759 introduced Debug build brake.
Debug build fails with:
```
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x23
lib/libMLIRTTIRPipelines.a(TTIRPipelines.cpp.o): in function `mlir::tt::ttir::createLinalgToLLVMPipeline(mlir::OpPassManager&, mlir::tt::ttir::LinalgToLLVMPipelineOptions const&)':
TTIRPipelines.cpp:(.text+0x50): undefined reference to `mlir::createConvertElementwiseToLinalgPass()'
/usr/bin/ld: TTIRPipelines.cpp:(.text+0x7d): undefined reference to `mlir::createConvertTensorToLinalgPass()'
/usr/bin/ld: TTIRPipelines.cpp:(.text+0x118): undefined reference to `mlir::bufferization::buildBufferDeallocationPipeline(mlir::OpPassManager&, mlir::bufferization::BufferDeallocationPipelineOptions const&)'
/usr/bin/ld: …
```
> Fixing missing libs for debug build

- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNWorkarounds.h
- include/ttmlir/Dialect/TTNN/Utils/TransformUtils.h
- include/ttmlir/Dialect/TTNN/Utils/Utils.h
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Dialect/TTNN/IR/TTNNWorkarounds.cpp
- lib/Dialect/TTNN/Transforms/Workarounds/TTNNWorkarounds.cpp
- lib/Dialect/TTNN/Utils/TransformUtils.cpp
- lib/Dialect/TTNN/Utils/Utils.cpp
- test/ttmlir/Dialect/TTNN/Transforms/Workarounds/embedding_workaround.mlir
This PR introduces a solution for handling data type workarounds for operation operands and results. To address input operand data type workarounds, we insert a `toLayout` operation between the input operands and the operation itself. This casts the input to the desired data type. If the data type of the output result changes due to a workaround, we will revert it to the previous data type by inserting a `ToLayoutOp` after the operation's output.
Additionally, this PR provides necessary workarounds to ensure that the embedding operation functions correctly. Specifically, it changes the input to an RM layout and casts both the input weight and the output to bf16. Other ops will be onboarded to this type of workaround in a separate PR.
Example of IR today:
```mlir
module attributes …
```
> [TTNN] Adding support for data type workarounds and introducing Embedding workarounds

- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Dialect/TTNN/Transforms/Passes.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- test/ttmlir/Silicon/TTNN/emitc/mnist.mlir
- test/unittests/Optimizer/TestGreedyL1InterleavedPolicy.cpp
- test/unittests/Optimizer/TestShardSolver.cpp
- tools/ttnn-standalone/CMakeLists.txt
- tools/ttnn-standalone/ttnn-precompiled.hpp
This PR enables MNIST in EmitC path.
Couple of smaller changes are bundled together to make this happen:
- `ttnn::empty` changed its signature in the lib, the dialect was updated to reflect this and several call-sites were updated
- `ttnn::relu` is mismodelled, added a converter in TTNNToEmitC
- `ttnn::matmul` isn't DPS but we model is as if it is - added a converter in TTNNToEmitC to fix it and filed #1661 
- standalone build was broken after metal uplifts, now fixed
Closes #1175
> [EmitC] Support MNIST

- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Dialect/TTNN/IR/TTNNWorkarounds.cpp
- runtime/include/tt/runtime/detail/workarounds.h
- runtime/lib/common/workarounds.cpp
- runtime/lib/ttnn/operations/layout/typecast.cpp
- runtime/tools/python/ttrt/common/run.py
- test/ttmlir/Dialect/TTNN/Transforms/Workarounds/embedding_workaround.mlir
- test/ttmlir/Dialect/TTNN/Transforms/Workarounds/max_pool2d_workaround.mlir
- test/ttmlir/Dialect/TTNN/pooling/simple_maxpool2d.mlir
- test/ttmlir/Silicon/TTNN/embedding/simple_embedding.mlir
- test/ttmlir/Silicon/TTNN/pooling/simple_pooling.mlir
Applying bf16 data type workaround on max_pool2d op.
With this change, I rewrote the workaround test, silicon, and compiler test.
Closes #1389
> Adding bf16 data type workaround for max_pool2d op and fixing embedding workaround tests

- .github/CODEOWNERS
1. Add additional codeowners for optimizer components to account for Nikola leaving.
2. Add ownership of TTNN Interface implementation.
3. Add two more people to own the CODEOWNERS file itself to have more redundancy.
> Adjust optimizer team codeowners

- test/ttmlir/Silicon/TTNN/kv_cache/update_cache.mlir
- third_party/CMakeLists.txt
This PR uplifts the third_party/tt-metal to the 2a86ff7fdde8561ec6c60f1635937ac2b13e122f
> Uplift third_party/tt-metal to 2a86ff7fdde8561ec6c60f1635937ac2b13e122f 2024-12-27

- .github/CODEOWNERS
- include/ttmlir/Dialect/TTNN/Utils/OptimizerOverrides.h
- include/ttmlir/Dialect/TTNN/Utils/PassOverrides.h
- lib/Dialect/TTNN/Utils/OptimizerOverrides.cpp
- lib/Dialect/TTNN/Utils/PassOverrides.cpp
- python/OptimizerOverrides.cpp
- python/TTNNModule.cpp
- python/Util.cpp
- tools/explorer/CMakeLists.txt
- tools/explorer/test/run_tests.py
- tools/explorer/tt_adapter/src/tt_adapter/main.py
- tools/explorer/tt_adapter/src/tt_adapter/mlir.py
- tools/explorer/tt_adapter/src/tt_adapter/runner.py
- tools/explorer/tt_adapter/src/tt_adapter/utils.py
TT-explorer now supports editing output tensor layout of ops from the UI.
Changes made:
* Create editable fields for op output layout instead of readonly attributes.
* Keep perf trace as state for every executed model on the backend
* Clean up location parsing logic
* Fix a few bugs in override parsing / handling
Closes #1178
> Add optimizer overrides to explorer

- runtime/lib/ttnn/operations/data_movement/permute.cpp
- third_party/CMakeLists.txt
This PR uplifts the third_party/tt-metal to the fe6a3da9cf5d064a61a4fc626502cf1544446eb9
- Update runtime code to to use ::ttnn::SmallVector<int64_t> for ::ttnn::permute()
Fixes compile error "no known conversion from 'std::vector<long>' to 'const SmallVector<int64_t>'"
> Uplift third_party/tt-metal to fe6a3da9cf5d064a61a4fc626502cf1544446eb9 2025-01-04

- third_party/CMakeLists.txt
This PR uplifts the third_party/tt-metal to the cb02e398ca4021496be4b248834995e57aa98a24
> Uplift third_party/tt-metal to cb02e398ca4021496be4b248834995e57aa98a24 2025-01-06

- test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
- third_party/CMakeLists.txt
This PR uplifts the third_party/tt-metal to the e6c029ed92adade7e1d42c4a5468df5a7af1a5b0
- Reduce MatmulInterleavedTests/OpModelMatmulParam.MatmulParam/0 expectedCbSize due to tt-metal 3787a8aa2f
- this includes some tt-metal build time fixes
> Uplift third_party/tt-metal to e6c029ed92adade7e1d42c4a5468df5a7af1a5b0 2025-01-07

- lib/OpModel/TTNN/Conversion.cpp
- runtime/lib/ttnn/include/tt/runtime/ttnn/utils.cpp
- runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/utils.cpp
- test/unittests/OpModel/TTNN/Conversion/TestConversion.cpp
- third_party/CMakeLists.txt
This PR uplifts the third_party/tt-metal to the a6ec1c0a02c3b9dc55e769618639e0439ef9c06b
- This brings 1D tensor fix for forge fails blocking uplifts recently, and increased matmul precision fixes in some caes
- Remove halo=false on ShardSpec, was removed in tt-metal at df59448e
> Uplift third_party/tt-metal to a6ec1c0a02c3b9dc55e769618639e0439ef9c06b 2025-01-13

- include/ttmlir/Utils.h
Abstraction for getting pair of integers from `mlir::Atributte` that can be `IntegerAttr` or `DenseArrayAttr`. Useful for mulitple ops currently in development (upsample/downsample/conv_transpose2d), that's why I send it as a separate PR, so it's easier to sync development.
> Pair of integers util function

- python/Passes.cpp
Closes https://github.com/tenstorrent/tt-mlir/issues/1753. The description is in the issue. I decided to change `llvm::function_ref` to `std::function`. The other option would be to inline lambda directly as an argument to the `addToPipeline`.
> Bugfix of dangling llvm::function_ref

- third_party/CMakeLists.txt
This PR uplifts the third_party/tt-metal to the 0d4d99618a90640bd2a742535bb4f6c8ec6ba164
> Uplift third_party/tt-metal to 0d4d99618a90640bd2a742535bb4f6c8ec6ba164 2025-01-14

- python/test_infra/ttir_builder.py
- test/python/golden/test_ttir_ops.py
This change adds tests for lowerings of most of the remaining elementwise ops in TTNN. The resulting `.ttnn` files can be used to golden test these ops as well. This change does not test all elementwise ops, as there are a few that require a slightly more robust testing system in place to use. 
Closes #1748
> Test Most Elementwise Ops for TTNN

- test/ttmlir/Silicon/TTNN/kv_cache/update_cache.mlir
After the recent metal uplift, the following issue was resolved:
https://github.com/tenstorrent/tt-metal/issues/16312#issuecomment-2580951096
With this PR I am reenabling the affected test.
> Enabling update cache test after metal fix

- include/ttmlir/Dialect/TTIR/IR/TTIRBase.td
- include/ttmlir/Dialect/TTIR/IR/TTIROps.h
- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTIR/IR/TTIRTraits.h
- lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
- lib/Dialect/TTIR/IR/CMakeLists.txt
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTIR/IR/TTIRTraits.cpp
- lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
- test/ttmlir/Dialect/TTIR/canonicalize/binary_idempotence_tests.mlir
- test/ttmlir/Dialect/TTIR/canonicalize/bitwise_xor_canonicalize_tests.mlir
- test/ttmlir/Dialect/TTIR/canonicalize/broadcast_fold_tests.mlir
- test/ttmlir/Dialect/TTIR/canonicalize/idempotence_tests.mlir
- test/ttmlir/Dialect/TTIR/canonicalize/involution_tests.mlir
- test/ttmlir/Dialect/TTIR/canonicalize/linear_op_fold_tests.mlir
- test/ttmlir/Dialect/TTIR/canonicalize/permute_op_canonicalize_tests.mlir
- test/ttmlir/Dialect/TTIR/canonicalize/revese_op_canonicalize_tests.mlir
- test/ttmlir/Dialect/TTIR/canonicalize/transpose_fold_tests.mlir
- test/ttmlir/Dialect/TTNN/convolution/simple_conv1d.mlir
- test/ttmlir/Dialect/TTNN/linear/linear_tests_positive.mlir
- test/ttmlir/Dialect/TTNN/linear/simple_linear.mlir
- test/ttmlir/Dialect/TTNN/optimizer/greedy_l1_interleaved_policy/fork_join.mlir
- test/ttmlir/Dialect/TTNN/permute/permute_tests_positive.mlir
- test/ttmlir/Silicon/TTNN/simple_linear.mlir
Canonicalization can be roughly divided into three forms:
1. Traits (properties) of some ops that allows them to be folded (Involution, Idempotence)
2. Per op foldings
4. Per op canonicalization (pattern rewriters)
The first one allows us to decleratively add folding for a large class of ops. While traits like `Involution` already exists in `MLIR` infrastructure it doesn't account for DPS, so I added a new one that takes care of it.
The second one allows us in practice to define some simple graph rewritings where we replace the producing value of op with some existing value (or constant).
The third one gives us the most freedom, where we can do arbitrary graph rewritings, we usually use it when we have to create a new op during rewriting.
I added a `canonicalize` pass both before and …
> Canonicalization of TTIR ops

- runtime/include/tt/runtime/detail/ttmetal.h
- runtime/include/tt/runtime/detail/ttnn.h
- runtime/include/tt/runtime/runtime.h
- runtime/lib/runtime.cpp
- runtime/lib/ttmetal/runtime.cpp
- runtime/lib/ttnn/runtime.cpp
- runtime/tools/python/ttrt/runtime/module.cpp
L1 small size is a device property and needs to be set when opening device, adding a parameter so that the user can toggle this as needed. 
A future improvement would be to expose an API to the user to calculate the l1 small size directly, or maybe have a field in the device attr in the mlir that the compiler calculates and populates.
FYI @LPanosTT
> Add l1 small size as an optional parameter to open device

- CMakeLists.txt
- include/ttmlir/Target/Utils/FuncOpToProgram.h
e2e compile time from stableHLO to flatbuffer is dominated by flatbuffer generation (>99%). Disabling debug strings lowers flatbuffer generation time to 25% of total, lowering e2e times from, for example, 2.5 min to 2 sec.
> Optionally disable debug strings in flatbuffer, greatly reduces compile time

- runtime/lib/common/system_desc.cpp
- runtime/lib/ttmetal/runtime.cpp
- runtime/lib/ttnn/runtime.cpp
- third_party/CMakeLists.txt
This PR uplifts the third_party/tt-metal to the 3a9637d52b003d5d5eda455cc72fbeb75a689f32
- Use `MeshDeviceConfig` explicit constructor instead of passing in `MeshShape` implicitly due to metal commit 2c4a641
> Uplift third_party/tt-metal to 3a9637d52b003d5d5eda455cc72fbeb75a689f32 2025-01-15

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Target/TTNN/program.fbs
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Dialect/TTNN/Transforms/TTNNLayout.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/lib/ttnn/operations/CMakeLists.txt
- runtime/lib/ttnn/operations/conv/conv_transpose2d.cpp
- runtime/lib/ttnn/operations/conv/conv_transpose2d.h
- runtime/lib/ttnn/program.cpp
- test/ttmlir/Dialect/TTIR/conv_transpose2d/conv_transpose2d_tests_negative.mlir
- test/ttmlir/Dialect/TTIR/conv_transpose2d/conv_transpose2d_tests_positive.mlir
- test/ttmlir/Silicon/TTNN/perf_unit/test_perf_conv_transpose2d.mlir
- test/ttmlir/Silicon/TTNN/simple_conv_transpose2d.mlir
closes https://github.com/tenstorrent/tt-mlir/issues/1084
> Add support for conv_transpose2d operation

- runtime/lib/ttnn/operations/ccl/mesh_shard.cpp
- third_party/CMakeLists.txt
This PR uplifts the third_party/tt-metal to the eadc98f1c0f714c423fdfc97689afbc50c0dca3b
- Update order of arguments passed into `distributed::distribute_tensor` due to parameters changed in tt-metal commit abc55d2
> Uplift third_party/tt-metal to eadc98f1c0f714c423fdfc97689afbc50c0dca3b 2025-01-16

- docs/src/ttrt.md
- runtime/include/tt/runtime/detail/ttmetal.h
- runtime/include/tt/runtime/detail/ttnn.h
- runtime/include/tt/runtime/runtime.h
- runtime/include/tt/runtime/types.h
- runtime/lib/runtime.cpp
- runtime/lib/ttmetal/runtime.cpp
- runtime/lib/ttnn/runtime.cpp
- runtime/tools/python/ttrt/common/callback.py
- runtime/tools/python/ttrt/common/run.py
- runtime/tools/python/ttrt/runtime/__init__.py
- runtime/tools/python/ttrt/runtime/module.cpp
This will dump a memory json report after every op execution with the following structure for every device in meshDevice
```
"0": {
"loc": "loc(\"/code/tt-mlir/build/test/ttmlir/Silicon/TTNN/perf_unit/Output/test_perf_and.mlir.tmp.mlir\":9:10)",
"debug_str": "%0 = \"ttnn.get_device\"() <{mesh_shape = #ttnn<mesh_shape 1x1>}> : () -> !tt.device<<workerGrid = #tt.grid<8x8, (d0, d1) -> (0, d0, d1)>, l1Map = (d0, d1)[s0, s1] -> (0, d0 floordiv s0, d1 floordiv s1, (d0 mod s0) * s1 + d1 mod s1), dramMap = (d0, d1)[s0, s1] -> (0, 0, ((((d0 floordiv s0) * 8 + d1 floordiv s1) * (s1 * s0) + (d0 mod s0) * s1 + d1 mod s1) floordiv 8192) mod 12, (((d0 floordiv s0) * 8 + d1 floordiv s1) * (s1 * s0) + (d0 mod s0) * s1 + d1 mod s1) floordiv 98304 + (((d0 floordiv s0) * 8 + d1 floordiv s1) * (s1 * s0) + …
```
> #1683: Updated memory collection and report of dram and l1 using new metal APIs

- .github/Dockerfile.base
- docs/src/build.md
- runtime/tools/python/setup.py
As of https://github.com/tenstorrent/tt-metal/commit/76ce6c7548bc66b69fc04636cb374838a0852a91, we have no more LFS assets!
> remove LFS references now that metal/SFPI/UMD have no LFS assets

- include/ttmlir/Conversion/TTIRToTTNN/Utils.h
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTIRToTTNN/Utils.cpp
- test/ttmlir/Dialect/TTNN/embedding/simple_embedding_backward.mlir
A utils function in:
lib/Conversion/TTIRToTTNN/Utils.cpp
```C++
ttnn::ReshapeOp generateReshape(Value input, ArrayRef<int64_t> newShape,
PatternRewriter &rewriter);
```
It doesn't account for the output layout change of a reshaped op. This PR fixes the output layout of a newly generated reshape op.
Added a simple test to capture this.
Closes #1855
> TTNN utils generate reshape fix

- include/ttmlir/Dialect/TTIR/Transforms/Passes.td
- lib/Conversion/TTIRToTTMetal/AttachMetalLayout.cpp
- lib/Conversion/TTIRToTTMetal/CMakeLists.txt
- test/ttmlir/Dialect/TTMetal/simple_attach_metal_layout.mlir
Add an initial pass to attach canonical `tt.metal_layout` to all tensors in the graph.
i.e.
```mlir
func.func @maximum(%arg0: tensor<64x128xf32>, %arg1: tensor<64x128xf32>) -> tensor<64x128xf32> {
%0 = tensor.empty() : tensor<64x128xf32>
%1 = "ttir.maximum"(%arg0, %arg1, %0) <{operandSegmentSizes = array<i32: 2, 1>}> : (tensor<64x128xf32>, tensor<64x128xf32>, tensor<64x128xf32>) -> tensor<64x128xf32>
return %1 : tensor<64x128xf32>
}
```
becomes
```mlir
#l1_ = #tt.memory_space<l1>
#layout = #tt.metal_layout<(d0, d1) -> (d0, d1), undef, <1x1>, memref<64x128xf32, #l1_>>
module {
func.func @maximum(%arg0: tensor<64x128xf32, #layout>, %arg1: tensor<64x128xf32, #layout>) -> tensor<64x128xf32, #layout> {
%0 = tensor.empty() : tensor<64x128xf32, #layout>
%1 = "ttir.maximum"(%arg0, %arg1, %0) …
```
> D2M Pass 1: Attach Metal Layout

- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Conversion/TTNNToEmitC/Utils.cpp
- lib/OpModel/TTNN/MetalHeaders.h
- runtime/include/tt/runtime/detail/ttmetal.h
- runtime/include/tt/runtime/detail/ttnn.h
- runtime/lib/common/system_desc.cpp
- runtime/lib/ttnn/operations/creation/empty.cpp
- runtime/lib/ttnn/operations/creation/full.cpp
- runtime/lib/ttnn/operations/creation/ones.cpp
- runtime/lib/ttnn/runtime.cpp
- third_party/CMakeLists.txt
- tools/ttnn-standalone/CMakeLists.txt
- tools/ttnn-standalone/ttnn-dylib.cpp
- tools/ttnn-standalone/ttnn-precompiled.hpp
- tools/ttnn-standalone/ttnn-standalone.cpp
This PR uplifts the third_party/tt-metal to the a8396fa5071ea9b0d6754c0317b68871c65d3283
- Update header include paths for tt-metal public API reorg at fa45b9b1a1
- cpp/hpp/h include updates from running script from afuller
'git ls-files '*.cpp' '*.hpp' '*.h' | xargs sed -Ef reorg-api.consumer.sed -i'
- Modify include paths to pick up metal headers, can remove root
third_party/tt-metal/src/tt-metal include dir not needed anymore.
- Use SimpleShape instead of legacy shape following metal change at 80c4aac
> Uplift third_party/tt-metal to a8396fa5071ea9b0d6754c0317b68871c65d3283 2025-01-17

- .github/Dockerfile.ird
This change adds some QoL tools to the docker image for working with the compiler
> Add `tmux` & `clangd` to the IRD docker

- include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
- include/ttmlir/Dialect/TTKernel/IR/TTKernelOpsTypes.td
- lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
- lib/Dialect/TTMetal/IR/TTMetalOps.cpp
- lib/Target/TTMetal/TTMetalToFlatbuffer.cpp
Fix #915 
Add support for all tt-metal semaphore functions, as well as some utility functions that are useful for using semaphores through compiler
For example, code below
```cpp
Value zero = i32(0, builder);
auto sem_id = builder.create<ttkernel::GetArgValOp>(arithOrMathOp.getLoc(), zero);
auto sem_addr = builder.create<ttkernel::GetSemaphoreOp>(arithOrMathOp.getLoc(), sem_id);
auto sem_l1_ptr = builder.create<ttkernel::CastToL1PtrOp>(arithOrMathOp.getLoc(), sem_addr);
builder.create<ttkernel::NocSemaphoreWaitOp>(arithOrMathOp.getLoc(), sem_l1_ptr, zero);
```
will generate kernel code
```cpp
int32_t v5 = get_arg_val<uint32_t>(v4);
int32_t v6 = get_semaphore(v5);
volatile tt_l1_ptr uint32_t*  v7 = reinterpret_cast<volatile tt_l1_ptr uint32_t*>(v6);
noc_semaphore_wait(v7, v4);
```
> Support tt-metal semaphores

- docs/src/dialects-overview.md
- include/ttmlir/Conversion/TTKernelToEmitC/TTKernelToEmitC.h
- include/ttmlir/Dialect/TTMetal/IR/TTMetalOps.td
- lib/Conversion/TTIRToTTMetal/TTIRToTTMetal.cpp
- lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
- lib/Dialect/TTKernel/IR/TTKernelOps.cpp
- lib/Dialect/TTMetal/IR/TTMetalDialect.cpp
- lib/Dialect/TTMetal/IR/TTMetalOps.cpp
- lib/Target/TTMetal/TTMetalToFlatbuffer.cpp
- test/ttmlir/Silicon/TTMetal/perf_unit/test_perf_add.mlir
- test/ttmlir/Silicon/TTMetal/perf_unit/test_perf_div.mlir
- test/ttmlir/Silicon/TTMetal/perf_unit/test_perf_exp.mlir
- test/ttmlir/Silicon/TTMetal/perf_unit/test_perf_max.mlir
- test/ttmlir/Silicon/TTMetal/perf_unit/test_perf_multiply.mlir
- test/ttmlir/Silicon/TTMetal/simple_constant.mlir
- test/ttmlir/Silicon/TTMetal/simple_eltwise.mlir
- test/ttmlir/Silicon/TTMetal/simple_max.mlir
- test/ttmlir/Silicon/TTMetal/simple_reduce.mlir
- test/ttmlir/Silicon/TTMetal/simple_reduce_1x1.mlir
- test/ttmlir/Silicon/TTMetal/tiled_reblock.mlir
- test/ttmlir/Silicon/TTMetal/to_layout.mlir
Ticket: #364 
Refactors:
- DispatchOp -> EnqueueProgramOp
- HostWriteOp -> EnqueueWriteBufferOp
- HostReadOp -> EnqueueReadBufferOp
- AllocOp -> CreateBufferOp
- DeallocOp -> DeallocateBufferOp
> #364: Rename metal ops to be consistent with host_api.hpp

- python/test_infra/test_utils.py
- python/test_infra/ttir_builder.py
- test/python/golden/test_ttir_ops.py
Allows the choosing of input types to generated MLIR and golden checks via `inputs_types` kwarg. Take `torch.dtype`s as inputs, then converts them to MLIR `Type`s upon context introduction.
Closes #1765
> Enable choosing of input type for lowering tests

- lib/OpModel/TTNN/SingletonDeviceContext.cpp
- runtime/include/tt/runtime/detail/common.h
- runtime/include/tt/runtime/detail/ttmetal.h
- runtime/include/tt/runtime/detail/ttnn.h
- runtime/include/tt/runtime/runtime.h
- runtime/include/tt/runtime/types.h
- runtime/lib/common/system_desc.cpp
- runtime/lib/runtime.cpp
- runtime/lib/ttmetal/runtime.cpp
- runtime/lib/ttnn/runtime.cpp
- runtime/tools/python/ttrt/runtime/module.cpp
- test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
- test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
- test/unittests/OpModel/TTNN/OpModelFixture.h
Current behaviour always sets dispatch core type to worker. This leads to a different grid size on N300 `7x8` and N150 `8x8`, since N300 is dual row harvested. This change moves dispatch to Ethernet cores on N300, freeing up another row and giving the same grid size. 
While I was adding, I gave the option of overriding from FEs when opening the device.
> Set dispatch core to Ethernet on N300, ensuring 8x8 grid across devices

- include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
- lib/Conversion/TTIRToTTMetal/TTIRToTTMetal.cpp
- lib/OpModel/TTNN/TTNNOpModelLib.cpp
- runtime/lib/ttnn/runtime.cpp
- third_party/CMakeLists.txt
- tools/ttnn-standalone/CMakeLists.txt
This PR uplifts the third_party/tt-metal to the 182c42462cd61515f60a11a46ee84f303ed073ee
- update type name (QueryResponse is now ConstraintQueryResponse)
- Remove reference to Tensor constructor deprecated in metal commit ba35246703
- Update json cpmcache hash include dir and use temp workaround to set -DCMAKE_CXX_SCAN_FOR_MODULES=FALSE
- Update copy_tile_init API to accept CB argument
> Uplift third_party/tt-metal to 182c42462cd61515f60a11a46ee84f303ed073ee 2025-01-23

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
- lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecompositionPass.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/reduction/reduce_and_op.mlir
- test/ttmlir/Decomposition/TTIR/reduction/reduce_and.mlir
- test/ttmlir/Silicon/StableHLO/reduction/reduce_and_op.mlir
TTNN does not support reduction for logical and operator. So stablehlo.reduce
for stablehlo.and operator is decomposed into reduction sum op along give
dimension and then compared with the size of given dimension.
> Add support for stablehlo.reduce op for logical and operator

- lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
- test/ttmlir/Dialect/TTNN/embedding/gather_to_embedding.mlir
- test/ttmlir/Dialect/TTNN/embedding/gather_to_embedding_negative.mlir
After the workarounds pass was added and workarounds were enabled for EmbeddingOp, the constraint that operands have to be in BF16 for GatherOp -> EmbeddingOp conversion should no longer be necessary. This PR removes it.
> Remove the BF16 type constraint from TTIR gather to embedding conversion

- include/ttmlir/Conversion/TTNNToEmitC/Utils.h
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Conversion/TTNNToEmitC/Utils.cpp
Before `ttnn::SimpleShape` was introduced, the easiest way for us to create `ttnn::Shape` objects was to do `ttnn::Shape(ttnn::LegacyShape(c, h, w, ...))` - but the `ttnn::LegacyShape()` constructor is NOT needed anymore, as `ttnn::SimpleShape` accepts an initializer list.
> Remove ttnn::LegacyShape, ttnn::SimpleShape doesn't need it

- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/multiple_maxpool2d_op.mlir
Lowering stablehlo.reduce_window to ttir.pooling may cause a failure since we are erasing the init_value in the pattern rewrite:
```
void llvm::ilist_traits<mlir::Operation>::removeNodeFromList(Operation *): Assertion `op->block && "not already in an operation block!"' failed.
```
I've removed the logic that does this since it is removed regardless due to it becoming a dead value.
Added a maxpool test to one which would have failed if this logic remained.
> stablehlo.reduce_window lowering fix.

- lib/Dialect/TTIR/IR/TTIRDialect.cpp
- lib/Dialect/TTMetal/IR/TTMetalDialect.cpp
- test/ttmlir/Dialect/TTIR/ttir_generic_hoist.mlir
Closes #1970
This prevents constant operations nested inside of a ttir generic region from being hoisted out of the region body.
> Add TTIR Constant hoist interface for generic ops

- include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
- lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
This PR implements the following TTKernel OPs needed by [first PyKernel eltwise example](https://github.com/tenstorrent/tt-mlir/issues/1984):
- [get_read_ptr](https://github.com/tenstorrent/tt-mlir/issues/1987) 
- [get_compile_time_arg_val](https://github.com/tenstorrent/tt-mlir/issues/1988)
- [get_tile_size](https://github.com/tenstorrent/tt-mlir/issues/1985)
> TT kernel operations needed for first eltwise PyKernel

- include/ttmlir/Conversion/Passes.td
- include/ttmlir/Conversion/TTKernelToEmitC/TTKernelToEmitC.h
- include/ttmlir/Dialect/TTKernel/IR/TTKernelBase.td
- include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
- lib/Conversion/TTIRToTTMetal/TTIRToTTMetal.cpp
- lib/Conversion/TTKernelToEmitC/CMakeLists.txt
- lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
- test/ttmlir/Silicon/TTMetal/simple_reduce.mlir
This is an onboarding ticket that resolves #496 and that has got a little out of hand. 
The salient changes are:
1. `memref` is now a supported dialect to use in TTKernel IR. There are builtin conversions for {alloca, global, get_global, load, store}.
2. `ConvertTTKernelToEmitCPass` is now a module pass -- this allows us to emit global constants and helper funcs at the module scope level
3. `TTKernelToEmitC` API has been cleaned up a little, to remove methods with odd Region parameters created by caller but populated by callee, etc
4. the original implementation of reduce ops used an "unrolled" loop over operations and could thus emit riscv code that was O(core grid size) in size, with some address calculations repeated redundantly -- the new implementation retains an emitc-level for-loop …
> optimize looping over NOC data movement ops

- runtime/lib/common/system_desc.cpp
- runtime/lib/ttmetal/runtime.cpp
- runtime/lib/ttnn/runtime.cpp
- third_party/CMakeLists.txt
This PR uplifts the third_party/tt-metal to the 064646adfcb5f0b923a24a633d532552bd43e06d
- Call allocator APIs from allocator, not IDevice, after metal change 2b8c66c
> Uplift third_party/tt-metal to 064646adfcb5f0b923a24a633d532552bd43e06d 2025-01-30

- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
- lib/Conversion/TTIRToTTMetal/AttachMetalLayout.cpp
- lib/Conversion/TTIRToTTMetal/TTIRToTTMetal.cpp
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Conversion/TosaToTTIR/TosaToTTIRPatterns.cpp
See LLVM Docs for more information.
The code transformation wraps all classes or structs declared inside of a .cpp file in an anonymous namespace:
```
namespace {
class TTIRAttachMetalLayout
: public impl::TTIRAttachMetalLayoutBase<TTIRAttachMetalLayout> {
...
};
} // namespace
```
Closes #1982
> Wrap all classes declared in cpp file in anonymous namespace

- include/ttmlir/Target/Common/types.fbs
- lib/Target/TTMetal/TTMetalToFlatbuffer.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/include/tt/runtime/detail/ttmetal.h
- runtime/include/tt/runtime/detail/workarounds.h
- runtime/lib/binary.cpp
- runtime/lib/common/workarounds.cpp
- runtime/tools/python/ttrt/common/run.py
Remove stride from flatbuffer, as they will not be valid for tilized tensors, we'll need a more sophisticated strategy to handle custom strides in runtime. For now adding a runtime workaround wherever we used to read the stride from the flatbuffer to calculate the stride instead.
FYI @nsmithtt @pilkicTT
> Remove stride from flatbuffer

- include/ttmlir/Dialect/TTNN/IR/TTNNOpModelInterface.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/OpModel/TTNN/TTNNOpModel.h
- lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
- lib/OpModel/TTNN/MetalHeaders.h
- lib/OpModel/TTNN/SingletonDeviceContext.cpp
- lib/OpModel/TTNN/SingletonDeviceContext.h
- lib/OpModel/TTNN/TTNNOpModelLib.cpp
- test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
- test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
#2002 
Enable compile time op runtime estimation for ops that already support constraints and L1 estimation
Builds on APIs from tt-metal in [#16921](https://github.com/tenstorrent/tt-metal/pull/16921)
Create a `getOpRuntime` API for ReLu, Softmax, Matmul, and add which:
- matches the interface of the `getOpConstraints` API
- translates ttmlir types to ttnn/metal types
- connects to the underlying API in tt-metal to run the op via trace capture and obtain a runtime estimate
- Added `getOpRuntime` API to ReLu, Softmax, Matmul, and add
- API exactly matches the interface and structure of the `getOpConstraints` API 
- Added unit tests 
- Small refactors to reduce code duplication between getOpConstraints and getOpRuntime
There is a big opportunity to refactor the unit tests, but this PR is …
> #2002: Enable Compile Time Op Runtime Estimation

- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- runtime/lib/ttnn/operations/data_movement/repeat.cpp
- third_party/CMakeLists.txt
This PR uplifts the third_party/tt-metal to the 9d69fb143bac50983dff914c5348539d0a7d2021
- Replace Shape with SimpleShape after metal change 452da80
> Uplift third_party/tt-metal to 9d69fb143bac50983dff914c5348539d0a7d2021 2025-01-31

- .github/actions/build-tt-mlir-action/action.yaml
- .github/workflows/build-and-test.yml
- runtime/include/tt/runtime/detail/debug.h
- runtime/include/tt/runtime/detail/ttmetal.h
- runtime/include/tt/runtime/detail/ttnn.h
- runtime/include/tt/runtime/runtime.h
- runtime/lib/common/debug.cpp
- runtime/lib/runtime.cpp
- runtime/lib/ttmetal/runtime.cpp
- runtime/lib/ttnn/runtime.cpp
- runtime/tools/python/ttrt/common/run.py
- runtime/tools/python/ttrt/runtime/module.cpp
Move async mode flag from debug env to a parameter to open device.
FYI @AleksKnezevic
> Add async ttnn parameter in open device

- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNWorkarounds.h
- include/ttmlir/Dialect/TTNN/Transforms/Workarounds/Decomposition/CumSumOpRewritePattern.h
- lib/Dialect/TTNN/IR/TTNNWorkarounds.cpp
- lib/Dialect/TTNN/Transforms/CMakeLists.txt
- lib/Dialect/TTNN/Transforms/Workarounds/Decomposition/CumSumOpRewritePattern.cpp
- lib/Dialect/TTNN/Transforms/Workarounds/TTNNWorkarounds.cpp
- test/ttmlir/Dialect/TTNN/Transforms/Workarounds/cumsum_workaround.mlir
- test/ttmlir/Silicon/StableHLO/moreh_cumsum_op.mlir
* Add a layout workaround for input tensor of integer type.
* Add a reshape workaround for input tensor of rank less than 4.
closes #1980
> [TTNN] Add workarounds for cumsum op

- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/ccl_ops.mlir
Meshes we will support
- 1x2
- 1x8
- 2x4
- 1x32
- 8x4
Multi-device tests consolidation
`test/ttmlir/Conversion/StableHLOToTTIR/ccl_ops.mlir`
- all_reduce tests for all meshes
- all_gather tests for all meshes
> #2004: Added shlo to ttir conversion pass for all_gather and updated shlo to ttir conversion test cases for all gather

- runtime/include/tt/runtime/detail/ttmetal.h
- runtime/include/tt/runtime/detail/ttnn.h
- runtime/include/tt/runtime/runtime.h
- runtime/lib/common/system_desc.cpp
- runtime/lib/runtime.cpp
- runtime/tools/python/ttrt/common/query.py
- runtime/tools/python/ttrt/common/run.py
- runtime/tools/python/ttrt/runtime/__init__.py
This is needed because galaxy does not support dispatch on ethernet cores.
> #2029: Added option in ttrt to disable putting dispatch on ethernet cores

- include/ttmlir/Conversion/TTNNToEmitC/Utils.h
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Conversion/TTNNToEmitC/Utils.cpp
- lib/OpModel/TTNN/Conversion.cpp
- lib/OpModel/TTNN/Conversion.hpp
- runtime/lib/ttnn/operations/ccl/mesh_shard.cpp
- runtime/lib/ttnn/operations/creation/empty.cpp
- runtime/lib/ttnn/operations/creation/full.cpp
- runtime/lib/ttnn/operations/creation/ones.cpp
- runtime/lib/ttnn/operations/data_movement/repeat.cpp
- runtime/lib/ttnn/operations/pool/maxpool2d.cpp
- runtime/lib/ttnn/runtime.cpp
- runtime/test/include/tt/runtime/ttnn/test/dylib.cpp
- test/unittests/OpModel/TTNN/Conversion/TestConversion.cpp
- third_party/CMakeLists.txt
- tools/ttnn-standalone/ttnn-standalone.cpp
This PR uplifts the third_party/tt-metal to the f8fe02d9f591f4c7f929131630ce5147cfe88f8e
- Updates in all mlir code for TTNN Shape related refactoring/updates
- ttnn::SimpleShape renamed to ttnn::Shape in tt-metal 2df6e60cd9
- Tensor get_shape() -> get_logical_shape() due to tt-metal 8063f0ab02
- Removed some code in EmitC path to do with selecting between Shape and SimpleShape
now just using Shape (previously called SimpleShape).
> Uplift third_party/tt-metal to f8fe02d9f591f4c7f929131630ce5147cfe88f8e 2025-02-01

- include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
- lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
- test/ttmlir/Conversion/TTKernelToEmitC/ttkernel.mlir
This PR implements the last TTKernel op needed by [eltwise kernel example](https://github.com/tenstorrent/tt-mlir/issues/1984)
`get_noc_addr_from_bank_id` is templated in `dataflow_api.h` on the metal side
```
template <bool DRAM>
get_noc_addr_from_bank_id(uint32_t bank_id, uint32_t bank_address_offset, uint8_t noc = noc_index) {
```
Further investigation shows that every kernel written sets `DRAM` to true. 
Similar API like `get_noc_addr` is templated the same way and this template is not exposed in the tablegen for mlir (would love to know how to expose it), so I will also not expose it.
> `get_noc_addr_from_bank_id` needed for first eltwise PyKernel

- lib/Dialect/TTNN/Transforms/TTNNDecomposeLayouts.cpp
- test/ttmlir/Dialect/TTNN/typecast.mlir
In certain cenarios we can end up with element type mismatch between return op and func op return types which causes to have invalid IR. This happens because of how we convert mlir builtin types to tt types and vice versa.
There is an issue created for this a while ago which should add conversion pass for element types.
https://github.com/tenstorrent/tt-mlir/issues/1277
This fix is a temporary solution and should not be in main branch until we have proper conversion which requires some discussion.
> Fixing result type mismatch when using typecast

- lib/Dialect/TTNN/IR/TTNNOps.cpp
- test/ttmlir/Dialect/TTNN/reduction/simple_mean.mlir
- test/ttmlir/Dialect/TTNN/reduction/simple_sum.mlir
- test/ttmlir/EmitC/TTNN/reduction/mean.mlir
- test/ttmlir/Silicon/TTNN/perf_unit/test_perf_max.mlir
- test/ttmlir/Silicon/TTNN/perf_unit/test_perf_sum.mlir
- test/ttmlir/Silicon/TTNN/simple_reductions.mlir
- Added verifier for reduction ops - tests whether output shape matches what the op will return.
- Fixed tests so that IRs are correct
Closes #1942
> Add output verifier shape for reduction ops and fix erroneous tests

- docs/src/adding-an-op.md
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- tools/ttnn-standalone/ttnn-precompiled.hpp
Following suggestions from https://github.com/tenstorrent/tt-mlir/pull/1928#issuecomment-2619423303, updating the docs.
Improved Adding-an-op docs, specifically emitc section - added note on adding op conversion from ttnn to emitc and including header in `ttnn-precompiled.hpp`.
> Add improvements to Adding-an-op docs, specifically emitc sections

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Target/TTNN/program.fbs
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/lib/ttnn/operations/CMakeLists.txt
- runtime/lib/ttnn/operations/creation/zeros.cpp
- runtime/lib/ttnn/operations/creation/zeros.h
- runtime/lib/ttnn/program.cpp
- runtime/lib/ttnn/runtime.cpp
- test/ttmlir/Conversion/TTNNToEmitC/zeros.mlir
- test/ttmlir/EmitC/TTNN/tensor/ones.mlir
- test/ttmlir/EmitC/TTNN/tensor/zeros.mlir
- test/ttmlir/Silicon/TTNN/zeros.mlir
Adds `ttnn::zeros` op support.
Closes #374
Edit:
I've also added EmitC tests for both ttnn::ones and ttnn::zeros - they however failed. Opened #2072 to track.
> Add ttnn::zeros op

- python/test_infra/ttir_builder.py
- runtime/tools/python/ttrt/common/util.py
This change (originally authored by @tapspatel) implements some flattening and unflattening logic for golden tensors across the flatbuffer barrier. This is a temporary strategy and will be rolled back once multidimensonal flatbuffer arrays are implemented for our schema.
> Flatten and Reshape Golden Tensors

- include/ttmlir/Dialect/TTNN/IR/TTNNOpModelInterface.h
- include/ttmlir/Dialect/TTNN/IR/TTNNOpModelInterface.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.h
- include/ttmlir/OpModel/TTNN/TTNNOpModel.h
- lib/Dialect/TTNN/Analysis/ShardSolver.cpp
- lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
- lib/OpModel/TTNN/TTNNOpModelLib.cpp
- test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
- test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
#2046 
- `getOpConstraints` and `getOpRuntime` APIs return a convoluted tuple of optionals that is confusing and verbose to use
- Unit tests for `getOpConstraints` and `getOpRuntime` have a lot of code duplication and do not allow easy testing of new ops. This is a problem as new ops
- Resolves #2046 
- Changed both `getOpConstraints` and `getOpRuntime` to return an `llvm::Expected` object
- Updated tests, usage and documentation
- Heavily refactored unit tests for `getOpRuntime` and `getOpConstraints`
- Mostly separated test data from test code
- Changed ReLu and Add tests into parametrized tests. When adding the next unary or binary op(s), it is trivial to parametrize these on the op in addition to the data as the test code 100% will be identical
> #2046: Change OpModel APIs to return llvm::Expected and Refactor Unit Tests

- runtime/lib/ttnn/operations/ccl/mesh_shard.cpp
- passed CI because it's not built in Release mode
> [bugfix] DEBUG_ASSERT non-existing member function

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Target/TTNN/program.fbs
- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/include/tt/runtime/detail/ttnn.h
- runtime/include/tt/runtime/detail/workarounds.h
- runtime/lib/common/workarounds.cpp
- runtime/lib/ttnn/operations/CMakeLists.txt
- runtime/lib/ttnn/operations/data_movement/pad.cpp
- runtime/lib/ttnn/operations/data_movement/pad.h
- runtime/lib/ttnn/program.cpp
- runtime/tools/python/ttrt/common/run.py
- test/ttmlir/Conversion/StableHLOToTTIR/pad_op.mlir
- test/ttmlir/Dialect/TTNN/simple_pad.mlir
- test/ttmlir/EmitC/TTNN/other/pad.mlir
- test/ttmlir/Silicon/TTNN/simple_pad.mlir
- Added PadOp in ttnn, ttir dialects.
- Flatbuffer/Runtime implementations for PadOp
- Stablehlo --> ttir lowering for PadOp
Closes https://github.com/tenstorrent/tt-mlir/issues/421
> Add Conversion from StableHLO Padding Op along with end-to-end Implementation

- python/test_infra/ttir_builder.py
- test/python/golden/test_ttir_ops.py
This change streamlines our bindings within the TTIR builder by having the output shape passed to the TTIR op be computed from the golden (torch) output. This both makes adding new ops easier, and reduces the chance of a bug in how we manually calculate shapes.
During testing, I also discovered we have no single test for a matmul through the builder, so I added one to show that the new feature works
> Infer shape in builder from golden output

- include/ttmlir/Dialect/TT/IR/TTOpsEnums.td
- include/ttmlir/Dialect/TT/IR/TTOpsTypes.h
- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Dialect/TTIR/Transforms/Passes.td
- include/ttmlir/Dialect/TTMetal/Pipelines/TTMetalPipelines.h
- lib/Conversion/TTIRToTTMetal/AttachMetalLayout.cpp
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp
This is WIP for #1895. Because this breaks several .mlir tests that match on `#tt.metal_layout`, want to get some quick feedback.
When the stream layout parameter is set on a `metal_layout`, things get more verbose:
```
#tt.metal_layout<(d0, d1) -> (d0, d1), undef, <1x1>, memref<64x128xf32, #tt.stream<(d0, d1) -> (d0, d1), stream, 2>, #l1_>>
```
for streams and and
```
#tt.metal_layout<(d0, d1) -> (d0, d1), undef, <1x1>, memref<64x128xf32, #tt.stream<(d0, d1) -> (d0, d1), alias>, #l1_>>
```
for aliases.  Whenever `numBuffers` is 1 it is not shown.
Questions:
1. `TT_BufferAttr` is also going away, correct?
2. I assume we want to start using (default) alias stream layouts starting at AttachMetalLayout, correct?
> StreamLayoutAttr replaces BufferAccessAttr in d2m

- python/CMakeLists.txt
- python/pykernel/pykernel_ast.py
- python/pykernel/types.py
- test/pykernel/add_2_integers_in_compute/add_2_tiles.py
- test/pykernel/add_2_integers_in_compute/reader_binary_1_tile.py
- test/pykernel/add_2_integers_in_compute/writer_1_tile.py
- test/pykernel/eltwise_sfpu/eltwise_sfpu.py
- test/pykernel/eltwise_sfpu/reader_unary.py
- test/pykernel/eltwise_sfpu/writer_unary.py
- test/pykernel/unit_tests.py
This PR lowers 2 basic kernels into MLIR
- eltwise kernel example: https://github.com/tenstorrent/tt-mlir/issues/1850
- [add_2_integers kernel](https://github.com/tenstorrent/tt-metal/tree/main/tt_metal/programming_examples/add_2_integers_in_compute) example: 
Changes made to support: 
- all assign statements will default to SSA only unless using AnnAssign (eg: `x: int = 1`) which will use memref
- a `CircularBuffer` type in Python to [interface with kernel function](https://github.com/tenstorrent/tt-mlir/issues/1849), this is basically the `class Tensor` defined in `simple_kernel.py`
> Pykernel examples - eltwise_sfpu and add_2_integers

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Utils.h
- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- lib/Conversion/TTIRToLinalg/TTIRToLinalg.cpp
- lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TosaToTTIR/TosaToTTIRPatterns.cpp
- lib/Dialect/TTIR/Transforms/Constant.cpp
- lib/Dialect/TTIR/Transforms/Layout.cpp
- lib/Dialect/TTNN/Transforms/TTNNLayout.cpp
The goal of this PR is to simplify the creation of DPS ops. Most DPS ops follow the same pattern, where op is defined in TableGen as:
```
def DPSOp {
...
let arguments = (ins
AnyRankedTensor:$input1,
...,
AnyRankedTensor:$inputN,
AnyRankedTensor:$output,
Attribute:$attr1,
...,
Attribute:$attrM);
...
}
```
with the appropriate builder where arguments follow the order of operands and attributes in the op definition. Frontends from which we lower to TTIR are non-DPS, so when we lower from those frontends to TTIR we end up (in the best case) with the following code:
```cpp
RankedTensorType outputType = mlir::cast<RankedTensorType>(
this->getTypeConverter()->convertType(srcOp.getResult().getType()));
tensor::EmptyOp output = rewriter.create<tensor::EmptyOp>(
adaptor.getLoc(), …
```
> Interface for DPS op creation

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Utils.h
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- runtime/lib/ttnn/operations/conv/conv_transpose2d.cpp
- test/ttmlir/Dialect/TTIR/conv_transpose2d/conv_transpose2d_tests_negative.mlir
- test/ttmlir/Dialect/TTIR/conv_transpose2d/conv_transpose2d_tests_positive.mlir
[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/2073)
The padding attribute in ConvTranspose2dOp currently only accepts 1 or 2 values, but not 4.
Added support for passing 4 values for the padding attribute and made minor updates to the ConvTranspose2dOp documentation and verification.
> [TTIR] Support passing 4 values for padding in ConvTranspose2d

- include/ttmlir/Dialect/TTNN/Transforms/Workarounds/Decomposition/ReduceOpsRewritePattern.h
- lib/Dialect/TTNN/Transforms/Workarounds/TTNNWorkarounds.cpp
- test/ttmlir/Dialect/TTNN/reduction/simple_reduce_min.mlir
- test/ttmlir/Silicon/StableHLO/n150/reduction/reduce_add_op.mlir
- test/ttmlir/Silicon/StableHLO/n150/reduction/reduce_maximum_op.mlir
- test/ttmlir/Silicon/StableHLO/n150/reduction/reduce_min_op.mlir
- test/ttmlir/Silicon/TTNN/n150/perf/test_perf_reduce_min.mlir
- test/ttmlir/Silicon/TTNN/n150/simple_max.mlir
- test/ttmlir/Silicon/TTNN/n150/simple_mean.mlir
- test/ttmlir/Silicon/TTNN/n150/simple_reduce_min.mlir
- test/ttmlir/Silicon/TTNN/n150/simple_sum.mlir
This workaround is still required in case of reducing entire tensor.
closes #1640
> remove reduce ops workaround for keepDim attribute

- lib/Dialect/TTNN/Transforms/TTNNLayout.cpp
Defaults conv weights layout to host since they need to be prepared on host anyway. Patches uplift CI failures on tt-torch and tt-forge-fe.
FYI: @kmabeeTT @AleksKnezevic @pilkicTT
> Default conv weights on host

- runtime/include/tt/runtime/detail/workarounds.h
- runtime/lib/binary.cpp
- runtime/lib/common/workarounds.cpp
- runtime/tools/python/ttrt/common/run.py
This change is made to avert an innocuous bug where `ttrt` can't find a symbol when it is built in debug mode.
Sometimes the symbol `_ZN2tt7runtime10workaround3Env3getEbbbbb` is missing from a `Debug` built `ttrt`.
The code that introduces a dependency on that symbol has been removed
> Remove dep. on runtime workaround in `binary.cpp`

- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- third_party/CMakeLists.txt
- tools/ttnn-standalone/CMakeLists.txt
This PR uplifts the third_party/tt-metal to the b093594aa5fc01f7c008a0b5ffddbcf2713bd8f7
- Update boost core include dir after metal commit a1eb4d9
- Update repeat op invoke param to not pass in empty config after metal change b45f5a2
> Uplift third_party/tt-metal to b093594aa5fc01f7c008a0b5ffddbcf2713bd8f7 2025-02-06

- third_party/CMakeLists.txt
After commit 62517e0 the installation path for `tt-metal` shared libs is wrong. It does not respect `CMAKE_INSTALL_PREFIX`.
When using `install(FILES)` and specifying `DESTINATION`, cmake will append it to the `CMAKE_INSTALL_PREFIX` under the hood. However, `file(INSTALL)` does not do that.
Fixing so that the full path is provided to the `file(INSTALL)` command.
> [build] fix install of tt-metal shared libs

- .github/build-docker-images.sh
Docker images haven't been auto-tagged with latest
Issue seems to be: when you create PR, new docker image is created.  When you merge PR, cached docker image from PR is found => we don't tag with latest.  Idea here is to move the latest tag logic out of the if/else s.t. it always runs on main.  Apparently, similar fix was made for tt-forge-fe and works there.
> Fix docker tagging logic

- include/ttmlir/Target/Utils/FuncOpToProgram.h
https://github.com/tenstorrent/tt-mlir/issues/2156
As described here https://github.com/tenstorrent/tt-mlir/pull/1782 `getOpDebugString` was taking more than 99% of the time of `ttmlir-translate -ttnn-to-flatbuffer` execution. From that time, 99% was spent on op verification.
- added `assumeVefied()` to `printFlags` that are used for printing ops (the way we are running our pipelines I believe this is a safe assumption)
- greatly lowers TTNN->Flatbuffer compile time (on LlamaPrefill example from https://github.com/tenstorrent/tt-mlir/pull/2144) compile time was lowered from ~70s -> ~1.5s (around 0.8s was spent on op printing)
> Skip op verification in opDebugString

- runtime/lib/ttnn/operations/data_movement/pad.cpp
- runtime/lib/ttnn/operations/pool/maxpool2d.cpp
- third_party/CMakeLists.txt
- tools/ttnn-standalone/CMakeLists.txt
This PR uplifts the third_party/tt-metal to the 38578b33849c41ad70f5375856d736bc77239b8c
- Use strongly typed QueueID after metal commit 14f9739
> Uplift third_party/tt-metal to 38578b33849c41ad70f5375856d736bc77239b8c 2025-02-10

- test/ttmlir/Silicon/TTNN/n150/perf/test_perf_conv_transpose2d.mlir
- test/ttmlir/Silicon/TTNN/n150/simple_conv_transpose2d.mlir
- third_party/CMakeLists.txt
This PR uplifts the third_party/tt-metal to the 02fb2125f3fe1f05afd38bcea7993ccb7df87313
- Mark ttnn.conv_transpose2d tests as unsupported after metal change 9b459f0
> Uplift third_party/tt-metal to 02fb2125f3fe1f05afd38bcea7993ccb7df87313 2025-02-11

- include/ttmlir/Dialect/TTNN/Transforms/Workarounds/Decomposition/ReduceOpsRewritePattern.h
- lib/Dialect/TTNN/Transforms/Workarounds/TTNNWorkarounds.cpp
- test/ttmlir/Silicon/StableHLO/n150/reduction/reduce_add_op.mlir
- test/ttmlir/Silicon/StableHLO/n150/reduction/reduce_maximum_op.mlir
- test/ttmlir/Silicon/StableHLO/n150/reduction/reduce_min_op.mlir
- test/ttmlir/Silicon/TTNN/n150/simple_sum.mlir
closes #1624 
#1624 
TTNN workaround was added to handle tt-metal issue (https://github.com/tenstorrent/tt-metal/issues/16118). This issue is resolved now.
TTNN workaround removed.
> Remove reduce op workaround for full tensor reduction

- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNWorkarounds.h
- lib/Dialect/TTNN/IR/TTNNWorkarounds.cpp
- test/ttmlir/Dialect/TTNN/Transforms/Workarounds/concat_workaround.mlir
- test/ttmlir/Silicon/StableHLO/n150/Binary/concat_op.mlir
closes #2181 
[#2181 ](https://github.com/tenstorrent/tt-mlir/issues/2181)
tt-metal applies padding (before concatenation) to the input tensors if the
layout is tile and the shape is not divisible by tile size along concatenated
dimension for any input tensor. Padding can only be applied for float or
bfloat16 tensors.
Add layout workaround for data types other than float32 or bfloat16
> Add data type workaround for concat op

- include/ttmlir/Dialect/TTNN/IR/TTNNOps.h
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOpsAttrs.td
- include/ttmlir/Dialect/TTNN/IR/TTNNTraits.h
- include/ttmlir/Dialect/TTNN/IR/TTNNTraits.td
- include/ttmlir/Target/TTNN/program.fbs
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Dialect/TTNN/IR/TTNNOpsAttrs.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/lib/ttnn/operations/data_movement/concat.cpp
- test/ttmlir/Dialect/TTIR/data_movement/concat/concat_tests_negative.mlir
- test/ttmlir/Dialect/TTNN/data_movement/concat/concat_tests_negative.mlir
- test/ttmlir/Dialect/TTNN/data_movement/to_memory_config/to_memory_config_tests_negative.mlir
Following GH issue contains all the ops that requires memory_config:
https://github.com/tenstorrent/tt-mlir/issues/1637
Concat op is one on the list.
TTNN Concat op requires a memory config attribute.
With this PR we changed:
- We defined the HasMemoryConfigTrait trait that verifies the layout of all the ops with this trait.
- We passed the memory config attribute from TTNN Dialect concat op definition down to the runtime.
> Memory config validation and adding memory config attribute to concat op

- test/ttmlir/Dialect/TTNN/data_movement/concat/concat_tests_negative.mlir
TTNNWorkaround pass assumes that all the previous passes are executed and TTNN IR contains layout and other attributes. However ttnn.concat negative test does not include said attributes causing TTNNWorkaround pass to crash.
Temporarily disable the test.
> Disable ttnn.concat negative test

- .github/actions/build-tt-mlir-action/action.yaml
- cmake/modules/TTMLIRVersion.cmake
closes #2169
Current git stansa `git describe --tags --abbrev=0` can pick up tags from personal dev branches, which will results in empty  TTMLIR_VERSION_MAJOR/TTMLIR_VERSION_MINOR defs and a broken build.
Final change is to add a glob filter that will select the latest tag matching `v<digit>*.<digit>*`, which is compatible with our current release tag format but should also reduce the probability that a personal dev tag gets picked up.
Note that using `git tag --merged main ...` was promising in local builds but seems problematic in CI which uses detached head clones. 
Tested against multiple tags in a dev branch and observed a CI run succeed with the latest changes.
> make release tag discovery more robust

- include/ttmlir/Dialect/TTNN/Utils/TransformUtils.h
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Dialect/TTNN/Transforms/Passes.cpp
- lib/Dialect/TTNN/Utils/TransformUtils.cpp
- test/ttmlir/EmitC/TTNN/models/llama_prefill.mlir
- test/ttmlir/EmitC/TTNN/models/resnet.mlir
- test/ttmlir/EmitC/TTNN/tensor/repeat_interleave.mlir
- tools/ttnn-standalone/ci_compile_dylib.py
- tools/ttnn-standalone/ttnn-precompiled.hpp
Closes #2143
Add llama and resnet tests for emitc path.
- For llama, it was needed to tackle several issues:
- `ttnn::repeat_interleave` support added thru emitc
- Pass `--ttnn-create-input-gens` wasn't putting tensors on device when they were assumed on device by their layout desc, fixed that
- Added resnet test, currently unsupported, awaiting further op support
- Change the dylib compilation script `ci_compile_dylib.py` to not remove `ttnn-dylib.cpp` as it is useful for debugging - this is okay as the file is gitignored already
> Add llama and resnet emitc tests

- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNWorkarounds.h
- lib/Dialect/TTNN/IR/TTNNWorkarounds.cpp
- lib/Dialect/TTNN/Transforms/TTNNLayout.cpp
- test/ttmlir/Dialect/TTNN/Transforms/Workarounds/slice_workaround.mlir
- test/ttmlir/Silicon/StableHLO/n150/slice_op.mlir
* Strided slice can only work with bfloat16 tensor
closes #1453 
closes #2150 
#1453 
#2150 
tt-metal supports strided slice operation for bfloat16 data type
Added a layout workaround for converting data type to bfloat16 in case of strided slice operation.
> Add workaround for strided slice operation

- runtime/tools/python/CMakeLists.txt
https://github.com/tenstorrent/tt-mlir/issues/2187
The incremental build of TTRT is not working properly.  As I understand the root cause is that `python -m pip wheel` will run only when one of the files in `runtime/tools/python` is touched, but it should also run in case `TTRuntime` or some of its dependencies have changed because we need to rebuild `ttrt.runtime._C` and `ttrt.binary._C` shared libraries.
Added new dependencies. This is a somewhat hacky solution, so I'm very open to suggestions on how to improve this, or even take a different approach.
> TTRT incremental build fix

- include/ttmlir/Dialect/TTMetal/Pipelines/TTMetalPipelines.h
- test/python/golden/test_ttir_ops.py
- test/ttmlir/Silicon/TTMetal/n150/perf/test_perf_add.mlir
- test/ttmlir/Silicon/TTMetal/n150/perf/test_perf_div.mlir
- test/ttmlir/Silicon/TTMetal/n150/perf/test_perf_exp.mlir
- test/ttmlir/Silicon/TTMetal/n150/perf/test_perf_max.mlir
- test/ttmlir/Silicon/TTMetal/n150/perf/test_perf_multiply.mlir
- test/ttmlir/Silicon/TTMetal/n150/simple_constant.mlir
- test/ttmlir/Silicon/TTMetal/n150/simple_eltwise.mlir
- test/ttmlir/Silicon/TTMetal/n150/simple_max.mlir
- test/ttmlir/Silicon/TTMetal/n150/simple_reduce_1x1.mlir
This closes #2131
Existing ttmetal tests get broken when the new stream/alias encoding is enabled, this disables the failing tests until v1 pipeline is ready.
- TTMetalPipelines.h: set 'version' default to be 1
- test/ttmlir/Silicon/TTMetal/n150/* mlir tests marked with `// UNSUPPORTED: true`
- test/python/golden/test_ttir_ops.py all tests marked with `targets=["ttnn"]`
- looking for CI to remain green on n150 arch
> mark failing v0 tests UNSUPPORTED

- runtime/include/tt/runtime/detail/workarounds.h
- runtime/lib/common/workarounds.cpp
- runtime/lib/ttnn/operations/pool/maxpool2d.cpp
- runtime/tools/python/test/test_run.py
- runtime/tools/python/ttrt/common/run.py
https://github.com/tenstorrent/tt-mlir/issues/855
We currently pre-shard the input to ttnn::max_pool2d in the runtime.
I've removed this workaround since this is taken care of within the ttnn::max_pool2d op.
> Remove maxpool2d preshard workaround

- runtime/include/tt/runtime/detail/workarounds.h
- runtime/lib/common/workarounds.cpp
- runtime/lib/ttnn/operations/conv/conv_transpose2d.cpp
- runtime/lib/ttnn/operations/data_movement/pad.cpp
- runtime/lib/ttnn/operations/pool/maxpool2d.cpp
- runtime/tools/python/ttrt/common/run.py
https://github.com/tenstorrent/tt-mlir/issues/2167
With https://github.com/tenstorrent/tt-metal/pull/17640 `QueueId` is now optional in all calls. There were 3 cases where we couldn't use signature without `QueueId`, that restriction is now removed.
Removed `QueueId` and stuff related to it from `conv_transpose2d`, `pad` and `max_pool2d`.
> Remove `QueueId` from ops in runtime

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Target/TTNN/program.fbs
- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Dialect/TTNN/Transforms/Workarounds/TTNNWorkarounds.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/lib/ttnn/operations/ccl/all_gather.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/ccl_ops.mlir
- test/ttmlir/Dialect/TTNN/ccl/all_gather.mlir
- test/ttmlir/Dialect/TTNN/ccl/all_gather_negative.mlir
- test/ttmlir/Dialect/TTNN/ccl/all_reduce.mlir
- test/ttmlir/Silicon/TTNN/llmbox/ccl/ccl_1x8.mlir
- test/ttmlir/Silicon/TTNN/llmbox/ccl/ccl_2x4.mlir
- test/ttmlir/Silicon/TTNN/llmbox/perf/all_gather.mlir
- test/ttmlir/Silicon/TTNN/llmbox/perf/all_reduce.mlir
- test/ttmlir/Silicon/TTNN/n300/ccl/ccl_1x2.mlir
- test/ttmlir/Silicon/TTNN/n300/perf/all_gather.mlir
- test/ttmlir/Silicon/TTNN/n300/perf/all_reduce.mlir
- test/ttmlir/Silicon/TTNN/tg/ccl/ccl_1x32.mlir
- test/ttmlir/Silicon/TTNN/tg/ccl/ccl_8x4.mlir
- test/ttmlir/Silicon/TTNN/tg/perf/all_gather.mlir
Captured all all_gather attributes in shlo dialect into ttir. Kept consistent naming convention for attributes found in shlo across tt-mlir stack. Updated ttir to ttnn conversion to account for dynamic cluster_axis and removed cluster axis constraint of being 1 in runtime code for all_gather.
We model all_gather in ttir dialect as the following
```
let arguments = (ins AnyRankedTensor:$input,
AnyRankedTensor:$output,
SI32Attr:$all_gather_dim,
OptionalAttr<SI32Attr>:$channel_handle,
UnitAttr:$use_global_device_ids,
I64ElementsAttr:$replica_groups);
```
ttnn model
```
let arguments = (ins AnyRankedTensor:$input,
TT_Device:$device,
SI32Attr:$all_gather_dim,
SI32Attr:$cluster_axis,
DefaultValuedAttr<SI32Attr, "1">:$num_links);
```
Previously, cluster_axis was set to 1 in runtime, however, if …
> #2061: Updated all_gather shlo conversion into ttir and ttnn

- lib/Conversion/TTIRToTTMetal/AttachMetalLayout.cpp
- lib/Dialect/TTIR/Transforms/Layout.cpp
- lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp
This PR has a few miscellaneous changes to prep for metal backend lowering flow:
- initialize tensor inputs as tilized
- Setup boilerplate pass structure
> Prerequisite changes for d2m new lowering

- tools/explorer/tt_adapter/src/tt_adapter/mlir.py
Closes #2154 
Multiple occurrences of the same operand were being added to the graph. 
Now adding only one node to the graph for each operand.
> Omit duplicate operands in graph

- runtime/include/tt/runtime/detail/ttnn.h
- runtime/include/tt/runtime/runtime.h
- runtime/lib/runtime.cpp
- runtime/lib/ttnn/runtime.cpp
As outlined in issue https://github.com/tenstorrent/tt-mlir/issues/2203, the fact that there is no way to create an owned tensor has posed a significant problem to the tt-xla frontend and the multichip effort. This PR exposes that functionality, allowing creating of tensors in which the ttnn runtime owns the tensor data.
Fixes https://github.com/tenstorrent/tt-mlir/issues/2203
> Exposed the createOwnedTensor API in the runtime to the frontends

- include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- python/Passes.cpp
- python/test_infra/ttir_builder.py
- tools/explorer/tt_adapter/src/tt_adapter/runner.py
- PR closes #2027 
- Changes container for `GoldenTensor` in Python to be a shared_ptr, ensuring data is maintained and not copied.
- Uses `GoldenTensor` custom constructor instead of `create_golden_tensor`.
- Creates copy of supplied data_ptr (size of data must also be provided, example in `ttir_builder.py`) and stores within GoldenTensor object.
> Removed create_golden_Tensor, created "safe" custom Constructor

- python/test_infra/ttir_builder.py
- test/python/golden/test_ttir_ops.py
Closes #1961
Closes #1759
`transpose` wasn't exposed to `ttir_builder`, preventing llama attention layer modelling
To @vprajapati-tt for inadvertently fixing a blocking memory issue that was exposed by this bug (See #2136 )
> Add `transpose` to `ttir_builder`

- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNWorkarounds.h
- include/ttmlir/Target/TTNN/program.fbs
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Dialect/TTNN/IR/TTNNWorkarounds.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/lib/ttnn/include/tt/runtime/ttnn/utils.h
- runtime/lib/ttnn/operations/CMakeLists.txt
- runtime/lib/ttnn/operations/creation/constant.cpp
- runtime/lib/ttnn/operations/creation/constant.h
- runtime/lib/ttnn/program.cpp
- runtime/lib/ttnn/runtime.cpp
- runtime/lib/ttnn/utils/utils.cpp
- test/ttmlir/Dialect/TTNN/simple_constant.mlir
- test/ttmlir/Silicon/TTNN/n150/simple_constant.mlir
https://github.com/tenstorrent/tt-mlir/issues/1584
We didn't have a way to create an arbitrary constant tensor. This PR introduces constant 'op' in the TTNN dialect and runtime.
Here is a good description of the approach https://github.com/tenstorrent/tt-mlir/issues/1584#issuecomment-2543314700. To summarize, there isn't a constant op in `TTNN` lib, but the way to deal with it is to model it as a `ConstantOp` in TTNN dialect and use the provided `ttnn::Tensor` constructor for creation of tensor in the runtime.
Previously, there was a `ttir.constant` that would lower to `ttnn.full` if provided value is a single number that broadcasts to full dimension. This PR doesn't change that case, and still tries to lower to `ttnn.full` whenever possible, but otherwise lowers to `ttnn.constant`.
> ConstantOp in TTNN and runtime

- include/ttmlir/Dialect/TTIR/IR/TTIROpsAttrs.td
- lib/Dialect/TTIR/Transforms/HoistCPUOps.cpp
- lib/Dialect/TTNN/Transforms/TTNNLayout.cpp
- test/ttmlir/Dialect/TTNN/ttir_to_ttnn_pipeline_hoist_call.mlir
In earlier TTNNLayout PR, I missed a change to HoistCPUOps.cpp which tags hoisted calls with special attr.  This PR adds in this change + makes it a ttir dialect attr instead of an anonymous one.
Small change to hoisting logic to tag resulting calls with `ttir.hoisted_call` attr, used by TTNNLayout.cpp.  Change testcase to reflect this.
> Tag hoisted calls with special attr

- CMakeLists.txt
- include/ttmlir/Target/Utils/FuncOpToProgram.h
https://github.com/tenstorrent/tt-mlir/issues/2159
Described in https://github.com/tenstorrent/tt-mlir/pull/2157 and https://github.com/tenstorrent/tt-mlir/pull/1782.
This should fix the issue with debug string execution time for good. I have removed the workaround introduced in https://github.com/tenstorrent/tt-mlir/pull/1782, since debug string execution time is now negligible even for larger models. 
All credits to @nsmithtt for discovering this.
> Use `AsmState` instead of `PrintFlags` in `getOpDebugString` 

- include/ttmlir/Dialect/TT/IR/TTOpsEnums.td
- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Dialect/TT/Utils/PopulateArgumentTypes.h
- include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
- lib/Dialect/TT/CMakeLists.txt
- lib/Dialect/TT/Utils/CMakeLists.txt
- lib/Dialect/TT/Utils/PopulateArgumentTypes.cpp
- lib/Dialect/TTNN/Pipelines/CMakeLists.txt
- lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
- lib/RegisterAll.cpp
- test/ttmlir/Dialect/TTIR/populate_argument_types/negative/incorrect_arg_count_provided.mlir
- test/ttmlir/Dialect/TTIR/populate_argument_types/negative/invalid_function_name_provided.mlir
- test/ttmlir/Dialect/TTIR/populate_argument_types/positive/populate_multiple_funcs_with_existing_attrs.mlir
- test/ttmlir/Dialect/TTIR/populate_argument_types/positive/populate_with_exsting_attrs.mlir
- test/ttmlir/Dialect/TTIR/populate_argument_types/positive/populate_with_no_existing_attrs.mlir
Issue: https://github.com/tenstorrent/tt-mlir/issues/2032
- Create `TTPopulateArgumentTypes` pass which can be used to add argument types to the functions of a module. 
- Provide `TTIRToTTNNBackedPipeline` option which can be used to populate the argument types of all public functions in the MLIR module. `TTPopulateArgumentTypes` is added to `TTIRToTTNNBackendPipeline`
- Argument types are stored in the `FuncOp`s `arg_attrs` attribute. 
- If this option is unpopulated it defaults to an empty `llvm::StringMap`, in which case the pass that populates the attributes returns immediately - doing nothing.
- If any arg attributes are populated before running this pass, they will remain. **Except** any existing `tt.argument_type` attributes. If this pass is run, the existing `tt.argument_type` …
> Add argument type and pass which can populate them

- .github/workflows/build-and-test.yml
Part of bringing up runtime debug in CI #2125
Currently we don't have runtime debug tests in CI.
Added runtime debug silicon tests with `-DTT_RUNTIME_DEBUG=ON`
> Add runtime debug silicon tests to n150 CI

- include/ttmlir/Dialect/TT/IR/TTOpsTypes.h
- include/ttmlir/Dialect/TTNN/Utils/Utils.h
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- lib/Dialect/TTNN/Analysis/LegalLayoutAnalysis.cpp
- lib/Dialect/TTNN/Transforms/TTNNDecomposeLayouts.cpp
- lib/Dialect/TTNN/Transforms/TTNNLayout.cpp
- lib/Dialect/TTNN/Transforms/Workarounds/TTNNWorkarounds.cpp
- lib/Dialect/TTNN/Utils/TransformUtils.cpp
- lib/Dialect/TTNN/Utils/Utils.cpp
- test/ttmlir/Dialect/TTNN/typecast.mlir
Before we used to perform conversion from mlir type to tt type in different places in the code. #1744 added type conversion in TTNNLayout which converts all types to tt supported types which makes this workaround redundant.
> Remove workaround for to layout in decompose layouts

- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNWorkarounds.h
- lib/Dialect/TTNN/IR/TTNNWorkarounds.cpp
- test/ttmlir/Dialect/TTNN/Transforms/Workarounds/where_workaround.mlir
- test/ttmlir/Silicon/StableHLO/n150/select_op.mlir
closes #2195 
#2195 
tt-metal uses data type of predicate for implementation of ttnn.where op. If the predicate and inputs/output have different data type; then ttnn.where can generate incorrect results or may cause other failures.
Add a data type workaround to apply the input data type to `predicate` if `input` data type is not same as of `predicate`
> Add workaround for ttnn.where

- lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
- lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecompositionPass.cpp
- test/ttmlir/Decomposition/TTIR/pooling/max_pool2d.mlir
- test/ttmlir/Silicon/StableHLO/n150/maxpool2d_op.mlir
closes #2171 
https://github.com/tenstorrent/tt-mlir/issues/2171
TTIR to TTIR decomposition of ttir.pooling to ttir.max_pool2d only handle cases where `kernel size` and `strides` are greater than 1
TTIR to TTIR decomposition pass modified to handle following cases
* Kernel size of 1
* Kernel size of (1, n) or (n, 1)
* Stride size of 1
* Stride size of (1, n) or (n, 1)
> Enhance functionality of max_pool2d op

- include/ttmlir-c/TTAttrs.h
- include/ttmlir/Dialect/TT/IR/TTOpsEnums.td
- include/ttmlir/Dialect/TT/IR/TTOpsTypes.h
- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTIR/Transforms/Passes.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOpsEnums.td
- include/ttmlir/Dialect/TTNN/Utils/Utils.h
- lib/CAPI/TTAttrs.cpp
- lib/Conversion/TTIRToTTMetal/TTIRToTTMetal.cpp
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTIR/Transforms/Layout.cpp
- lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp
- lib/Dialect/TTNN/Utils/Utils.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- python/TTModule.cpp
- test/python/tensor_layout.py
- test/ttmlir/Dialect/TTIR/split_compound_layout.mlir
- test/ttmlir/Dialect/TTIR/test_allocate.mlir
- tools/explorer/tt_adapter/src/tt_adapter/mlir.py
closes #596 
TT_TensorMemoryLayout is unneeded since metal backend doesn't use it. 
Since I just merged #2217 which removes TensorMemoryLayout from metal flatbuffer as well as TensorMemoryLayout::None from ttnn flatbuffer, I thought I would do the same for the compiler as well. 
This PR removes TT_TensorMemoryLayout. With this, TensorMemoryLayout should be unified end to end.
> Remove TT_TensorMemoryLayout

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
- lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecompositionPass.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/reduction/reduce_or_op.mlir
- test/ttmlir/Decomposition/TTIR/reduction/reduce_or.mlir
- test/ttmlir/Dialect/TTNN/reduction/simple_reduce_or.mlir
- test/ttmlir/Silicon/StableHLO/n150/reduction/reduce_or_op.mlir
- test/ttmlir/Silicon/TTNN/n150/simple_reduce_or.mlir
TTNN does not support reduction for logical or operator. So stablehlo.reduce for stablehlo.or operator is decomposed into reduction sum op along give dimension. If ttnn.sum output is zero then reduce_or output is false; otherwise the output is true.
closes #1143 
#1143 
Add support for reduction operation for logical or operator
- `ttir.reduce_or` op is added in TTIR dialect
- `ttir.reduce_or` op is decomposed/converted to `ttir.sum` op as tt-metal does not support reduction or operation.
- Stablehlo conversion for reduce or op.
> Add support for stablehlo.reduce op for logical or operator

- CMakeLists.txt
https://github.com/tenstorrent/tt-mlir/issues/2270
Currently, Shardy include files are not available to frontend SW stack since we are not installing them to install directory.
This patch allows include files after building Shardy and install files in install directory.
- [V] Locally confirmed that files are copied to install directory.
> Allow shardy include files in install directory

- include/ttmlir/Dialect/TTIR/IR/TTIRGenericRegionOps.td
- lib/Dialect/TTIR/IR/TTIRGenericRegionOps.cpp
#1948 
Add `ttir.tile_tilize_block` and `ttir.tile_untilize_block` ops to the TTIR generic region ops. 
Add respective verifiers to match input/output element types.
> Add tilize/untilize ttir generic region ops

- test/unittests/lit.cfg.py
I assume this was added during development for debug purposes, it would print something like
```
[0/1] Running the ttmlir regression tests
/localdev/azecevic/tt-mlir
/opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/ttrt/runtime
ARCH_NAME=wormhole_b0
```
every time you run `check-ttmlir`.
> Remove debug print when running tests

- runtime/lib/common/system_desc.cpp
- runtime/lib/ttmetal/runtime.cpp
- runtime/lib/ttnn/operations/context/get_device.cpp
- runtime/lib/ttnn/operations/eltwise/binary/binary.cpp
- runtime/lib/ttnn/operations/eltwise/binary/binary_composite.cpp
- runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/eltwise/binary/utils.cpp
- runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/eltwise/binary/utils.h
- runtime/lib/ttnn/runtime.cpp
- third_party/CMakeLists.txt
This PR uplifts the third_party/tt-metal to the 57ba436ec4366d9129df6a53b2d9e1e828ef0356
- Remove references to SimpleMeshShape after metal commit f3bb74d
- Temporary hacks to support int32 for binary ops in runtime (binary.cpp, binary_composite.cpp, utils.cpp, utils.h changes) because tt-metal disallow uint32 for some binary ops.
> Uplift third_party/tt-metal to 57ba436ec4366d9129df6a53b2d9e1e828ef0356 2025-02-25

- python/test_infra/test_utils.py
- test/python/golden/test_ttir_models.py
- test/python/golden/test_ttir_ops.py
- test/ttmlir/Silicon/TTNN/n150/models/llama_attention.mlir
Closes #1768 
PoC for large real world model chunks through `TTBuilder`. Also demonstrates a golden check for said model.
The Silicon test of the generated `ttir` `mlir` Llama attention block is _not_ filechecked. If requested we could use [this script](https://github.com/llvm/llvm-project/blob/main/mlir/utils/generate-test-checks.py) to generate them, but our canonical and atomic checks for ops and common patterns should be robust enough to guarantee correctness here. I attempted to manually do it and got about halfway before thoughts of sunken cost fallacy started entering my head. We should set up a set of standards for FileCheck in the future.
> Add LLama Attention Block To `TTBuilder` & Test

- include/ttmlir/Utils.h
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- test/ttmlir/Dialect/TTNN/simple_subtract_to_add.mlir
https://github.com/tenstorrent/tt-mlir/issues/2283
In one place in TTIR->TTNN conversion, `NegOp` is created as DPS op, even though it isn't.
Since `NegOp` is elementwise op and they were recently changed from DPS to non DPS op it was an error to create it like a DPS op, because it took empty tensor as an input. Added `static_assert`s in DPSOp creation functions to check if target op is actually a DPS op.
> Create `ttnn.neg` as non-DPS op

- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/constant_op.mlir
- test/ttmlir/Dialect/TTNN/simple_constant.mlir
closes https://github.com/tenstorrent/tt-mlir/issues/2287
LLVM disabled `implicitTruncate` as default option for APInt constructor which triggered assertion for negative constant. It also caused failure for 64 bit constant as 64 bit constants are converted to 32 bit implicitly (64 bit integer is unsupported hardware type).
- Use APInt object to extract constant values instead of basic data types (int16_t, 
uint16_t, int32_t, uint32_t, etc.) which covers both positive and negative values.
- Use APInt::truncSSat() (truncation with sign saturation) instead of implicit truncation. 
This will convert `-INT64_MIN` to `-INT32_MIN` instead of converting it to `0`.
- TTIR->TTNN conversion for `ttir.constant` is also updated to consider signless integer
as signed value as they can also store …
> Add support for negative constant

- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Dialect/TTNN/Transforms/TTNNLayout.cpp
- test/ttmlir/Dialect/TTNN/Canonicalizer/simple_to_layout_op_canonicalizer.mlir
Closes https://github.com/tenstorrent/tt-mlir/issues/2102
In certain passes, we add multiple TTNN ToLayoutOps and have an assertion check in LayoutDecomposition to identify redundant ToLayoutOps.
A new folder has been created for TTNN ToLayoutOps that folds them when a redundant ToLayoutOp is detected.
> Adding ToLayout op folding

- tools/ttnn-standalone/CMakeLists.txt
- tools/ttnn-standalone/ttnn-standalone.cpp
#2301
TTNN Standalone fails on main due to 2 errors:
- stale LegacyShape used
- ttnn-dylib.cpp doesn't exist so the build script fails
Removed stale LegacyShape; added few lines to CMake script to create file if not already there.
> Fix ttnn-standalone.cpp; auto create ttnn-dylib.cpp so that the build script doesn't fail

- .github/workflows/build-and-test.yml
N/A
We started running out of space when building on Github runners.
~Free up space on runners by removing unneeded packages using https://github.com/easimon/maximize-build-space action~
Free up space on runners by using custom action that removes unused software packages from Github runner
> Maximize build space on Github runners

- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNWorkarounds.h
- lib/Dialect/TTNN/IR/TTNNWorkarounds.cpp
- test/ttmlir/Dialect/TTNN/Transforms/Workarounds/binary_ops_workaround.mlir
- test/ttmlir/Dialect/TTNN/data_movement/repeat/implicit_repeat.mlir
- test/ttmlir/Dialect/TTNN/implicit_broadcast.mlir
Closes https://github.com/tenstorrent/tt-mlir/issues/2321
tt-metal has introduced type checker for binary ops which aborts program
in case of any mismatch. 
tt-metal PR: https://github.com/tenstorrent/tt-metal/pull/17828
Add a workaround for binary ops.
> Add data type workaround for binary ops

- include/ttmlir/Conversion/StableHLOToTTIR/ShardingUtils.h
- lib/Conversion/StableHLOToTTIR/ShardyToTTIRPatterns.cpp
- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/lib/ttnn/operations/ccl/mesh_shard.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/ccl/ccl_ops_gspmd.mlir
- test/ttmlir/Conversion/StableHLOToTTIR/ccl/ccl_ops_shardy.mlir
https://github.com/tenstorrent/tt-mlir/issues/2297
PJRT expects the return values to be sharded instead of being merged into a tensor with a single buffer if there is sharding attribute in return value. 
This PR provides special care for the return values just like we do for input tensors. It checks the return value attribute and if the sharding attribute is there, mark the returning mesh_shard op as manual such that runtime will not perform any concat operation and returns multiple buffers.
- [V] New/Existing tests provide coverage for changes
> Check and update return sharding

- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Dialect/TTNN/Transforms/Workarounds/Decomposition/ReduceOpsRewritePattern.h
- include/ttmlir/Target/TTNN/program.fbs
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTIRToTTNN/Utils.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Dialect/TTNN/Transforms/Workarounds/TTNNWorkarounds.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/lib/ttnn/operations/data_movement/concat.cpp
- runtime/lib/ttnn/operations/data_movement/reshape.cpp
- test/ttmlir/Dialect/TTIR/data_movement/reshape/reshape_tests_negative.mlir
- test/ttmlir/Dialect/TTNN/data_movement/reshape/reshape_folding_test.mlir
- test/ttmlir/Dialect/TTNN/data_movement/reshape/reshape_tests_negative.mlir
- test/ttmlir/Dialect/TTNN/data_movement/reshape/reshape_tests_positive.mlir
- test/ttmlir/Dialect/TTNN/simple_reshape.mlir
- test/ttmlir/Silicon/TTNN/n150/data_movement/reshape/reshape.mlir
The following GH issue contains all the ops that require memory_config:
https://github.com/tenstorrent/tt-mlir/issues/1637
Reshape op is one on the list.
TTNN Reshape op requires a memory config attribute.
I added the memory config trait to a reshape op and implemented the memory config e2e.
> Adding memory config to a reshape op

- lib/OpModel/TTNN/CMakeLists.txt
- runtime/lib/ttmetal/CMakeLists.txt
- test/unittests/OpModel/TTNN/Conversion/CMakeLists.txt
- test/unittests/OpModel/TTNN/Lib/CMakeLists.txt
- test/unittests/OpModel/TTNN/Op/CMakeLists.txt
- third_party/CMakeLists.txt
- tools/ttnn-standalone/CMakeLists.txt
This PR uplifts the third_party/tt-metal to the f05457a1eb5b45fddbd60b35835439994e06ae9d
- Include tt_metal/ header path in ttnn-standalone after metal commit 8b2d814
- Get rid of no-rtti to support dynamic_cast
- Pick this tt-metal commit f05457a1eb5b45 intentionally since commit right after gives error "Kernel file tests/tt_metal/tt_metal/test_kernels/compute/tilize_wh.cpp doesn't exist"
> Uplift third_party/tt-metal to f05457a1eb5b45fddbd60b35835439994e06ae9d 2025-02-28

- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/OpModel/TTNN/TTNNOpModel.h
- lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
- lib/OpModel/TTNN/MetalHeaders.h
- lib/OpModel/TTNN/TTNNOpModelLib.cpp
- test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
- test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
#2314 
The optimizer needs more ops with constraints and runtime support to be able to ingest real models. Transpose is useful for both rennet (#2277) and llama (#2084)
Added constraints and runtime APIs to the `transposeOp`. Added unit tests to exercise the new API
Closes #2314
> Add constraints and runtime API to transpose 

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/ccl/ccl_ops_gspmd.mlir
- test/ttmlir/Dialect/TTIR/ccl/all_gather/all_gather_negative.mlir
- test/ttmlir/Dialect/TTIR/ccl/all_reduce/all_reduce_negative.mlir
- test/ttmlir/Dialect/TTIR/ccl/reduce_scatter/reduce_scatter_negative.mlir
- test/ttmlir/Dialect/TTNN/ccl/all_gather.mlir
- test/ttmlir/Dialect/TTNN/ccl/all_gather/all_gather_negative.mlir
- test/ttmlir/Dialect/TTNN/ccl/all_gather/all_gather_positive.mlir
- test/ttmlir/Dialect/TTNN/ccl/all_gather_negative.mlir
- test/ttmlir/Dialect/TTNN/ccl/all_reduce/all_reduce_negative.mlir
- test/ttmlir/Dialect/TTNN/ccl/all_reduce/all_reduce_positive.mlir
- test/ttmlir/Dialect/TTNN/ccl/reduce_scatter/reduce_scatter_negative.mlir
- test/ttmlir/Dialect/TTNN/ccl/reduce_scatter/reduce_scatter_positive.mlir
- test/ttmlir/Silicon/TTNN/llmbox/ccl/ccl_1x8.mlir
- test/ttmlir/Silicon/TTNN/llmbox/ccl/ccl_2x4.mlir
- test/ttmlir/Silicon/TTNN/llmbox/perf/reduce_scatter.mlir
- test/ttmlir/Silicon/TTNN/n300/ccl/ccl_1x2.mlir
- test/ttmlir/Silicon/TTNN/n300/perf/reduce_scatter.mlir
- test/ttmlir/Silicon/TTNN/tg/ccl/ccl_1x32.mlir
- test/ttmlir/Silicon/TTNN/tg/ccl/ccl_8x4.mlir
- test/ttmlir/Silicon/TTNN/tg/perf/reduce_scatter.mlir
Implemented conversion patterns between dialects and flatbuffer. Added tests cases for all valid multichip mesh configurations
> #2005: Added representation of reduce scatter in ttir and ttnn dialect

- tools/scripts/stablehlo_splitter/requirements.txt
- tools/scripts/stablehlo_splitter/shlo_split.py
Add a script that splits stablehlo module into sub modules representing each op individually. Need to pip install -r tools/stablehlo_splitter/requirements.txt to install dependencies.
https://github.com/tenstorrent/tt-mlir/issues/2317
Front-ends (tt-xla, tt-torch) want to run stablehlo graphs op-by-op. We need a mechanism to break down stablehlo modules into standalone sub-modules corresponding to each op individually. 
Added `tools/stablehlo_splitter/shlo_split.py` and `tools/stablehlo_splitter/requirements.txt` 
```
#
from mlir.ir import Context, Module
import mlir.dialects.stablehlo as stablehlo
def parse_module_from_str(module_str):
module = None
with Context() as ctx:
stablehlo.register_dialect(ctx)
module = Module.parse(module_str)
return module
class StablehloSplitter:
def …
```
> Script to split stablehlo module into sub modules [#2317]

- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNWorkarounds.h
- include/ttmlir/Dialect/TTNN/Transforms/Workarounds/Decomposition/ArgMaxOpRewritePattern.h
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Dialect/TTNN/IR/TTNNWorkarounds.cpp
- lib/Dialect/TTNN/Transforms/CMakeLists.txt
- lib/Dialect/TTNN/Transforms/Workarounds/Decomposition/ArgMaxOpRewritePattern.cpp
- lib/Dialect/TTNN/Transforms/Workarounds/TTNNWorkarounds.cpp
- test/ttmlir/Dialect/TTNN/Transforms/Workarounds/argmax_workaround.mlir
- test/ttmlir/Dialect/TTNN/reduction/simple_argmax.mlir
- test/ttmlir/Silicon/StableHLO/n150/reduction/argmax_op.mlir
- test/ttmlir/Silicon/TTNN/n150/simple_argmax.mlir
closes https://github.com/tenstorrent/tt-mlir/issues/2057
tt-metal has some restrictions for `ttnn.argmax` op. Details can be found here
https://docs.tenstorrent.com/tt-metal/latest/ttnn/ttnn/api/ttnn.argmax.html
- Add data type, layout, and reshape workaround.
> ArgMax workaround implementation

- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Dialect/TTIR/IR/TTIROps.h
- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- lib/Conversion/TTIRToTTMetal/TTIRToTTMetal.cpp
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTIR/Transforms/GenericLinearizeMemref.cpp
- lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp
- test/ttmlir/Dialect/TTIR/bufferization/bufferization.mlir
- test/ttmlir/Dialect/TTIR/bufferization/memory_effects.mlir
- test/ttmlir/Dialect/TTIR/generic/generic_negative.mlir
- test/ttmlir/Dialect/TTIR/ttir_generic_hoist.mlir
This change adds 2 new TTIR layout related ops and makes a few refactors to better share common interface and verifier code between them.  The verifiers are also significantly improved and check for many more illegal cases.
StreamLayout operation, similar to the ToLayout operation, but with the difference that this op is not eagerly evaluated and is instead used as a means for defining a stream. The primary usecases include, to enable streaming a large tensor out of dram via a small L1 buffer and also as a means for forming reduce or gather multicast operations. A stream definition includes:
- The tensor to be streamed.
- The storage buffer to be used for streaming.
- Backing memory for a list of DMA transactions to be filled in by the backend.
- A result, which is also able to take a …
> Add View/StreamLayout Operation

- include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
- include/ttmlir/Dialect/TTKernel/IR/TTKernelOpsEnums.td
- include/ttmlir/Dialect/TTKernel/IR/TTKernelOpsTypes.td
- lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
- python/pykernel/pykernel_ast.py
- test/pykernel/matmul_common/reader_bmm_8bank.py
- test/pykernel/matmul_common/reader_bmm_8bank_output_tiles_partitioned.py
- test/pykernel/matmul_common/writer_bmm_8bank.py
- test/ttmlir/Conversion/TTKernelToEmitC/ttkernel.mlir
https://github.com/tenstorrent/tt-mlir/issues/2254
More specifically: 
https://github.com/tenstorrent/tt-mlir/issues/2178
https://github.com/tenstorrent/tt-mlir/issues/2247
https://github.com/tenstorrent/tt-mlir/issues/2249
Want to be able to write reader and writer kernels used in matmul programming examples.
`InterleavedAddrGenFast` cpp struct mapping:
- struct itself is exposed to python through TTKernelOp `get_interleaved_addr_gen_fast`
- conversionpatternrewriter for said Op that will do the following:
```
%6 = "ttkernel.get_interleaved_addr_gen_fast"(%3, %0, %4, %5) : (i1, i32, i32, !ttkernel.DataFormat) -> !ttkernel.interleaved_addr_gen_fast
-> to emitc
%14 = "emitc.variable"() <{value = #emitc.opaque<"">}> : () -> !emitc.lvalue<!emitc.opaque<"InterleavedAddrGenFast<true>">>
%15 = …
```
> Pykernel - matmul common reader/writer kernels

- lib/OpModel/TTNN/Conversion.cpp
- lib/OpModel/TTNN/MetalHeaders.h
- runtime/include/tt/runtime/detail/ttmetal.h
- runtime/lib/ttmetal/command_queue.cpp
- runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/utils.cpp
- runtime/lib/ttnn/operations/reduction/argmax.cpp
- test/unittests/OpModel/TTNN/Conversion/TestConversion.cpp
- third_party/CMakeLists.txt
This PR uplifts the third_party/tt-metal to the bec3eced688f5b154520abed9357aa6440c498db
- Use fully qualified tt_metal types after using namespace directive removed in metal commit 3b28664
- Point tt-metal to commit bec3ece for tilize_wh kernel fix after metal commit 6c77212
- Update argmax params after metal commit 5f6a7b1
> Uplift third_party/tt-metal to bec3eced688f5b154520abed9357aa6440c498db 2025-03-05

- test/unittests/OpModel/TTNN/Lib/CMakeLists.txt
- test/unittests/OpModel/TTNN/Op/CMakeLists.txt
We had a Debug build breakage when -DTTMLIR_ENABLE_OPMODEL=ON on main, so I am bringing back `fno-rtti` compile option to fix it.
> Fix Debug build when -DTTMLIR_ENABLE_OPMODEL=ON

- include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
https://github.com/tenstorrent/tt-mlir/issues/2343
Part of the effort to onboard all TTNN ops to conversion infrastructure introduced in https://github.com/tenstorrent/tt-mlir/pull/2331
Transitioned ops with existing conversion to conversion with the new converter. Few changes in the Emitter class, mainly in the way how operands are treated, to accommodate more complex cases like `Variadic` of tensors that maps to `std::vector<ttnn::Tensor>`.
> TTNN->EmitC transition existing ops to new converter

- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- test/ttmlir/Dialect/TTIR/reduction/negative_invalid_dim_high.mlir
- test/ttmlir/Dialect/TTIR/reduction/negative_invalid_dim_low.mlir
- test/ttmlir/Dialect/TTIR/reduction/negative_shape_mismatch.mlir
- test/ttmlir/Dialect/TTMetal/simple_attach_metal_layout.mlir
Closes https://github.com/tenstorrent/tt-mlir/issues/2369
Some erroneous shapes would pass verification and only fail in the runtime due to wrong interpretation of `dim_arg` when its value is `nullopt`. There is an example in the linked issue.
- Added verification when `dim_arg` is nullopt in TTNN
- Added a shape verification in TTIR
- Added negative tests
> Output shape verification for reduce ops

- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/constant_op.mlir
- test/ttmlir/Dialect/TTNN/constant/negative/simple_constant_sparse_resource.mlir
- test/ttmlir/Dialect/TTNN/constant/positive/simple_constant.mlir
- test/ttmlir/Silicon/StableHLO/n150/Constant/constant_bf16.mlir
- test/ttmlir/Silicon/StableHLO/n150/Constant/constant_bool.mlir
- test/ttmlir/Silicon/StableHLO/n150/Constant/constant_dense_resource_bf16.mlir
- test/ttmlir/Silicon/StableHLO/n150/Constant/constant_f32.mlir
- test/ttmlir/Silicon/StableHLO/n150/Constant/constant_f64.mlir
- test/ttmlir/Silicon/StableHLO/n150/Constant/constant_i16.mlir
- test/ttmlir/Silicon/StableHLO/n150/Constant/constant_i32.mlir
- test/ttmlir/Silicon/StableHLO/n150/Constant/constant_i64.mlir
- test/ttmlir/Silicon/StableHLO/n150/Constant/constant_ui16.mlir
- test/ttmlir/Silicon/StableHLO/n150/Constant/constant_ui32.mlir
- test/ttmlir/Silicon/StableHLO/n150/Constant/constant_ui64.mlir
Closes https://github.com/tenstorrent/tt-mlir/issues/2378
When the value of a `stalbehlo/ttir/ttnn` constant op is a `DenseResourceElementsAttr` instead of a `DenseElementsAttr`, we fail to lower stablehlo to ttir. We also do not yet handle the case where the value of a constant is in a `DenseResourceElementsAttr` when generating the flatbuffer.
- Legalize lowering of `stablehlo.constant` when the value type is `DenseResourceElementsAttr`
- Handle case where value type is `DenseResourceElementsAttr` when generating flatbuffer
- Add verifier to `ttnn.constant` to ensure that the `ElementsAttr` holding the constant data is either `DenseResourceElementsAttr` or `DenseElementsAttr`
> DenseResourceElementsAttr as constant value E2E

- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Target/TTNN/program.fbs
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/lib/ttnn/operations/pool/maxpool2d.cpp
- test/ttmlir/Dialect/TTNN/Transforms/Workarounds/max_pool2d_workaround.mlir
- test/ttmlir/EmitC/TTNN/other/pad.mlir
- test/ttmlir/EmitC/TTNN/pooling/max_pool2d.mlir
- test/ttmlir/Silicon/StableHLO/n150/maxpool2d_op.mlir
- tools/ttnn-standalone/ttnn-precompiled.hpp
#2328 
Maxpool2d is not supported thru emitc.
- Changed MaxPool2d signature in TTNN dialect to match signature of lib.
- Added conversion TTNN->EmitC
- Added test
> Fix maxpool2d signature + add emitc conversion&test

- include/ttmlir/Bindings/Python/TTMLIRModule.h
- include/ttmlir/Dialect/TTNN/Utils/OptimizerOverrides.h
- include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
- lib/Dialect/TTNN/Utils/OptimizerOverrides.cpp
- python/CMakeLists.txt
- python/OptimizerOverrides.cpp
- python/Overrides.cpp
- python/Passes.cpp
- python/TTIRModule.cpp
- python/TTKernelModule.cpp
- python/TTMLIRModule.cpp
- python/TTModule.cpp
- python/TTNNModule.cpp
- python/Util.cpp
- PR closes #1774 
- `nanobind` is now supported through MLIR. It's hopefully leaner, faster, and better supported.
- We should switch our Python bindings over to `nanobind` ASAP to prevent further complications
- Few functional changes to nanobind to support new python object storage methods.
- Switched all of the bindings and build system from `pybind11` -> `nanobind`.
> Move Python Bindings from being defined with Pybind -> Nanobind

- cmake/modules/TTMLIRBuildTypes.cmake
- test/ttmlir/Translate/LLVM/dylib.mlir
Generate a coverage report with:
```bash
lcov --ignore-errors inconsistent,format --include $(pwd) --exclude $BUILD_DIR --directory $BUILD_DIR --capture --output-file $BUILD_DIR/coverage.info
genhtml --ignore-errors inconsistent,format,category $BUILD_DIR/coverage.info -o $BUILD_DIR/coverage-site
echo "Coverage report is available at $BUILD_DIR/coverage-site/index.html"
```
> Add cmake support for code coverage build type

- include/ttmlir/Dialect/TTNN/IR/TTNNOpsAttrs.td
- lib/Dialect/TTNN/Analysis/DFShardingPolicy.cpp
- lib/Dialect/TTNN/Analysis/ShardSolver.cpp
- lib/Dialect/TTNN/IR/TTNNOpsAttrs.cpp
There were a couple methods on TTNN layout that make reference to the device l1/dram memory maps.  These maps are not intended for use in the TTNN dialect and do not model TTNN behavior, they are intended for metal backend only.
I noticed failures because we're trying to change the way these maps work for metal path refactor.
> Remove TTNN layout methods that reference device memory maps

- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/reduction/argmax_op.mlir
Fixes #2387 
ReduceOp conversion pattern fails to match the ReduceOp emitted from JAX for argmax over boolean inputs.
I added the case for i1(booleans) inside the `checkInitValue` function.
> Fix argmax for boolean inputs

- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- test/ttmlir/Dialect/TTIR/conv2d/conv2d_tests_negative.mlir
- test/ttmlir/Dialect/TTNN/conv2d/conv2d_tests_negative.mlir
- test/ttmlir/Dialect/TTNN/conv2d/conv2d_tests_negative_padding.mlir
- test/ttmlir/Dialect/TTNN/conv2d/conv2d_tests_positive.mlir
- test/ttmlir/Dialect/TTNN/convolution/simple_conv2d.mlir
- test/ttmlir/Silicon/TTNN/n150/perf/test_perf_conv2d_config.mlir
- test/ttmlir/Silicon/TTNN/n150/simple_conv2d.mlir
[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/1854)
The TTNN verification was previously reverted in [this commit](https://github.com/tenstorrent/tt-mlir/commit/cc6f36d02687d60a40b0e8712d81c4792becd1f0) to unblock the uplift of frontends. This PR restores the verification while improving test coverage.
- Reintroduce the reverted TTNN verification
- Add positive and negative tests for Conv2D TTNN verification
- Update the description for conv2d in tablegen files
> Refactor TTNN verification and add tests for conv2d op

- lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
- test/ttmlir/Dialect/TTNN/convolution/simple_conv1d.mlir
https://github.com/tenstorrent/tt-mlir/issues/2357
In TTIR to TTIR decomposition, `Legalize1DConvolutionPattern` is not currently supporting spatial dimensions other than 2.
This case is already supported and the check isn't necessary. After reshaping input and output to match 2D `ttir.convolution` op and the new `ttir.convolution` op is picked up by the `ConvolutionToConv2dPattern`, the dimensions are permuted and handled correctly.
Added a test for this case.
> 1D Convolution where input spatial dimension isn't 2

- python/test_infra/ttir_builder.py
- test/python/golden/test_ttir_ops.py
https://github.com/tenstorrent/tt-mlir/issues/1539
Not all TTIR ops are supported by TTIR builder.
Added support in ttir_builder.py for ops sum, max, min.
Added tests in test_ttir_ops.py.
> Added sum, min, max support and tests for TTIR Builder

- runtime/include/tt/runtime/detail/ttmetal.h
- runtime/include/tt/runtime/detail/ttnn.h
- runtime/include/tt/runtime/runtime.h
- runtime/include/tt/runtime/types.h
- runtime/lib/runtime.cpp
- runtime/lib/ttmetal/runtime.cpp
- runtime/lib/ttnn/runtime.cpp
- runtime/test/python/ttnn/test_runtime_api.py
- runtime/tools/python/ttrt/common/callback.py
- runtime/tools/python/ttrt/common/util.py
- runtime/tools/python/ttrt/runtime/__init__.py
- runtime/tools/python/ttrt/runtime/module.cpp
This change implements an API on runtime tensors to reflect tensor metadata and contents reflecting the underlying TTNN tensor. This functionality is pybound as well, allowing for easy casting to torch tensors. Please see `runtime/test/python/ttnn/test_runtime_api.py` for an example.
NOTE: This is not the most efficient implementation possible, as there is effectively a double copy to get the data in a pybindable row major format. There is probably some trickery that can be done later to avoid this, but I would like to get this functionality out ASAP and avoid premature optimization
Big thanks to @tapspatel for helping me figure out the namespace dispatch intricacies here!
Closes #1957
> Implement runtime tensor desc API

- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/OpModel/TTNN/TTNNOpModel.h
- lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
- lib/OpModel/TTNN/Conversion.cpp
- lib/OpModel/TTNN/Conversion.hpp
- lib/OpModel/TTNN/MetalHeaders.h
- lib/OpModel/TTNN/TTNNOpModelLib.cpp
- test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
- test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
- test/unittests/OpModel/TTNN/OpModelFixture.h
#2315 
The optimizer needs more ops with constraints and runtime support to be able to ingest real models. Typecast is used in resnet  (#2277)
Added constraints and runtime API support for typecast. Added unit tests for the new APIs
Closes #2315
> Add constraints and runtime API to typecast

- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Dialect/TTIR/Transforms/Passes.td
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- lib/Dialect/TTIR/Transforms/Utility.cpp
- lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp
- lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
This change adds support for multi-device default values for the system descriptor in the compiler. It assumes a linear mesh connected in ring topology connections. This does not map to a physical layout but allows the user to run compiler passes on a multi-device configuration without having to provide a multi-device system descriptor. 
With change, you can now do this
```
ttmlir-opt --ttir-to-ttnn-backend-pipeline="mesh-shape=2,4" test.mlir
```
> #2403: Updated default system descriptor attributes in compiler to handle multi-device meshes

- test/unittests/Optimizer/TestOptimizerOverrides.cpp
Register OverrideOutputLayoutOption once for all subtests by making it static.
> Fix macos nightly CI

- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/cumsum_op.mlir
fixes #2401 
We retrieve the padding attribute in two places but only guard against it not existing in one place.
Now we read the padding attribute only once and pass it down trough arguments to where it's needed.
> Fix a segfault in ReduceWindowOp conversion

- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
closes https://github.com/tenstorrent/tt-mlir/issues/2418
A function to determine if a constant op is initialized with the desired value is 
implemented in two conversion patterns; reduce op and reduce_window op. 
Duplicate code can cause inconsistent results.
Code refactoring to remove duplicate function and use same function for both
op conversion patterns.
> Remove duplicate code

- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/OpModel/TTNN/TTNNOpModel.h
- lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
- lib/OpModel/TTNN/Conversion.cpp
- lib/OpModel/TTNN/Conversion.hpp
- lib/OpModel/TTNN/MetalHeaders.h
- lib/OpModel/TTNN/TTNNOpModelLib.cpp
- test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
- test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
#2316
The optimizer needs more ops to have runtime/constraints APIs to be able to ingest real models. ToLayout is used in resent (#2277)
Added runtime and constraints API to ToLayout. Added unit tests to exercise the new API. Closes #2316
> Add Constraints and Runtime API for ToLayoutOp

- docs/src/SUMMARY.md
- docs/src/python-bindings.md
- PR closes #947 
- Lack of documentation around Python bindings.
- Simple documentation to understand more about the nuances of the Python bindings, and understand what goes into creating them.
- Look into using `pydoc` to automatically generate function signatures and documentation for Python Bindings. Could be worthwhile upstream change.
> Added Documentation for Python Bindings

- include/ttmlir/Dialect/TT/IR/TTOpsEnums.td
- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Utils.h
- lib/Conversion/TTIRToTTMetal/AttachMetalLayout.cpp
- lib/Conversion/TTIRToTTMetal/TTIRToTTMetal.cpp
- lib/Dialect/TT/IR/TTOpsTypes.cpp
- lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp
- test/ttmlir/Dialect/TTIR/loops/linearize_memref.mlir
- test/ttmlir/Dialect/TTIR/test_allocate.mlir
- test/ttmlir/Silicon/TTMetal/n150/tiled_reblock.mlir
- test/ttmlir/Silicon/TTMetal/n150/to_layout.mlir
This commit is largely broken into 2 parts:
- Reformulations of the l1 and dram memory map
- Breaking the stream layout in half, to distinguish physical shard layout, from a virtual stream layout. This layout refactoring was also done such that their affine maps compose with the way the device memory maps have been redefined.
This PR reformulates the l1 and dram memory maps to make them simpler, easier to use, and more compatible with the new direction of the direct to metal backend path.
This PR also breaks the stream layout into two.  This makes the interpretation of memory for each layout much more explicit and should make it easier for lowering passes to use them in conjunction with the device memory maps.
Describes a stream layout of a memref buffer.
- AffineMap: Provides affine map …
> Reformulate l1 and dram memory maps

- include/ttmlir/Conversion/TTNNToEmitC/Utils.h
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Conversion/TTNNToEmitC/Utils.cpp
- tools/ttnn-standalone/ttnn-precompiled.hpp
Currently, if emitC is run on the following operations (all_gather, reduce_scatter, mesh_shard) it produces incorrect C++ codegen. This PR adds in proper support for all_gather and reduce_scatter to emitC conversion. It adds in an assert for mesh_shard operation until that can be supported.
example
```
ttnn::Tensor v3 = v1[0];
assert(0 && "Mesh shard operation is not supported in emitc yet.");
ttnn::Tensor v4 = ttnn::mesh_shard(v3);
```
> #2426: Add support for all_gather and reduce_scater ttnn to emitc path. Add runtime assert for mesh_shard operation.

- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
- include/ttmlir/Target/TTNN/program.fbs
- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
- lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
- lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- runtime/lib/ttnn/operations/CMakeLists.txt
- runtime/lib/ttnn/operations/ccl/collective_permute.cpp
- runtime/lib/ttnn/operations/ccl/collective_permute.h
- runtime/lib/ttnn/program.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/ccl/ccl_ops_gspmd.mlir
- test/ttmlir/Dialect/TTIR/ccl/collective_permute/collective_permute_negative.mlir
- test/ttmlir/Dialect/TTNN/ccl/collective_permute/collective_permute_negative.mlir
- test/ttmlir/Dialect/TTNN/ccl/collective_permute/collective_permute_positive.mlir
- test/ttmlir/Silicon/TTNN/llmbox/ccl/ccl_1x8.mlir
- test/ttmlir/Silicon/TTNN/llmbox/ccl/ccl_2x4.mlir
- test/ttmlir/Silicon/TTNN/n300/ccl/ccl_1x2.mlir
- test/ttmlir/Silicon/TTNN/tg/ccl/ccl_1x32.mlir
- test/ttmlir/Silicon/TTNN/tg/ccl/ccl_8x4.mlir
- test/ttmlir/Silicon/TTNN/tg/device_parallel/device_parallel_8x4.mlir
In order to support pipeline parallelism in the compiler, collective permute operation lowering is introduced.
The collective permute operation takes a list of source_target_pairs that define how tensor shards currently living in a src device should move to the dest device. 
For example, for a 1x2 mesh system, you could have `[0, 1], [1, 0]` source_target_pairs list. This indicates that the device shard living in device 0 should move to device 1, and the device shard living in device 1 should move to device 0.
In the situation where you have incomplete devices as the 'dest', those devices will acquire a device shard with all values set to 0
Currently, TTNN doesn't not natively support collective_permute or point to point communication ops (send, recv) so the mapping is done by bringing …
> #2377: Added support for collective permute operation with all supported multi device configurations

- lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
- lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecompositionPass.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/OpModel/TTNN/MetalHeaders.h
- lib/OpModel/TTNN/SingletonDeviceContext.h
- lib/OpModel/TTNN/TTNNOpModelLib.cpp
- runtime/lib/common/system_desc.cpp
- runtime/lib/ttnn/operations/data_movement/pad.cpp
- runtime/test/ttnn/dylib.cpp
- test/ttmlir/Decomposition/TTIR/arange/arange_tests_positive.mlir
- test/ttmlir/Dialect/TTIR/Decomposition/arange_decomposition.mlir
- third_party/CMakeLists.txt
- tools/ttnn-standalone/CMakeLists.txt
This PR uplifts the third_party/tt-metal to the bf1298a3e4a3b92dfeae7842f4769826ffa87194
- Update path of tt_stl after metal commit c9dec81
- Include allocator header after transitive includes removed in metal commit c913e48
- Remove reference to v0 namespace after namespace removed in metal commit a9328e6
- Modify ArangeForceLastDimensionPattern to ensure that the output shape is 1D after metal commit 43047b1b26
- Ignore IDevice mangled name
> Uplift third_party/tt-metal to bf1298a3e4a3b92dfeae7842f4769826ffa87194 2025-03-13

- runtime/lib/ttmetal/command_queue.cpp
- runtime/lib/ttmetal/runtime.cpp
- third_party/CMakeLists.txt
This PR uplifts the third_party/tt-metal to the 95e4842659459bdf01c7b961706d0c943f2d5e4d
- Include tracy header after transitive include from metal removed in commit 2725392
> Uplift third_party/tt-metal to 95e4842659459bdf01c7b961706d0c943f2d5e4d 2025-03-14

- include/ttmlir/Conversion/StableHLOToTTIR/ShardingUtils.h
- include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
- include/ttmlir/Dialect/TTNN/IR/TTNNOpsAttrs.h
- include/ttmlir/Dialect/TTNN/IR/TTNNOpsAttrs.td
- lib/CAPI/TTNNAttrs.cpp
- lib/Conversion/StableHLOToTTIR/ShardingUtils.cpp
- lib/Conversion/StableHLOToTTIR/ShardyToTTIRPatterns.cpp
- lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPass.cpp
- lib/Dialect/TTNN/IR/TTNNOps.cpp
- lib/Dialect/TTNN/IR/TTNNOpsAttrs.cpp
- lib/Dialect/TTNN/Transforms/TTNNLayout.cpp
- lib/Target/TTNN/TTNNToFlatbuffer.cpp
- python/TTNNModule.cpp
- test/ttmlir/Conversion/StableHLOToTTIR/ccl/ccl_ops_shardy.mlir
- test/ttmlir/Conversion/StableHLOToTTIR/ccl/e2e_fsdp_shardy.mlir
https://github.com/tenstorrent/tt-mlir/issues/2429
In order to handle single device and multi-device tensors in a graph, we need to know each tensor belongs to single device or multi-device (mesh).
Propagate mesh_sharding attribute including associated "mesh" information to multi-device tensors. Currently, we include associated "mesh" information that the tensor belongs to. We can add detailed sharding info with the following PRs.
No impact on single-device tensors.
Muti-device tensors:
Given mesh info in module attribute, tt.meshes = #tt.meshes<[<"mesh" = 2x4>]> 
TTIR tensors looks like tensor<4096x16384xf32, #tt<mesh_sharding["mesh"]>.
TTNN layout looks like 
#ttnn_layout3 = #ttnn.ttnn_layout<(d0, d1) -> (d0, d1), <1x1>, mesh = ["mesh"], memref<4096x196xf32, #system_memory>>
> Annotate multi-device tensors with TensorMeshShardingAttr

- docs/src/docker-notes.md
Fixes
- https://github.com/tenstorrent/tt-mlir/issues/1191
- The docker build `-build-args` flag should be `--build-arg`
- Fixed several spelling/grammar/markdown lint errors.
This PR is a rebase of https://github.com/tenstorrent/tt-mlir/pull/1192
> Fix docker build flag #1191

- include/ttmlir/Dialect/TTNN/Analysis/BFInterleavedPolicy.h
- include/ttmlir/Dialect/TTNN/Analysis/DFShardingPolicy.h
- include/ttmlir/Dialect/TTNN/Analysis/GreedyL1InterleavedPolicy.h
- include/ttmlir/Dialect/TTNN/Analysis/L1ChainConfig.h
- include/ttmlir/Dialect/TTNN/Analysis/LegalLayoutAnalysis.h
- include/ttmlir/Dialect/TTNN/Analysis/MemoryLayoutAnalysis.h
- include/ttmlir/Dialect/TTNN/Analysis/MemoryLayoutAnalysisPolicy.h
- include/ttmlir/Dialect/TTNN/Analysis/OpConfig.h
- include/ttmlir/Dialect/TTNN/Analysis/OpConfigAnalysis.h
- include/ttmlir/Dialect/TTNN/Analysis/ShardSolver.h
- lib/Dialect/TTNN/Analysis/BFInterleavedPolicy.cpp
- lib/Dialect/TTNN/Analysis/DFShardingPolicy.cpp
- lib/Dialect/TTNN/Analysis/GreedyL1InterleavedPolicy.cpp
- lib/Dialect/TTNN/Analysis/L1ChainConfig.cpp
- lib/Dialect/TTNN/Analysis/LegalLayoutAnalysis.cpp
- lib/Dialect/TTNN/Analysis/MemoryLayoutAnalysis.cpp
- lib/Dialect/TTNN/Analysis/OpConfigAnalysis.cpp
- lib/Dialect/TTNN/Analysis/ShardSolver.cpp
- lib/Dialect/TTNN/Transforms/Optimizer.cpp
- test/unittests/Optimizer/TestGreedyL1InterleavedPolicy.cpp
- test/unittests/Optimizer/TestShardSolver.cpp
Up to now optimizer only changes op output layout. In order to get max performance out of an op we need to control it's "config" as well (e.g. Conv2dConfig, MatmulProgramConfig...)
Provide boilerplate needed to start using op configs in Optimizer (for overrides and automatic config picking).
* Add OpConfig as struct that covers both output layout and op specific configurations
* Change all optimizer analysis to use OpConfig instead of just output layout
* All configs are still null
> Add boilerplate for op configs in optimizer

- include/ttmlir/Dialect/TTIR/IR/CMakeLists.txt
- include/ttmlir/Dialect/TTIR/IR/TTIRBase.td
- include/ttmlir/Dialect/TTIR/IR/TTIRGenericRegionOps.td
- include/ttmlir/Dialect/TTIR/IR/TTIROps.h
- include/ttmlir/Dialect/TTIR/IR/TTIROps.td
- include/ttmlir/Dialect/TTIR/IR/TTIROpsTypes.h
- include/ttmlir/Dialect/TTIR/IR/TTIROpsTypes.td
- include/ttmlir/Dialect/TTIR/Transforms/Passes.td
- lib/Dialect/TTIR/IR/CMakeLists.txt
- lib/Dialect/TTIR/IR/TTIRDialect.cpp
- lib/Dialect/TTIR/IR/TTIRGenericRegionOps.cpp
- lib/Dialect/TTIR/IR/TTIROps.cpp
- lib/Dialect/TTIR/IR/TTIROpsTypes.cpp
- lib/Dialect/TTIR/Transforms/CMakeLists.txt
- lib/Dialect/TTIR/Transforms/GenericDatamovement.cpp
- lib/Dialect/TTIR/Transforms/GenericGenerateDatamovement.cpp
- lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp
- test/ttmlir/Dialect/TTIR/generic/generic_datamovement.mlir
- test/ttmlir/Dialect/TTIR/loops/linearize_memref.mlir
- test/ttmlir/Dialect/TTIR/optimize_tensor_layout/optimize_tensor_layout.mlir
This commit adds support for generic op to have multiple regions and also autogenerating generic datamovement threads.
This pass makes the following transformation, given a generic compute region:
```mlir
#map = affine_map<(d0, d1) -> (d0, d1)>
#parallel = #tt.iterator_type<parallel>
^bb0(%arg2: memref<2x4x!tt.tile<32x32, f32>, #l1_>, %arg3: memref<2x4x!tt.tile<32x32, f32>, #l1_>, %arg4: memref<2x4x!tt.tile<32x32, f32>, #l1_>):
affine.for %arg5 = 0 to 2 {
affine.for %arg6 = 0 to 4 {
%0 = affine.load %arg2[%arg5, %arg6] : memref<2x4x!tt.tile<32x32, f32>, #l1_>
%1 = affine.load %arg3[%arg5, %arg6] : memref<2x4x!tt.tile<32x32, f32>, #l1_>
%2 = "ttir.tile_add"(%0, %1) : (!tt.tile<32x32, f32>, !tt.tile<32x32, f32>) -> !tt.tile<32x32, f32>
affine.store %2, %arg4[%arg5, %arg6] : …
```
> TTIR Generic datamovement pass and dma ops
