docs/src/additional-reading.md
docs/src/build.md

As i onboard on the project adding some resources that are missing the the docs.

Update additional reading and build docs

---

docs/src/adding-an-op.md
include/ttmlir/CMakeLists.txt
include/ttmlir/Conversion/CMakeLists.txt
include/ttmlir/Conversion/Passes.h
include/ttmlir/Conversion/Passes.td
include/ttmlir/Conversion/TTNNToEmitC/TTNNToEmitC.h
include/ttmlir/Dialect/TTNN/Passes.td
lib/CMakeLists.txt
lib/Conversion/CMakeLists.txt
lib/Conversion/PassDetail.h
lib/Conversion/TTNNToEmitC/CMakeLists.txt
lib/Conversion/TTNNToEmitC/PopulatePatterns.h
lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
lib/Conversion/TTNNToEmitC/TypeConverter.h
lib/Dialect/TTNN/Transforms/CMakeLists.txt
lib/Dialect/TTNN/Transforms/TTNNToCpp.cpp
lib/Dialect/TTNN/Transforms/TTNNToSerializedBinary.cpp
lib/RegisterAll.cpp
tools/ttmlir-opt/CMakeLists.txt

- #148, take two, as previous one was reverted due to a bug that's since been fixed

Change ttnn->emitc transform to use dialect conversion API

---

.github/workflows/build.yml
test/CMakeLists.txt

Display test summary on gihub
Upload test results as artifacts
Closes #194

Show and upload test report

---

include/ttmlir/Dialect/TTIR/IR/TTIROps.h
include/ttmlir/Dialect/TTIR/IR/TTIROps.td
include/ttmlir/Dialect/TTIR/IR/TTIROpsInterfaces.h
include/ttmlir/Dialect/TTIR/IR/TTIROpsInterfaces.td
lib/Dialect/TTIR/IR/CMakeLists.txt
lib/Dialect/TTIR/IR/TTIROpsInterfaces.cpp

Eltwise interface and builders

---

docs/src/SUMMARY.md
docs/src/specs/device.md
include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
include/ttmlir/Dialect/TTIR/Transforms/Passes.td
include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
lib/Dialect/TT/IR/TTOpsTypes.cpp
lib/Dialect/TTIR/Transforms/Passes.cpp
lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
lib/Dialect/TTNN/Transforms/Passes.cpp
lib/Target/TTNN/TTNNToFlatbuffer.cpp
python/TTModule.cpp
test/python/device_attr.py
test/ttmlir/Dialect/TTIR/test_allocate.mlir
test/ttmlir/Dialect/TTIR/test_generic.mlir
test/ttmlir/Dialect/TTIR/test_grid_set.mlir
test/ttmlir/Dialect/TTIR/test_layout.mlir
test/ttmlir/Dialect/TTMetal/simple_multiply.mlir
test/ttmlir/Dialect/TTNN/multiple_add_with_loc.mlir
test/ttmlir/Dialect/TTNN/multiple_add_with_loc_grid_override.mlir
test/ttmlir/Dialect/TTNN/simple_ge.mlir
test/ttmlir/Dialect/TTNN/simple_matmul.mlir
test/ttmlir/Dialect/TTNN/simple_multiply.mlir
test/ttmlir/Dialect/TTNN/simple_relu.mlir
test/ttmlir/Dialect/TTNN/simple_subtract.mlir
test/ttmlir/Dialect/TTNN/simple_sum.mlir
test/ttmlir/Dialect/TTNN/softmax/simple_softmax.mlir
test/ttmlir/Dialect/TTNN/softmax/softmax_negative_1.mlir
test/ttmlir/Dialect/TTNN/softmax/softmax_negative_2.mlir
test/ttmlir/Dialect/TTNN/ttir_to_ttnn_pipeline.mlir
test/ttmlir/Dialect/TTNN/ttir_to_ttnn_pipeline_custom_opt.mlir

Getting the ball rolling on a device spec.  I still want to add to the section regarding TTNN lowering, but I figure I could start collecting feedback for the rest of it.

Add `tt.device` spec #91

---

runtime/lib/ttnn/program.cpp
runtime/test/ttnn/test_subtract.cpp

#79
Runtime support for Relu op targeting TTNN backend

Runtime Relu op support

---

include/ttmlir/Dialect/TTIR/IR/TTIROps.td
include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/Target/TTNN/program.fbs
lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
lib/Dialect/TTIR/IR/TTIROps.cpp
lib/Dialect/TTIR/Transforms/Passes.cpp
lib/Dialect/TTNN/IR/TTNNOps.cpp
lib/Target/TTNN/TTNNToFlatbuffer.cpp
runtime/lib/ttnn/program.cpp
test/ttmlir/Dialect/TTNN/transpose/simple_transpose.mlir
test/ttmlir/Dialect/TTNN/transpose/simple_transpose_8x16_reverse_dims.mlir
test/ttmlir/Dialect/TTNN/transpose/simple_transpose_8x8.mlir
test/ttmlir/Dialect/TTNN/transpose/simple_transpose_negative_dims.mlir

Implemented Transpose op through TTIR, TTNN, flatbuffer, runtime. Added unit tests.
#242

Implemented Transpose op end-to-end.

---

include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
include/ttmlir/Dialect/TTKernel/IR/TTKernelOpsTypes.td
lib/Dialect/TTMetal/IR/TTMetalDialect.cpp
lib/Dialect/TTMetal/Transforms/KernelsToCpp.cpp
lib/Dialect/TTMetal/Transforms/Passes.cpp
test/python/simple_kernel.py

- Add new noc dataflow APIs
- Lower them to EmitC dialect
- Add EmitC dialect type conversion for NocAddr
- Add support for arith dialect in TTKernelToEmitC path
- Protect arith constants from being hoisted outside of ttmetal.dispatch region

Add noc dataflow API for doing async read/write prereq for #321

---

runtime/lib/ttnn/program.cpp
test/ttmlir/Dialect/TTNN/transpose/simple_transpose.mlir
test/ttmlir/Dialect/TTNN/transpose/simple_transpose_8x16_reverse_dims.mlir
test/ttmlir/Dialect/TTNN/transpose/simple_transpose_8x8.mlir
test/ttmlir/Dialect/TTNN/transpose/simple_transpose_negative_dims.mlir

Modified transpose op to work with new TTNN version.
Modified transpose tests to match PR #289.

Modified transpose op to work with new TTNN version.

---

runtime/lib/ttnn/program.cpp

Closes #391 
Previously fullOp didn't do anything so no issues. With the addition of EmptyOp replacing FullOp, EmptyOp now occupies the global id slot in the live tensors map, therefore any try_emplaces from any later op that outputs to the same global id will be rejected. Updating to insert_or_assign fixes this issue.

Fix output after EmptyOp update

---

test/ttmlir/Dialect/TTIR/test_stablehlo_dialects.mlir

Add test to check all additional dialects when stablehlo is enabled.

Add test to check stablehlo dialects.

---

include/ttmlir/Dialect/TTIR/Analysis/LegalGridAnalysis.h
include/ttmlir/Dialect/TTIR/Analysis/OptimalTargetGridAnalysis.h
lib/Dialect/TTIR/Analysis/LegalGridAnalysis.cpp
lib/Dialect/TTIR/Transforms/Passes.cpp

The entire layout spec is needed in order to perform analysis.

Change grid analysis to use LayoutAttr

---

runtime/lib/ttnn/program.cpp

Handle OWNED type storage, update asserts to use TT_FATAL for better error messages.
FYI @LPanosTT

Handle OWNED type host storage in ttnn runtime

---

include/ttmlir-c/TTAttrs.h
include/ttmlir/Dialect/TT/IR/TTOpsEnums.td
include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
include/ttmlir/Target/Common/types.fbs
include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
lib/CAPI/TTAttrs.cpp
lib/Dialect/TT/IR/TTOpsTypes.cpp
python/TTModule.cpp
runtime/lib/common/system_desc.cpp

Currently using placeholder values. [#433]

Added supported_data_types and supported_tile_sizes to ChipDesc.

---

include/ttmlir/Dialect/TTIR/IR/TTIROps.td
include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/Target/TTNN/program.fbs
lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
lib/Dialect/TTIR/IR/TTIROps.cpp
lib/Dialect/TTNN/IR/TTNNOps.cpp
lib/Target/TTNN/TTNNToFlatbuffer.cpp
runtime/include/tt/runtime/detail/ttnn.h
runtime/lib/ttnn/program.cpp
test/ttmlir/Dialect/TTNN/simple_concat.mlir

Adding concat op

---

include/ttmlir/Dialect/TTIR/IR/TTIROps.td
include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/Target/TTNN/program.fbs
lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
lib/Dialect/TTIR/IR/TTIROps.cpp
lib/Dialect/TTNN/IR/TTNNOps.cpp
lib/Target/TTNN/TTNNToFlatbuffer.cpp
runtime/lib/ttnn/program.cpp
test/ttmlir/Dialect/TTNN/simple_reshape.mlir

Adding reshape op

---

python/Passes.cpp

As title mentions, simply added a default string argument to the python function `ttir_to_ttnn_backend_pipeline`.

#599 - Added Options Argument to TTIR->TTNN Python-bound Pipeline

---

include/ttmlir/Target/TTNN/program.fbs
lib/Target/TTNN/TTNNToFlatbuffer.cpp
runtime/lib/ttnn/program.cpp

Runtime support for dealloc op, slight refactor

---

runtime/include/tt/runtime/detail/ttmetal.h

Calculate pageSize using dataType byte size

---

include/ttmlir/Conversion/TTKernelToEmitC/TTKernelToEmitC.h
include/ttmlir/Dialect/TTKernel/IR/CMakeLists.txt
include/ttmlir/Dialect/TTKernel/IR/TTKernelAttrInterfaces.td
include/ttmlir/Dialect/TTKernel/IR/TTKernelOpsEnums.td
include/ttmlir/Dialect/TTKernel/IR/TTKernelOpsTypes.h
include/ttmlir/Dialect/TTKernel/IR/TTKernelOpsTypes.td
include/ttmlir/Dialect/TTMetal/IR/TTMetalOps.td
include/ttmlir/Target/Common/types.fbs
include/ttmlir/Target/TTMetal/program.fbs
lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
lib/Dialect/TTKernel/IR/TTKernelOps.cpp
lib/Dialect/TTKernel/IR/TTKernelOpsTypes.cpp
lib/Dialect/TTMetal/Transforms/Passes.cpp
lib/Target/TTMetal/TTMetalToFlatbuffer.cpp
runtime/lib/ttmetal/command_queue.cpp

Refactor program.fbs and add Noc, Ethernet, Tensix KernelConfigs [Compiler/Runtime] [#266]

---

runtime/tools/python/ttrt/common/api.py

Closes #628
**Implemented**
- Added `--artifact-dir` flag to TTRT CLI such that artifacts can be saved to a custom directory.

Added --artifact-dir flag to TTRT CLI

---

include/ttmlir/Dialect/TTIR/IR/TTIROps.td
lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
lib/Dialect/TTIR/IR/TTIROps.cpp
lib/Dialect/TTIR/Transforms/Passes.cpp
test/ttmlir/Conversion/StableHLOToTTIR/constant_op.mlir
test/ttmlir/Dialect/TTNN/simple_constant.mlir

Implement conversion of stablehlo.constant OP to TTIR dialect

---

.github/workflows/build-and-test.yml
lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
runtime/tools/python/ttrt/common/api.py

Also introduce ttrt flag --non-zero to assert the output is non-zero.

Fix main; use to_memory_config to copy back to host

---

runtime/include/tt/runtime/detail/debug.h
runtime/lib/common/debug.cpp
runtime/lib/ttnn/runtime.cpp
runtime/test/CMakeLists.txt
runtime/tools/python/ttrt/common/api.py

Add option to disable async ttnn in debug environment

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp

Add MeshShape as optional argument to GetDeviceOp

---

lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp

The to_layout/from_device was causing the following fallout:
- #779
- #788
- All zeros output, separately addressed #776
For now just reverting back to to_memory_config.

Partial revert 19732d0b2a10b053109d41243a29f95acc9cbabe

---

lib/Dialect/TTNN/IR/TTNNOps.cpp
runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/utils.cpp

Closes #718 
Added these asserts to make sure we don't shard width/height until compiler supports it. As long as the configs generated by the compiler are correct, height/width sharding should work through runtime.

remove runtime asserts that prohibit height and width sharding

---

runtime/lib/ttnn/operations/creation/empty.cpp
runtime/lib/ttnn/operations/creation/full.cpp
runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/utils.cpp
runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/utils.h
test/ttmlir/Silicon/TTNN/simple_constant.mlir

Fixes seg fault when allocating tensors with empty/full on system memory. Add subsequent tests.

Fix empty and full when allocating on system memory, add tests

---

lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
test/ttmlir/Conversion/StableHLOToTTIR/compare_op.mlir

Conversion of stablehlo.compare op to TTIR

---

docs/src/adding-an-op.md
runtime/lib/ttnn/operations/CMakeLists.txt
runtime/lib/ttnn/operations/matmul/matmul.cpp
runtime/lib/ttnn/program.cpp
test/ttmlir/Dialect/TTNN/matmul/simple_matmul.mlir
test/ttmlir/Silicon/TTNN/simple_matmul.mlir

Closes #746 
Also updated compilation headers of matmul unit tests

Update adding an op documentation

---

lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
test/ttmlir/Conversion/StableHLOToTTIR/conv2d_op.mlir
test/ttmlir/Conversion/StableHLOToTTIR/maxpool2d_op.mlir
test/ttmlir/Conversion/StableHLOToTTIR/rehsape_op.mlir

Added conversion patterns so that TTIR can consume a stablehlo conv2d and maxpool2d.

Add conversion pattern for Conv2d and MaxPool2d: Stablehlo --> TTIR

---

runtime/CMakeLists.txt
runtime/lib/ttnn/runtime.cpp

Fix perf dump in close devices

---

lib/Dialect/TTIR/Transforms/Passes.cpp
test/ttmlir/Dialect/TTIR/test_layout.mlir

Fix issue https://github.com/tenstorrent/tt-mlir/issues/885

Fix ttir-layout tensor type mismatch when the func have unused argument

---

lib/Dialect/TTIR/IR/TTIROps.cpp
lib/Dialect/TTNN/IR/TTNNOps.cpp

Currently, all our op verifiers and other op extensions(extraClassDeclarations and op interfaces) are implemented in one big cpp file per dialect:
https://github.com/tenstorrent/tt-mlir/blob/main/lib/Dialect/TTIR/IR/TTIROps.cpp
https://github.com/tenstorrent/tt-mlir/blob/main/lib/Dialect/TTNN/IR/TTNNOps.cpp
This change introduces the structure of operations into these files, improving code readability. For example, all op-specific methods(verifier, folder, etc...) are grouped inside the large file. As we add more MLIR features(like op interfaces, external op declarations, op folders, etc.), this change and organization will simplify future code contributions.
Closes https://github.com/tenstorrent/tt-mlir/issues/896
Closes https://github.com/tenstorrent/tt-mlir/issues/888
**Edit**: We …

Refactoring TTIR\TTNN ops cpp files

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
lib/Dialect/TTNN/IR/TTNNOps.cpp
lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
lib/Target/TTNN/TTNNToFlatbuffer.cpp
test/ttmlir/Dialect/TTNN/embedding/simple_embedding.mlir
test/ttmlir/Dialect/TTNN/remove_empty_op.mlir
test/ttmlir/Dialect/TTNN/simple_max.mlir
test/ttmlir/Dialect/TTNN/simple_mean.mlir
test/ttmlir/Dialect/TTNN/simple_sum.mlir
test/ttmlir/Dialect/TTNN/softmax/simple_softmax.mlir
test/ttmlir/Silicon/TTNN/sharded/simple_eltwise_sharded.mlir
test/ttmlir/Silicon/TTNN/simple_eltwise.mlir
test/ttmlir/Silicon/TTNN/simple_mean.mlir
test/ttmlir/Silicon/TTNN/simple_reductions.mlir

[TTNN Dialect] Fix ops which don't support dps

---

include/ttmlir/Dialect/TTNN/Transforms/Passes.td
lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
lib/Dialect/TTNN/Transforms/Passes.cpp
runtime/lib/ttnn/operations/conv/conv2d.cpp
runtime/lib/ttnn/operations/data_movement/concat.cpp
runtime/lib/ttnn/operations/data_movement/reshape.cpp
runtime/lib/ttnn/operations/data_movement/slice.cpp
runtime/lib/ttnn/operations/data_movement/transpose.cpp
runtime/lib/ttnn/operations/deletion/dealloc.cpp
runtime/lib/ttnn/operations/eltwise/binary.cpp
runtime/lib/ttnn/operations/eltwise/unary.cpp
runtime/lib/ttnn/operations/embedding/embedding.cpp
runtime/lib/ttnn/operations/layout/from_device.cpp
runtime/lib/ttnn/operations/layout/to_device.cpp
runtime/lib/ttnn/operations/layout/to_layout.cpp
runtime/lib/ttnn/operations/layout/to_memory_config.cpp
runtime/lib/ttnn/operations/matmul/matmul.cpp
runtime/lib/ttnn/operations/normalization/softmax.cpp
runtime/lib/ttnn/operations/pool/maxpool2d.cpp
runtime/lib/ttnn/operations/reduction/reduction.cpp
test/ttmlir/Silicon/TTNN/dealloc.mlir

Simple first version which deallocates tensor memory after its last usage.
https://github.com/tenstorrent/tt-mlir/issues/576

[TTNN] Introducing dealloc pass for tensor memory deallocation.

---

include/ttmlir/Dialect/TTIR/Analysis/LegalGridAnalysis.h
include/ttmlir/Dialect/TTIR/Transforms/Passes.td
include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
lib/Dialect/TTIR/Transforms/Optimizer.cpp
lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
test/ttmlir/Dialect/TTNN/sharding_matmul_override_0.mlir
test/ttmlir/Dialect/TTNN/sharding_matmul_override_32.mlir

Added variable max-legal-layouts parameter (#777)

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the

Uplift third_party/tt-metal to  2024-10-19

---

third_party/CMakeLists.txt

Reverts tenstorrent/tt-mlir#950

Revert "Uplift third_party/tt-metal to  2024-10-19"

---

include/ttmlir/Dialect/TTIR/Pipelines/TTIRPipelines.h
lib/Conversion/StableHLOToTTIR/CMakeLists.txt
lib/Dialect/TTIR/Pipelines/TTIRPipelines.cpp
test/ttmlir/Conversion/StableHLOToTTIR/composite_op.mlir

This way the TTIR inliner pass can inline the function calls.

Convert stablehlo.composite ops to func.call ops

---

lib/CAPI/CMakeLists.txt
lib/Conversion/TTNNToEmitC/CMakeLists.txt
lib/Conversion/TosaToTTIR/CMakeLists.txt
python/CMakeLists.txt
python/Passes.cpp

Fix python tests in debug build

---

lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp

Fixes asserts hit on #969 
FYI @LPanosTT

Get element type from memref not tensor

---

lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
test/ttmlir/Dialect/TTNN/simple_constant.mlir

Handle different value types for constant op explicitly for TTNN backend

---

.github/workflows/issue-last-updated.yml

Changing to hardcode ids instead of secret store.

Update IDs from secrets to env vars

---

include/ttmlir/Dialect/TTKernel/IR/TTKernelAttrInterfaces.td

Everyone will want to cherry-pick this fix or rebase once merged.

Fix SPDX Header in TTKernelAttrInterfaces.td (spdx tool started checking it last hour)

---

runtime/include/tt/runtime/detail/ttmetal.h
runtime/include/tt/runtime/detail/ttnn.h
runtime/lib/common/system_desc.cpp

Demote Error via -Wzero-length-array in 3 headers exposed by tt-metal uplift (#1146)

---

runtime/include/tt/runtime/detail/workarounds.h
runtime/lib/common/workarounds.cpp
runtime/lib/ttnn/operations/matmul/matmul.cpp
runtime/tools/python/test/test_run.py
runtime/tools/python/ttrt/common/run.py

Workaround introduced in https://github.com/tenstorrent/tt-mlir/pull/894 is not needed anymore. The issue was fixed in metal https://github.com/tenstorrent/tt-metal/pull/13819.
Closes https://github.com/tenstorrent/tt-mlir/issues/891
FYI @odjuricicTT

Matmul1DProgramConfig workaround removal

---

tools/ttnn-standalone/CMakeLists.txt
tools/ttnn-standalone/README.md
tools/ttnn-standalone/run
tools/ttnn-standalone/ttnn-dylib.cpp
tools/ttnn-standalone/ttnn-dylib.hpp
tools/ttnn-standalone/ttnn-standalone.cpp

- Add CMake target for dylib `ttnn-dylib` with example in `ttnn-dylib.cpp`
- Update `README.md`

Add CMake target for EmitC TTNN dylibs

---

tools/explorer/test/run_tests.py

Fixing CI break due to changing test paths.

[Fix CI] Fix TT-Explorer tests in Ci.

---

lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPass.cpp
lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
test/ttmlir/Conversion/StableHLOToTTIR/binary/concat_op.mlir
test/ttmlir/Conversion/StableHLOToTTIR/constant_op.mlir
test/ttmlir/Silicon/StableHLO/Constant/constant_f64.mlir

Handle stableHLO 64 bit floating point type

---

runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/utils.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the

Uplift third_party/tt-metal to  2024-11-20

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the

Uplift third_party/tt-metal to  2024-11-21

---

third_party/CMakeLists.txt

Update - Passes tt-mlir and tt-forge-fe CI :
tt-mlir::  https://github.com/tenstorrent/tt-mlir/actions/runs/12017989573
tt-forge-fe:  https://github.com/tenstorrent/tt-forge-fe/actions/runs/12019053867

Uplift tt-metal Nov25 69870bd

---

.github/workflows/nightly-uplift.yml

Fix uplift PR by reverting change from https://github.com/tenstorrent/tt-mlir/commit/c7557926ff2f19839a6fa884979a4ae9e32e710f#diff-49eef8ffc84d8d5077f3867d5c3ba2cb9355840b1bc6123dadf8eddca55221ccR40
where tt-mlir reference was used instead of tt-metal

Fix uplift PR

---

runtime/lib/ttmetal/CMakeLists.txt
runtime/test/CMakeLists.txt
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the ab3dc0c4f5c3ce9722261c878970bfa92a212fc9

Uplift third_party/tt-metal to ab3dc0c4f5c3ce9722261c878970bfa92a212fc9 2024-12-02

---

runtime/include/tt/runtime/detail/ttnn.h
runtime/lib/ttnn/operations/pool/maxpool2d.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 6a524ab817aeb09c273e37254f39ad8124ddf2f8

Uplift third_party/tt-metal to 6a524ab817aeb09c273e37254f39ad8124ddf2f8 2024-12-03

---

tools/explorer/tt_adapter/src/tt_adapter/main.py
tools/explorer/tt_adapter/src/tt_adapter/mlir.py
tools/explorer/tt_adapter/src/tt_adapter/runner.py
tools/explorer/tt_adapter/src/tt_adapter/utils.py

- Interim PR, demonstrates the key functionality of node generation, tying in the loc data with the ops perf results and then generating a graph with these results.
- Depends on #1401

Integrate Perf Data into TT-Explorer

---

runtime/lib/common/system_desc.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the dde5614e816b20110b0bb8c96aeefe5a0a7bada1

Uplift third_party/tt-metal to dde5614e816b20110b0bb8c96aeefe5a0a7bada1 2024-12-04

---

runtime/lib/ttnn/operations/conv/conv2d.cpp
runtime/lib/ttnn/operations/pool/maxpool2d.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 3389120b3747b521fa9b7ef333a379554359d961

Uplift third_party/tt-metal to 3389120b3747b521fa9b7ef333a379554359d961 2024-12-05

---

runtime/tools/python/setup.py
third_party/CMakeLists.txt
tools/ttnn-standalone/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 4952f01a39068cba4e85c93cf34c4f95f10f5c34

Uplift third_party/tt-metal to 4952f01a39068cba4e85c93cf34c4f95f10f5c34 2024-12-06

---

runtime/tools/python/ttrt/common/perf.py
tools/explorer/tt_adapter/src/tt_adapter/mlir.py

- PR closes #1499
- Simple fix for the redundant nodes, tested with MNIST + sample provided in issue.
- Carried over rebase fix from #1401

Added fix for redundant constant nodes + small carry over from #1401

---

lib/Conversion/TosaToTTIR/TosaToTTIRPatterns.cpp
test/ttmlir/Conversion/TosaToTTIR/reductions/max.mlir
test/ttmlir/Conversion/TosaToTTIR/reductions/sum.mlir

Add TOSA to TTIR conversions for sum and max reductions

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 10eeea8080971e280fd33ffa0a81d9ec06d49917

Uplift third_party/tt-metal to 10eeea8080971e280fd33ffa0a81d9ec06d49917 2024-12-07

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 8ee1f823ccc6680fd4ba5aa9004487692da1c545

Uplift third_party/tt-metal to 8ee1f823ccc6680fd4ba5aa9004487692da1c545 2024-12-08

---

include/ttmlir/Bindings/Python/TTMLIRModule.h
include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
include/ttmlir/Dialect/TTNN/Utils/OptimizerOverrides.h
include/ttmlir/Dialect/TTNN/Utils/PassOverrides.h
lib/Dialect/TTNN/Utils/OptimizerOverrides.cpp
lib/Dialect/TTNN/Utils/PassOverrides.cpp
python/CMakeLists.txt
python/OptimizerOverrides.cpp
python/TTMLIRModule.cpp
python/test_infra/test_optimizer_overrides.py
python/ttmlir/optimizer_overrides.py

Add initial version of Python lib for optimizer overrides. This library is just pybind wrapper around C++ class for optimizer overrides in MLIR.

Add Python bindings for override mechanism.

---

lib/Conversion/TosaToTTIR/TosaToTTIRPatterns.cpp
test/ttmlir/Conversion/TosaToTTIR/maxpool2d_op.mlir

Adds support for MaxPool2D going trough TTIR's MaxPool2D Op.
closes #1427

Add TOSA to TTIR conversion for MaxPool2D

---

third_party/CMakeLists.txt
tools/ttnn-standalone/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 7768e89929915f40f7fdb45e352dd4b83f335168

Uplift third_party/tt-metal to 7768e89929915f40f7fdb45e352dd4b83f335168 2024-12-09

---

runtime/tools/python/requirements.txt

* Update pytorch version to match `tt-torch`

Update TTRT requirements

---

runtime/lib/common/system_desc.cpp
runtime/lib/ttmetal/runtime.cpp
runtime/lib/ttnn/operations/conv/conv2d.cpp
runtime/lib/ttnn/runtime.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the c2d7b099da7b194475ca7e6cf18c2eff496f866c

Uplift third_party/tt-metal to c2d7b099da7b194475ca7e6cf18c2eff496f866c 2024-12-10

---

runtime/lib/common/system_desc.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 2f59d5e02ef0da955b99cf0f49da1759c772a67a

Uplift third_party/tt-metal to 2f59d5e02ef0da955b99cf0f49da1759c772a67a 2024-12-11

---

tools/explorer/tt_adapter/src/tt_adapter/mlir.py

- Thanks for the help Marco! PR closes #1212 
- Simple string conversion of attributes not being parsed by the frontend.

Fixed Tensor Shapes not showing in Explorer

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the ed413ee399ad289740105b709c20e9144ec4f035

Uplift third_party/tt-metal to ed413ee399ad289740105b709c20e9144ec4f035 2024-12-14

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 6d7cc2c38ae3efc36326f5407698b05fb314b5b0

Uplift third_party/tt-metal to 6d7cc2c38ae3efc36326f5407698b05fb314b5b0 2024-12-16

---

lib/Dialect/TTNN/Transforms/Passes.cpp
runtime/lib/ttnn/include/tt/runtime/ttnn/types.cpp
test/ttmlir/Runtime/TTNN/runtime_stitching/eltwise_binary_op_chain.mlir

ttnn now allows tilizing on device for fp32, updated layout passes to mark this as a valid case

Update layout passes to accept device tilize for f32

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 34e10c321807d0b24fc3bd9c349a9a67c4e5741c

Uplift third_party/tt-metal to 34e10c321807d0b24fc3bd9c349a9a67c4e5741c 2024-12-28

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the d0326ed27d1885b7f0c573f4885f4c9d4f0c9676

Uplift third_party/tt-metal to d0326ed27d1885b7f0c573f4885f4c9d4f0c9676 2024-12-29

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 6b3b9ece9d10715c3fb2aeffa898338a0c5f9a1a

Uplift third_party/tt-metal to 6b3b9ece9d10715c3fb2aeffa898338a0c5f9a1a 2024-12-30

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the c4df003d49057066c59a227d7511fca2e9999043

Uplift third_party/tt-metal to c4df003d49057066c59a227d7511fca2e9999043 2024-12-31

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 0979abdb853ad4cc8a32d90cce6825a3967d1adc

Uplift third_party/tt-metal to 0979abdb853ad4cc8a32d90cce6825a3967d1adc 2025-01-01

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the d9304dd4acf235b03a3e8953b70a069802e0704c

Uplift third_party/tt-metal to d9304dd4acf235b03a3e8953b70a069802e0704c 2025-01-02

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the c066c3f3d2202c87258ed400307e7f6e26d372a7

Uplift third_party/tt-metal to c066c3f3d2202c87258ed400307e7f6e26d372a7 2025-01-03

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the aaf2d7304c138c046efd5c0a94c14da3e6f95ce4

Uplift third_party/tt-metal to aaf2d7304c138c046efd5c0a94c14da3e6f95ce4 2025-01-05

---

.github/workflows/on-pr.yml

During the uplift process trigger tt-torch and tt-forge-fe pipelines for specific version of mlir using override option.
Use uplift mlir version to check if tt-torch and tt-forge-fe can pas when using it.

Add tt-torch to downstream checks

---

lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
lib/Conversion/TTNNToEmitC/TTNNToEmitCPass.cpp
lib/OpModel/TTNN/SingletonDeviceContext.h
lib/OpModel/TTNN/TTNNOpModelLib.cpp
runtime/include/tt/runtime/detail/ttmetal.h
runtime/lib/common/system_desc.cpp
runtime/lib/ttmetal/command_queue.cpp
runtime/lib/ttmetal/runtime.cpp
runtime/lib/ttnn/include/tt/runtime/ttnn/types.cpp
runtime/lib/ttnn/include/tt/runtime/ttnn/types.h
runtime/lib/ttnn/operations/context/get_device.cpp
runtime/lib/ttnn/operations/creation/arange.cpp
runtime/lib/ttnn/operations/creation/empty.cpp
runtime/lib/ttnn/operations/creation/full.cpp
runtime/lib/ttnn/operations/creation/ones.cpp
runtime/lib/ttnn/operations/layout/to_layout.cpp
runtime/lib/ttnn/runtime.cpp
third_party/CMakeLists.txt
tools/ttnn-standalone/ttnn-dylib.cpp
tools/ttnn-standalone/ttnn-precompiled.hpp
tools/ttnn-standalone/ttnn-standalone.cpp

- This PR uplifts the third_party/tt-metal to 47fb1a2fb and includes IDevice changes
- Updates (mostly search and replace) in tt-mlir code to accomodate

Uplift third_party/tt-metal to 47fb1a2fb6e0b62ddfe3fc5fef95c18d4b857c20 2025-01-09 (IDevice changes)

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 9c5a0b2e0a0edba747613d2afb3e56dacb5776ac

Uplift third_party/tt-metal to 9c5a0b2e0a0edba747613d2afb3e56dacb5776ac 2025-01-10

---

tools/explorer/CMakeLists.txt

- Feature branch was merged & deleted on `tenstorrent/model-explorer`. Changed commit to latest on main

Uplift model-explorer commit to latest

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 5d4c047dacf2606dd56c7b4d51d5049bf2c6846a

Uplift third_party/tt-metal to 5d4c047dacf2606dd56c7b4d51d5049bf2c6846a 2025-01-15

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 0b35308ff8e1c37d9643b385fe193ac1bc78bf41

Uplift third_party/tt-metal to 0b35308ff8e1c37d9643b385fe193ac1bc78bf41 2025-01-18

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the eef7b862079a1f5417690b53380412d1aba30440

Uplift third_party/tt-metal to eef7b862079a1f5417690b53380412d1aba30440 2025-01-19

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 8833f73528eb5a606f44c64016ed51f7220352f2

Uplift third_party/tt-metal to 8833f73528eb5a606f44c64016ed51f7220352f2 2025-01-20

---

lib/Dialect/TTNN/IR/TTNNOps.cpp
runtime/lib/ttnn/operations/ccl/mesh_shard.cpp

Enforce input/output tensor of mesh_shard op to be host storage by removing meshDevice in ttnn::distributed APIs.

Enforce input/output tensor of mesh_shard op to be host storage

---

lib/Dialect/TTNN/IR/TTNNOps.cpp
runtime/lib/ttnn/operations/ccl/mesh_shard.cpp

Fix format to meet tt-mlir coding guideline of prior commit 77dad37c072dd3f58b52827332d79cbc40d4caba

Fix format to meet tt-mlir coding guideline

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the dea22dcd2cf9eaf01f872849b0916b1064721653

Uplift third_party/tt-metal to dea22dcd2cf9eaf01f872849b0916b1064721653 2025-01-21

---

.github/workflows/on-pr.yml

Run 'on-pr.yml' workflow in all fronted repos
- tenstorrent/tt-forge-fe
- tenstorrent/tt-torch
- tenstorrent/tt-xla

Run downstream checks for all frontends

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 78f2c0b774ab48bf243093d3111717a8c880dc78

Uplift third_party/tt-metal to 78f2c0b774ab48bf243093d3111717a8c880dc78 2025-01-22

---

.github/CODEOWNERS

Removing @nobradovictt from codeowners file.

Remove @nobradovictt from codeowners

---

runtime/tools/python/CMakeLists.txt
runtime/tools/python/ttrt/common/util.py

- Incrementally copy files to build staging area
- Incrementally build only if files have updated
- Fixup utils.py to support python3.9 (macOS)

ttrt incremental build

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 3430e961a34f7ca91164e7e1a96b86008df68c27

Uplift third_party/tt-metal to 3430e961a34f7ca91164e7e1a96b86008df68c27 2025-01-28

---

include/ttmlir/Dialect/TTIR/Transforms/Passes.td
lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp

Set pipeline pass option default memory space to L1

Add AttachMetalLayout to the metal backend pipeline

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 3adec9c1702bd61f3015d3c659da802fe130be27

Uplift third_party/tt-metal to 3adec9c1702bd61f3015d3c659da802fe130be27 2025-01-29

---

include/ttmlir/Dialect/TTIR/IR/TTIROps.td
include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/Target/TTNN/program.fbs
lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
lib/Dialect/TTIR/IR/TTIROps.cpp
lib/Target/TTNN/TTNNToFlatbuffer.cpp
runtime/include/tt/runtime/detail/ttnn.h
runtime/lib/ttnn/operations/CMakeLists.txt
runtime/lib/ttnn/operations/moreh/moreh_cumsum.cpp
runtime/lib/ttnn/operations/moreh/moreh_cumsum.h
runtime/lib/ttnn/program.cpp
test/ttmlir/Conversion/StableHLOToTTIR/cumsum_op.mlir
test/ttmlir/Dialect/TTIR/cumsum/cumsum_test_negative.mlir
test/ttmlir/Dialect/TTNN/simple_cumsum.mlir
test/ttmlir/EmitC/TTNN/other/cumsum.mlir
test/ttmlir/Silicon/StableHLO/moreh_cumsum_op.mlir
test/ttmlir/Silicon/TTNN/perf_unit/test_perf_cumsum.mlir
test/ttmlir/Silicon/TTNN/simple_cumsum.mlir
tools/ttnn-standalone/ttnn-precompiled.hpp

End to End implementation of moreh cumsum op

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 2e804030c40753c4420a12cbce8ad4639bb50ac8

Uplift third_party/tt-metal to 2e804030c40753c4420a12cbce8ad4639bb50ac8 2025-02-02

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the be19f2d17d56b7ea5267deda107baaad42829888

Uplift third_party/tt-metal to be19f2d17d56b7ea5267deda107baaad42829888 2025-02-03

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 8d9efbfbab99a03f71ca69681606a6c3c05a67ea

Uplift third_party/tt-metal to 8d9efbfbab99a03f71ca69681606a6c3c05a67ea 2025-02-04

---

runtime/lib/ttnn/operations/context/get_device.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the b981271938b34827a53a9f74a49be9a0c3388eed
- Update create_submesh to not pass in mesh type after metal commit b9692a8

Uplift third_party/tt-metal to b981271938b34827a53a9f74a49be9a0c3388eed 2025-02-05

---

python/test_infra/ttir_builder.py
test/python/golden/test_ttir_ops.py

Add `ttir.{Squeeze,Unsqueeze}Op` to Builder

---

.github/actions/build-tt-mlir-action/action.yaml
.github/workflows/build-and-test.yml

Adds a build test to CI that builds ttmlir with `-DTT_RUNTIME_DEBUG=ON`

Add runtime debug build test to CI

---

python/test_infra/ttir_builder.py
test/python/golden/test_ttir_ops.py

Bind `ttir.ReshapeOp` to Builder

---

test/ttmlir/Dialect/TTNN/arange/arange_tests_positive.mlir

closes #1448 
#1448 
Provide context for the problem.

Enable arange test

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the d221ac28c4ed0d25616f5e6aeff50c12b9b9592b

Uplift third_party/tt-metal to d221ac28c4ed0d25616f5e6aeff50c12b9b9592b 2025-02-12

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 7fe2764ae519084817342949a1307cf163d030f4

Uplift third_party/tt-metal to 7fe2764ae519084817342949a1307cf163d030f4 2025-02-13

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 941b34cff33ce2953cf984ec8898af25dbfbfbb3

Uplift third_party/tt-metal to 941b34cff33ce2953cf984ec8898af25dbfbfbb3 2025-02-14

---

tools/explorer/tt_adapter/src/tt_adapter/mlir.py

Added 'schedule' attribute for each op in explorer graph.
Closes #2043

Added schedule as an attribute #2043

---

docs/src/build.md

Document LLVM_BUILD_TYPE

---

include/ttmlir/Dialect/TTIR/IR/TTIROps.td
include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/Target/TTNN/program.fbs
lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecompositionPass.cpp
lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
lib/Dialect/TTIR/IR/TTIROps.cpp
lib/Target/TTNN/TTNNToFlatbuffer.cpp
runtime/include/tt/runtime/detail/ttnn.h
runtime/lib/ttnn/operations/CMakeLists.txt
runtime/lib/ttnn/operations/reduction/argmax.cpp
runtime/lib/ttnn/operations/reduction/argmax.h
runtime/lib/ttnn/program.cpp
test/ttmlir/Conversion/StableHLOToTTIR/reduction/argmax_op.mlir
test/ttmlir/Dialect/TTIR/reduction/negative_argmax_dims.mlir
test/ttmlir/Dialect/TTNN/reduction/simple_argmax.mlir
test/ttmlir/EmitC/TTNN/reduction/argmax.mlir
test/ttmlir/Silicon/TTNN/n150/perf/test_perf_argmax.mlir
test/ttmlir/Silicon/TTNN/n150/simple_argmax.mlir

Add e2e implementation of argmax reduction op

---

runtime/lib/ttnn/include/tt/runtime/ttnn/types.h
runtime/lib/ttnn/operations/creation/empty.cpp
runtime/lib/ttnn/operations/creation/full.cpp
runtime/lib/ttnn/runtime.cpp
runtime/lib/ttnn/types/types.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 3200cb91afaaa05b33d7f23db424912ac370cfbb
- Remove references to mesh_device->get_device_index() after metal Commit 911e5c8

Uplift third_party/tt-metal to 3200cb91afaaa05b33d7f23db424912ac370cfbb 2025-02-19

---

runtime/lib/common/system_desc.cpp
runtime/lib/ttmetal/runtime.cpp
runtime/lib/ttnn/runtime.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 99e8f45516093967fd56ff3de98efa47868a3a02
- Wrap MeshShape with SimpleMeshShape after metal change f4719c78f6

Uplift third_party/tt-metal to 99e8f45516093967fd56ff3de98efa47868a3a02 2025-02-21

---

.github/workflows/build-and-test.yml
python/CMakeLists.txt
test/ttmlir/Silicon/TTNN/n150/Transforms/DecomposeLayouts/decomposing_layouts_from_host.mlir
test/unittests/OpModel/TTNN/Conversion/CMakeLists.txt
test/unittests/OpModel/TTNN/Lib/CMakeLists.txt
test/unittests/OpModel/TTNN/Op/CMakeLists.txt

Add libraries for missing symbols to the python target.

Fix debug build

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the e0585b2cdb34e013544623d04beb2120209bda8e

Uplift third_party/tt-metal to e0585b2cdb34e013544623d04beb2120209bda8e 2025-02-26

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 45186bcf465d6bad3d5e8efaf3ef5afb9e2de2d9

Uplift third_party/tt-metal to 45186bcf465d6bad3d5e8efaf3ef5afb9e2de2d9 2025-02-27

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 9b3d8557734bba9b5c7e91e178b85e4e019022cf

Uplift third_party/tt-metal to 9b3d8557734bba9b5c7e91e178b85e4e019022cf 2025-02-28

---

CONTRIBUTING.md

/
I was adding a CONTRIBUTING.md to tt-xla so I've noticed that tt-mlir CONTRIBUTING.md has a few typos.
Fixed typos.

Fix few typos in CONTRIBUTING.md

---

.github/CODEOWNERS

Reorganized our code owners file to ensure all areas are covered and to redistribute reviewers.

Reorganize CODEOWNERS

---

lib/Dialect/TTIR/IR/TTIROps.cpp
test/ttmlir/Conversion/StableHLOToTTIR/device_parallel/device_parallel_gspmd.mlir
test/ttmlir/Dialect/TTNN/ccl/all_gather/all_gather_negative.mlir
test/ttmlir/Dialect/TTNN/ccl/all_reduce/all_reduce_negative.mlir
test/ttmlir/Dialect/TTNN/ccl/reduce_scatter/reduce_scatter_negative.mlir
test/ttmlir/Silicon/TTNN/llmbox/device_parallel/device_parallel_1x8.mlir
test/ttmlir/Silicon/TTNN/llmbox/device_parallel/device_parallel_2x4.mlir
test/ttmlir/Silicon/TTNN/n300/device_parallel/device_parallel_1x2.mlir
test/ttmlir/Silicon/TTNN/tg/ccl/ccl_8x4.mlir
test/ttmlir/Silicon/TTNN/tg/device_parallel/device_parallel_1x32.mlir
test/ttmlir/Silicon/TTNN/tg/device_parallel/device_parallel_8x4.mlir

[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/2022)
Increase coverage for data and tensor parallel tests for n300, t3000 and tg systems for all supported mesh types.

#2022: Added data parallel and tensor parallel tests for all multichip configurations

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the dff46752a7abdaccd6ce9ef4a9d8e7d078ceddce

Uplift third_party/tt-metal to dff46752a7abdaccd6ce9ef4a9d8e7d078ceddce 2025-03-06

---

runtime/lib/ttnn/operations/ccl/mesh_shard.cpp
runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/utils.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 830a442ade6fbe1691e2dfe69f4a3f327327eaec
- Address namespace rename comment from previous metal uplift 9b42005

Uplift third_party/tt-metal to 830a442ade6fbe1691e2dfe69f4a3f327327eaec 2025-03-07

---

lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
test/ttmlir/Dialect/TTNN/conv_transpose2d/conv_transpose2d_conversion_tests_negative.mlir
test/ttmlir/Dialect/TTNN/conv_transpose2d/conv_transpose2d_tests_positive.mlir

https://github.com/tenstorrent/tt-mlir/issues/2389
Explained in the linked issue.
Explained in the linked issue.

ConvTranspose2d verification fix

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 6044ef45b7adfe4999e31fb6c4dcdc55bc1c3377

Uplift third_party/tt-metal to 6044ef45b7adfe4999e31fb6c4dcdc55bc1c3377 2025-03-11

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the cd5cf40ccce9dd9e13fa00bc412df22566816edb

Uplift third_party/tt-metal to cd5cf40ccce9dd9e13fa00bc412df22566816edb 2025-03-12

---

include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h
lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
test/ttmlir/EmitC/TTNN/pooling/upsample.mlir
test/unittests/TTNNToEmitC/TestEmitCConversion.cpp
tools/ttnn-standalone/ttnn-precompiled.hpp

https://github.com/tenstorrent/tt-mlir/issues/2312
- Added UpsampleOp to EmitC path

[TTNN->EmitC] UpsampleOp

---

include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h

https://github.com/tenstorrent/tt-mlir/issues/2455
Order of SourceTy and TargetTy is flipped at the moment, so explicit instantiation with just TargetTy is impossible (which goes against original intention).
Flipped the order of `SourceTy` and `TargetTy` in `emit` member function. Added a `TTNNTarget` template struct that maps type to the only TTNN C++ type that would make sense, so we can still instantiate a lot of cases implicitly.

EmitCTTNNEmitter refactor

---

.gitignore
docs/src/tt-explorer-usage-api.md

Closes https://github.com/tenstorrent/tt-mlir/issues/2391
Add documentation for `tt-explorer` overrides.
Explained all the possible fields accepted by overrides on `tt-explorer`, providing examples and the inferfaces they are based on.

Docs: add docs about overrides in `tt-explorer`

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 1d2d6be673f8694bfa95a8afb727b3ae006b3767

Uplift third_party/tt-metal to 1d2d6be673f8694bfa95a8afb727b3ae006b3767 2025-03-17

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 0a5d7803308965f78eada0a572082fdef73e5d01

Uplift third_party/tt-metal to 0a5d7803308965f78eada0a572082fdef73e5d01 2025-03-18

---

docs/src/adding-an-op.md
docs/src/ttrt.md

[#1730](https://github.com/tenstorrent/tt-mlir/issues/1730)
This PR includes documentation updates to address issues related to the TTRT toolchain, its build process, and common troubleshooting steps. 
- `docs/src/adding-an-op.md`: Updated sections related to adding operations to the toolchain.
- `docs/src/ttrt.md`: Added details for this specific problem in`ttrt` documentation, including troubleshooting and common issues with builds.
- No testing is required for documentation updates.

Update TTRT docs related to issue (#1730)

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 52d0d874360b7261a9ca65782c1e56e89ae781fb

Uplift third_party/tt-metal to 52d0d874360b7261a9ca65782c1e56e89ae781fb 2025-03-19

---

test/ttmlir/Dialect/TTIR/bufferization/prepare_tensors.mlir

Fix CI - debug build

---

python/test_infra/ttir_builder.py
test/python/golden/test_ttir_ops.py
ttrt.log

[Issue #2530](https://github.com/tenstorrent/tt-mlir/issues/2530)
ConvTranspose2dOp was not supported in TTIR builder
Added support in ttir_builder.py for ConvTranspose2dOp
Added test in test_ttir_ops.py.

Add ConvTranspose2dOp and Test

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 5ae0757cba914aef30af1a8629a4b1749cab914a

Uplift third_party/tt-metal to 5ae0757cba914aef30af1a8629a4b1749cab914a 2025-03-21

---

lib/Dialect/TTIR/Transforms/GeneralizeNamedOps.cpp

This follows up on #2492.
- rm leftover comments on an #include
- rename "result" -> "output"
- make anonymous ns tight
- fix misc typos not noticed earlier

addressing follow-up suggestions for #2492

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 501c655f49707b4039e8db6c4e9680de0a3db827

Uplift third_party/tt-metal to 501c655f49707b4039e8db6c4e9680de0a3db827 2025-03-26

---

python/test_infra/ttir_builder.py
test/python/golden/test_ttir_ops.py

[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/2646)
ArangeOp was not supported in TTIRBuilder
ArangeOp now has support and a test.

Added arange test and support

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 8245606cbc6a6fba60a1f43f02a34212ba2454e8

Uplift third_party/tt-metal to 8245606cbc6a6fba60a1f43f02a34212ba2454e8 2025-03-27

---

python/test_infra/ttir_builder.py
test/python/golden/test_ttir_ops.py

[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/2656)
WhereOp was non-functional
Corrected the golden argument handling
WhereOp is now supported

Corrected WhereOp

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the fc292ceb0c2325ca3f3653e9fa19e3587607cec6

Uplift third_party/tt-metal to fc292ceb0c2325ca3f3653e9fa19e3587607cec6 2025-03-28

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/OpModel/TTNN/TTNNOpModelLib.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

Closes #2583 
- Added constraint and runtime API for sqrt op.
- Created a template for element wise unary ops.

[OpModel] constraint and runtime API for sqrt

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 3407c8fd749afee4ec15c2d44dbb2bf3036ee278

Uplift third_party/tt-metal to 3407c8fd749afee4ec15c2d44dbb2bf3036ee278 2025-03-31

---

.github/CODEOWNERS

Added @rpavlovicTT and @arminaleTT to relevant sections.

Update optimizer codeowners

---

CODE_OF_CONDUCT.md

Tracker ticket - https://github.com/tenstorrent/tt-forge/issues/40?issue=tenstorrent%7Ctt-forge%7C69
Add community leader to code of conduct.
New contact info.

add community leader

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 636094054d73552b36166a596e4deb79c5756a2f

Uplift third_party/tt-metal to 636094054d73552b36166a596e4deb79c5756a2f 2025-04-03

---

include/ttmlir/Dialect/TTNN/IR/TTNNOpsAttrs.td
include/ttmlir/Target/TTNN/types.fbs
include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
lib/OpModel/TTNN/Conversion.cpp
lib/Target/TTNN/TTNNToFlatbuffer.cpp
python/TTNNModule.cpp
runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/utils.cpp
test/ttmlir/Silicon/TTNN/n150/perf/test_perf_conv2d_config.mlir

https://github.com/tenstorrent/tt-mlir/issues/2130
- Added the core grid parameter to Conv2DConfigAttr
- Changed the types of other parameters to align with other attributes

[TTNN] Add the core grid parameter to the Conv2DConfigAttr

---

python/test_infra/test_utils.py
python/test_infra/ttir_builder.py
runtime/tools/python/ttrt/common/callback.py
test/python/golden/test_ttir_ops.py

https://github.com/tenstorrent/tt-mlir/issues/2448
Explained in title.
Quantize ops support + convert to float for comparisons with golden tensor.

Adding quantize/dequantize/requantize to IR builder

---

include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
lib/Target/TTNN/TTNNToFlatbuffer.cpp

https://github.com/tenstorrent/tt-mlir/issues/2840
`std::optional<T>` is handled ad-hoc in TTNNToFlatubuffer. There is an existing infra that lets us hook into existing serializations, so that we could handle `std::optional<T>` generically.
Added a generic `toFlatbuffer(std::optional<T>)` serialization that utilizes the serialization for the `T` itself.

toFlatbuffer for std::optional<T>

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the e2365cefc8aa1a73d58bc3b20a099e76cd8e75e1

Uplift third_party/tt-metal to e2365cefc8aa1a73d58bc3b20a099e76cd8e75e1 2025-04-08

---

runtime/lib/ttnn/operations/data_movement/pad.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 678a464f7f15d3581fae286df0017100882e7975
- Update pad op after metal commit 8d50fef

Uplift third_party/tt-metal to 678a464f7f15d3581fae286df0017100882e7975 2025-04-09

---

docs/src/adding-an-op.md
include/ttmlir/Target/TTNN/CMakeLists.txt
include/ttmlir/Target/TTNN/program.fbs

Documentation inconsistent after #2860 
Updated documentation for flatbuffer schema step in `adding-an-op.md`

Doc update for adding a flatbuffer schema

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the ddba2f06d0a120ce4d65ecfad15befd65400e9c7

Uplift third_party/tt-metal to ddba2f06d0a120ce4d65ecfad15befd65400e9c7 2025-04-11

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the ea25506219c719e491c8deb100c504a60bd0e392

Uplift third_party/tt-metal to ea25506219c719e491c8deb100c504a60bd0e392 2025-04-15

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the e75564a41b6f7d4e51229dd2f2953e35c1a636bc

Uplift third_party/tt-metal to e75564a41b6f7d4e51229dd2f2953e35c1a636bc 2025-04-23

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 0d26beb2720e95946d48a6bb9e096e0052f647af

Uplift third_party/tt-metal to 0d26beb2720e95946d48a6bb9e096e0052f647af 2025-04-24

---

python/test_infra/ttir_builder.py
test/python/golden/test_ttir_ops.py

[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/3063)
SoftmaxOp had no test in `test_ttir_ops.py`.
Added test for SoftmaxOp in `test_ttir_ops.py`.
Changed torch.softmax to torch.nn.functional.softmax

Added softmax test

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/OpModel/TTNN/MetalHeaders.h
lib/OpModel/TTNN/TTNNOpModelLib.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

Closes #2930 
Add constraint API for SigmoidOp

[OpModel] Constraint API for Sigmoid Op

---

.github/workflows/build-and-test.yml

Provide context for the problem.

Change back to tt-forge builder

---

.github/workflows/wheel-build.yml

Provide context for the problem.

Switch mlir-wheel-builder to old builder

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/OpModel/TTNN/MetalHeaders.h
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

#2931 
Add OpConstraint and OpRuntime API for ClampScalar

[OpModel] support clamp scalar op

---

.github/workflows/on-pr.yml
.github/workflows/pages.yml

Switch to ubuntu-latest to save on cost

switch pages to ubuntu latest

---

tools/explorer/tt_adapter/src/tt_adapter/mlir.py

Temp fix perf tests

---

include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h
lib/OpModel/TTNN/Conversion.cpp
runtime/lib/ttnn/utils/utils.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the c43020c7219c1ab2037c6b84a6e9923ca892e544
- Update memory config construction and accessor usage after metal change 5440d62a14

Uplift third_party/tt-metal to c43020c7219c1ab2037c6b84a6e9923ca892e544 2025-05-09

---

runtime/tools/ttrt/ttrt/common/run.py

This allows having both randomness and precision with TF32 math by keeping results in TF32's mantissa range.

Support ones randomly mixed with zeroes with specified density

---

include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
lib/Dialect/TT/IR/TTOpsTypes.cpp
lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp
python/TTModule.cpp
python/test_infra/test_utils.py
python/test_infra/ttir_builder.py
test/python/golden/test_metal_layout.py
test/python/golden/test_ttir_ops.py

Add support for supplying your own set of pipeline passes from pytest.

pytest custom pipeline refactor

---

third_party/CMakeLists.txt
tools/ttnn-standalone/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 3d4cffba4c2cfd72d8dda8f20e37dd5f00aca0e0
- Fix xtensor include paths to use patched cache keys after metal change 6863b57

Uplift third_party/tt-metal to 3d4cffba4c2cfd72d8dda8f20e37dd5f00aca0e0 2025-05-13

---

tools/ttnn-standalone/ci_compile_dylib.py

Compile `.cpp` file into a dylib iff it's newer than existing corresponding `.so` file.

`ci_compile_dylib.py` incremental build

---

.github/workflows/build-and-test.yml

Move one of the llmbox runners to the shared pool

Move single llmbox to shared infra

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 6f8b06c566a627fa06117852643175e1f9298c0a

Uplift third_party/tt-metal to 6f8b06c566a627fa06117852643175e1f9298c0a 2025-05-14

---

lib/Conversion/StableHLOToTTIR/ShardingUtils.cpp
test/ttmlir/Conversion/StableHLOToTTIR/ccl/ccl_ops_gspmd.mlir

https://github.com/tenstorrent/tt-mlir/issues/3371
https://github.com/tenstorrent/tt-mlir/issues/3376
The devices string from torchXLA has unexpected transposed mesh shape as follows.
devices=[4,2]0,4,1,5,2,6,3,7}
while we currently expect the following.
devices=[2,4]0,1,2,3,4,5,6,7}
New detection mechanism should check the order of device IDs to confirm if they are correct order or transposed.

Fix GSPMD devices string parsing bug with torchXLA frontend

---

include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
include/ttmlir/Dialect/TT/Transforms/Passes.td
include/ttmlir/Dialect/TT/Transforms/Transforms.h
lib/Dialect/TT/IR/TTOpsTypes.cpp
lib/Dialect/TT/Transforms/TTRegisterDevice.cpp

getDefault will create a WH system desc unless a different arch is specified.

Add Blackhole system desc

---

.github/workflows/build-and-test.yml

Provide context for the problem.

move ttnn_runtime card runners to shared pool

---

include/ttmlir/Target/TTMetal/command.fbs
lib/Target/TTMetal/TTMetalToFlatbuffer.cpp
runtime/include/tt/runtime/detail/debug.h
runtime/include/tt/runtime/detail/logger.h
runtime/include/tt/runtime/detail/ttmetal/profiler.h
runtime/lib/common/debug.cpp
runtime/lib/ttmetal/executor.cpp
runtime/lib/ttmetal/runtime.cpp
runtime/lib/ttnn/program_executor.cpp
runtime/lib/ttnn/runtime.cpp
runtime/tools/ttrt/setup.py
runtime/tools/ttrt/ttrt/common/perf.py
runtime/tools/ttrt/ttrt/common/run.py

Device profile support for metal runtime

---

test/ttmlir/Dialect/TTNN/data_movement/to_memory_config/to_memory_config_tests_negative.mlir

N/A
We missed adding code coverage for the tensor memory layout.
We added a test case for the memory config tensor memory layout verifier.

Adding missing test for tensor memory layout verifier

---

test/ttmlir/Silicon/TTNN/n150/optimizer/resnet50_layer1_module2.mlir

#3264 
Adding a test for module2 of layer1 in resnet50 with applied overrides for convolutions.

Add resnet single module test

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 7ff86ba507e61e5b6cb9fd267030c4514a5223d1

Uplift third_party/tt-metal to 7ff86ba507e61e5b6cb9fd267030c4514a5223d1 2025-05-20

---

include/ttmlir/Dialect/TTIR/IR/TTIROpsEnums.td
lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
test/ttmlir/Conversion/StableHLOToTTIR/sumpool2d_op.mlir
test/ttmlir/Dialect/TTIR/Decomposition/sum_pool2d.mlir

closes https://github.com/tenstorrent/tt-mlir/issues/3418
Missing support for sum pooling
* Add sum pooling type
* Add stablehlo->ttir conversion for sum pooling
* Add TTIR decomposition for sum pooling to average pooling multiplied by kernel size

Sum pooling 2d

---

lib/Dialect/StableHLO/Transforms/ShardyAutomaticParallelization.cpp
test/ttmlir/Dialect/StableHLO/shardy_automatic_parallelization/slice.mlir

This PR adds support for multiple sharding along any tensor dimension for slice op in shardy automatic parallelization pass. This was seen in falcon data parallel and mistral tensor parallel models.
eg, we can now annotate any axis dimension
```
(%arg0: tensor<4x40x256xf32> {sdy.sharding = #sdy.sharding<@mesh, [{}, {"batch"}, {}]>}
```

Added multiple tensor sharding support for slice op in automatic shardy pass.

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/OpModel/TTNN/MetalHeaders.h
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

[OpModel] add constraint api for permute op

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/OpModel/TTNN/MetalHeaders.h
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

Closed #3441 
Add constraint and runtime API for UpsampleOp

[OpModel] support upsample op

---

.github/workflows/wheel-build.yml

Fixes issues from migration to new releaser.
https://github.com/tenstorrent/tt-forge/pull/134#issuecomment-2923527034

Fix tt-mlir nightly wheel pull

---

include/ttmlir/Dialect/TTIR/IR/TTIROps.td

Part of https://github.com/tenstorrent/tt-mlir/issues/401
We have a bunch of rudimentary descriptions of our ops in the TTIR dialect.
Generated descriptions for TTIR ops in a unified way. Most of the diff is generated using Cluade, and I double checked a lot of ops, but errors are possible.

Improving TTIR dialect operation descriptions

---

.github/CODEOWNERS

update CODEOWNERS (/test/unittests/Allocation -> d2m)

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 41ce500767a364f66034f6924837dabc133e8d4d

Uplift third_party/tt-metal to 41ce500767a364f66034f6924837dabc133e8d4d 2025-06-04

---

.github/workflows/issue-last-updated.yml

Add permissions for repository-projects, issues, and contents. Use default github token.

Use default github token

---

include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
lib/Conversion/TTIRToTTKernel/TTIRToTTKernel.cpp
lib/Dialect/TT/IR/TTOpsTypes.cpp

- Add convenience getChipDesc method for accessing the i-th chip id.
- Add convenience method on ViewLayoutAttr for composing multiple views together.

Add convenience getChipDesc method for accessing a specific chip id

---

runtime/include/tt/runtime/tensor_cache.h

Tensor cache is currently not thread safe, which could cause issues when running the same binary on multiple threads (e.g. runtime data parallel workflows). Invalid assert within tensor cache remove API.
Made tensor cache APIs thread safe, updated invalid assert.

Make tensor_cache thread safe, update invalid assert

---

tools/explorer/CMakeLists.txt

This PR uplifts the model-explorer version in tools/explorer to the latest commit f7550b500b64e0a44f91efda33a52939ec58da3e from previous version 80559f3db501c0a6384502ca1a789cbe86455a8d

Uplift model-explorer to f7550b500b64e0a44f91efda33a52939ec58da3e 2025-06-12

---

runtime/tools/ttrt/ttrt/common/util.py

Add missing schema version check for system desc

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/OpModel/TTNN/MetalHeaders.h
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

Closed #3555 
Add constraint API for slice op

[OpModel] support slice op

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/OpModel/TTNN/MetalHeaders.h
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

Closes #3554 
Add constraint API for Concat Op

[OpModel] support concat op

---

.github/workflows/wheel-build.yml
python/setup.py

- Main is once again broken :sob:
- Attempt to fix issue, I think `lld` version changed? Let's just revert to `ld`.

Wheel build hotfix, lld not working

---

include/ttmlir/Dialect/TTIR/IR/TTIROps.td
lib/Dialect/TTIR/IR/TTIROps.cpp
test/ttmlir/Dialect/TTIR/bufferization/bufferization.mlir
test/ttmlir/Dialect/TTIR/canonicalize/view_fold_tests.mlir
test/ttmlir/Dialect/TTIR/lower_to_layout.mlir

This commit adds a view layout folder that aggressively folds adjacent views into a single view.  Also updates the assembly syntax to be _slightly_ less verbose.

Add view layout folder

---

runtime/include/tt/runtime/detail/ttnn/program_executor.h
runtime/lib/ttmetal/runtime.cpp
runtime/lib/ttnn/program_executor.cpp
runtime/lib/ttnn/runtime.cpp

After uplift, metal added a new mesh device profile API
Ported to the mesh device profile API from single-device. Thanks @brataTT for finding this!

Update mesh device profile API

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/Target/TTNN/operations/conv.fbs
lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
lib/Target/TTNN/TTNNToFlatbuffer.cpp
runtime/lib/ttnn/operations/conv/conv_transpose2d.cpp
test/ttmlir/Silicon/TTNN/n150/perf/test_perf_conv_transpose2d.mlir
test/ttmlir/Silicon/TTNN/n150/perf/test_perf_conv_transpose2d_with_conv2d_config.mlir

It should be an optional parameter.
Closed #3819

add conv2dconfig to convtranspose2d

---

.github/workflows/issue-last-updated.yml

Removed cursor-based pagination from the GraphQL query to simplify the request

fix: Remove cursor-based pagination to resolve GraphQL API errors

---

tools/explorer/CMakeLists.txt

This PR uplifts the model-explorer version in tools/explorer to the latest commit d76cb38f80de7cda5f5006bedbf5bc3688726f35 from previous version 003bc3d4418da4fd4b459d154dd6148e74750547

Uplift model-explorer to d76cb38f80de7cda5f5006bedbf5bc3688726f35 2025-06-25

---

.github/workflows/issue-last-updated.yml

For initial testing limiting the workflow for first 100 project items. Removed pagination logic for time being to make sure if that is the root cause.

fix: limit project items query to first 100 issues

---

third_party/CMakeLists.txt

- This PR uplifts tt-metal to June 30th commit 7a44fb2489 introducing 76 commits

This PR uplifts the third_party/tt-metal to the 7a44fb2489

---

lib/Target/TTNN/TTNNToFlatbuffer.cpp

Fixes #3505 
The scale and zero point for quantization are inside constants and should be extracted as scalars in the per-tensor case. As such we need to enter into the const-eval function and go through the const-eval chain (walk through typecast (optional) -> to_device -> to_layout -> from_device) to reach the scalar value. This PR adds the logic for entering the const-eval function and continuing with the search.

fixing const-eval with quantize (quantize ttnn -> flatbuffer)

---

include/ttmlir/Dialect/TTIR/IR/TTIROps.td
include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/Target/TTNN/operations/reduction.fbs
include/ttmlir/Target/TTNN/program.fbs
lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
lib/Dialect/TTIR/IR/TTIROps.cpp
lib/Dialect/TTNN/IR/TTNNOps.cpp
lib/Target/TTNN/TTNNToFlatbuffer.cpp
runtime/include/tt/runtime/detail/ttnn/ttnn.h
runtime/lib/ttnn/operations/CMakeLists.txt
runtime/lib/ttnn/operations/reduction/sort.cpp
runtime/lib/ttnn/operations/reduction/sort.h
runtime/lib/ttnn/program_executor.cpp
test/ttmlir/Dialect/TTIR/sort/sort_tests_negative.mlir
test/ttmlir/Dialect/TTNN/sort/simple_sort.mlir
test/ttmlir/Dialect/TTNN/sort/sort_tests_negative.mlir
test/ttmlir/EmitC/TTNN/sort/sort.mlir
test/ttmlir/Silicon/TTNN/n150/sort/simple_sort.mlir

closes https://github.com/tenstorrent/tt-mlir/issues/3992
Missing support for sort op
End to End implementation of sort op

End to End implementation of sort op

---

third_party/CMakeLists.txt
tools/ttnn-standalone/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 5119c0b25a2d09a3116fb0427a39e4146d8990d6
- Update tt-logger after metal commit a2fc551a05

Uplift third_party/tt-metal to 5119c0b25a2d09a3116fb0427a39e4146d8990d6 2025-07-15

---

tools/explorer/README.md

N/A
The docs link on tt-explorer's readme file was wrong.
Updated the link.

[explorer] fix: update the URL for tt-explorer

---

include/ttmlir/Dialect/TTIR/Transforms/Passes.td
include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
lib/Dialect/TTIR/Transforms/TTIRFusing.cpp
lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
test/ttmlir/Dialect/TTIR/fusing/conv2d_multiply_commute.mlir
test/ttmlir/Dialect/TTIR/fusing/conv2d_multiply_pattern_disabled.mlir
test/ttmlir/Dialect/TTNN/fusing/resnet_pattern_fusing.mlir
test/ttmlir/Silicon/TTNN/n150/fusing/resnet_pattern_fusing.mlir

Add flag to enable Conv2dWithMultiply pattern in fusing pass

[TTIR] Add flag to enable Conv2dWithMultiply pattern in fusing pass

---

tools/explorer/CMakeLists.txt

This PR uplifts the model-explorer version in tools/explorer to the latest commit 99da5ea9334119ad6bcaaf181b5c64c9504ccf82 from previous version 4123573675a067dbc3305326a33edf46683ea14f

Uplift model-explorer to 99da5ea9334119ad6bcaaf181b5c64c9504ccf82 2025-07-18

---

docs/src/pykernel.md

- PyKernel docs were outdated.
-Added more relevant Multicore information and developer information.

Updated PyKernel Docs w/ Multicore References

---

runtime/tools/chisel/chisel/core/golden_executor.py
runtime/tools/chisel/chisel/core/tensors.py
runtime/tools/chisel/chisel/utils/mapping.py
runtime/tools/chisel/chisel/utils/runtime_utils.py
runtime/tools/chisel/test/test_golden_execution.py

1. #3356
2. #4010
3.  #4041
4. #3666
This PR introduces the Golden Executor component for the Chisel tool, which provides reference execution of MLIR operations using PyTorch. The implementation includes tensor management and supporting utilities for the execution pipeline.
- Implements reference execution of MLIR operations using PyTorch
- Tracks operation execution state and manages tensor values
- Provides hooks for operation execution and result comparison
- Introduces [TensorValue](cci:2://file:///localdev/ndrakulic/tt-mlir/runtime/tools/chisel/chisel/core/tensors.py:9:0-57:29) class for unified tensor handling
- Manages tensor references and data across execution contexts
- Supports both device and golden execution paths
- `mapping.py`: Provides TTIR to PyTorch operation mapping
- …

Golden Op executor for TTIR

---

runtime/lib/binary.cpp

Initial ordering was incorrect.

Swap the order of parsing the mesh shape

---

docs/src/emitc-testing.md
docs/src/ttrt.md

#4098 
Docs cover how to run all EmitC tests, but not a single test.
Docs update to additionally reflect how to run a single test.

Update EmitC test docs: single test

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

Add constraint API for WhereOp

---

include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h

[TTNN] Enable fusing pass by default

---

runtime/tools/ttrt/ttrt/common/run.py

closes https://github.com/tenstorrent/tt-mlir/issues/4243
TTRT uses `borrowed tensor` for inputs/outputs which cannot be
used for empty tensors.
- Use `owned tensors` in case of empty input/output tensors.
- Fix creation of torch output tensor in case of empty tensor.

[TTRT] Add support for empty tensors

---

include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td

Forgot to add in the initial PR
Add summary and descriptions

Add summary and description for TensorAccessor

---

tools/explorer/CMakeLists.txt

This PR uplifts the model-explorer version in tools/explorer to the latest commit 7dbec56d8fdeaa62c9761db7a25527d35fa8208b from previous version a333e83c65fe8dc86f340c606c49ee262420b4ec

Uplift model-explorer to 7dbec56d8fdeaa62c9761db7a25527d35fa8208b 2025-07-31

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/OpModel/TTNN/MetalHeaders.h
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

Add constraint API for embedding_bw op

---

.github/workflows/perf-benchmark.yml
.github/workflows/wheel-build.yml

closes https://github.com/tenstorrent/tt-mlir/issues/4103
Launch Performance benchmarks from tt-mlir
tt-mlir perfomance benchmark run will trigger tt-forge-fe, tt-xla, and tt-torch perfomance run in order to build their wheels with specific mlir version.

[CI] Add perfomance benchmark run

---

runtime/tools/ttrt/ttrt/binary/__init__.py

ttrt read quick fix

---

docs/src/coding-guidelines.md

We are enforcing this guideline informally in PR reviews. 
Added requirement to coding guidelines.

adding TODO enforce to coding guideline

---

test/python/golden/test_ttir_ops.py
tools/builder/base/builder.py
tools/builder/stablehlo/stablehlo_builder.py
tools/builder/ttir/ttir_builder.py

Part of #4360 
Proposed some function comments. Let's align on whether private functions in tools/builder files should include descriptions.

suggested doc improvement

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 3250801aecf626ebd03f8a3d0be94a97b121adaf

Uplift third_party/tt-metal to 3250801aecf626ebd03f8a3d0be94a97b121adaf 2025-08-14

---

include/ttmlir/Dialect/TTIR/IR/TTIRGenericRegionOps.td
test/ttmlir/Conversion/TTIRToTTKernel/semaphores.mlir

#3041 
Add lit testing for ttir -> ttkernel semaphore lowering.

D2M: Add ttir->ttkernel semaphore lit testing

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 98c764028d2001d60f66eabcb0311c248bc7006b

Uplift third_party/tt-metal to 98c764028d2001d60f66eabcb0311c248bc7006b 2025-08-15

---

.github/workflows/issue-work-started.yml

[Link to Github Issue](https://github.com/tenstorrent/tt-forge-internal/issues/10)

Set the work started field when status was last updated instead of current

---

.github/workflows/issue-work-started.yml

[Link to Github Issue](https://github.com/tenstorrent/tt-forge-internal/issues/10)

Test cron schedule: change to 30-minute intervals

---

.github/workflows/issue-work-started.yml

[Link to Github Issue](https://github.com/tenstorrent/tt-forge-internal/issues/10)

[skip ci] Update cron schedule to 11 PM Central Time 

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/OpModel/TTNN/SingletonDeviceContext.h
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

#4196
Added constraints for `Atan2Op`, `RemainderOp`.

Add constraints API for Atan2 and Remainder

---

.github/scripts/python/bulk_update_issues/bulk_update_issues.py
.github/scripts/python/bulk_update_issues/bulk_update_usage.md
.github/scripts/python/bulk_update_issues/requirements-bulk-update.txt
.github/workflows/issue-work-started.yml

Refactored the bulk work issues script to improve runtime and enable execution across all repositories. Long term, once this automation has been proven to work, it will be uplifted to tt-forge.
**Testing:**
https://github.com/tenstorrent/tt-mlir/actions/runs/17448099342/job/49547208087
Example of Updates
When no timestamp is found.
https://github.com/tenstorrent/tt-mlir/actions/runs/17448099342/job/49547208087#step:5:7348
With timestamp found
https://github.com/tenstorrent/tt-mlir/actions/runs/17448099342/job/49547208087#step:5:6779
Also added a error collector to print all the errors we find towards the end 
https://github.com/tenstorrent/tt-mlir/actions/runs/17448099342/job/49547208087#step:5:7376

refactor of bulk update for work started issues

---

lib/Dialect/StableHLO/Transforms/AnalyzeMesh.cpp

Issue: https://github.com/tenstorrent/tt-mlir/issues/4821

#4821: Fixed asan error related to copied but dangling meshOp memory.

---

tools/explorer/CMakeLists.txt

This PR uplifts the model-explorer version in tools/explorer to the latest commit 1df78077c6fec4d41b32ac2622345f0d2378e3e4 from previous version eecbe837b060ae2208cff00392aad4222936d7a7

Uplift model-explorer to 1df78077c6fec4d41b32ac2622345f0d2378e3e4 2025-09-15

---

docs/src/pykernel.md

minor doc changes on pykernel guide

---

tools/explorer/CMakeLists.txt

This PR uplifts the model-explorer version in tools/explorer to the latest commit a8c2343ea437b045c7a4a59cd8c43d94940e484c from previous version 1df78077c6fec4d41b32ac2622345f0d2378e3e4

Uplift model-explorer to a8c2343ea437b045c7a4a59cd8c43d94940e484c 2025-09-17

---

include/ttmlir/OpModel/TTNN/MetalHeaders.h
lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

Fix ConstantOp OpModel to include BF16 and float

---

lib/Dialect/TTIR/Transforms/TTIRFusing.cpp

Some conv weight get too big for dram when tilized (e.g. (2048, 2048, 1, 1) -> (2048, 2048, 32, 32). The current solution for this is to tag these weight and keep them on host memory. This is done for conv2d only, support for convolution is missing.
Tag ConvolutionOp weight for system memory as well.

Put ConvolutionOp weights in system memory

---

lib/Dialect/D2M/Transforms/GenericHWThreadSelection.cpp
test/ttmlir/Dialect/D2M/generic/generic_hw_thread_selection.mlir

Previously we were making the assumption that there will always be a 1-1 relationship between the number of operands and the number of datamovement regions.  In the context of manually written generic ops, this is not necessarily true, and the datamovement regions are already manually fused.
Instead we should count the number of datamovement threads which is more accurate.

Ops with # threads <= # DMA HW Threads don't need to be merged

---

test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
third_party/CMakeLists.txt
tools/tt-alchemist/templates/cpp/local/CMakeLists.txt
tools/ttnn-standalone/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the ce7d0b2bca023c54ba1f501c63148c5b594bad20

Uplift third_party/tt-metal to ce7d0b2bca023c54ba1f501c63148c5b594bad20 2025-10-01

---

.github/workflows/on-pr.yml

/
Tt-xla manual test dispatch refactor has functionality changes which have to be reflected in tt-mlir when triggering downstream tests on uplift PRs.
Tests triggered by uplift PRs will trigger 2 `manual-test.yml` test workflows in tt-xla in order to simulate tt-xla'x `On PR` workflow's testing.

Change tests triggered downstream in tt-xla

---

.github/test_matrix/pr-push-matrix.json

None
There were a couple ttrt typos
Corrected typos

CI Refurbishment Bug fixes

---

.github/workflows/build-and-test.yml

Follow up change for https://github.com/tenstorrent/tt-mlir/pull/5114#discussion_r2405470436

Switch build mlir to Civ2 CPU runner

---

.github/workflows/nightly-uplift.yml
.github/workflows/on-pr.yml

None
Since metal uplift now has rotating schedules, adding PR checklist.
This info is currently hidden away in a shared doc.
Added the following checklist to uplift PRs, and use single tt-xla CI preset added in https://github.com/tenstorrent/tt-xla/commit/7732e284daf2eee48cdd48c481821c8cff35ba1e
- **Frontend CI passing Links**
- **Follow-up Actions**

Add checklist to uplift PRs
