tenstorrent/tt-mlir

include/Constants.h
include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/Dialect/TTNN/Utils/Constants.h
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/Dialect/TTNN/Analysis/ShardSolver.cpp
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/OpModel/TTNN/Conversion.cpp
lib/OpModel/TTNN/Conversion.hpp
lib/OpModel/TTNN/MetalHeaders.h
lib/OpModel/TTNN/SingletonDeviceContext.cpp
lib/OpModel/TTNN/SingletonDeviceContext.h
lib/OpModel/TTNN/TTNNOpModelLib.cpp
runtime/include/tt/runtime/detail/ttnn.h
runtime/lib/ttnn/runtime.cpp
test/unittests/OpModel/TTNN/Conversion/TestConversion.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
test/unittests/OpModel/TTNN/OpModelFixture.h

Optimizer needs more ops with constraints and runtime support to be able to ingest real models. Conv is used in resnet :) (https://github.com/tenstorrent/tt-mlir/issues/2277)
* Added constraints and runtime API support for Conv2d. Added unit tests for the new APIs.
* Set L1_SMALL_SIZE for opmodellib device
* There is a bug with Conv2D and graph capture in NO_DISPATCH mode so we always get that the op failed until this is solved: https://github.com/tenstorrent/tt-metal/issues/18886
* For some reason device needs to be reopened before executing conv multiple times. This will be solved with: https://github.com/tenstorrent/tt-metal/issues/14000 but is not planned in the near future.

Add constraints and runtime API for Conv2d

---

lib/OpModel/TTNN/TTNNOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

This is a fix for a build break that happened because of a bad merge of [#2423](https://github.com/tenstorrent/tt-mlir/pull/2423)

Fix build break for conv2d constraints

---

cmake/modules/BuildFlatbuffers.cmake
include/ttmlir/Target/TTMetal/CMakeLists.txt
include/ttmlir/Target/TTNN/CMakeLists.txt

When trying to do incremental builds, there was a bug where flatc compiler did not regenerate the correct dependencies for a root flatbuffer schema if any of the dependencies were changed. This lead to seg faults when trying to read the flatbuffer in ttrt (since the runtime was using the serialized schema bytes from an old build and not the latest).

#2506: Fixed bug where flatbuffer dependencies were not getting regenerated in incremental build

---

include/ttmlir/Dialect/TTIR/IR/TTIROps.td
include/ttmlir/Dialect/TTIR/Transforms/Passes.td
lib/Dialect/TTIR/IR/TTIROps.cpp
lib/Dialect/TTIR/Transforms/Allocate.cpp
lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp
test/ttmlir/Dialect/TTIR/allocate/generic_form_streams.mlir

Currently this pass only does some simple heuristics for forming stream_layout ops for the situations that require it for correctness.  In the future, this pass will be replaced with a full allocate pass that has to do more sophisticated analysis for inserting streams on top of actually allocating.
Converts generic arguments that require a stream (i.e. local storage buffer for circular buffer):
```mlir
%alloc = memref.alloc() {alignment = 64 : i64} : memref<2x4x4x8x!tt.tile<32x32, f32>, #l1_>
%0 = "ttir.view_layout"(%arg0) : (memref<2x4x4x6x!tt.tile<32x32, f32>, #l1_>) -> memref<2x4x4x6x!tt.tile<32x32, f32>, #l1_>
%1 = "ttir.view_layout"(%arg1) : (memref<4x4x6x8x!tt.tile<32x32, f32>, #l1_>) -> memref<4x4x6x8x!tt.tile<32x32, f32>, #l1_>
ttir.generic (%0, %1, %alloc)
```
Into:
```mlir …
```

Placeholder allocate pass

---

include/ttmlir/Dialect/TTIR/IR/TTIROps.td
python/test_infra/ttir_builder.py
test/python/golden/test_ttir_ops.py

[Issue #2529 ](https://github.com/tenstorrent/tt-mlir/issues/2529)
Conv2dOp was not supported in TTIR builder
Added support in ttir_builder.py for Conv2dOp
Added test in test_ttir_ops.py.

Add Conv2dOp and Test

---

python/test_infra/ttir_builder.py
test/python/golden/test_ttir_ops.py

[Issue 2535](https://github.com/tenstorrent/tt-mlir/issues/2535)
EmbeddingOp was not supported in TTIR builder
Added support in ttir_builder.py for EmbeddingOp
Added test in test_ttir_ops.py.

Adding EmbeddingOp Support and Test

---

include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp

https://github.com/tenstorrent/tt-mlir/issues/2512
This pass has very high memory consumption, with a very little (if any) benefit.
Added an option to enable it if we find some use-case for it, but it's disabled by default.
- CI runs:
- [forge-fe](https://github.com/tenstorrent/tt-forge-fe/actions/runs/13948345509)
- [tt-torch](https://github.com/tenstorrent/tt-torch/actions/runs/13948354212)
- [tt-xla](https://github.com/tenstorrent/tt-xla/actions/runs/13948359539)

Disable RemoveDeadValues pass by default

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
include/ttmlir/Target/TTNN/program.fbs
lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/OpModel/TTNN/Conversion.cpp
lib/OpModel/TTNN/Conversion.hpp
lib/OpModel/TTNN/MetalHeaders.h
lib/OpModel/TTNN/TTNNOpModelLib.cpp
lib/Target/TTNN/TTNNToFlatbuffer.cpp
test/ttmlir/Dialect/TTNN/Transforms/Workarounds/max_pool2d_workaround.mlir
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
test/unittests/OpModel/TTNN/OpModelFixture.h

Related to https://github.com/tenstorrent/tt-mlir/issues/2277
Optimizer needs constraints and runtime model for every op in order to shard them properly. This commit adds support for MaxPool 2D op in that regard.
Implementation for GetOpConstraints & GetOpRuntime for MaxPool2D.
Unit tests for MaxPool2D API.

Implement op constraints & runtime API for MaxPool2D

---

lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
test/ttmlir/EmitC/TTNN/eltwise_ternary/where.mlir

Part of the following issues:
https://github.com/tenstorrent/tt-mlir/issues/1877
Currently we lack an emitC conversion for all where op.
This PR adds a missing emitC conversion for where op.

Adding emitC conversion for Where op

---

python/test_infra/test_utils.py
python/test_infra/ttir_builder.py

https://github.com/tenstorrent/tt-mlir/issues/2539
Closes #2539 
The mesh_shape information is required during MLIR module generation when using CCL (Collective Communication Library) ops such as all_gather, all_reduce, reduce_scatter, and mesh_shard.
Currently, this information is not passed into the compile_as_mlir_module flow, which prevents the backend pipeline from correctly configuring the module for these ops.
Added mesh_shape as an optional argument to compile_as_mlir_module.
mesh_shape is now passed through to the ttir_to_ttnn_backend_pipeline, enabling correct lowering and compilation for CCL ops.

Pass mesh_shape to backend pipeline to support CCL ops in TTIRBuilder

---

python/CMakeLists.txt
python/pykernel/pykernel_ast.py
test/pykernel/eltwise_sfpu/reader_unary.py

- PR closes #2472 
- EmitC output from PyKernel often looks like it came from Pre-Transformer LMs. The goal is to add some verbosity to these outputs so that we can understand what came from where in the original python source.
- Added `verbose` parameter to `ttkernel_compile`
- Added `emitc` to ttmlir Python bindings.
- Added some utility functions to produce `emitc.verbatim` throughout PyKernel module

Add Verbosity to PyKernel outputs

---

include/ttmlir/Conversion/StableHLOToTTIR/ShardingUtils.h
include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
lib/Conversion/StableHLOToTTIR/ShardingUtils.cpp
lib/Conversion/StableHLOToTTIR/ShardyToTTIRPatterns.cpp
test/ttmlir/Conversion/StableHLOToTTIR/ccl/ccl_ops_shardy.mlir
test/ttmlir/Conversion/StableHLOToTTIR/ccl/e2e_tp_shardy.mlir

maintaining multi-device tensors with pre-sharded inputs.
https://github.com/tenstorrent/tt-mlir/issues/2429
1. Some multi-device tensors need extra information to understand the actual shape of tensors across devices.
2. Some ops with pre-sharded input tensors try to compute single-device tensor with multi-device tensor. 
1. Elaborate multi-device tensors with extra sharding info if tensor shape is full shape.
- Single device tensor has no TensorMeshShardingAttr.
tensor<784x16384xf32>
- Multi-device tensors have TensorMeshShardingAttr.
(i) multi-device tensor without tensor mesh shard axis indicates all devices in "mesh"
have tensors with the given shape. e.g., 784x16384 for
tensor<784x16384xf32, #tt.mesh_sharding<"mesh">>
(ii) multi-device tensor with tensor mesh shard axis indicate all …

Details TensorMeshShardingAttr with extra info and fix bug in

---

.github/workflows/build-and-test.yml
env/build-requirements.txt

Recently clang-tidy bumped to version 20 on pypi which broke CI.

Fix clang-tidy version to 19.1.0

---

runtime/test/ttnn/dylib.cpp

https://github.com/tenstorrent/tt-mlir/issues/2483
- Tensor data in runtime and EmitC path were compared byte by byte. In case of mismatch, the value of mismatched byte were reported, which wasn't very helpful.
- Values are now compared element by element (with an appropriate type), and in the case of mismatch, the typed value is reported. To handle special values like NaN, Inf etc. we still compare individual elements byte by byte.
- Some redundant checks were removed.

Runtime and EmitC tensor mismatch error reporting

---

include/ttmlir/Conversion/StableHLOToTTIR/ShardingUtils.h
lib/Conversion/StableHLOToTTIR/ShardingUtils.cpp

In `tt-xla`, we need a function that will translate an object `mlir::tt::sharding_utils::MeshSharding` into a std::map of strings needed to call `CreateTensor()` on a multichip Tensor. Currently, this functionality is in `tt-xla`, this moves it to `tt-mlir`.

Added a `fillStrategyMapFromSharding` function to the SharingUtils class

---

lib/Conversion/TTIRToLinalg/TTIRToLinalg.cpp
test/ttmlir/Conversion/TTIRToLinalg/softmax.mlir

Closes #2580 
Currently, the TTIR dialect doesn't support lowering the `softmax` operation to the Linalg dialect. Since Linalg provides `linalg.softmax` opeartion, it should be possible to implement this lowering.
Implemented a basic lowering of `softmax` operation to the Linalg dialect. While lowering we distinguish between two cases for dimension attribute:
1) Negative dimension: we treated it as an index from the end, so we subtract it from the tensor's shape size.
2) Positive dimension: we just passed it through
If dimension is bigger than shape size, then `ttmlir-opt` reports an error before conversion.

Lowering of softmax op from TTIR to the Linalg dialect

---

lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
test/ttmlir/EmitC/TTNN/tensor/slice.mlir
tools/ttnn-standalone/ttnn-precompiled.hpp

Part of the following issues:
https://github.com/tenstorrent/tt-mlir/issues/1877
Currently, we lack an emitC conversion for slice op.
This PR adds a missing emitC conversion for slice op.

Adding EmitC conversion for slice op

---

python/test_infra/ttir_builder.py
test/python/golden/test_ttir_ops.py

[Issue #2576](https://github.com/tenstorrent/tt-mlir/issues/2576)
TTIR builder didn't have support for Upsample2dOp
Added Upsample2dOp and test

Add Upsample2d and test

---

lib/Dialect/TTIR/IR/TTIROps.cpp
lib/Dialect/TTIR/Transforms/GenericGenerateDatamovement.cpp
test/ttmlir/Dialect/TTIR/generic/generic_negative.mlir

This commit actually fixes a couple of issues in the semaphore generation part of the datamovement generation pass.  These include:
- Pregenerating all of the region function signatures for the new generic op, up front.  This is the core bug, previously we were just creating new regions on the fly, but this meant that they would miss out on previous region's semaphore additions.
- Compute region should also inherit semaphores.
- Modify only the newly created regions instead of the old op in place.
- Additional generic op verification and testing to enforce that all regions have the same number of arguments and the same type for each respective argument.
Closes #2526

Bug fix, generate semaphores for all generic regions in lockstep

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
lib/Dialect/TTNN/IR/TTNNOps.cpp
test/ttmlir/Dialect/TTNN/ccl/collective_permute/collective_permute_positive.mlir

https://github.com/tenstorrent/tt-mlir/issues/2406
closes #2406 
CollectivePermute Op is semantically meaningless when there is no tensor data movement from any device.
source_target_pair attribute describes where Tensor data moving from and to. There will be no data movement If source and target are same. Also if we don't have any effective movement description, we don't need to execute this op.
- Remove entries in the permute attribute where 'src' and 'target' are identical.
- Exclude the CollectivePermuteOp if the source_target_pair array becomes empty after cleanup.
- Added unit tests to verify folding

Add folding code for CollectivePermuteOp

---

lib/Dialect/TTNN/Transforms/Workarounds/TTNNWorkarounds.cpp
test/ttmlir/Silicon/TTNN/llmbox/ccl/ccl_1x8.mlir

https://github.com/tenstorrent/tt-mlir/issues/2626
closes #2626 
Using any dimension other than 3 generates incorrect output. 
Refer to the issue tenstorrent/tt-metal#19433
Fix dimension to 3 for broken down ops while lowering all_reduce. 
Raise a failure if dimension 3 of the input shape is not divisible by sizeOfDevices.

Fix scatter_dim/gather_dim to 3 during all_reduce lowering

---

include/ttmlir/Dialect/TTIR/IR/TTIRGenericRegionOps.td
include/ttmlir/Dialect/TTIR/IR/TTIROps.td
include/ttmlir/Dialect/TTIR/Transforms/Passes.td
lib/Dialect/TTIR/IR/TTIRGenericRegionOps.cpp
lib/Dialect/TTIR/IR/TTIROps.cpp
lib/Dialect/TTIR/Transforms/CMakeLists.txt
lib/Dialect/TTIR/Transforms/GenericGenerateLoops.cpp
lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp
test/ttmlir/Dialect/TTIR/bufferization/prepare_tensors.mlir
test/ttmlir/Dialect/TTIR/generic/generic_datamovement.mlir
test/ttmlir/Dialect/TTIR/generic/generic_loops.mlir
test/ttmlir/Dialect/TTIR/generic/generic_negative.mlir

This commit implements one of the final lowering forms of ttir generic op. This pass converts the affine declarative loops into imperative loops and the affine maps are erased. For example a generic region might transform as follows:
```mlir
#lhs = affine_map<(d0, d1, d2) -> (d0, d2)>
#rhs = affine_map<(d0, d1, d2) -> (d2, d1)>
#out = affine_map<(d0, d1, d2) -> (d0, d1)>
grid = #tt.grid<2x4>
operands : (memref<2x4x4x6x!tt.tile<32x32, f32>>, memref<4x4x6x8x!tt.tile<32x32, f32>>, memref<2x4x4x8x!tt.tile<32x32, f32>>)
^compute(%cb0: memref<4x6x!tt.tile<32x32, f32>, #l1_>, %cb1: memref<6x8x!tt.tile<32x32, f32>, #l1_>, %cb2: memref<4x8x!tt.tile<32x32, f32>, #l1_>):
ttir.await %cb0, %cb1
ttir.tile_matmul_block (%cb0, %cb1, %cb2)
ttir.yield %cb2
```
Into:
```mlir
^compute(%cb0: …
```

Generic op loop generation

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/Dialect/TTNN/IR/TTNNWorkarounds.h
lib/Dialect/TTNN/IR/TTNNWorkarounds.cpp
test/ttmlir/Dialect/TTNN/Transforms/Workarounds/pad_workaround.mlir

closes #2642 
* tt-metal does not support integer type inputs
* tt-metal produces incorrect result for tile layout
* Add layout workaround
* Add data type workaround

Add workaround for pad op

---

include/ttmlir/Dialect/TTKernel/Pipelines/TTKernelPipelines.h
lib/Dialect/TTKernel/CMakeLists.txt
lib/Dialect/TTKernel/Pipelines/CMakeLists.txt
lib/Dialect/TTKernel/Pipelines/TTKernelPipelines.cpp
lib/RegisterAll.cpp
python/Passes.cpp
python/pykernel/pykernel_ast.py

- PR closes #2562 
- It would be best to leverage some of MLIR's existing passes (+ the ones we have defined) before translation in PyKernel
- The pipeline provides a sufficient platform to hold those passes + define the compilation flow.
- Added a PyKernel Compile Pipeline to run passes before translation to C++.
- Pybound pipeline.
- Added SROA and EmitC's form-expressions passes to the pipeline (w/ Options)

Added PyKernel Compile Pipeline

---

include/ttmlir/Dialect/TTIR/IR/TTIROps.td
include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/Target/TTNN/program.fbs
include/ttmlir/Utils.h
lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
lib/Conversion/TosaToTTIR/TosaToTTIRPatterns.cpp
lib/Dialect/TTIR/IR/TTIROps.cpp
lib/Dialect/TTNN/IR/TTNNOps.cpp
lib/Target/TTNN/TTNNToFlatbuffer.cpp
python/test_infra/ttir_builder.py
runtime/lib/ttnn/operations/eltwise/unary/unary_composite.cpp
runtime/lib/ttnn/operations/eltwise/unary/unary_composite.h
test/ttmlir/Conversion/StableHLOToTTIR/clamp_op.mlir
test/ttmlir/Conversion/StableHLOToTTIR/clamp_tensor_op.mlir
test/ttmlir/Conversion/TosaToTTIR/clamp.mlir
test/ttmlir/Dialect/TTIR/clamp/clamp_tests_negative.mlir
test/ttmlir/Dialect/TTNN/clamp/clamp_tests_negative.mlir
test/ttmlir/Dialect/TTNN/simple_clamp.mlir
test/ttmlir/Dialect/TTNN/simple_clamp_tensor.mlir
test/ttmlir/EmitC/TTNN/eltwise_unary/clamp.mlir
test/ttmlir/Silicon/StableHLO/n150/Unary/clamp_op.mlir
test/ttmlir/Silicon/StableHLO/n150/Unary/clamp_tensor_op.mlir
test/ttmlir/Silicon/TTNN/n150/eltwise/unary/clamp/clamp.mlir
test/ttmlir/Silicon/TTNN/n150/eltwise/unary/clamp/clamp_tensor.mlir
test/ttmlir/Silicon/TTNN/n150/perf/test_perf_clamp.mlir

closes https://github.com/tenstorrent/tt-mlir/issues/2185
stablehlo.clamp is lowered to either 1) ttir.clamp or 2) ttir.maximum followed by ttir.minimum op.
However, tt-metal does not support implicit broadcast for maximum and minimum ops. These two
ops fail if the operand shapes does not match and broadcast is required. 
1. Broadcast min/max value(s) if the shape of min/max does not match with input operand.
2. If a constant op is indirectly used in the stablehlo.clamp op (e.g. constant is converted/reshaped and then used in clamp op), then determine the constant value of min/max and use it in ttir.clamp conversion.

Determine indirectly defined constant for clamp op

---

lib/Conversion/StableHLOToTTIR/ArithToStableHLOPass.cpp
lib/Conversion/StableHLOToTTIR/EmptyOpTypeConversion.cpp
lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPass.cpp
test/ttmlir/Conversion/StableHLOToTTIR/empty_op.mlir

closes #2659 
Stablehlo graph can contain `tensor.empty` op which didn't require any conversion (except type conversion). 
This conversion is affected after introducing `ttir.empty` op.
Convert tensor.empty op to ttir.empty op during Stablehlo to TTIR conversion.

Fix tensor.empty op conversion

---

runtime/tools/python/ttrt/common/perf.py
runtime/tools/python/ttrt/common/read.py
runtime/tools/python/ttrt/common/run.py
runtime/tools/python/ttrt/common/util.py

- `ttrt` will error out if a binary is provided that was compiled with a different in ttrt version. This changes _on commit_, so if I commit some unrelated issue and test it will error out.
- Added a `--ignore-version` flag to `read`, `perf`, and `run`. Flag is always defaulted to False unless explicitly set.
- Flag is run at user's own risk. They should not run the flag if changes are made to ttrt or the FB schema.

Add Ignore Version flag for TTRT to ignore patch differences.

---

include/ttmlir/Dialect/TTIR/IR/TTIRGenericRegionOps.h
include/ttmlir/Dialect/TTIR/IR/TTIRGenericRegionOps.td
include/ttmlir/Dialect/TTIR/Transforms/Passes.td
lib/Dialect/TTIR/IR/TTIRGenericRegionOps.cpp
lib/Dialect/TTIR/Transforms/CMakeLists.txt
lib/Dialect/TTIR/Transforms/GenericGenerateDatamovement.cpp
lib/Dialect/TTIR/Transforms/GenericLowerAffineDMAs.cpp
lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp
test/ttmlir/Dialect/TTIR/generic/affine_dma.mlir
test/ttmlir/Dialect/TTIR/generic/generic_datamovement.mlir

This pass lowers DMA ops from their affine form to indexed form. This is useful for doing analysis on the DMA ops and lowering them to an optimal loop nest of coalesced transactions.  This is acheived by sampling the affine map over the entire parent generic op iterator space. Note that the affine map provided to the DMA op must be one of the indexing maps of the parent generic op.
e.g.
```mlir
%tx = ttir.dma %stream<#map1>, %cb0
```
Might become:
```mlir
%c2 = arith.constant 2
%iter0 = ttir.iter_index(0)
%core0 = ttir.core_index(0)
%0 = arith.muli %core0, %c2
%1 = arith.addi %0, %iter0
%iter2 = ttir.iter_index(2)
%tx = ttir.dma %stream [%1, %iter2], %cb0
```

Add TTIR pass that lowers DMA ops from affine to index form

---

include/ttmlir/Dialect/TTIR/IR/TTIROps.td
lib/Dialect/TTIR/IR/TTIROps.cpp
test/ttmlir/Dialect/TTIR/bufferization/bufferization.mlir

Previously we were just using upstream `tensor.empty` bufferization which results in an alloc that looks like this:
```mlir
memref.alloc() : memref<1x1x2x2x!tt.tile<32x32, f32>, #l1_>
```
Note that it's missing the shard layout attribute which is required for allocating device tensors in the d2m flow. This commit implements the bufferization interface for `ttir.empty` with a correctly annotated allocation:
```mlir
memref.alloc() : memref<1x1x2x2x!tt.tile<32x32, f32>, #tt.shard<8192x4096>, #l1_>
```

Support bufferization interface for ttir.empty op

---

include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/Dialect/TTNN/Analysis/LegalLayoutAnalysis.cpp
lib/OpModel/TTNN/TTNNOpModelLib.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

Related to https://github.com/tenstorrent/tt-mlir/issues/2546
Sometimes compiler will query op constraints for invalid layout, which can cause various exceptions.
1. During layout generation in LegalLayoutAnalysis check if op layout can be converted to TensorSpec, which helps us discard invalid layouts.
2. Refactor op model queries so that they only catch exceptions of the query itself.

Check layout validity in LLAnaylsis + refactor op model queries

---

include/ttmlir/Target/TTNN/types.fbs
lib/Target/TTNN/TTNNToFlatbuffer.cpp

https://github.com/tenstorrent/tt-mlir/issues/2685
For the proper handling of multi-device tensors, runtime needs to know the specific mesh shape for each tensor.
This change allows TensorDesc to have associated meshShape info if it is multi-device tensor. 
If single-device tensor, the meshShape will be 1x1.

Enable Tensor MeshShape info in TensorDesc

---

docs/src/build.md
docs/src/ttrt.md
python/CMakeLists.txt
python/Passes.cpp
python/test_infra/test_utils.py
python/test_infra/ttir_builder.py
runtime/tools/python/ttrt/common/callback.py
runtime/tools/python/ttrt/common/util.py

Required for #2448. Separate PR for adding quantize/dequantize/requantize support in ir_builder will be filed after E2E support is merged. The fix in this PR can be merged first and apply to all ops.
The data type of the golden tensor in ir_builder is passed back to the flatbuffer.
`get_type_from_torch_dtype` now handles quantized types, with the first incremental change to translate the `torch.int32` -> `quant.uniform` int32 data type for TTIR/TTNN modules. 
Also includes some minor edits to the documentation.

Pass golden tensor data type to flatbuffer in ir_builder

---

lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
test/ttmlir/EmitC/TTNN/tensor/permute.mlir
tools/ttnn-standalone/ttnn-precompiled.hpp

Part of the following issues:
https://github.com/tenstorrent/tt-mlir/issues/1877
Currently, we lack an emitC conversion for permute op.
This PR adds a missing emitC conversion for permute op.

Adding EmitC conversion for Permute Op

---

include/ttmlir/Dialect/TTIR/IR/TTIRGenericRegionOps.td
include/ttmlir/Dialect/TTIR/Transforms/Passes.td
lib/Dialect/TTIR/IR/TTIRGenericRegionOps.cpp
lib/Dialect/TTIR/Transforms/CMakeLists.txt
lib/Dialect/TTIR/Transforms/GenericGenerateDatamovement.cpp
lib/Dialect/TTIR/Transforms/GenericLowerDMAs.cpp
lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp
test/ttmlir/Dialect/TTIR/generic/affine_dma.mlir

Augment the existing lower affine dma pass to also lower to fully indexed form.  This simplifies backend conversion because now there is only 1 form of dma style to lower.
Additionally remove one of the supported dma forms that is redundant with another, preferred, way to represent the same thing. Add new and clean up verification messages and add builders for all DMA variants.

Augment dma lowering pass

---

include/ttmlir/Utils.h
lib/Target/TTNN/TTNNToFlatbuffer.cpp

Using `static_assert(false);` only came into the standard as part of c++23. In order to support some older compilers, as a workaround the same objective can be accomplished by introducing a dependent type.
https://cplusplus.github.io/CWG/issues/2518.html

Fix macos build

---

python/pykernel/pykernel_ast.py
test/pykernel/unit_tests.py

- PR closes #1814 
- PR closes #1815 
- PR closes #1816 
- PR closes #1817 
- PR closes #1818  
- PyKernel didn't support Unary Ops before
- Use `emitc` calls directly to support Unary Ops, relying on the `emitc.expression` to update the value and have it pass through the compiler.
- Results now look a lot better than forcing `arith` ops to emulate the same behaviour.
- Updated Unit tests.

Added Unary Ops Not, Invert, USub, UAdd to PyKernel

---

lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp

N/A
With the recent change of `ttir::YieldOp` semantics and subsequent change of `ttir::ScatterOp` semantics there was some leftover code that's not used anymore.
- Removed private member function from `ScatterOp` conversion pattern that wasn't used anymore
- Removed `stablehlo::ReturnOp` conversion to `ttir::YieldOp` conversion, since the semantics of `ttir::YieldOp` has changed, so that conversion didn't make much sense

stablehlo::ScatterOp DCE

---

python/test_infra/ttir_builder.py
test/python/golden/test_ttir_ops.py

[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/2665)
PadOp and RepeatOp tests are failing e2e run
Cleaned up PadOp
Corrected PadOp and RepeatOp tests

Changing TTIRBuilder PadOp and RepeatOp and tests to pass e2e run

---

cmake/modules/BuildFlatbuffers.cmake
include/ttmlir/Target/Common/debug_info.fbs
include/ttmlir/Target/Common/system_desc.fbs
include/ttmlir/Target/TTMetal/binary.fbs
include/ttmlir/Target/TTMetal/command.fbs
include/ttmlir/Target/TTMetal/program.fbs
include/ttmlir/Target/TTMetal/types.fbs
include/ttmlir/Target/TTNN/binary.fbs
include/ttmlir/Target/TTNN/program.fbs
include/ttmlir/Target/TTNN/types.fbs
include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
lib/Dialect/TTNN/Transforms/CMakeLists.txt
lib/Target/TTKernel/CMakeLists.txt
lib/Target/TTMetal/CMakeLists.txt
lib/Target/TTMetal/TTMetalToFlatbuffer.cpp
lib/Target/TTNN/CMakeLists.txt

Currently, when including other FlatBuffers schemas in a FlatBuffers schema, such as in `include/ttmlir/Target/TTNN/types.fbs`, it looks like this:
```
include "Common/types.fbs";
```
The generated header for `include/ttmlir/Target/TTNN/types.fbs`, located at `build/include/ttmlir/Target/TTNN/types_generated.h`, will include the generated header for `include/ttmlir/Target/Common/types.fbs`, located at `build/include/ttmlir/Target/Common/types_generated.h`, as follows:
```
#include "types_generated.h";
```
This is problematic because they do not reside in the same folder. As a workaround, we have to configure CMake in multiple places to avoid build issues:
```
target_include_directories(TTMetalTargetFlatbuffer PUBLIC ${PROJECT_BINARY_DIR}/include/ttmlir/Target/Common)
```
Added the …

Improve flatbuffer header generation logic

---

include/ttmlir/Conversion/Passes.h
include/ttmlir/Conversion/StableHLOToTTIR/ShardingUtils.h
include/ttmlir/Conversion/StableHLOToTTIR/ShardyToTTIR.h
include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
lib/Conversion/StableHLOToTTIR/ShardingUtils.cpp
lib/Conversion/StableHLOToTTIR/ShardyToTTIRPatterns.cpp
lib/Dialect/TTIR/Pipelines/TTIRPipelines.cpp
test/ttmlir/Conversion/StableHLOToTTIR/ccl/ccl_ops_shardy.mlir

annotations and fix if there is any issue.
https://github.com/tenstorrent/tt-mlir/issues/2645
Found cases where stablehlo from JAX may not fully follow sharding rules for automatic parallelism with sharded inputs/outputs.
Instead of fixing the issue with case by case, the new pass is introduced that allows us to manage tensor annotations in a more general manner. In particular, this pass address following two cases.
1. Single device tensor op has multi device tensor argument in a single op.
In this case, we need to insert MeshShardOp before the op and change the
tensor to single device tensor.
2. Multi device tensor ops have missing multi device tensor annotation in
case of automatic parallelism with pre-sharded inputs and outputs. In this
case, we need to add missing …

Add a new pass that checks the match of input and output of tensor

---

lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
test/ttmlir/EmitC/TTNN/tensor/ones.mlir

Part of the following issue:
https://github.com/tenstorrent/tt-mlir/issues/2072
One's op emitted IDevice instead of OptionalAnyDevice.
Emition changed from IDevice to OptionalAnyDevice.

Fixing ones op conversion

---

docs/src/emitc-testing.md
tools/ttnn-standalone/ci_compile_dylib.py

Closes https://github.com/tenstorrent/tt-mlir/issues/2095
There are a couple of problems in the ci_compile_dylib.py script described in the above issue.
This PR adds the ability to specify a different build directory and provides an option to compile a single C++ file instead of a whole group. It also polishes the MD file on how to run the emitC tests locally.

ci_compile_dylib script improvements

---

python/pykernel/pykernel_ast.py
test/pykernel/eltwise_sfpu/reader_unary.py
test/pykernel/eltwise_sfpu/writer_unary.py
test/pykernel/matmul_common/reader_bmm_8bank.py
test/pykernel/matmul_common/writer_bmm_8bank.py
test/pykernel/unit_tests.py

- PR closes #1844 
- Previously AugAssign wasn't supported
- Added `AugAssign` for `Add`, `Mul`, `Sub` into PyKernel AST
- Only operates on MemRefTypes already defined in Symbol table.

Added AugAssign to PyKernel

---

include/ttmlir-c/TTNNAttrs.h
include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/Dialect/TTNN/IR/TTNNOpsAttrs.h
include/ttmlir/Dialect/TTNN/IR/TTNNOpsAttrs.td
include/ttmlir/Dialect/TTNN/IR/TTNNOpsEnums.td
include/ttmlir/Target/TTNN/program.fbs
include/ttmlir/Target/TTNN/types.fbs
include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
lib/CAPI/TTNNAttrs.cpp
lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
lib/Dialect/TTNN/IR/TTNNOpsAttrs.cpp
lib/Target/TTNN/TTNNToFlatbuffer.cpp
python/TTNNModule.cpp
runtime/lib/ttnn/include/tt/runtime/ttnn/utils.h
runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/utils.cpp
runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/utils.h
runtime/lib/ttnn/operations/matmul/matmul.cpp
runtime/lib/ttnn/utils/utils.cpp
test/ttmlir/Silicon/TTNN/n150/perf/test_perf_matmul_multi_core_reuse_multi_cast_1d_program_config.mlir
test/ttmlir/Silicon/TTNN/n150/perf/test_perf_matmul_multi_core_reuse_multi_cast_dram_sharded_program_config.mlir
test/ttmlir/Silicon/TTNN/n150/perf/test_perf_matmul_multi_core_reuse_multi_cast_program_config.mlir
test/ttmlir/Silicon/TTNN/n150/perf/test_perf_matmul_multi_core_reuse_program_config.mlir

Add E2E `MatmulProgramConfig` support
- Since `MatmulProgramConfig` in the TTNN library is of type `std::variant`, I had to model each variant as a separate attribute in the TTNN dialect (`TTNN_MatmulMultiCoreReuseProgramConfigAttr`, `TTNN_MatmulMultiCoreReuseMultiCastProgramConfigAttr`, …). I also added other attributes that model dependencies of `MatmulProgramConfig` (`TTNN_CoreCoordAttr`, `TTNN_CoreRangeAttr`, …).
- ~~The added silicon tests are marked UNSUPPORTED since the values passed to the matmul config in them are just placeholder values.~~ The added silicon tests are passing now.

[TTNN] Add E2E MatmulProgramConfig support

---

third_party/CMakeLists.txt
tools/ttnn-standalone/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 7598b7ecd1426ae6fe1f54eb532a1dca00efcbf0
- add workaround to include header files that were included without <tt_stl/...> in tt-metal

Uplift third_party/tt-metal to 7598b7ecd1426ae6fe1f54eb532a1dca00efcbf0 2025-04-01

---

include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
test/ttmlir/Conversion/StableHLOToTTIR/ccl/ccl_ops_shardy.mlir
test/ttmlir/Dialect/TTNN/ccl/mesh_shard.mlir

https://github.com/tenstorrent/tt-mlir/issues/2786
When loading ttir mlir file with tensor annotation info, it leads to some failure in parsing the TensorMeshShardingAttr.
Updated asm format that has no issue.

Fix asm parser bug in loading TensorMeshShardingAttr

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/Dialect/TTNN/IR/TTNNWorkarounds.h
lib/Dialect/TTNN/IR/TTNNWorkarounds.cpp
test/ttmlir/Dialect/TTNN/Transforms/Workarounds/permute_dtype_workaround.mlir

tt-metal issue: https://github.com/tenstorrent/tt-metal/issues/19950
ttnn.permute is not supported for 32-bit signed/unsigned integers, however the op will execute without error if you do pass an input in this data type.
Added a workaround to cast 32-bit integer permute inputs to float32, then back to integer.

Add workaround that prevents permute from operating on integers

---

python/pykernel/pykernel_ast.py
test/pykernel/unit_tests.py

- PR closes #1823 
- PR closes #1825 
- PR closes #1826 
- PR closes #1827 
- PR closes #1828 
- PR closes #1829 
- PR closes #1830 
- PR closes #1831 
- PR closes #1832 
- Certain niche BinOps + all BoolOps weren't supported before. They are needed to increase support for defining conditionals in if and while blocks.
- Added Support in PyKernel AST + Unit Tests for New BinOps + BoolOps.

Added More BinOps + BoolOp Support in PyKernel

---

python/test_infra/ttir_builder.py
test/python/golden/test_ttir_ops.py

[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/2724)
LinearOp was not supported in TTIRBuilder
Added LinearOp support and test

Adding LinearOp and test

---

lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
runtime/lib/ttnn/operations/eltwise/unary/unary.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 4acdb8b52797aa34b6c4bba1f8212deeefa0f68c
Also added:
- change in tt-metal #19768 changed sigmoid template causing build to fail
- update ::tt::sigmoid run function
- update sigmoid's TTNtoEmitC consversion pattern

Uplift third_party/tt-metal to 4acdb8b52797aa34b6c4bba1f8212deeefa0f68c 2025-04-02

---

.github/workflows/on-community-issue.yml

slack issue "External PR notification not working"
When PR is opened, it can't run workflows and doesn't send notifications to slack.
used pull_request_target which runs in PR's context and thus can run.

On community PR send message to slack

---

runtime/tools/python/ttrt/binary/__init__.py
test/ttmlir/Silicon/TTNN/n150/simple_constant.mlir

fixes #838 
ttrt would error out with a JsonDecodeError if a constant op contained infinity or a NaN value. This is because the way flatbuffer emits those values and what Python's json library expect do not match up(fb happily emits `inf` and `nan`, meanwhile Python refuses to accept anything else but `Infinity` and `NaN`)
Now we manually replace flatbuffer's textual representation with what Python expects. Very hacky in my opinion, but I don't have a better fix in mind.

Hacky workaround for a decode error when using ttrt on specific graphs

---

include/ttmlir/Dialect/TTIR/Transforms/Passes.td
include/ttmlir/Dialect/TTIR/Utils/UniformTypeRewriter.h
include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
lib/Dialect/TTIR/IR/TTIROps.cpp
lib/Dialect/TTIR/Transforms/CMakeLists.txt
lib/Dialect/TTIR/Transforms/ElementTypeNormalization.cpp
lib/Dialect/TTNN/IR/TTNNOps.cpp
lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
lib/Dialect/TTNN/Transforms/TTNNLayout.cpp
test/ttmlir/Dialect/TTIR/Decomposition/get_dimension_size_decomposition.mlir

* Adding pass which will be common place for canonicalization of all input mlir types into compiler
* Adding override flag for enabling f32 type - we plan to use bf16 for all float types since is more TT hardware friendly. Until I fix all tests to use bf16 I will leave this override to on
* Fixed `GetDimensionSizeOp::fold` - Currently, this folder creates a DenseElementsAttr with C++ type uint32_t and uses the result type of GetDimensionSizeOp (obtained via getType()) as the MLIR type for constructing the attribute. However, if that type happens to be a signed integer (e.g., si32), MLIR’s verification logic asserts, since it expects the C++ element type and the MLIR type to be consistent.
Because our pass converts si32 to i32 (signless), this mismatch causes a verification error during …

Element type normalization pass

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/Dialect/TTNN/IR/TTNNTraits.h
include/ttmlir/Dialect/TTNN/IR/TTNNTraits.td
include/ttmlir/Dialect/TTNN/IR/TTNNWorkarounds.h
lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/Dialect/TTNN/IR/TTNNOps.cpp
lib/Dialect/TTNN/IR/TTNNWorkarounds.cpp
lib/Target/TTNN/TTNNToFlatbuffer.cpp
test/ttmlir/Dialect/TTNN/clamp/clamp_tests_negative.mlir
test/ttmlir/Dialect/TTNN/eltwise/binary/binary_tests_negative.mlir
test/ttmlir/Dialect/TTNN/eltwise/ternary/ternary_tests_negative.mlir
test/ttmlir/Dialect/TTNN/eltwise/unary/unary_tests_negative.mlir
test/unittests/Optimizer/TestGreedyL1InterleavedPolicy.cpp
test/unittests/Optimizer/TestShardSolver.cpp

https://github.com/tenstorrent/tt-mlir/issues/2815
All TTNN eltwise ops regardless of arity have this signature
```mlir
class TTNN_ElementwiseOp<string mnemonic, list<Trait> traits = []> :
TTNN_Op<mnemonic, traits> {
let arguments = (ins Variadic<AnyRankedTensor>:$inputs);
let results = (outs Variadic<AnyRankedTensor>:$results);
}
```
This comes with all the pros and cons of such a generic signature. The main argument of having a separate signature for different arity is that arity is bounded below by 1 and bounded above by 3 (inclusive), so the cons easily outweigh the pros in this case.
All eltwise classes (defined by arity) now have separate signatures
```mlir
class TTNN_ElementwiseUnaryOp<string mnemonic, list<Trait> traits = []> :
TTNN_Op<mnemonic, traits> {
let summary = "Eltwise …
```

TTNN eltwise ops separate signature by arity

---

include/ttmlir/Utils.h

closes #2831 
Reassigning llvm::ArrayRef causing address sanitization error.
Use llvm::SmallVector instead which can be reassigned.

Address sanitizer bugfix

---

include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h
include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
include/ttmlir/Utils.h
lib/Dialect/TT/IR/TTOpsTypes.cpp
lib/Dialect/TTIR/IR/TTIROps.cpp
lib/Dialect/TTIR/Transforms/Allocate.cpp
lib/Target/TTMetal/TTMetalToFlatbuffer.cpp

N/A
LLVM currently builds with C++17 but provides some STL utilities that we've been using that are available in future versions https://llvm.org/doxygen/STLForwardCompat_8h_source.html.
Replaced existing functionalities with provided utilities, this will also be useful once LLVM starts to build with C++20/23, as these utilities will be marked as deprecated, and it will be easier to replace them with STL implementation. Fixed includes in touched files.

Use LLVM provided STL utils from future versions

---

include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h

#2813 
Details in linked ticket.
Fixed by removing `static` keyword.
Closes #2813

Fix context mismatch when comparing MLIR objects

---

python/test_infra/ttir_builder.py
test/python/golden/test_ttir_ops.py

[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/2849)
PadOp golden padding had incorrect dimension handling.
Reformatted golden padding dimensions.

Changing PadOp golden kwarg handling

---

runtime/include/tt/runtime/detail/ttnn.h
runtime/include/tt/runtime/runtime.h
runtime/lib/runtime.cpp
runtime/lib/ttnn/runtime.cpp
runtime/test/ttnn/gtest/test_subtract.cpp
runtime/tools/python/ttrt/runtime/module.cpp

https://github.com/tenstorrent/tt-mlir/issues/2757
Explained in details in the ticket https://github.com/tenstorrent/tt-mlir/issues/2757
- Changed tensor creation API functions to use `void *` instead of `shared_ptr` so frontends don't have to create `shared_ptr` with empty deleters to use the runtime API.
- Renamed tensor creation API functions to state clearly on which device is buffer created and with which storage type, and added documentation comments in header files. Beside more clarity about what each function does, now it's much easier to track usages of each function across the codebase, before if you searched `createTensor` you'd get tons of hits and would have to look at argument types.
- Added new tensor creation API function to create multi-device tensor from already existing …

Update runtime API for tensor creation

---

include/ttmlir/Dialect/TTNN/Analysis/LegalLayoutAnalysis.h
include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
include/ttmlir/Dialect/TTNN/Transforms/Optimizer.h
include/ttmlir/Dialect/TTNN/Utils/PassOverrides.h
include/ttmlir/Dialect/TTNN/Utils/TransformUtils.h
lib/Dialect/TTNN/Analysis/LegalLayoutAnalysis.cpp
lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
lib/Dialect/TTNN/Transforms/Optimizer.cpp
lib/Dialect/TTNN/Transforms/Workarounds/TTNNWorkarounds.cpp
lib/Dialect/TTNN/Utils/PassOverrides.cpp
lib/Dialect/TTNN/Utils/TransformUtils.cpp
test/ttmlir/Dialect/TTNN/optimizer/conv2d_config_override.mlir
test/unittests/Optimizer/TestOptimizerOverrides.cpp

Closes #2712
Overrides for Conv2d Config Attribute should be added to the Optimizer.
- Option to override Conv2d Config has been added to ttir-to-ttnn-backend-pipeline
- CLI string format and a parser for Conv2d Config overrides have been defined
- Conv2d Config overrides are applied in LegalLayoutAnalysis
- Suffix to loc of toLayout op that is created in the pass has been added so that ttnn.conv2d op can have a unique loc

Add Conv2dConfig overrides

---

.github/workflows/build-and-test.yml

slack req
Community contribution build fails
Add continue on error for showing test report as comment so community contributed builds with lower privileges can succeed. Clang-tidy is also uploaded as artifact because  commenting PR will fail on community builds.
Will test it after it is merged

Fixes to run community contributed builds

---

include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h
lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
test/ttmlir/EmitC/TTNN/conv/conv2d.mlir

N/A
For non-bf16 types TTNN asserts with current implementation.
Added a configuration that mirrors the one in the runtime, which should enable other input types as well (most notably f32).

Support for non-bf16 types for Conv2dOp in EmitC

---

runtime/lib/common/system_desc.cpp

closes #300 
We were using default alignment values when creating system descriptor
Metal now has support for dynamically querying alignments from device/hal. Migrated the hardcoded values to use the dynamic ones.

Query alignment info from device and hal

---

include/ttmlir/Dialect/TTNN/IR/TTNNBase.td
include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
lib/Target/TTNN/TTNNToFlatbuffer.cpp
runtime/lib/ttnn/operations/eltwise/unary/unary_composite.cpp

Closes #2856
Closes #2857
Closes #2859
Closes #1635
Closes #1636
We lack a memory config attribute in our eltwise ops in the TTNN dialect.
This PR introduces a memory config attribute in the TTNN dialect.

Adding memory config attribute to eltwise ops in TTNN dialect

---

runtime/lib/ttnn/operations/data_movement/pad.cpp
runtime/lib/ttnn/operations/eltwise/binary/binary.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the c9e4a1ac43c37f0b801788ac6280c25960ad5296
- Revert "Update pad op after metal commit 8d50fef" since change reverted in metal commit ce1f5de
- update binary op params after metal change d7a8dcd

Uplift third_party/tt-metal to c9e4a1ac43c37f0b801788ac6280c25960ad5296 2025-04-10

---

include/ttmlir/Dialect/TTIR/IR/TTIROps.td
lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
python/test_infra/ttir_builder.py
test/python/golden/test_ttir_ops.py
test/ttmlir/Conversion/StableHLOToTTIR/pad_op.mlir
test/ttmlir/Dialect/TTNN/simple_pad.mlir
test/ttmlir/Silicon/TTNN/n150/simple_pad.mlir

https://github.com/tenstorrent/tt-mlir/issues/2854
- PadOp is non-DPS op, but should be (more precisely it should belong to `TTIR_NamedOp` class)
- creations ops (`empty`, `arange`, `constant`, `zeros`, `ones` etc.) should have their own op class, because they aren't `DPS`, but are `Pure`
- `TTIR_GenericElementwiseXOp` doesn't make sense anymore, and they should be transferred to `TTIR_ElementwiseXOp` class
- some CCL ops were only `TTIR_DPSOp`s, but should be `TTIR_NamedOp`s
Fixed mentioned inconsistencies.

Fix TTIR tablegen op class inconsistencies

---

.github/CODEOWNERS
include/ttmlir/Dialect/TTIR/IR/TTIROps.td
include/ttmlir/Dialect/TTIR/IR/TTIROpsAttrs.td
include/ttmlir/Dialect/TTIR/IR/TTIROpsInterfaces.td
include/ttmlir/Dialect/TTIR/Transforms/EraseInverseOps/EraseInverseOps.h
include/ttmlir/Dialect/TTIR/Transforms/Passes.td
include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
lib/Conversion/TosaToTTIR/TosaToTTIRPatterns.cpp
lib/Dialect/TTIR/IR/TTIROps.cpp
lib/Dialect/TTIR/Transforms/CMakeLists.txt
lib/Dialect/TTIR/Transforms/EraseInverseOps/BroadcastCommutePatterns.cpp
lib/Dialect/TTIR/Transforms/EraseInverseOps/CMakeLists.txt
lib/Dialect/TTIR/Transforms/EraseInverseOps/ElementwiseCommutePatterns.cpp
lib/Dialect/TTIR/Transforms/EraseInverseOps/EraseInverseOps.cpp
lib/Dialect/TTIR/Transforms/FlattenSlidingWindow.cpp
lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
lib/Dialect/TTNN/Transforms/Optimizer.cpp
lib/Dialect/TTNN/Transforms/TTNNLayout.cpp
python/test_infra/ttir_builder.py
test/ttmlir/Dialect/TTIR/erase_inverse_ops/basic_eltwise_binary_commute.mlir
test/ttmlir/Dialect/TTIR/erase_inverse_ops/basic_eltwise_unary_commute.mlir
test/ttmlir/Dialect/TTIR/erase_inverse_ops/commute_reshape_broadcast.mlir
test/ttmlir/Dialect/TTIR/erase_inverse_ops/erase_permute_between_conv2d.mlir
test/ttmlir/Dialect/TTIR/erase_inverse_ops/no_tms_between_convs.mlir
test/ttmlir/Dialect/TTIR/flatten_sliding_window.mlir

This pass aims to purge the graph of TMs which are the inverses of each other when separated by a sequence of other ops.
- Added `EraseInverseOps` pass
- This pass applies _commute patterns_ to ops in the graph. That is the pattern will match some op, followed by a TM and move the TM to the producer of the op
- Patterns have been implemented to commute transposes, reshapes, and permutations through eltwise unary, eltwise binary, and broadcast ops.
- Added/replaced TM canonicalization patterns using `fold`
- This is because folding patterns run **during** passes automatically, whilst canonicalization must be explicitly called.
- These patterns are responsible for erasing back-to-back inverse TMs. The folding patterns are:
- Replace identity TM with its operand
- For back-to-back …

Erase Inverse Ops pass

---

runtime/lib/ttnn/operations/eltwise/binary/binary.cpp
runtime/lib/ttnn/operations/eltwise/binary/binary_composite.cpp
runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/utils.cpp
runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/utils.h

BInary operand swapping logic was accidentally removed during refactor, causing uplifts to fail on tt-torch.
Add back operand swapping logic for binary ops. Confirmed that this fixes uplifts on tt-torch. Since this unblocks uplifts, would probably want to merge in before 24h limit
FYI @brataTT

Add back binary op operand swapping logic

---

CMakeLists.txt
include/ttmlir/Support/Logger.h
test/unittests/CMakeLists.txt
test/unittests/Support/CMakeLists.txt
test/unittests/Support/LoggerTest.cpp

Currently there is no proper way to log things around in tt-mlir compiler (except in runtime which has its own logger). We can't reuse the same logger as it is built specifically for runtime with exceptions which are not supported in llvm based tt-mlir. 
LLVM provides with basic macro for debugging. This commit adds a logger which is basically a wrapper around it. It will be possible to specify log level (verbosity) and log component (optimizer, d2m, ttnn dialect...). To run with logs enabled we have to run in debug build, and set option `-debug` to enable all logs. This includes mlir logs so better use would be to set option `-debug-only=<log-component>`. 
Log looks like:

TT-MLIR logger

---

runtime/lib/ttnn/operations/ccl/collective_permute.cpp

closes #2901 
Current implementation on runtime for Collective Permute CCL op sends/receives tensors based on id from IDevice interface. This id is basically physical id. End users(Model builders) expect logical tensor/device ids to be used and should not depend on physical device deployment.
Changed to use logical device ID instead of physical device ID on collective permute.
The get_tensors_from_multi_device_storage function returns tensors in linear logical device
ID order. This eliminated the need to map logical device IDs to tensors.
Replaced the unordered_map with a simpler vector implementation.

Use logical device ID for collective permute.

---

include/ttmlir/Dialect/TTNN/Analysis/Edge.h

There was a compilation error during the uplift of `tt-mlir` to `tt-xla`. Adding a `constexpr` to the `mlir::tt::ttnn::Edge::operator==` function to fix it.

Fixing tt-mlir for enabling tt-xla uplift

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/Dialect/TTNN/IR/TTNNOpsAttrs.td
include/ttmlir/Target/TTNN/operations/get_device.fbs
lib/Dialect/TTNN/Transforms/Optimizer.cpp
lib/Dialect/TTNN/Utils/TransformUtils.cpp
lib/Target/TTNN/TTNNToFlatbuffer.cpp
runtime/lib/ttnn/operations/context/get_device.cpp
runtime/tools/python/ttrt/common/run.py
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

closes [tt-xla#484](https://github.com/tenstorrent/tt-xla/issues/484)
Get device op is still using device ids while we should be using mesh shape and offset.
Added mesh offset input attribute to `GetDeviceOp`, defaulting to (0, 0) for now, future plans would be to dynamically determine in the compiler or pass in by the user.
cc @wooseokTT @ajakovljevicTT

Add mesh offset to get device op, update runtime implementation

---

include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h
lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
runtime/lib/ttnn/operations/conv/conv2d.cpp
runtime/lib/ttnn/operations/eltwise/binary/binary_composite.cpp
runtime/lib/ttnn/operations/eltwise/unary/unary.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 4f706555c6cfcb35a6a1f69783333c04e20ce683
- Update binary maximum function signature after update in metal change 5b5b45e
- Update sigmoid op to take vector mode param reflecting new registration method in metal change 15c097d
- Update conv op to reflect new combined interface after metal change 7796cd1

Uplift third_party/tt-metal to 4f706555c6cfcb35a6a1f69783333c04e20ce683 2025-04-14

---

runtime/include/tt/runtime/workarounds.h
runtime/lib/ttnn/operations/ccl/mesh_shard.cpp
runtime/lib/ttnn/operations/ccl/mesh_shard_impl.h
runtime/tools/python/ttrt/common/run.py
tools/ttnn-standalone/CMakeLists.txt
tools/ttnn-standalone/ttnn-precompiled.hpp

https://github.com/tenstorrent/tt-mlir/issues/2367
Need to clean up mesh_shard op for emitC.
Restructured code such that mesh_shard function emulates the ttnn::mesh_shard and standalone emitC can reuse the code from ttnn-precompiled.hpp. 
Remove workaround as https://github.com/tenstorrent/tt-metal/issues/18842 is closed.

Restructure runtime mesh_shard op for emitC

---

python/pykernel/pykernel_ast.py
test/pykernel/unit_tests.py

- PR closes #1840 
- Couldn't create arrays using alloca in PyKernel. 
- Create Arrays using List notation: `l = [1, 2, 3]`
- Create Nested Arrays: `l = [[1, 2], [3, 4]]`
- Create Arrays with Variables + Expressions: `l = [x - 1, 3, x + 1]`
- Access and modify list elements: `l[0] = 42` `for i in range(10): sum += l[i]`
- Create Memrefs of certain sizes without initial values: `l: [int, 8, 8] = 0 -> memref<8x8xi32>` 
- Added Tests

Added Arrays to PyKernel

---

include/ttmlir/Conversion/TTIRToTTIRGeneric/TTIRToTTIRGeneric.h
include/ttmlir/Dialect/TTIR/IR/TTIRGenericRegionOps.td
lib/Conversion/TTIRToTTIRGeneric/TTIRToTTIRGeneric.cpp
lib/Conversion/TTIRToTTIRGeneric/TTIRToTTIRGenericPass.cpp
test/ttmlir/Conversion/TTIRToTTIRGeneric/named_to_generic.mlir
test/ttmlir/Conversion/TTIRToTTIRGeneric/use_tile_matmul.mlir
test/ttmlir/Conversion/TTIRToTTIRGeneric/use_tile_matmul_false.mlir

Closes #2937 
- Add `ttir.tile_matmul` operation;
- Add `use-tile-matmul` flag to `ttir-to-ttir-generic` pass;
- When flag is set use alternative rewriting for `ttir.matmul`.

Add option to lower ttir.matmul to linalg.generic plus ttir.tile_matmul

---

include/ttmlir/Dialect/TTMetal/IR/TTMetalOps.td
include/ttmlir/Target/TTMetal/command.fbs
lib/Conversion/TTIRToTTMetal/TTIRToTTMetal.cpp
lib/Conversion/TTIRToTTMetal/TTIRToTTMetalPass.cpp
lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
lib/Dialect/TT/IR/TTOpsTypes.cpp
lib/Dialect/TTMetal/IR/TTMetalOps.cpp
lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp
lib/Target/TTMetal/TTMetalToFlatbuffer.cpp
runtime/lib/ttmetal/command_queue.cpp
test/ttmlir/Conversion/TTIRToTTMetal/alloc_lowering.mlir
test/ttmlir/Conversion/TTIRToTTMetal/generic_lowering.mlir

**Split from #2809**
#2609
We need to lower new TTIR generic ops & functions to TTMetal and TTKernel dialects to fit the new D2M lowering scheme.
**TTMetal Lowering Pass**
- Replaces all old code in `TTIRToTTMetal.cpp` but maintains the pass itself
- Adds two rewriters:
- `MemrefAllocRewriter` - rewrites `memref.alloc` ops to `ttmetal.create_buffer`
- Pulls the `address` attr from `memref.alloc` if it exists. If not, defaults to `address = 1000` (arbitrary default until alloc pass is implemented.
- `TTIRGenericRewriter` - rewrites `ttir.generic` to `ttmetal.enqueue_program`
- Changed the `ttmetal.enqueue_program` op to include a `threads` attribute which is inherited from `ttir.generic`
- Applies identical core ranges to each kernel, all equal to the grid size of `ttir.generic`
Parts of …

D2M New TTMetal Lowering

---

lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
runtime/lib/ttnn/operations/reduction/argmax.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 70883c9145a607b37adaca05a22e3a9ca2f61368
- Update argmax to pass in keepdim arg after interface updated in metal commit 0d93eb7

Uplift third_party/tt-metal to 70883c9145a607b37adaca05a22e3a9ca2f61368 2025-04-16

---

runtime/lib/ttnn/operations/conv/conv2d.cpp

https://github.com/tenstorrent/tt-mlir/pull/2927#discussion_r2043926633
During uplift, `QueueId()` had to be added to conv2d call.
Instead of targeting a specific impl of conv2d, now the "generic" `::ttnn::conv2d` interface is called, allowing the removal of `QueueId` param.
fyi @brataTT

Remove QueueId from conv2d call in runtime

---

include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
test/ttmlir/Dialect/EmitC/ttir_to_emitc_pipeline_sanity.mlir
test/ttmlir/Dialect/EmitC/ttir_to_emitc_so_pipeline_sanity.mlir

#2953 
TTNN to EmitC conversion is done in 2 ways: one for ttnn-standalone, and one for ttnn-dylib (i.e. shared object path).
We already have a pipeline for ttnn-standalone (ttir-to-emitc-pipeline), we want to add ttir-to-emitc-so-pipeline for the shared object path.
These pipelines differ only in surrounding boilerplate around the emitted forward function. The ttir-to-emitc-pipeline adds a function to generate inputs, and a main fn to drive execution, while the ttir-to-emitc-so-pipeline will repackage forward function to take in a vector of tensors and a device (targeted for shared object compilation).
Added the new pipeline, added a test, changes to `ttir-to-emitc-pipeline` test making it more robust.

[EmitC] Add TTIR to EmitC SO pipeline

---

runtime/lib/common/system_desc.cpp
runtime/lib/ttnn/operations/data_movement/pad.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the f50d050e2d0ce343b9766a3f8826c1975d0802e3
- Remove reference to hal_ref after metal change 760ad8f
- Update pad op padding datatype after metal change fa45df9

Uplift third_party/tt-metal to f50d050e2d0ce343b9766a3f8826c1975d0802e3 2025-04-17

---

include/ttmlir/Dialect/TTNN/IR/TTNNOpModelInterface.td
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/Dialect/TTNN/Analysis/ShardSolver.cpp
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/Dialect/TTNN/IR/TTNNOpsAttrs.cpp
lib/OpModel/TTNN/Conversion.cpp
lib/OpModel/TTNN/Conversion.hpp
lib/OpModel/TTNN/TTNNOpModelLib.cpp
test/unittests/OpModel/TTNN/Conversion/TestConversion.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
test/unittests/OpModel/TTNN/OpModelFixture.h

#2450
Searching for legal output layouts takes a long time in the optimizer since most ops only allow one or a few output layouts for a given input layout. We should let the op set the output and simply read it back. 
As of #2873 we have the conversion API required for getting a `TTNNLayoutAttr` from the `TensorSpec` returned from the metal API
- Integrate the conversion API with `getOpConstraints()`
- Pass in the device grid from the operation and the `MLIRContext` to the MLIR-Metal boundary
- After receiving the constraints response from Metal, call the conversion function to construct a `TTNNLayoutAttr` from the `TensorSpec`
- Return the `TTNNLayoutAttr` all the way back to the callers
- Ensure `getOpConstraints()` can be called with `outputLayout` set to `nullptr`
- Added tests for …

[Optimizer] Integrate TensorSpec to TTNNLayoutAttr conversion into getOpConstraints and return the TTNNLayoutAttr to the caller

---

runtime/include/tt/runtime/runtime.h
runtime/include/tt/runtime/types.h
runtime/lib/common/system_desc.cpp
runtime/lib/runtime.cpp
runtime/test/python/ttnn/device_agnostic/test_runtime_api.py
runtime/tools/python/ttrt/runtime/module.cpp

[Torch Issue 580](https://github.com/tenstorrent/tt-torch/issues/580)
Creating system descriptor currently opens a device by itself. Which means callers cannot have the same device open when `getCurrentSystemDesc` is called.
Allow `getCurrentSystemDesc` to accept a device as argument so it doesn't need to create one itself and callers can have the same device open when this function is called.

Allow getCurrentSystemDesc to take in Device as optional parameter

---

include/ttmlir/Dialect/TTNN/Utils/OptimizerOverrides.h
include/ttmlir/Dialect/TTNN/Utils/PassOverrides.h
include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
lib/Dialect/TTNN/Analysis/LegalLayoutAnalysis.cpp
lib/Dialect/TTNN/Utils/OptimizerOverrides.cpp
lib/Dialect/TTNN/Utils/PassOverrides.cpp
python/OptimizerOverrides.cpp
python/TTNNModule.cpp
test/unittests/Optimizer/TestOptimizerOverrides.cpp
tools/explorer/tt_adapter/src/tt_adapter/main.py
tools/explorer/tt_adapter/src/tt_adapter/mlir.py
tools/explorer/tt_adapter/src/tt_adapter/runner.py

Closes #2454 
- Added python bindings for overriding Conv2dConfig in tt-explorer
- In *LegalLayoutAnalysis.cpp*, made Conv2dConfig attribute always present for conv2d ops (if nothing is overridden, default values are set) so that it appears in the explorer 
- Added a temporary solution in *MLIRToFlatbuffer.h* to handle optional parameters (will be changed properly in #2912 or #2913 ) 
- Set `dtype` and `weights_dtype` parameters in *LegalLayoutAnalysis.cpp* to get through a tt-metal assert in *prepare_conv2d_weights.cpp* where `weight_tensor_.get_dtype() == weights_bias_dtype`
- Removed some redundant comments in *OptimizerOverrides.h*

Enable Conv2dConfig overrides in explorer

---

lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
test/ttmlir/Conversion/StableHLOToTTIR/constant_op.mlir

https://github.com/tenstorrent/tt-mlir/issues/2988
- With recent commit fc6cfdad28918ce0d75da8f6f96c9357fbb97a56 which moves type conversion from stable hlo to ttmlir, dropped special case: `value` ElementAttr of `shlo.constant` op needs to be rewritten only in case we are dealing with a scalar. Current code rewrites this attribute regardless if we are dealing with scalar or shaped tensor. 
- This PR address this by skipping `value` attr rewrite in case its shaped type, like previous code.
- Bunch of problematic gelu ops in tt-torch models, new test
- Note: One thing to note (and this was the case with old code), if we have splat value which is 1 bit or 64 bits rewrites will take long time also. True with previous version of code too, not fixed here.
closes #2988

Fix shlo constant op rewriter (slowdown seen in tt-torch ops)

---

cmake/modules/CMakeLists.txt
lib/Dialect/TTKernel/IR/CMakeLists.txt
lib/Dialect/TTMetal/IR/CMakeLists.txt

While trying to set up an out-of-tree pass that lowers to TTKernel and TTMetal dialects. Linking failed as it was not able to   find the definitions for MemorySpaceAttr, MetalLayoutAttr, TypeIDResolver, etc.
And another error while finding the TTMLIRConfig:
```
CMake Error at CMakeLists.txt:27 (find_package):
Found package configuration file:
../tt-mlir/build/lib/cmake/ttmlir/TTMLIRConfig.cmake
but it set TTMLIR_FOUND to FALSE so package "TTMLIR" is considered to be
NOT FOUND.  Reason given by package:
The following imported targets are referenced, but are missing:
TTNN::TTNNOpModelLib
```
Export `TTNNOpModelLib` and `coverage_config` as part of `TTMLIR_EXPORTS`.
Set right dependencies for `MLIRTTKernelDialect` and `MLIRTTMetalDialect`

Changes required to use tt-mlir dialects out-of-tree

---

include/ttmlir-c/TTAttrs.h
include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
include/ttmlir/Dialect/TT/Utils/PhysicalCoreCoord.h
include/ttmlir/Target/Common/types.fbs
include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
lib/CAPI/TTAttrs.cpp
lib/Dialect/TT/IR/TTOpsTypes.cpp
python/TTModule.cpp
runtime/lib/common/system_desc.cpp
tools/explorer/tt_adapter/src/tt_adapter/mlir.py

#2056
We would like to switch to [translated coordinates](https://github.com/tenstorrent/tt-umd/blob/main/docs/coordinate_systems.md#translated-coordinates) (tt-metal calls them virtual coordinates but will change in the future) for the worker cores.
Calculate the physical-to-translated coordinate translation offsets by querying what coordinates does the worker core `{0, 0}` translates to, and do subtraction (assuming the worker core grid is contiguous in the translated coordinates).
Store the offsets in the system descriptor flatbuffer schema and the tablegen file.
Compute the full worker core grid when needed.
The array of worker core coordinates is removed from the flatbuffer schema and tablegen file.
The structure that holds the dram/eth/inactive_eth core coordinates remains, but …

Adopt virtualized/translated worker core coordinates

---

lib/Dialect/TTNN/Transforms/Workarounds/TTNNWorkaroundsPatterns.cpp
test/ttmlir/Dialect/TTNN/ccl/all_reduce/all_reduce_positive.mlir

Closes #2675 
We decompose all_reduce into reduce_scatter and all_gather as a workaround. However, reduce_scatter requires that the size along scatter_dim be divisible by the number of devices. This constraint propagates back to all_reduce, limiting our ability to compile certain models. In cases where this divisibility requirement is not met, compilation can fail.
Added a new decomposition path for the AllReduce TTIR op using AllGather + local Reduce.
This serves as an alternative to the existing ReduceScatter + AllGather workaround.
The new decomposition is applied when:
- The tensor shape along the scatter_dim is not divisible by the number of devices, or
- The input tensor is smaller than heuristically found size_limit

Introduce new workaround for all_reduce op.

---

lib/Conversion/StableHLOToTTIR/ShardingUtils.cpp
lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
test/ttmlir/Conversion/StableHLOToTTIR/ccl/ccl_ops_gspmd.mlir
test/ttmlir/Conversion/StableHLOToTTIR/ccl/ccl_ops_shardy.mlir

https://github.com/tenstorrent/tt-mlir/issues/3035
Bug 1. shard_dims should have the size of meshShape but has size of input tensor shape
Bug 2. checking custom_call op with stablehlo should confirm one use of current op not following custom_call op.
Fix 1. change the shape of shard_dims using meshShape.
Fix 2. checking srcOp use instead of following custom_call op's uses.

Fix bug in parsing mesh_shard op

---

.github/actions/build-tt-mlir-action/action.yaml
CMakeLists.txt
third_party/CMakeLists.txt
tools/ttnn-standalone/CMakeLists.txt

N/A
Building the tt-mlir repo takes a long time (sometimes over 30 min on CI), especially for a fresh build
When clang is used as the compiler, try to find and use the matching lld linker
The same linker is passed to the tt-metal external project as well
Detect the `CPM_SOURCE_CACHE` environment variable and pass it to the tt-metal build command, so we don't re-download the 1.4 GB tt-metal external dependencies every time, if the environment variable is set to some out-of-tree location
Set up persistent cmake CPM cache in the CI

Speedup build for both local and CI

---

test/ttmlir/Dialect/TTNN/simple_cumsum.mlir
test/ttmlir/Silicon/TTNN/n150/simple_cumsum.mlir

N/A
Currently moreh cumsum in ttnn only supports `dim == 0` and `dim == 1`.
When tt-metal is built with debug mode, the following assertion will be triggered for higher dimensions:
https://github.com/tenstorrent/tt-metal/blob/6943a39ea9a136d00e8841f4f6db3cfdc1acba2b/ttnn/cpp/ttnn/operations/moreh/moreh_cumsum/device/moreh_cumsum_program_factory.cpp#L23
Move the unsupported tests from silicon test to a regular test

Move unsupported moreh cumsum silicon tests

---

docs/src/ttmlir-translate.md

N/A
The previous path was out-of-date 
`test/ttmlir/Dialect/TTNN/simple_multiply.mlir`
to
`test/ttmlir/Dialect/TTNN/eltwise/binary/multiply/simple_multiply.mlir `
Update the path so the command works out of box

update path for `simple_multiply.mlir`

---

lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
lib/OpModel/TTNN/MetalHeaders.h
runtime/lib/ttnn/operations/eltwise/binary/binary_composite.cpp
test/ttmlir/Silicon/TTNN/n150/eltwise/binary/maximum/maximum_broadcast.mlir
test/ttmlir/Silicon/TTNN/n150/eltwise/binary/minimum/minimum_broadcast.mlir
test/ttmlir/Silicon/TTNN/n150/eltwise/binary/pow/pow_broadcast.mlir
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
third_party/CMakeLists.txt
tools/ttnn-standalone/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 5147622f25fc1cdb13f83cca1762b7f623cc2b00
- Update min op to use new paramater list after metal change 6aed15e
- Update fmt include hash after package updated in metal change 0185369ae6
- Update filename after buffer_constants renamed to buffer_types in metal change ed4f0c7
- Reduce expected OpModelTest space usage for reshape op after metal change ed0a405
- Update pow op to use new paramater list after metal change a5740e0
- Set `use_legacy` param to false for eltwise binary ng ops that need broadcast
- Temporarily disable op model lib ops due to reshape segfault #3054

Uplift third_party/tt-metal to 5147622f25fc1cdb13f83cca1762b7f623cc2b00 2025-04-21

---

include/ttmlir/Dialect/TTIR/IR/TTIROps.td
lib/Dialect/TTIR/IR/TTIROps.cpp
test/ttmlir/Dialect/TTIR/cumsum/cumsum_test_negative.mlir
test/ttmlir/Dialect/TTNN/simple_cumsum.mlir

Part of the https://github.com/tenstorrent/tt-mlir/issues/3053
CumSumOp assumed that axis index attribute will be in the range [0, rank).
Relaxed the condition so it now accepts axis index in the range [-rank, rank) on the input and normalize that range to [0, rank) as a part of the folding.

CumSumOp negative axis index attr

---

include/ttmlir/Dialect/TTIR/IR/TTIROps.td
include/ttmlir/Dialect/TTNN/IR/TTNNOpsAttrs.td
include/ttmlir/Target/TTNN/operations/conv.fbs
include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
lib/Dialect/TTIR/IR/TTIROps.cpp
lib/Dialect/TTNN/Analysis/LegalLayoutAnalysis.cpp
lib/Dialect/TTNN/IR/TTNNOpsAttrs.cpp
lib/OpModel/TTNN/Conversion.cpp
python/TTNNModule.cpp
runtime/lib/ttnn/operations/include/tt/runtime/ttnn/operations/utils.cpp
test/ttmlir/Dialect/TTIR/conv2d/conv2d_tests_negative.mlir
test/ttmlir/Dialect/TTNN/conv/conv2d/conv2d_tests_negative.mlir
test/ttmlir/Silicon/TTNN/n150/perf/test_perf_conv2d_config.mlir

If we want to fuse relu and conv we need to set activation param in `Conv2dConfigAttr`, but since majority of it's params are non-optional we would have to determine correct parameters. This PR changes all params of `Conv2dConfgAttr` so that we can easily specify which parameter we want to override and leave the rest to default to whatever is set in ttnn.

Make all params or `Conv2dConfigAttr` optional

---

.github/workflows/wheel-build.yml
python/setup.py

- Issues with how `tt-forge` will integrate with artifacts from wheel-build.
- Fixed Default Docker Image for `workflow-dispatch` runs.

Fixes for wheel-build run to integrate with tt-forge releases

---

include/ttmlir/Dialect/TT/IR/TTOpsTypes.h
include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
include/ttmlir/Dialect/TTIR/IR/TTIRGenericRegionOps.td
include/ttmlir/Dialect/TTIR/IR/TTIROps.td
include/ttmlir/Dialect/TTIR/IR/TTIROpsInterfaces.h
include/ttmlir/Dialect/TTIR/IR/TTIROpsInterfaces.td
include/ttmlir/Dialect/TTIR/Transforms/Passes.td
lib/Conversion/TTIRToTTKernel/TTIRToTTKernel.cpp
lib/Dialect/TT/IR/TTOpsTypes.cpp
lib/Dialect/TTIR/IR/TTIROps.cpp
lib/Dialect/TTIR/IR/TTIROpsInterfaces.cpp
lib/Dialect/TTIR/Transforms/Allocate.cpp
lib/Dialect/TTIR/Transforms/GenericGenerateDatamovement.cpp
lib/Dialect/TTIR/Transforms/GenericLowerDMAs.cpp
lib/Dialect/TTIR/Transforms/GenericRegionsToFuncs.cpp
test/ttmlir/Conversion/TTIRToTTKernel/dma_lowering.mlir
test/ttmlir/Conversion/TTIRToTTKernel/tiled_matmul.mlir
test/ttmlir/Conversion/TTIRToTTMetal/generic_lowering.mlir
test/ttmlir/Dialect/TTIR/allocate/generic_form_streams_matmul.mlir
test/ttmlir/Dialect/TTIR/generic/affine_dma.mlir
test/ttmlir/Dialect/TTIR/generic/generic_datamovement.mlir
test/ttmlir/Dialect/TTIR/generic/generic_loops.mlir
test/ttmlir/Dialect/TTIR/generic/generic_regions_to_funcs.mlir

Introduce a new op interface for ops that can take views of memory, i.e. view_layout and stream_layout ops.  This interface generalizes and applyViews function which recursively evaluates chains of view ops over their underlying physical memory.
This change also renames StreamLayoutAttr to ViewLayoutAttr to better align with the semantics.  That is, view layout ops always return memrefs with layout ViewLayoutAttr, of which stream_layout is a special case.

View layout op interface

---

runtime/tools/python/ttrt/common/run.py

Fix program level golden comparison on ttrt #3086
close #3086
The program-level golden comparison code in runtime/tools/python/ttrt/common/run.py still references the now-removed total_outputs variable, causing ttrt to throw an exception when running with program-level golden tensors 
Load all golden outputs and compare each against the corresponding runtime output
Remove the outdated total_outputs-based comparison block

Fix program-level golden comparison logic in ttrt

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/Dialect/TTNN/IR/TTNNWorkaroundsPass.h
lib/Dialect/TTNN/IR/TTNNWorkaroundsPass.cpp
test/ttmlir/Dialect/TTNN/Transforms/Workarounds/reduction_ops_workaround.mlir

closes #3074 
TTNN reduction ops does not work correctly for integer inputs.
Add a workaround for reduction ops in case of integer inputs.

Data type workaround for reduction ops

---

.github/workflows/build-and-test.yml
runtime/tools/python/ttrt/common/run.py
test/python/golden/ccl_test/llmbox/test_ttir_ccl_ops_llmbox.py
test/python/golden/ccl_test/n300/test_ttir_ccl_ops_n300.py

closes #3092 
The CI pipeline currently does not execute any golden‐output verification tests, so regressions in operator calculations can slip through undetected. We recently ran into an issue that CI didn’t catch because no golden tests were being run on CI.
- Introduce a new test type 'golden that runs our hand-written golden verification testcases .
- Add additional multidevice golden testcases under `test/python/golden/ccl_tests` (generate with TTIRBuilder)

Add golden output verification to CI pipeline

---

lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
test/ttmlir/EmitC/TTNN/conv/conv_transpose2d.mlir
tools/ttnn-standalone/ttnn-precompiled.hpp

[Link to Github Issue](https://github.com/orgs/tenstorrent/projects/54/views/5?filterQuery=Emitc&pane=issue&itemId=94186922&issue=tenstorrent%7Ctt-mlir%7C1877)
Added a conversion for ConvTranspose2D in EmitC

[EmitC] Add TTNN to EmitC conversion for ConvTranspose2D

---

include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/OpModel/TTNN/MetalHeaders.h
lib/OpModel/TTNN/TTNNOpModelLib.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
test/unittests/OpModel/TTNN/OpModelFixture.h

PrepareConv2dWeightsOp has vary complex logic around calculating the resulting shape of the weights. This is dependent on the input memory config and Conv2dConfig params.
In order not to replicate this logic inside IR we call PrepareConv2dWeights with graph capture and read the resulting output TensorSpec.
* Add OpModel API to return output of prepared weights 
* Adjust conv2d constraint calls so that weights are prepared first

Create API for prepare conv2d weight output

---

include/ttmlir/Dialect/TTIR/IR/TTIROps.td
lib/Dialect/TTIR/IR/TTIROps.cpp

This op previously had incorrect memory semantics, it should have always been pure.  This op is only representational.

StreamLayoutOp should have Pure memory semantics

---

include/ttmlir/Dialect/TTNN/Analysis/OpConfig.h
include/ttmlir/Dialect/TTNN/IR/TTNNOpModelInterface.h
include/ttmlir/Dialect/TTNN/IR/TTNNOpModelInterface.td
include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
lib/Dialect/TTNN/Analysis/ShardSolver.cpp
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

#2441
Some important ops (e.g. conv2d, matmul) have op-sepcific config structs that greatly affect op performance/legality. The optimizer uses the `OpConfig` struct to generically encapsulate the output layout and these config structs. OpModel APIs (`getOpConstraints` and `getOpRuntime`) should accept these structs to allow easy sweeping.
To start, Conv2dConfig should be enabled end to end
- Closes #2441 
- Modify the OpModelInterface methods to accept an `OpConfig` struct in place of `TTNNLayoutAttr outputLayout`
- For all ops, read the output layout from the struct
- For conv2d, check if the config attribute has been set. If set, cast and pass it in. If not, read the op property (previous behaviour)
- Add unit tests to ensure Conv2dConfig is being passed all the way to the TTNN op
- …

Refactor OpModel APIs to take OpConfig instead of just output layout

---

include/ttmlir/Dialect/TTNN/Transforms/Workarounds/Decomposition/EmbeddingOpSqueezeWeightRewritePattern.h
lib/Dialect/TTIR/IR/TTIROps.cpp
lib/Dialect/TTNN/IR/TTNNOps.cpp
lib/Dialect/TTNN/Transforms/CMakeLists.txt
lib/Dialect/TTNN/Transforms/Workarounds/Decomposition/EmbeddingOpSqueezeWeightRewritePattern.cpp
lib/Dialect/TTNN/Transforms/Workarounds/TTNNWorkaroundsPatterns.cpp
test/ttmlir/Dialect/TTIR/embedding/embedding_negative.mlir
test/ttmlir/Dialect/TTNN/Transforms/Workarounds/embedding_weight_workaround.mlir
test/ttmlir/Silicon/TTNN/n150/embedding/embedding_6D_weight.mlir

https://github.com/tenstorrent/tt-mlir/issues/2845
Verification of EmbeddingOp was lacking in all departments in both dialects.
- Enhanced verification and added appropriate tests (input with a rank !=2 will not fail but it seems it doesn't produce meaningful result, I will have to check with TTNN folks)
- Added a workaround for >4D weight tensor (with leading 1s)

EmbeddingOp enhanced verification

---

CMakeLists.txt

N/A
With the merge of this PR https://github.com/tenstorrent/tt-mlir/pull/2687 warnings from StableHLO started to appear during compilation.
```
[507/689] Building CXX object python/CMakeFiles/TTMLIRPythonModules....chain/src/stablehlo/stablehlo/integrations/python/StablehloApi.cpp.o
In file included from /opt/ttmlir-toolchain/src/stablehlo/stablehlo/integrations/python/StablehloApi.cpp:16:
In file included from /opt/ttmlir-toolchain/src/stablehlo/stablehlo/integrations/python/StablehloApi.h:19:
In file included from /opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/nanobind/include/nanobind/nanobind.h:48:
/opt/ttmlir-toolchain/venv/lib/python3.10/site-packages/nanobind/include/nanobind/nb_types.h:182:64: warning: cast from 'const _object *' to '_object *' drops const qualifier …
```

Suppress third party build warnings

---

cmake/modules/TTMLIRVersion.cmake

N/A
When building in a forked repository, the version detection fails because git tags are not automatically fetched from the upstream repository. This causes the `git describe` command to fail with the error "No names found, cannot describe anything", resulting in an empty `GIT_TAG` variable.
```bash
fatal: No names found, cannot describe anything.
CMake Error at cmake/modules/TTMLIRVersion.cmake:27 (string):
string sub-command REGEX, mode MATCH needs at least 5 arguments total to
command.
Call Stack (most recent call first):
CMakeLists.txt:73 (include)
```
This PR fixes the issue by:
1. Adding a check for the existence of version tags locally using `git tag -l`
2. If no tags are found, explicitly fetching tags from the upstream repository using `git fetch --tags upstream`

Fix: Add tag fetching from upstream for forked repositories

---

include/ttmlir/Dialect/TTNN/Transforms/Passes.td
lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
lib/Dialect/TTNN/Transforms/CMakeLists.txt
lib/Dialect/TTNN/Transforms/TTNNOptimizeConv2d.cpp
lib/Dialect/TTNN/Transforms/TTNNPrepareConv2dWeights.cpp
test/ttmlir/Dialect/TTNN/optimizer/conv2d_config_override.mlir
test/ttmlir/Silicon/TTNN/n150/optimizer/prepare_conv2d_weights.mlir

[Link to Github Issue](https://github.com/issues/assigned?issue=tenstorrent%7Ctt-mlir%7C2636)
Each time the `ttnn.conv2d` operation is executed, it preprocesses the weights under the hood. This introduces significant performance overhead, as a lot of time is spent preparing the weights on the host and then copying them to the device.
To address this, instead of allowing `ttnn.conv2d` to implicitly prepare the weights each time, we’ve extracted a dedicated operation called `ttnn.prepare_conv2d_weights`. The idea is to insert this operation before every  `ttnn.conv2d` in the graph so that it can be consteval’d once consteval support is complete.
Introduced the `TTNNPrepareConv2dWeights` pass, which inserts `ttnn.prepare_conv2d_weights` before every `ttnn.conv2d` op in the graph.
When …

[TTNN] Introduce TTNNPrepareConv2dWeights pass

---

.github/actions/build-tt-mlir-action/action.yaml

CPM cache size is affecting our GitHub actions cache due to its size (over 600 Mb), which causes cache thrashing. Disabling this only for CI until we figure out another plan

Remove metal cpm cache

---

env/activate
include/ttmlir-c/TTKernelTypes.h
include/ttmlir/Conversion/TTKernelToEmitC/TTKernelToEmitC.h
include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
include/ttmlir/Dialect/TTKernel/IR/TTKernelOpsEnums.td
include/ttmlir/Dialect/TTKernel/IR/TTKernelOpsTypes.td
include/ttmlir/Target/TTKernel/TTKernelToCpp.h
lib/CAPI/TTKernelTypes.cpp
lib/Conversion/TTIRToTTKernel/CMakeLists.txt
lib/Conversion/TTIRToTTKernel/TTIRToTTKernel.cpp
lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
lib/Dialect/TTKernel/IR/TTKernelOps.cpp
lib/Target/TTKernel/CMakeLists.txt
lib/Target/TTKernel/TTKernelToCpp.cpp
lib/Target/TTKernel/TTKernelToCppRegistration.cpp
lib/Target/TTMetal/TTMetalToFlatbuffer.cpp
python/CMakeLists.txt
python/Passes.cpp
python/TTKernelModule.cpp
python/pykernel/ast.py
test/pykernel/eltwise_sfpu/eltwise_sfpu.py
test/pykernel/eltwise_sfpu/reader_unary.py
test/pykernel/eltwise_sfpu/writer_unary.py
test/ttmlir/Conversion/TTKernelToEmitC/ttkernel.mlir
test/ttmlir/Translate/TTKernel/ttkernel_compute.mlir
test/ttmlir/Translate/TTKernel/ttkernel_noc.mlir
tools/ttmlir-translate/ttmlir-translate.cpp

This change does a number of cleanups to the ttkernel to emitc flow including:
- Remove old/dead code paths for D2M emitc generation.
- Removal of some TTKernel ops and EmitC conversions that are no longer used.
- Cleanup of some emitc conversions.
- Support for MyXOp and MyYOp via new literal rewriter.
- Rename Tensix thread type to Compute to better align with tt-metal naming convention.
- Clear separation between EmitC dialect conversion and C++ translation, these two worlds are no longer mixed and matched.
- Tagging ttkernel thread type as a function attribute, which avoids the need to have separate function handlers or passing around an enum:
```mlir
func.func @ttkernel_compute(...) attributes {ttkernel.thread = #ttkernel.thread<compute>} {
```

TTKernel to EmitC to C++ refactor

---

lib/Conversion/StableHLOToTTIR/ShardyToTTIRPatterns.cpp
lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
test/ttmlir/Conversion/StableHLOToTTIR/ccl/ccl_ops_shardy.mlir

https://github.com/tenstorrent/tt-xla/issues/549
https://github.com/tenstorrent/tt-mlir/issues/3132
1. error: 'ttir.pooling' op expected type of operand #1 ('tensor<16x26x26x64xbf16>') to match type of corresponding result ('tensor<16x26x26x64xbf16, #tt.mesh_sharding<"mesh">>')
2.  Inconsistency found in TensorMeshShardingAttr : expected (#tt.mesh_sharding<"mesh", [ 8(1),  1]>) and current (#tt.mesh_sharding<"mesh">) are different.
This patch fix two bugs in parsing graph with Shardy. First, add missing tensor encoding and second relax check and let the following pass handles the issue.

Fix Shardy parsing related bugs

---

test/ttmlir/EmitC/TTNN/eltwise_binary/atan2.mlir
test/ttmlir/EmitC/TTNN/eltwise_binary/maximum.mlir
test/ttmlir/EmitC/TTNN/eltwise_binary/minimum.mlir
test/ttmlir/EmitC/TTNN/eltwise_binary/remainder.mlir
test/ttmlir/EmitC/TTNN/eltwise_binary/scatter.mlir
test/ttmlir/EmitC/TTNN/eltwise_unary/cbrt.mlir
test/ttmlir/EmitC/TTNN/tensor/permute.mlir

Closes https://github.com/tenstorrent/tt-mlir/issues/2508
Closes https://github.com/tenstorrent/tt-mlir/issues/2261
Closes https://github.com/tenstorrent/tt-mlir/issues/2713
These tests used to fail during runtime when you run them in a group.
\-

Enable `UNSUPPORTED` EmitC test

---

.github/workflows/wheel-build.yml

- Since dev branch with container was not on main, the latest tag was never updated. Now it will pull from the latest tag.
- Update to pull from "latest" tag.

Update to manylinux image to latest tag

---

docs/src/adding-an-op.md

program.cpp was renamed to program_executor.cpp (ad55294d8036eac2938d1e6b1da6ae0a9e4a371e @vwellsTT )
N/A
docs build failed because it couldn't find program.cpp

[docs] fix filename

---

include/ttmlir/Dialect/TTNN/Analysis/OpConfig.h
lib/Dialect/TTNN/Analysis/LegalLayoutAnalysis.cpp
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/Dialect/TTNN/Transforms/Optimizer.cpp

#2441 
#2979 addressed the functionality required for #2441, but introduced awkward and difficult to understand statements like `opConfig.config`.
The `OpConfig` struct represents a particular configuration of a TTNN Op for the purpose of the optimizer. It has two fields:
- `TTNNLayoutAttr outputLayout` representing a specific output tensor layout for the op
- `Attribute config` representing op-specific configuration structs (e.g. matmul or conv2d)
We should better distinguish between `OpConfig` and its field `config`.
- Rename `config` to `opSpecificAttr` so `opConfig.config` becomes `opConfig.opSpecificAttr`
The initial discussion in #2979 was centred around renaming `OpConfig` to `OpParams` or `TTNNOperationParams`. However, this would necessitate changing a large number of variables …

Rename OpConfig Field for Readability

---

include/ttmlir/Dialect/TTMetal/IR/CMakeLists.txt

Removed `TTMetalBaseAttrs` generation from `TTMetalOpsBaseAttrs.td` that doesn't exist.

Fix docs CI build

---

.github/workflows/pages.yml

Pages won't run if the `in-service` label
https://github.com/tenstorrent/tt-mlir/actions/runs/14783193228/job/41506428466

Remove inservice label in pages

---

include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
lib/Conversion/TTIRToTTKernel/TTIRToTTKernel.cpp
lib/Conversion/TTIRToTTKernel/TTIRToTTKernelPass.cpp
lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp
lib/Target/TTKernel/TTKernelToCpp.cpp
test/ttmlir/Conversion/TTIRToTTKernel/tiled_matmul.mlir

#2608 
Various follow on fixes for d2m backend. 
- Added DMA lowering address offsets from compile time buffer addresses 
- Added matmul init, fixed matmul syntax (transpose flag)
- Added matmul include to emitc lowering 
- Fixed insertion point for load lowering for ops with inits

D2M: Fix matmul and dma lowering issues

---

lib/Transforms/ConstEvalHoist.cpp
test/ttmlir/Dialect/TTNN/const-eval/const-eval.mlir

NA
@AleksKnezevic found a bug in const-eval during tt-torch testing.  In the case of `CreationOps`, we want to treat them specially s.t. not ever tensor creation is always const-eval'ed.  However, I was missing logic to properly treat the Values of a creationOp which has been merged into a subgraph as part of that subgraph w.r.t. merging other subgraphs.
Any creationOp added to a given subgraph also has the values it produces treated as part of this subgraph, s.t. proper merging occurs  when multiple subgraphs share a creationOp

Fix const-eval bug for case where subgraphs only share creation op

---

lib/Dialect/TTNN/IR/TTNNWorkaroundsPass.cpp
test/ttmlir/Dialect/TTNN/Transforms/Workarounds/add_integer_broadcasting_workaround.mlir

[#489](https://github.com/tenstorrent/tt-torch/issues/489) in tt-torch
TTNN currently fails to handle broadcasting for int32 inputs in the `add` op, which is used internally to represent `expand` operations. When an `expand` op with int32 is lowered to `add` with broadcasting, execution does not work as expected.
As a temporary workaround, inputs are converted to bfloat16 when shapes differ. This should be removed once TTNN properly supports broadcasting for int.

Add workaround for int broadcasting in 'Add' op

---

.github/workflows/build-and-test.yml
docs/src/ci.md
docs/src/ttrt.md
include/ttmlir/Dialect/TTNN/Transforms/Workarounds/Decomposition/ConcatOpReshapeRewritePattern.h
lib/Dialect/TTNN/Transforms/CMakeLists.txt
lib/Dialect/TTNN/Transforms/Workarounds/Decomposition/ConcatOpReshapeRewritePattern.cpp
lib/Dialect/TTNN/Transforms/Workarounds/TTNNWorkaroundsPatterns.cpp
runtime/include/tt/runtime/types.h
runtime/lib/ttnn/include/tt/runtime/ttnn/debug_apis.h
runtime/lib/ttnn/runtime.cpp
runtime/test/python/ttnn/multi_device/test_data_parallel.py
runtime/test/python/ttnn/multi_device/test_input_deallocate.py
runtime/test/python/ttnn/utils.py
runtime/tools/python/test/test_run.py
runtime/tools/python/ttrt/common/run.py
runtime/tools/python/ttrt/runtime/module.cpp
test/python/op_by_op_infra/test_mlir_module_executor.py
test/python/op_by_op_infra/test_op_by_op_workflows.py
test/ttmlir/Dialect/TTNN/Transforms/Workarounds/concat_workaround.mlir
test/ttmlir/Silicon/StableHLO/n150/Binary/concat_op.mlir
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 3fbf1875cf87cdb4de7ecebc5b687c27ef49f13f
- Skip op by op tests failing due to hardcoded system desc after metal commit 0913688335
- Remove device async mode after metal commit 047802
- Remove MULTI_DEVICE storage type after removed from metal in metal change 861d26f
- Add workaround for concat op after metal change aa7b4fb

Uplift third_party/tt-metal to 3fbf1875cf87cdb4de7ecebc5b687c27ef49f13f 2025-04-29

---

include/ttmlir/OpModel/TTNN/SingletonDeviceContext.h
lib/CMakeLists.txt
lib/Dialect/TTNN/Analysis/CMakeLists.txt
lib/Dialect/TTNN/Transforms/TTNNPrepareConv2dWeights.cpp
lib/OpModel/TTNN/CMakeLists.txt
lib/OpModel/TTNN/SingletonDeviceContext.cpp

Related: https://github.com/tenstorrent/tt-forge-fe/issues/1597
In order to enable optimizer in benchmark tests FFE build of tt-mlir needs to set `TTMLIR_ENABLE_OPMODEL=ON`.
* Explicitly close device after opmodel constraint calls
* Set install RPATH for TTMLIRCompiler target

Enable FFE build with OPMODEL

---

docs/src/overview.md
include/ttmlir/Conversion/Passes.td
include/ttmlir/Dialect/TTIR/IR/TTIROps.td
include/ttmlir/Dialect/TTIR/Transforms/Passes.td
include/ttmlir/Transforms/Passes.td

https://github.com/tenstorrent/tt-mlir/pull/3102
After https://github.com/tenstorrent/tt-mlir/pull/3102, some documentation became stale.
- Updated documentation to reflect the current state.
- Fixed few parentheses match issues that I found the tablegen files

Remove elementwise `operandSegmenetSizes` from docs

---

lib/Dialect/TTNN/IR/TTNNWorkaroundsPass.cpp

Related: #3154 
WhereOp gives all zeros when ran using int32 datatype.
Added a workaround to cast both the predicate and the inputs to bfloat16 using the workarounds pass.

Add a workaround to perform WhereOp in float32

---

include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
test/ttmlir/Dialect/TTNN/fusing/resnet_pattern_fusing.mlir

When trying to uplift FFE it seems that fusing is triggering some code paths in metal which are untested, and we are getting asserts. Disable fusing by default to unblock FFE uplift. This is hotfix change.

Disable fusing pass by default

---

lib/Dialect/TTNN/Transforms/CMakeLists.txt

FFE build with optimizer TTMLIR_ENABLE_OPMODEL definition in order to properly close device.
* Add `TTMLIR_ENABLE_OPMODEL` to `MLIRTTNNTransforms`

Add opmodel definition for MLIRTTNNTransforms

---

test/python/golden/lit.local.cfg
test/python/lit.local.cfg
test/python/op_by_op_infra/lit.cfg.py
test/unittests/lit.cfg.py

Fix warning from `llvm-lit` when running `cmake --build build -- check-ttmlir`:
```
llvm-lit: /localdev/mtopalovic/src/tt-mlir/env/build/llvm-project-prefix/src/llvm-project/llvm/utils/lit/lit/discovery.py:184: warning: standalone_tests set in LIT config but suffixes or excludes are also set
llvm-lit: /localdev/mtopalovic/src/tt-mlir/env/build/llvm-project-prefix/src/llvm-project/llvm/utils/lit/lit/discovery.py:250: warning: test suite '<unnamed>' contained no tests
```
`test/python/op_by_op_infra` and `test/python/golden` are not run using `llvm-lit`. In CI we are using `pytest` to run these tests. Regardless llvm-lit searches for tests in these directories and reports warnings. This PR explicitly excludes this directories in top level config file.

Fix llvm-lit warnings

---

tools/explorer/tt_adapter/src/tt_adapter/main.py
tools/explorer/tt_adapter/src/tt_adapter/mlir.py

Change the graph id, so it is based on the file name instead of the hard coded `tt-graph`.
Resolves: https://github.com/tenstorrent/model-explorer/issues/37, https://github.com/tenstorrent/model-explorer/issues/43
Relates to: https://github.com/tenstorrent/model-explorer/pull/44

[tt-explorer] Update graph id to be based on the file name

---

include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td

Mark ttkernel.get_compile_time_arg_val op as Pure
This will enable to get rid of the duplicates of this op with the help of CSE pass. Also, it will enable hoisting out of this op to the top.

Mark ttkernel.get_compile_time_arg_val op as Pure

---

lib/Dialect/TTMetal/IR/TTMetalOps.cpp

Update ttmetal.enqueue_program_op verifier to remove a check that ensures that the number of buffer operands and the cb operands are equal.
Update ttmetal.enqueue_program_op verifier to remove a check that ensures that the number of buffer operands and the cb operands are equal. This condition need not be always true. e.g. a compute kernel might only read and write to circular buffers and do not depend on any global buffer.

Update ttmetal.enqueue_program_op verifier

---

include/ttmlir/Dialect/TTNN/Transforms/Workarounds/Decomposition/ConcatOpReshapeRewritePattern.h
lib/Dialect/TTNN/Transforms/Workarounds/Decomposition/ConcatOpReshapeRewritePattern.cpp
test/ttmlir/Dialect/TTNN/Transforms/Workarounds/concat_workaround.mlir
test/ttmlir/Silicon/StableHLO/n150/Binary/concat_op.mlir

[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/3193)
Concat op is failing for following two cases. 
1. If all input tensors have shape of [1, 1] or [1, 1, 1] and concat is performed on last dimension then the generated output is incorrect. The first element of the output is correct while all other elements are zero. 
2. The second case is extension of the first one if any tensor's last dim is not `1` (but not for all tensors) then it crashes with `TT_FATAL` error. For example we want to concatenate 3 tensors and the shapes are [1, 32], [1, 2], [1, 1] then this will crash.
Add one additional dimension to all the input tensor (using reshape) for the cases described above so that concatenation is not applied on the last dim of the input tensor. After concatenation; …

Add workaround for concat op

---

.github/workflows/issue-last-updated.yml

Updated GitHub workflow token from ISSUE_TOKEN to GH_SECRET_PROJECTS. This change is needed to use the new token for calls in the issue last updated workflow.

Use GH_SECRET_PROJECTS token

---

tools/ttnn-standalone/ttnn-precompiled.hpp

N/A
- Accidental inclusion of `cpp` instead of `hpp`
- Updated `DeviceGetter` to better reflect the current situation with TTNN device(s), as some parts were out of place

Fix `ttnn-precompiled.hpp`

---

include/ttmlir/OpModel/TTNN/Conversion.h
lib/OpModel/TTNN/Conversion.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Conversion/TestConversion.cpp

#3082
The optimizer sweeps a large space of `TTNNLayoutAttr`s to discover legal layouts for ops. Some of these `TTNNLayoutAttr`s are not valid `TensorSpec`s at all. It would be preferable to detect these early rather than waiting for the op execution to fail during the `getOpConstraints` call.
- Frontload the calls to `TensorSpec` methods needed during `allocate_device_tensor` so validation happens prior to setting up the rest of the `query_op_constraints` infrastructure
- Create a new `conversions::validateTensorSpec` function that includes both previous and new checks
- Refactor the `TTNNLayoutAttr` -> `TensorSpec` conversion wrapper to:
- call the new validation function
- get rid of complicated templating that was used for batch conversions (no longer needed)
- Closes #3082

[Optimizer] Perform Additional Validation on TensorSpecs While Looking for Valid TTNNLayoutAttrs

---

runtime/tools/python/ttrt/common/callback.py
runtime/tools/python/ttrt/common/run.py
runtime/tools/python/ttrt/common/util.py

https://github.com/tenstorrent/tt-mlir/issues/3210
closes #3210
Moving get_atol_rtol_pcc from callback.py to util.py left it calling logging.debug(…) without the logging symbol in scope.
When a numerical check triggers that debug branch (e.g., tensors containing NaNs), the function raises
```
NameError: name 'logging' is not defined
```
Added a required logger parameter to get_atol_rtol_pcc; removed implicit logging reference.
Passes the active logger when invoking get_atol_rtol_pcc.

Pass logger instance explicitly into get_atol_rtol_pcc to fix NameError (#3210)

---

tools/explorer/tt_adapter/src/tt_adapter/mlir.py

- PR closes #3128 
- Locally generated MLIR module was used, with no explicit locations defined. The `regex` didn't catch these cases resulting in no actual perf data being sent up.
- Use only full locations to resolve the overlay information instead of relying on the regex function to match against the named_location.

Fix Explorer Overlay Op Resolution to use Full Locations

---

cmake/modules/TTMLIRVersion.cmake

N/A
When forking a repository using `gh repo fork`, the upstream remote is automatically configured. However, when forking through other methods, the upstream remote needs to be manually set.
This commit check if upstream remote exists, then adds it automatically if not configured.

Add automatic upstream remote configuration for version tags

---

.github/workflows/on-pr.yml
.github/workflows/on-push.yml

Require that pre-commit and spdx first pass before building and testing. This will ensure these issues are fixed before triggering an expensive build
(Precommit issue that skipped build)
https://github.com/tenstorrent/tt-mlir/actions/runs/14872018616/job/41762181257?pr=3236

Skip Build test if pre-commit or spdx fails

---

runtime/tools/python/ttrt/common/perf.py
tools/explorer/tt_adapter/src/tt_adapter/mlir.py

Closes #2981 
`ttrt perf` omits locations for some ops when generating `ops_perf_results.csv`, which is caused by bad parsing of loc's in `tracy_ops_data.csv`.
This problem results in perf data not being properly loaded in the explorer.
- Added a fix in `perf.py` for proper parsing of locations in `tracy_ops_data.csv`
- Added an assert in model explorer (`mlir.py`) to prevent incorrect perf data to be loaded in the future

Fix loc parsing in ttrt perf

---

include/ttmlir/OpModel/TTNN/SingletonDeviceContext.h
lib/OpModel/TTNN/SingletonDeviceContext.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
runtime/lib/ttnn/runtime.cpp
third_party/CMakeLists.txt
tools/ttnn-standalone/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 1a9bf1ab81550daf2031b928e7152aabf1396260
- Remove reference to raise_unsupported_storage removed in tt-metal 6f3458e
- Replace references to IDevice with MeshDevice and increase traceregionsize after metal commit ebbdb91397
- Update xtensor lib include paths after metal commit 458187359b
- Temporarily using `file(GLOB ...)` to find xtensor include path, since local and CI resolve to different include paths.

Uplift third_party/tt-metal to 1a9bf1ab81550daf2031b928e7152aabf1396260 2025-05-02

---

lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp
test/ttmlir/Conversion/TTIRToTTMetal/decomposable_lowering_dot_general.mlir
test/ttmlir/Conversion/TTIRToTTMetal/decomposable_lowering_gather.mlir
test/ttmlir/Conversion/TTIRToTTMetal/decomposable_lowering_reduce_or.mlir

Closes #3038
Do the TTIR decomposition pass in the D2M pipeline as well
Only `dot_general` -> `matmul` lowering with 2D multiples-of-32 tiles is actually tested, higher dimensions require #3027 and/or #3025
The `gather` -> `embedding` test depends on #3024 and so is disabled for now
The `reduce_or` -> `sum` tests are causing hangs/crashes depending on input shapes, so they are disabled as well

Add TTIRToTTIRDecomposition pass to metal pipeline

---

include/ttmlir/Dialect/TTNN/Transforms/Passes.td

I made a typo in the documentation for `PrepareConv2dWeights`, where I wrote `DTTMLIR_ENABLE_OP_MODEL` as the name of the flag instead of the correct `DTTMLIR_ENABLE_OPMODEL`.

Fix a typo in the documentation for the PrepareConv2dWeights pass

---

lib/Target/TTKernel/TTKernelToCpp.cpp

When translating to C++ we clone the kernel function into its own module, but never free the new module. This fix erases the module after translation.
Closes #1567

Fix asan detected memory leak #1567

---

include/ttmlir/Dialect/TTNN/Transforms/Workarounds/Decomposition/ReduceOpsRewritePattern.h
lib/Dialect/TTNN/Transforms/Workarounds/TTNNWorkaroundsPatterns.cpp
test/ttmlir/Dialect/TTNN/Transforms/Workarounds/reduction_ops_workaround.mlir
test/ttmlir/Dialect/TTNN/reduction/simple_max.mlir
test/ttmlir/Dialect/TTNN/reduction/simple_reduce_min.mlir
test/ttmlir/Silicon/StableHLO/n150/reduction/reduce_maximum_op.mlir
test/ttmlir/Silicon/StableHLO/n150/reduction/reduce_min_op.mlir
test/ttmlir/Silicon/TTNN/n150/perf/test_perf_reduce_min.mlir
test/ttmlir/Silicon/TTNN/n150/simple_max.mlir
test/ttmlir/Silicon/TTNN/n150/simple_reduce_min.mlir

There is a bug in metal ( https://github.com/tenstorrent/tt-metal/issues/21615 ) where max reduction with all negative inputs erroneously returns zero instead of the real maximum in cases where the dimension is not divisible by 32. This is hit in some model tests from tt-xla.
Same failure mode is observed for min and all positive inputs.
I added a TTNN workaround to pad the input tensor with the neutral element for reduction in cases where the input has reduction dimensions that aren't a multiple of 32.

Workaround for max and min reductions when dimensions are not multiple of 32

---

.gitignore
include/ttmlir/Dialect/TTNN/Transforms/Passes.td
lib/Dialect/TTNN/Transforms/Passes.cpp
test/ttmlir/Dialect/EmitC/func_name_collision.mlir
test/ttmlir/Dialect/EmitC/ttir_to_emitc_pipeline_sanity.mlir
test/ttmlir/Dialect/TTNN/Transforms/ttnn_create_input_gens_0.mlir
tools/ttnn-standalone/ttnn-standalone.cpp

https://github.com/tenstorrent/tt-mlir/issues/3240
`TTNNCreateInputGenerators` creates `main` and `createInputsFor_${funcName}`. If one of the existing module functions have the same name, it will cause a name collision and module's symbol table will report a following error during verification
```
error: redefinition of symbol named '${funcName}'
```
- prepended a `_` to all existing functions to avoid name collision (namespaces would be a better idea in C++, but that would require major refactoring of the pass pipeline; if someone has a better idea, please let me know)
- decided to refactor the whole `TTNNCreateInputGenerators`, which I'm sure will make extending the generation of inputs to different creation functions a much easier task in the future

[EmitC] Fix function name collision

---

runtime/include/tt/runtime/detail/common.h
runtime/include/tt/runtime/utils.h

Header file that is exposed to the frontends (`runtime/include/tt/runtime/utils.h`) now includes `tt/runtime/detail/flatbuffer_operator_ostream.h`, which is not, causing uplifts to fail. This PR fixes that.

Fixing header linking for frontend uplift

---

include/ttmlir/Support/Logger.h
lib/Dialect/TTNN/Analysis/ShardSolver.cpp
test/unittests/Support/LoggerTest.cpp

The original macro defs required awkward workaround when logging messages without format args, e.g.
```cpp
TTMLIR_TRACE(ttmlir::LogComponent::Optimizer, "{}",
"ShardSolver::resolveStep: returning true");
```
Needing to use "{}" above is unconventional/surprising. 
The original macro def expanded into malformed syntax because of the trailing comma in
```cpp
OS << "] " << llvm::formatv(fmt, __VA_ARGS__) << "\n";
```
I've changed the definition to pass `fmt` implicitly, as part of `__VA_ARGS__`.  Also added comment prefix for `...` to explain usage/signature. I've been using this version in an ongoing PR and it is working fine.

fold 'fmt' into the va args block for TTMLIR_DEBUG-like macros

---

.github/CODEOWNERS

N/A
N/A
@staylorTT has added [mlir teams](https://github.com/orgs/tenstorrent/teams/forge/teams) within the github tenstorrent org - these are all the teams prefixed with `forge-developers-mlir-`. This PR changes CODEOWNERS to use teams instead of personal aliases, where possible.
This change will make it easier to track which groups of people are needed to review PRs.
Let's keep a working list of teams here so that folks can edit - when we're ready, we'll then update the teams in github and mark this PR as ready. Comment on the CODEOWNERS file as well where needed, and please let me know if we need to add/remove some teams, and @staylorTT will happily jump in to lend a hand :)
List of teams:
- forge-developers-mlir-build - @nsmithtt @mtopalovicTT @vwellsTT
- forge-developers-mlir-core - …

Swap personal in favor of team aliases

---

include/ttmlir/Conversion/StableHLOToTTIR/ShardingUtils.h
lib/Conversion/StableHLOToTTIR/ShardingUtils.cpp
lib/Conversion/StableHLOToTTIR/ShardyToTTIRPatterns.cpp

https://github.com/tenstorrent/tt-mlir/issues/3130
Current code restrict sdy mesh to be size of 2d, which may hurt user experience of using JAX with our hardware.
This patch allows sdy mesh to be either empty or 1d.

Adjust empty and single sdy mesh shape

---

docs/src/ttrt.md
runtime/tools/ttrt/ttrt/__init__.py

Relaunch ttrt inside of gdb automatically with:
```
ttrt --gdb run ...
```

Add gdb support to ttrt

---

include/ttmlir/Dialect/TTMetal/IR/TTMetalOps.td
lib/Conversion/TTIRToTTMetal/TTIRToTTMetal.cpp
lib/Target/TTMetal/TTMetalToFlatbuffer.cpp
test/ttmlir/Silicon/TTMetal/n150/simple_add.mlir

NA
When transferring a buffer from device to host, we ought to barrier to ensure queued commands complete before moving the data.
Whenever we generate an enqueue_buffer_read op, we also enqueue a finish op to barrier right afterwards.  In the future, we should insert a targeted wait op instead and only await whichever ops we strictly depend on, but this seems like an easy first step.

Add finish barrier after any enqueue_buffer_read ops to ensure sync

---

env/activate
env/activate.fish
runtime/tools/ttrt/setup.py
third_party/CMakeLists.txt
tools/ttnn-standalone/CMakeLists.txt

#3279
Compiling ttnn-standalone and running `tracy` results in errors. Upon debugging, it looks like tracy expects `tt-metal` dir to have a `build` dir. However, we're using cmake's `ExternalProject_Add`, which will by default create a `tt-metal-build` dir.
Explicitly set build dir path in `ExternalProject_Add` command for  tt-metal, so that it changes from:
`third_party/tt-metal/src/tt-metal-build`
to
`third_party/tt-metal/src/tt-metal/build`
With this (and a follow-up fix), tracy works for ttnn-standalone.

Fix tt-metal build dir path for tracy to work

---

runtime/include/tt/runtime/detail/test/ttnn/utils.h
runtime/include/tt/runtime/detail/ttmetal/ttmetal.h
runtime/include/tt/runtime/detail/ttnn/debug_apis.h
runtime/include/tt/runtime/detail/ttnn/program_executor.h
runtime/include/tt/runtime/test/ttnn/dylib.h
runtime/include/tt/runtime/types.h
runtime/lib/ttmetal/runtime.cpp
runtime/lib/ttnn/debug/debug_apis.cpp
runtime/lib/ttnn/operations/CMakeLists.txt
runtime/lib/ttnn/operations/cache/load_cached.cpp
runtime/lib/ttnn/program_executor.cpp
runtime/lib/ttnn/runtime.cpp
runtime/lib/ttnn/utils/utils.cpp
runtime/test/ttnn/CMakeLists.txt
runtime/test/ttnn/dylib.cpp
runtime/test/ttnn/utils.cpp
runtime/tools/ttrt/ttrt/runtime/module.cpp
test/ttmlir/EmitC/TTNN/conv/conv2d_with_prepare_conv2d_weights.mlir
test/ttmlir/EmitC/TTNN/conv/prepare_conv2d_weights.mlir
test/ttmlir/Silicon/TTNN/n150/conv/prepare_conv2d_weights/simple_prepare_conv2d_weights.mlir

Closes #3247 
Closes #3254 
* `detail/test/ttnn/dylib.h` is now a public emitC header thus moving it out of detail
* TensorDesc `volume` and `size` APIs should use int64_t to prevent overflow and also be compatible with torch data types. 
* I didn't update the member variable data types because that would cause inconsistency with runtime APIs as well as TTNN APIs (TTNN uses uint32_t for shape, stride etc.)
* We weren't comparing expected vs actual tensor location in runtime debug mode.
* Renamed `detail/test/ttnn/dylib.h` as `test/ttnn/dylib.h`
* Updated tensor descriptor API return types
* Added storage comparison when running in runtime debug mode. 
* Updated prepare_conv2d_weights tests because the output tensor location was set incorrectly in the tests.
Misc
* Renamed …

Update TensorDesc APIs to int64_t, move dylib out of detail, compare storage in debug mode

---

include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
lib/Conversion/TTIRToTTKernel/TTIRToTTKernel.cpp
lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
test/ttmlir/Conversion/TTIRToTTKernel/tiled_matmul.mlir

#3230 
We incorrectly used `mm_init` for matmul lowering and were missing `mm_init_short`.
- Add `mm_init_short` op
- Insert `mm_init_short` instead of `mm_init` inside loops 
- Insert `mm_init` at the earliest possible position in the kernel, outside of the loops

D2M: Add mm_init_short and reposition init/init_short for matmul

---

include/ttmlir/Dialect/TTIR/IR/TTIROps.td
include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
lib/Dialect/TTIR/Transforms/TTIRFusing.cpp
lib/Transforms/ConstEvalHoist.cpp
test/ttmlir/Dialect/TTIR/fusing/conv2d_multiply_commute.mlir
test/ttmlir/Dialect/TTNN/const-eval/const-eval.mlir

* Previously constant op in TTNN was not tagged with CreationOp trait. This PR adds tag for constant op and reconstructs creation ops in TTNN to have similar strucutre to TTIR equivalents.
* Fixed bug when return op was pulled in for hoisting. This can happen if whole graph can be const evaled.
* Removed constant for commuting conv2d and multiply to function arguments only.
* Added test for both commuting creation ops in conv2d+multiply commute and const evaling creation ops.
closes #3180

Hoist constant op in TTNN

---

.github/build-docker-images.sh
.github/workflows/build-and-test.yml

- Fixed the issue where the latest tag would overwrite the original docker tag. Now, it appends the newest tag and perverse the original tag. This had a chance of causing cache thrashing for other PRs when merged to the main.
- Added configured to load shed n150 runners (need to wait for capacity from GHA infra team)
https://github.com/tenstorrent/tt-mlir/actions/runs/14842530718/job/41761015424#step:3:18

docker habor pull through cache and preserve original docker tag

---

runtime/include/tt/runtime/detail/ttnn/ttnn.h
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the ccfdebb197663efa8b85cc5ec0d83f30c174e0c9
- Update host_buffer header include after metal change 9f2d64d6e1

Uplift third_party/tt-metal to ccfdebb197663efa8b85cc5ec0d83f30c174e0c9 2025-05-13

---

cmake/modules/CMakeLists.txt

TT dialect transform passes and tt-kernel-to-emitc conversion passes are added to the set of targets to export.
Currently, the downstream projects of tt-mlir can't register `-tt-register-device` and `convert-ttkernel-to-emitc` passes.
Two additional CMake targets are added to the set of exported targets - TTMLIRTTKernelToEmitC and MLIRTTTransforms.

Export TTMLIRTTKernelToEmitC and MLIRTTTransforms

---

.github/workflows/build-and-test.yml

The "Download build artifacts" job step had a poorly defined "if" clause which resulted in the step always getting triggered.
Upon fixing the condition and it working as intended by the clause, all of the tests failed ([workflow preview](https://github.com/tenstorrent/tt-mlir/actions/runs/14991074320)) because they actually require the step to get executed. 
In the end I just removed the condition so that it is obvious that we always want it to run.
Workflow's behaviour hasn't changed.
Tests are still passing [workflow](https://github.com/tenstorrent/tt-mlir/actions/runs/14993789564)

Build-and-test workflow's logic fix

---

.github/workflows/macos-build.yml
docs/src/getting-started.md

Some macos builds are timing out at 6 hours.  Locally I have to set this cmake flag to avoid IO thrashing and kernel slowdown.  I speculate the same could be happening here so going to try this fix.

Fix macos build timeout

---

lib/Conversion/TTIRToTTKernel/TTIRToTTKernel.cpp
test/ttmlir/Conversion/TTIRToTTKernel/copy_tile_guards.mlir

#3229 
We use `copy_tile` to load partials from the output cb into dst for further accumulation. Right now, we copy on every iteration of the inner loop, but this causes us to copy garbage data on the first iteration.
Check for loop variables that DO NOT participate in the calculation of the copy tile CB index. We then need to check that these variables `!= 0` when we run our `copy_tile` instructions, as these are the circumstances where we are copying garbage data. 
Use these found loop variables are insert an if block around the `copy_tile_init` & `copy_tile` to prevent this copy on the first iteration.

D2M: Add copy_tile guards for ops that require spill/reloading partials to/from dst

---

runtime/lib/ttnn/runtime.cpp

NA
LoadCached op is missing from `getOpOutputTensor` callbacks.
Add LoadCachedOp to set of ops which aren't supported (because it returns arbitrary number of tensors, and this callback expects an op to return a single tensor).

bugfix const-eval loadcached op for getOutputCallback

---

.github/workflows/build-and-test.yml
third_party/CMakeLists.txt
tools/scripts/filter-compile-commands.py
tools/ttnn-standalone/ttnn-precompiled.hpp
tools/ttnn-standalone/ttnn-standalone.cpp

N/A
As @vvukomanTT was adding CI test for ttnn-standalone, he realized the default example broke on main with a recent metal uplift.
Remove `IDevice*` in favor of `MeshDevice*` and regenerate the example C++.

fix ttnn-standalone

---

lib/Dialect/TTNN/Analysis/LegalLayoutAnalysis.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
runtime/lib/ttnn/debug/debug_apis.cpp
runtime/lib/ttnn/operations/ccl/collective_permute.cpp
runtime/lib/ttnn/operations/eltwise/binary/binary_composite.cpp
runtime/lib/ttnn/operations/kv_cache/update_cache.cpp
runtime/lib/ttnn/operations/utils/utils.cpp
runtime/lib/ttnn/runtime.cpp
runtime/lib/ttnn/types/types.cpp
runtime/lib/ttnn/utils/utils.cpp
runtime/test/ttnn/dylib.cpp
third_party/CMakeLists.txt
tools/ttnn-standalone/CMakeLists.txt
tools/ttnn-standalone/ttnn-precompiled.hpp

This PR uplifts the third_party/tt-metal to the 1a58dca1c570bc38bdef6b728b692ee4e8c34a55
- Update Tensor getters after metal change 11cedac
- Include paths for new ttnn core and api components after metal change 89cf9e2

Uplift third_party/tt-metal to 1a58dca1c570bc38bdef6b728b692ee4e8c34a55 2025-05-15

---

include/ttmlir/Dialect/TTNN/IR/TTNNOpsAttrs.td
lib/Dialect/TTIR/Transforms/TTIRFusing.cpp
lib/Dialect/TTNN/Analysis/LegalLayoutAnalysis.cpp
lib/Dialect/TTNN/IR/TTNNOpsAttrs.cpp
lib/Dialect/TTNN/Transforms/TTNNFusing.cpp
test/ttmlir/Silicon/TTNN/n150/fusing/resnet_pattern_fusing.mlir
test/ttmlir/Silicon/TTNN/n150/fusing/softmax_fusing.mlir

We found couple of issues with fusing while testing resnet. Below is first batch of fixes. Second batch should only contain layout changes and moving conv2d to workarounds.
* Address second bullet from #3308 as well as aligns `Conv2dConfigParams` constructor with `Conv2dConfig` from metal because we didn't represent well `shard_layout` which should be `optional<TensorMemoryLayout>` and `reallocate_halo_output` should be true.
* On optimizer side when applying conv2d config overrides we need to merge them with conv2d config on op - previously we ignored conv2d config from op when applying overrides which lead to some settings being overriden.
* Fix locations of ops which are created by fusing.

Different fixes for fusing

---

docs/src/tt-explorer-usage-api.md
tools/explorer/CMakeLists.txt
tools/explorer/test/run_tests.py
tools/explorer/tt_adapter/src/tt_adapter/main.py
tools/explorer/tt_adapter/src/tt_adapter/mlir.py
tools/explorer/tt_adapter/src/tt_adapter/runner.py

- PR closes #3241 (backend side)
- Need to generate EmitC code for further testing and analysis and optimization space by hand.
- Added options to hook into FE changes and produce `.cpp` code using Compiler passes and return for FE to process in Explorer.
- TODO: Add support for using the `--emitc` flag with `ttrt perf`.

Added Backend changes to generate C++ code

---

include/ttmlir/Target/TTMetal/command.fbs
include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
lib/Target/TTMetal/TTMetalToFlatbuffer.cpp
runtime/lib/ttmetal/executor.cpp

Closes #3022 
`ttir.constant` is lowered to `memref.global`/`memref.get_global`. It needs to be further lowered to TTMetal command to allocate the memory and load its content from `ttm` Flatbuffers.
- Extend `HostAllocCommand` with `data` field containing constant bytes
- Emit `HostAllocCommand` for `memref.get_global`

D2M: ttir.constant -> memref.get_global -> HostAllocCommand

---

lib/Dialect/TT/IR/TTOpsTypes.cpp
lib/Target/TTMetal/TTMetalToFlatbuffer.cpp
runtime/include/tt/runtime/utils.h
runtime/lib/ttmetal/executor.cpp

To simplify buffer memory management always align up allocation size on a tile of corresponding elements.

D2M: Align up allocation size on tile

---

tools/CMakeLists.txt

Closes #3393
When `DTTMLIR_ENABLE_BINDINGS_PYTHON=OFF`, various tools would cause build failures.
Inclusion of the subdirs the problem tools live in has been guarded against the bindings being disabled

Guard misc `tools/` against disabled bindings

---

include/ttmlir/Dialect/TTIR/IR/TTIROps.td
lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
test/ttmlir/Conversion/StableHLOToTTIR/conv_transpose2d_op.mlir
test/ttmlir/Dialect/TTIR/Decomposition/conv_transpose2d_decomposition.mlir
test/ttmlir/Silicon/StableHLO/n150/conv_transpose2d_op.mlir

closes #3267 
Stablehlo has `convolution` op which is used for both `conv2d` and `conv_transpose2d` op.
Currently, `stablehlo.convolution` is lowered to `ttir.convolution` and
then always decomposed to `ttir.conv2d` op (TTIRToTTIRDecomposition pass).
This results in incorrect lowering of `conv_transpose2d` to `conv2d` op. 
Lower `ttir.convolution` to either `ttir.conv2d` or `ttir.conv_transpose2d` op in TTIRToTTIRDecomposition pass.

conv2d_transpose

---

third_party/CMakeLists.txt
tools/ttnn-standalone/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 0176b3bea0d4d4f0d296d73870e545a69c48a551
- Update reflect include after updated in metal commit 4fd0c68e1c

Uplift third_party/tt-metal to 0176b3bea0d4d4f0d296d73870e545a69c48a551 2025-05-16

---

include/ttmlir/Dialect/StableHLO/Transforms/Passes.td
lib/Dialect/StableHLO/Pipelines/StableHLOPipelines.cpp
lib/Dialect/StableHLO/Transforms/ShardyAutomaticParallelization.cpp

This PR introduces a new pass
```
- update-automatic-shard-shapes
```
It does not split any shapes during the `shardy-wrap-manual-computation` pass. This is to further separate the passes for debug ability as well as be a stepping stone for being able to convert sharding constraints into reshards and into collectives (https://github.com/tenstorrent/tt-mlir/issues/3288)
The sequence of passes in `automatic-sharding-pipeline` is as follows
```
createInlinerPass
createTTPopulateArgumentTypes
createShardyAnnotateArgumentsPass
createAggressivePropagationPass
createShardyWrapManualComputationPass
createUpdateAutomaticShardShapesPass
createCloseShardingsPass
createCanonicalizerPass
```

#3380: Refactor manual computation pass and add in a new update shard shape pass for automatic parallelization via shardy.

---

include/ttmlir/Target/TTNN/utils.h
include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
lib/Target/TTNN/TTNNToFlatbuffer.cpp

This fixes the namespace ordering from `tt::mlir` to `mlir::tt`.

Fix namespace order ttmlir/Target/TTNN/utils.h

---

test/unittests/Optimizer/TestGreedyL1InterleavedPolicy.cpp
test/unittests/Optimizer/TestLayoutAnalysis.cpp
test/unittests/Optimizer/TestOptimizerOverrides.cpp
test/unittests/Optimizer/TestShardSolver.cpp
test/unittests/Support/LoggerTest.cpp
test/unittests/TestScheduler/TestScheduler.cpp

We use llvm cmake macro's to link against their included version of gtest, ensure the headers pickup the llvm version explicitly in the case when there might be a system gtest installation also present.

Ensure link against llvm gtest

---

test/python/golden/test_ttir_ops_llmbox.py
test/python/golden/test_ttir_ops_n300.py

https://github.com/tenstorrent/tt-mlir/issues/3410
closes #3410
The recent uplift brought in a tt-metal commit that fixes an execution issue with shapes whose dimensions are not multiples of the tile size.
To validate this fix, we added TTIR-builder test cases and run them in CI to ensure the improvement is preserved going forward.
- Added new TTIR-builder tests for n300 and llmbox.
- Marked several tests as run_error or fails_golden because of additional issues that still need to be addressed (see #3410).

Add more testcases with shapes not a multiple of tilesize

---

include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
include/ttmlir/Dialect/TT/Transforms/Passes.td
include/ttmlir/Dialect/TT/Transforms/Transforms.h
include/ttmlir/Dialect/TTMetal/Pipelines/TTMetalPipelines.h
include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
include/ttmlir/Dialect/TTNN/Utils/PassOverrides.h
lib/Dialect/TT/IR/TTOpsTypes.cpp
lib/Dialect/TT/Transforms/TTRegisterDevice.cpp
lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp
lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp

This change cleans up the naming and creation of system descriptors via the mock arch enum path.  It also plumbs it through backend pipeline options.

tt-register device mock system desc arg CLI cleanup

---

.github/workflows/build-and-test.yml
test/python/golden/test_ttir_llama_1x2_tp.py

https://github.com/tenstorrent/tt-mlir/issues/3414
- Added a new ttir_builder test case for the Llama model manually sharded on a (1, 2) mesh targeting the N300 device.  
- The model is divided into two sub-graphs; each sub-graph is compiled and compared against golden outputs to avoid precision mismatches.

Add manually sharded llama block builder test for n300

---

lib/Conversion/TTIRToTTKernel/TTIRToTTKernel.cpp
test/ttmlir/Conversion/TTIRToTTKernel/copy_tile_guards.mlir

Condition for first copy guard (not first iteration) should be `(arg0 != 0) || (arg1 != 0) || ...`

D2M: Fix first copy guard condition

---

runtime/lib/common/system_desc.cpp

Checking device connection is done by querying the active ethernet cores and the devices they are connected to. On blackhole chips, the connection might be down, causing a runtime exception. As a temporary workaround, we skip this step until an API is made public from the metal side or when we need to support multiple BH devices.

Skip connection check when querying system desc

---

include/ttmlir/Dialect/TTIR/Analysis/AllocationPlanner.h
include/ttmlir/Support/Logger.h
lib/Conversion/TTIRToTTMetal/TTIRToTTMetal.cpp
lib/Conversion/TTIRToTTMetal/TTIRToTTMetalPass.cpp
lib/Dialect/TTIR/Analysis/AllocationPlanner.cpp
lib/Dialect/TTIR/Analysis/CMakeLists.txt
lib/Dialect/TTIR/Transforms/Allocate.cpp
test/unittests/Allocation/CMakeLists.txt
test/unittests/Allocation/TestAllocation.cpp
test/unittests/CMakeLists.txt

Implements one algorithm for #3034, "greedy-by-size" as used by TFLite and derivative projects. 
(Alternative impl path was investigated in related #2246.)
This is our first non-naive "static memory allocator" in the sense that it can re-use memory based on live range analysis. On randomized inputs this seems to generate allocation plans with usage ratios (mem usage/max load) of 1.X, with X in single or teen per cent. Further perf work will be done to assess this on realistic model inputs.
Good background reference is:
- Pisarchyk, Lee, [“Efficient Memory Management for Deep Neural Net Inference”](https://arxiv.org/abs/2001.03288), 2020
- to help experiment with more algorithms in the future, the planner is encapsulated behind the API in …

greedy-by-size algorithm implementation for the ttir-allocate pass

---

include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h
include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/Target/TTNN/operations/pool.fbs
lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
lib/Target/TTNN/TTNNToFlatbuffer.cpp
runtime/lib/ttnn/operations/pool/pool2d.cpp
test/ttmlir/Dialect/TTNN/Transforms/Workarounds/max_pool2d_workaround.mlir
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

Closes https://github.com/tenstorrent/tt-mlir/issues/2547
Few attributes were missing from the pooling ops.
This PR adds missing attributes to pooling ops:
- memory_config
- applied_shard_scheme
- inPlaceHalo
Additionally this PR merges Max and Avg pool into a single class definition in TTNN dialect.

Add missing attributes to max pool op

---

include/ttmlir/Utils.h
lib/Dialect/TTIR/Transforms/TTIRFusing.cpp
lib/Dialect/TTNN/Transforms/TTNNLayout.cpp
test/ttmlir/Dialect/TTIR/fusing/weight_tagging.mlir

Context
When testing fusing for resnet we hit OOM when pushing inputs from host to DRAM. This is because layouting logic prefers inputs in tile/dram when possible. This wasn't the case before fusing because we had special casing in layouting for function inputs which are used by conv2d to put them in host/rm.
When fusing came some operations were commuted upward which made this special cases useless in sense that now all inputs were forced in tile/dram. Since resnet has weights which are not channel last when tilized these tensors become quite large and they can't fit into dram.
Workaround
Long term we want to have all layouts in host/rm but this is not quite simple. While trying to convert all to RM/Host we found some bugs which are not easy fix (see …

[Fusing] Move conv2d weights to Host/RM workaround

---

include/ttmlir/OpModel/TTNN/MetalHeaders.h
runtime/include/tt/runtime/detail/ttnn/ttnn.h
runtime/lib/ttnn/operations/eltwise/unary/unary.cpp
runtime/test/python/ttnn/multi_device/test_input_deallocate.py
third_party/CMakeLists.txt
tools/ttnn-standalone/ttnn-precompiled.hpp

This PR uplifts the third_party/tt-metal to the f025854dea69b6b62c8b1ce0075917daffce6898
- Update to_layout test after host tensor deallocation updated in metal change 0ed611c
- Update copy.hpp location after moved in metal change d6e9bf6ba4

Uplift third_party/tt-metal to f025854dea69b6b62c8b1ce0075917daffce6898 2025-05-21

---

include/ttmlir/OpModel/TTNN/MetalHeaders.h

N/A
There were a bunch of clang diagnostic pragmas to suppress warnings.
Since those include dirs are searched with `-isystem`, warnings will be suppressed anyway.

Remove clang diagnostic pragmas from OpModel

---

docs/src/SUMMARY.md
docs/src/ttnn-bug-repros.md

https://github.com/tenstorrent/tt-metal/issues/18551
tt-mlir compiler is able to generate TTNN op calls in C++ (EmitC) - it is not trivial for metal devs to consume and run these code snippets.
Change https://github.com/tenstorrent/tt-metal/pull/22241 enabled easy plug&play of generated C++ code (EmitC) to tt-metal's GTest infra. This change adds docs in tt-mlir on how to use the infra.

Add TTNN bug repro guide doc

---

runtime/include/tt/runtime/detail/ttmetal/ttmetal.h
runtime/include/tt/runtime/detail/ttnn/ttnn.h
runtime/include/tt/runtime/runtime.h
runtime/lib/runtime.cpp
runtime/lib/ttmetal/runtime.cpp
runtime/lib/ttnn/runtime.cpp
runtime/test/python/ttnn/multi_device/test_runtime_api.py
runtime/tools/ttrt/ttrt/runtime/module.cpp

With automatic pipeline parallel enabled on tt-torch, it would be desirable to dynamically query the dram size from device so that we can cut the model correctly.
Added APIs to query dram/l1 sizes.

Add device dram/l1 query APIs

---

lib/Dialect/TTNN/Transforms/Passes.cpp
runtime/test/ttnn/dylib.cpp
test/ttmlir/EmitC/TTNN/other/const-eval-device.mlir
test/ttmlir/EmitC/TTNN/other/embedding.mlir
tools/ttnn-standalone/ttnn-precompiled.hpp

https://github.com/tenstorrent/tt-mlir/issues/3397#issuecomment-2893207925
EmitC currently has special handling for getDevice ops which changes function signatures, which was breaking logic in const-eval for subgraphs which use getDevice ops.
Instead of passing the device as an argument to functions with getDevices op, we want to utilize the existing conversion to get a singleton device object.  This requires adding a global setter for this field in the precompiled .hpp as well, and invoking it via the dylib in `ttrt` prior to execution.

Refactor GetDevice handling in EmitC dylib signature conversion

---

lib/Conversion/StableHLOToTTIR/ShardyToTTIRPatterns.cpp
test/ttmlir/Conversion/StableHLOToTTIR/ccl/ccl_ops_shardy.mlir
test/ttmlir/Dialect/StableHLO/shardy_automatic_parallelization/user_annotations_simple.mlir

https://github.com/tenstorrent/tt-mlir/issues/3515
When trying to convert scalar operands via sdy manual computation op, there was a bug where it wouldn't apply the type converter to the operand.
```
ttmlir-opt --stablehlo-to-ttir-pipeline
```
Before
```
module @sdy_manual_computation_constant {
sdy.mesh @mesh = <["x"=2, "y"=4]>
func.func public @main(%arg0: tensor<f32>) -> tensor<f32> {
%0 = sdy.manual_computation(%arg0) in_shardings=[<@mesh, []>] out_shardings=[<@mesh, []>] manual_axes={"x", "y"} (%arg1: tensor<f32>) {
sdy.return %arg1 : tensor<f32>
} : (tensor<f32>) -> tensor<f32>
return %0 : tensor<f32>
}
}
->
failed to legalize unresolved materialization from ('tensor<1xi32>') to ('tensor') that remained live after conversion
```
After (conversion applied successfully)
```
module …
```

#3515: Fixed bug in conversion from manual computation to mesh shard op for scalar operands.

---

runtime/python/CMakeLists.txt

On macOS nanobind fails with some warnings that we treat as errors. This patch works around the issue by disabling those warnings on the nanobind target.

Fix macOS nanobind build failure

---

runtime/python/CMakeLists.txt

Nanobind compile was triggering build failures on tt-forge-fe
Suppress warnings for `nanobind-static` for all builds.
- Build passing on with fix on ffe: https://github.com/tenstorrent/tt-forge-fe/actions/runs/15221750869

Fix forge-fe nanobind build issue

---

docs/src/getting-started.md

None made yet.
Currently for the "getting-started" docs, under the ubuntu section, the "here" link in the note is not shown correctly.
Made the link work as intended.

Fix hyper link in docs

---

include/ttmlir/Dialect/StableHLO/Transforms/ShardyUtils.h
lib/Dialect/StableHLO/Transforms/ShardyAutomaticParallelization.cpp
test/ttmlir/Dialect/StableHLO/shardy_automatic_parallelization/slice.mlir

[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/3494)
Slice op in automatic shardy pass needed to be supported specially because it encodes the shape of it's output in it's attribute dictionary, whereas most other ops do not. Thus, when updating the shapes of the tensors to match their shard shape, we also need to pay careful attention to slice.
Example
```
ttmlir-opt --automatic-sharding-pipeline="mesh-shape=1,2"
```
before fix
```
module {
sdy.mesh @mesh = <["model"=1, "batch"=2]>
func.func @concat_operands_are_results_of_slices(%arg0: tensor<4x40x256xf32>, %arg1: tensor<4x60x256xf32>) -> tensor<4x80x256xf32> {
%0 = sdy.manual_computation(%arg0, %arg1) in_shardings=[<@mesh, [{"batch"}, {}, {}]>, <@mesh, [{"batch"}, {}, {}]>] out_shardings=[<@mesh, [{"batch"}, {}, …
```

#3494: Added slice op support for automatic parallelization pass with shardy.

---

runtime/tools/ttrt/test/test_run.py
runtime/tools/ttrt/ttrt/common/run.py
runtime/tools/ttrt/ttrt/common/util.py

Issue: https://github.com/tenstorrent/tt-mlir/issues/2959
Usage
```
ttrt run <flatbuffer>
```
This will populate a host duration time per op in the results.json file
run_results.json
```
[
{
"file_path": "/code/tt-mlir/build/test/ttmlir/Silicon/TTNN/n300/ccl/Output/ccl_1x2_all_gather.mlir.tmp.ttnn",
"result": "pass",
"exception": "",
"log_file": "",
"artifacts": "/code/tt-mlir/ttrt-artifacts",
"program_index": "all",
"e2e_duration_milliseconds": 19785.75575305149
}
]
```

#2959: Add support for measuring e2e perf from ttrt.

---

lib/OpModel/TTNN/Conversion.cpp
runtime/lib/ttnn/operations/conv/conv2d.cpp
test/ttmlir/EmitC/TTNN/conv/conv2d_bf16.mlir
test/ttmlir/EmitC/TTNN/conv/conv2d_f32.mlir
test/ttmlir/EmitC/TTNN/conv/depthwise_conv2d.mlir
test/ttmlir/EmitC/TTNN/conv/depthwise_separable_conv2d.mlir
test/ttmlir/EmitC/TTNN/conv/dilated_conv2d.mlir
test/ttmlir/EmitC/TTNN/conv/grouped_conv2d.mlir
test/ttmlir/EmitC/TTNN/models/resnet.mlir
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 17c897f7c80034e6fe46a416f309138785b765ff
- Replace call to tensorSpec.compute_shard_spec_buffer() after removed in metal commit 5e617d95
- Update default conv2d computeconfig after being used by ttnn::linear in metal change 7ec6d04607
- Lower PCC in 2x tt-torch torchvision tests full-eval-regnet_x_32gf , full-eval-regnet_y_16gf exposed here

Uplift third_party/tt-metal to 17c897f7c80034e6fe46a416f309138785b765ff 2025-05-28

---

tools/ttnn-standalone/ttnn-precompiled.hpp

https://github.com/tenstorrent/tt-mlir/issues/3595
My recent changes to the way emitC handles getInstance seems to have broken some tt_metal dtor ordering due to changing the type of static variable involved.  Unfortunately, CI did not catch this issue, but it is causing segfaults when running ttnn-standalone.
This should resolve the issue by keeping the "ownedInstance" as a local static variable instead of a class-level variable, as before.  Locally, this fixes the issue

Fix bug with getInstance logic for emitC standalone

---

lib/Dialect/TTNN/IR/TTNNOps.cpp
lib/Dialect/TTNN/Transforms/Passes.cpp
test/ttmlir/Dialect/TTNN/optimizer/conv2d_config_override.mlir
test/ttmlir/Silicon/TTNN/n150/deallocate_override.mlir

Closes #3383
When overriding `dellocate_activation` parameter in Conv2dConfig, a `ttnnTensor.is_allocated()` error may occur in runtime due to a deallocate op for conv2d activation already being added in the `TTNNDeallocate` pass.
- `ttnn.deallocate` will not be added in `TTNNDeallocate` pass for conv2d op activation if `deallocate_activation` parameter is set to `true`.
- added a test `test/ttmlir/Silicon/TTNN/n150/deallocate_override.mlir`
- (_not related to the issue_) changed `test/ttmlir/Dialect/TTNN/optimizer/conv2d_config_override.mlir` to be more flexible if new conv2d config parameters are added

Skip deallocation of conv2d activation when it is overridden

---

test/python/golden/conftest.py

Enable running tests whose mesh shapes are a subset of the current device.

Add ttir-builder flag allow-subset-mesh

---

include/ttmlir/Dialect/TT/IR/TTOpsTypes.h
include/ttmlir/Dialect/TTIR/IR/TTIRGenericRegionOps.td
include/ttmlir/Dialect/TTIR/IR/TTIROps.td
include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
lib/Conversion/TTIRToTTIRGeneric/TTIRToTTIRGeneric.cpp
lib/Conversion/TTIRToTTKernel/TTIRToTTKernel.cpp
lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
lib/Dialect/TTIR/IR/TTIROps.cpp
lib/Target/TTKernel/TTKernelToCpp.cpp
test/ttmlir/Conversion/TTKernelToEmitC/ttkernel.mlir
test/ttmlir/Conversion/TosaToTTIR/elementwise_unary/cast.mlir
test/ttmlir/Dialect/TTIR/data_movement/typecast/typecast_folding.mlir
test/ttmlir/Silicon/TTMetal/n150/typecast.mlir

Closes #3012
Add typecast support to the D2M path
Changed the TTIR typecast folding canonicalizer: instead of folding any two consecutive typecasts, check the narrowing/widening feature of the two ops and only fold if it won't introduce breaking changes to the semantics or accuracy of the original code
Add an additional `conservative_folding` boolean attribute to `ttir.typecast`that enables the check above, off by default

Add D2M typecast support

---

runtime/lib/ttnn/operations/ccl/mesh_shard.cpp
test/python/golden/test_ttir_ops_llmbox.py
third_party/CMakeLists.txt
tools/ttnn-standalone/workarounds.hpp

This PR uplifts the third_party/tt-metal to the 3c4aedc9ff67e3a247cd2f30a13c5e525214a51e
- Runtime sharding updated after multi-device ND sharding APIs introduced in metal commit c0832bc02d

Uplift third_party/tt-metal to 3c4aedc9ff67e3a247cd2f30a13c5e525214a51e 2025-05-29

---

.github/workflows/nightly-model-explorer-uplift.yml

- We currently provide `model-explorer` uplifts by hand and it's a grossly inefficient process. 
- Added a `nightly` run that creates a PR for uplift if the hash has changed. It will also run our PR CI, which ensures that the FE changes don't impact the explorer backend.

Added Nightly Uplift from Explorer

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

#3556 
This PR adds constraint APIs for `subtractOp`.
Adds support for `getOpConstraints` and `getOpRuntime` for `SubtractOp`.

feat: add constraint APIs for subtract op

---

docs/src/tt-explorer.md

Explained in title. 
@vprajapati-tt Can you comment on moving the Project Arch (high-level summary) before Quick Start? Seems more intuitive so the user can understand what the tool is before proceeding. 
Also the TT-Explorer page launched by `tt-explorer` says the following:
> Supported model formats: [TF](https://www.tensorflow.org/) (.pb, .pbtxt, .graphdef), [TFLite](https://www.tensorflow.org/lite) (.tflite), [TFJS](https://www.tensorflow.org/js) (.json), [JAX](https://www.tensorflow.org/guide/jax2tf) (.pb), [PyTorch ExportedProgram](https://github.com/google-ai-edge/model-explorer/wiki/2.-User-Guide#how-to-select-pytorch-models) (.pt2), MLIR (.mlir, .mlirbc).
But it sounds like we can support .ttnn files as well?

(nit): Update tt-explorer.md documentation

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/OpModel/TTNN/MetalHeaders.h
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/OpModel/TTNN/SingletonDeviceContext.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

#3639 
Missing support for constraint API for `ttnn::maximum`.
This PR:
- Adds constraint APIs for `MaximumOp`,
- Adds constraint APIs for `MinimumOp`,
- Commonizes some code in `TTNNOpModelInterface`.

add constraint APIs for MaximumOp and MinimumOp

---

lib/Dialect/TTNN/IR/TTNNWorkaroundsPass.cpp
test/ttmlir/Dialect/TTNN/constant/positive/simple_constant_positive.mlir
test/ttmlir/Dialect/TTNN/quantization/simple_dequantize.mlir
test/ttmlir/Dialect/TTNN/quantization/simple_quantize.mlir
test/ttmlir/Dialect/TTNN/quantization/simple_requantize.mlir
test/ttmlir/Dialect/TTNN/simple_get_dimension_size.mlir
test/ttmlir/Silicon/StableHLO/n150/Constant/constant_i32.mlir
test/ttmlir/Silicon/StableHLO/n150/Constant/constant_i64.mlir
test/ttmlir/Silicon/StableHLO/n150/get_dimension_size_op.mlir
test/ttmlir/Silicon/TTNN/n150/eltwise/unary/get_dimension_size/get_dimension_size.mlir
test/ttmlir/Silicon/TTNN/n150/perf/test_perf_dequantize.mlir
test/ttmlir/Silicon/TTNN/n150/perf/test_perf_quantize.mlir
test/ttmlir/Silicon/TTNN/n150/perf/test_perf_requantize.mlir
test/ttmlir/Silicon/TTNN/n150/quantization/simple_dequantize.mlir
test/ttmlir/Silicon/TTNN/n150/quantization/simple_quantize.mlir
test/ttmlir/Silicon/TTNN/n150/quantization/simple_requantize.mlir

[Link to Github Issue](https://github.com/tenstorrent/tt-torch/issues/895)
There are several op combinations that may implicitly trigger a uint32 -> float32 typecast. For example, broadcasting with a constant integer value (int32 dtype) followed by an unsqueeze can result in the following decomposition:
ttnn.full
ttnn.reshape
->
ttnn.full (uint32)
ttnn.typecast (uint32 -> int32)
ttnn.typecast (int32 -> float32)
ttnn.reshape (float32)
This sequence introduces an unintended uint32 -> float32 conversion.
This patch extends the existing typecast prevention logic to cover these additional cases and avoid such conversions.
Building on the same idea as #3637 , this patch prevents additional cases of unintended uint32 -> float32 typecasts.

Prevent unintended typecast from uint32 to float32

---

test/python/golden/test_ttir_ops.py
tools/ttir-builder/builder.py

[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/3678)
ttir-builder's `upsample2d` was throwing a size mismatch error
Fixed it

Fixing ttir-builder upsample2d

---

cmake/modules/BuildFlatbuffers.cmake
include/ttmlir/Dialect/TT/IR/TTOpsTypes.td
include/ttmlir/Target/Common/CMakeLists.txt
include/ttmlir/Target/Common/Target.h
include/ttmlir/Target/Common/system_desc.fbs
include/ttmlir/Target/TTMetal/CMakeLists.txt
include/ttmlir/Target/TTMetal/Target.h
include/ttmlir/Target/TTMetal/binary.fbs
include/ttmlir/Target/TTNN/CMakeLists.txt
include/ttmlir/Target/TTNN/Target.h
include/ttmlir/Target/TTNN/binary.fbs
lib/Dialect/TT/IR/TTOpsTypes.cpp
lib/Dialect/TT/Transforms/TTRegisterDevice.cpp
lib/Target/TTMetal/TTMetalToFlatbuffer.cpp
lib/Target/TTNN/TTNNToFlatbuffer.cpp
runtime/include/tt/runtime/types.h
runtime/lib/binary.cpp
runtime/lib/common/system_desc.cpp
runtime/python/binary/binary.cpp
runtime/tools/ttrt/ttrt/common/util.py
tools/scripts/sha256-include-gen.py

The current flatbuffer schema verification check is flawed since it only checks the git tag version is the same, this is problematic for 2 reasons:
1. False positives: You could have changed the schema as part of _this_ commit and the compiler would be perfectly fine loading this system desc and parsing fields out (incorrectly).
2. False negatives: You could have committed a change that has nothing to do with flatbuffer schema, but this commit bumps the patch number which causes a system desc version mismatch.
This patch resolves both of these issues by hashing the flatbuffer schemas and storing the hash in the flatbuffer.  This enables both the runtime and the compiler to verify the schema is at the expected version.  It has the added benefit of passing the verification when no …

Improved flatbuffer schema verification

---

.github/workflows/wheel-build.yml
tools/pykernel/requirements.txt

- Previous bash script to get latest release is failing, resolve to a static release.
- Permanent solution is to package `ttmlir` within PyKernel, this is an incoming PR. Hotfix is meant to keep CI green.

Set pykernel dep. to latest tt-mlir wheel release on tt-forge

---

lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecompositionPass.cpp
test/ttmlir/Dialect/TTIR/Decomposition/reduce_prod.mlir
test/ttmlir/Dialect/TTNN/reduction/negative_reduce_prod_op.mlir

closes https://github.com/tenstorrent/tt-mlir/issues/1861
tt-metal supports product reduction along one or all dimensions. 
TTIR->TTIR decomposition is added to transform product reduction op to
multiple reduction ops. Each op will perform reduction along one dimension only.

TTIR decomposition of ttir.prod op

---

test/pykernel/demo/requirements.txt

- Broke CI once again.
- Potential Problem: `ttnn` wheel version was updated and this didn't correspond with our toolchain (so things broke).
- Downgrade `ttnn` wheel dep.

[CI Hotfix] Downgrade TTNN Wheel for PyKernel Test

---

test/ttmlir/Silicon/TTNN/n150/optimizer/shard_transpose.mlir
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 02bda8e52e88a96f2d0837f517bc4e600fad4706
- Skip `test/ttmlir/Silicon/TTNN/n150/optimizer/shard_transpose.mlir` after metal commit daf8fbadc8 opened https://github.com/tenstorrent/tt-mlir/issues/3743 to follow up

Uplift third_party/tt-metal to 02bda8e52e88a96f2d0837f517bc4e600fad4706 2025-06-06

---

CMakeLists.txt
docs/src/getting-started.md
lib/CMakeLists.txt

The docs state that CMake 3.20 or higher is required to build tt-mlir. 
However, tt-metal (a third party dependency) now requires CMake 3.24. That is now the new minimal requirement to build tt-mlir. 
Additionally when building the project with CMake 3.24 and configured with -DTTMLIR_ENABLE_STABLEHLO=ON the following error is observed:
```
undefined reference to `mlir::sdy::AxisListRef::strictPrefixOf(mlir::sdy::AxisListRef const&) const'
undefined reference to `mlir::sdy::AxisListRef::truncateWithoutOverlap(mlir::sdy::AxisListRef const&)'
undefined reference to `mlir::sdy::AxisListRef::getShardingSize(mlir::sdy::MeshAttr) const'
undefined reference to `mlir::sdy::AxisListRef::toVector() const'
undefined reference to `mlir::sdy::AxisListRef::operator<(mlir::sdy::AxisListRef const&) const' …
```

Build tt-mlir with cmake 3.24

---

include/ttmlir/Dialect/TTNN/Analysis/Edge.h
include/ttmlir/Dialect/TTNN/Analysis/L1ChainConfig.h
include/ttmlir/Scheduler/Scheduler.h
lib/Dialect/TTNN/Analysis/BFInterleavedPolicy.cpp
lib/Dialect/TTNN/Analysis/DFShardingPolicy.cpp
lib/Dialect/TTNN/Analysis/GreedyL1InterleavedPolicy.cpp
lib/Dialect/TTNN/Analysis/ShardSolver.cpp
lib/Dialect/TTNN/Transforms/Optimizer.cpp
lib/Scheduler/Scheduler.cpp
test/ttmlir/Silicon/TTNN/n150/optimizer/shard_transpose.mlir
test/unittests/TestScheduler/TestScheduler.cpp

Three fold change in this commit:
1. Allow sharding join nodes in fork-join structure.
2. Change scheduler to prioritize "shorter" branches first. This will enabled us create longer chains including join nodes.
3. Fix connections after creating spill to dram op following join node. This node is followed by other chains and it's possible to skip reading from DRAM in some paths.
Piggyback: re-enable sharding of eltwise binary ops.
Related to https://github.com/tenstorrent/tt-mlir/issues/2276

Shard join nodes

---

runtime/include/tt/runtime/detail/ttnn/program_executor.h
runtime/include/tt/runtime/types.h
runtime/lib/ttnn/operations/cache/load_cached.cpp
runtime/lib/ttnn/program_executor.cpp
runtime/tools/ttrt/ttrt/common/perf.py

This PR adds tracking ability for showing which ops are part of a const-eval cached routine. It will dump this information in the perf csv report file.
eg

#3782: Updated device perf csv file to show which ops are const eval values.

---

runtime/lib/common/system_desc.cpp

None
A semantic change to DeviceAttr::get() to use chipDescIndices remapping causes tt-torch multidevice and pipeline parallel test failures.
Revert minimal changeset in lib/Dialect/TT/IR/TTOpsTypes.cpp to avoid this extra remapping of chipIds through chipDescIndices.

Fix chipDescIndices to map valid indices into chipDescs

---

lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
runtime/lib/common/system_desc.cpp
runtime/lib/ttnn/operations/pool/pool2d.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the f1d7b9ae9de8ba6329e9fae984e9b95b46730838
- Update maxpool and avgpool functions signatures after metal change a5014d7
- Follow up #3771 
- Skip connecting eth core devices due to metal exception after metal change 33a0ccc732
- Follow up #3781 
- Update cbsize for eltwise binary ops after binary_ng made default in f1d7b9ae9d

Uplift third_party/tt-metal to f1d7b9ae9de8ba6329e9fae984e9b95b46730838 2025-06-12

---

lib/Dialect/TTNN/Transforms/TTNNLayout.cpp
test/ttmlir/Dialect/TTNN/ccl/mesh_shard.mlir

https://github.com/tenstorrent/tt-mlir/issues/3733
Current ttnnLayout pass forces outputs to system memory if any of the result is from mesh_shard op. However, Andrej reported that new version of JAX mixes multi-device return values with single device one, causing issue. 
Update TTNNLayout rewriteOutput to be per-output based approach.

Update rewriteOutput as per-result based checking

---

docs/src/ttir-builder.md
test/python/golden/test_ttir_ops.py

[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/3723)
[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/1797)
[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/1798)
[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/1799)
These ops: `ttir.tan`, `ttir.log`, and `ttir.log1p` have golden pcc failures at/near certain input values. As input values approach the vertical asymptotes of these ops' graphs, output values have huge reactions to small variations in input values.
Wrote individual test functions for each op constricting input values of both graph and golden input tensors. Golden handling is typically done in `builder.py`'s op-constructing functions. However, for these to pass, a margin of error was necessary …

Fixing TTIRBuilder PCC errors in tan, log, log1

---

docs/src/ttrt.md
runtime/tools/ttrt/ttrt/common/run.py
runtime/tools/ttrt/ttrt/common/util.py
test/python/golden/test_ttir_ops.py
tools/ttir-builder/builder.py

None
PCC has its flaws, we need at least one other test to check the results' accuracy, ref: https://github.com/tenstorrent/tt-metal/issues/22994
Debugging ttrt golden failures is a bit difficult, can't see the input tensors and what the error looks like
- Added an additional `torch.allclose()` check that verifies `|golden - output| <= atol + rtol * |golden|`
- This check is only enabled when running ttmetal flatbuffers
- Print the top-k entries ranked by absolute difference, should a golden failure occur
- Also print the input tensors and top-k relative differences when a golden failure occur
- Update `--init xxx` to imply `--disable-golden`
- Added `--print-input-output-tensors` that prints the input & output tensors even if golden test is disabled or passes

Add the allclose check and QoL improvements to ttrt golden tests

---

tools/pykernel/setup.py

- `lld` still used for `pykernel` build, not working in `cibuildwheel`.
- Replaced with `ld`.

Removed lld from pykernel build process

---

docs/src/python-bindings.md
include/ttmlir-c/TTKernelTypes.h
include/ttmlir/Dialect/TTKernel/IR/TTKernelOpsTypes.td
lib/CAPI/TTKernelTypes.cpp
lib/Conversion/TTIRToTTKernel/TTIRToTTKernelPass.cpp
lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
lib/Dialect/TTKernel/IR/TTKernelOps.cpp
python/CMakeLists.txt
python/TTKernelModule.cpp
python/ttmlir/dialects/TTKernelEnumBinding.td
python/ttmlir/dialects/ttkernel.py
test/pykernel/eltwise_sfpu/eltwise_sfpu.py
test/pykernel/eltwise_sfpu/reader_unary.py
test/pykernel/eltwise_sfpu/writer_unary.py
test/ttmlir/Conversion/TTKernelToEmitC/ttkernel.mlir
test/ttmlir/Dialect/TTKernel/ops.mlir
test/ttmlir/Translate/TTKernel/ttkernel_compute.mlir
tools/pykernel/ast.py
tools/pykernel/op.py

#3089 
We have legacy unused attributes on the TTKernel CB type
Remove the unused attributes from this type, making it a low level wrapper of a memref. 
Remove supporting code that utilizes/depends on these attributes.

D2M: Remove port, address, pageSize, numBuffers from TTKernel CBType

---

include/ttmlir/Dialect/TTCore/IR/Utils.h
include/ttmlir/Utils.h
lib/Dialect/TTIR/Transforms/TTIRFusing.cpp
lib/Dialect/TTNN/Analysis/ShardSolver.cpp
lib/Dialect/TTNN/Transforms/TTNNPrepareConv2dWeights.cpp
lib/Dialect/TTNN/Transforms/TTNNTraceHoistTransform.cpp
lib/Transforms/ConstEvalHoist.cpp

- Decouple `include/ttmlir/Utils.h` from `ttmlir/Dialect/TTIR/IR/TTIROps.h` to avoid circular dependencies
- Rename `populateConstParams` to `getConstsAndParams` and move to `include/ttmlir/Dialect/TT/IR/Utils.h`
- Remove unused `getOtherOperands`

Refactor utils

---

test/python/golden/test_ttir_ops.py
tools/ttir-builder/builder.py
tools/ttir-builder/utils.py

Closes #2683 
General cleanup of builder and tests. The diff looks intimidating, but it's one or two changes that were needed in a bunch of places. Real meat of the change is in the builder `conv2d` and `conv_transpose2d` functions.
- Moved all references to IR Attrs behind the builder API, no attr construction is needed to use the API anymore
- Fix various `conv*` op tests, they now pass goldens
- Fixed the type signature of `unit_attrs` to properly use `None`

Fix `conv*` Tests & General Builder API Cleanup

---

.github/workflows/build-and-test.yml
runtime/lib/ttnn/operations/ccl/collective_permute.cpp
runtime/lib/ttnn/operations/utils/utils.cpp
runtime/lib/ttnn/runtime.cpp
runtime/test/ttnn/dylib.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 3fbd3ff68830cbe5fc3ae69cfb8ae036138a1ebd
- Rename tensor->padded_volume() to tensor->physical_volume after metal change d82e42461f
- Disable Pykernel tests since ttnn wheel needs to match uplifted metal after commit 7d7b51a

Uplift third_party/tt-metal to 3fbd3ff68830cbe5fc3ae69cfb8ae036138a1ebd 2025-06-17

---

include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h
lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp

Closes https://github.com/tenstorrent/tt-mlir/issues/3828
Running ResNet through `ttnn-standalone` one would get an OOM issue. Root cause of the issue is the way the `conv2d` is dealt with in generated code
```cpp
std::variant<Tensor,...> v = conv2d(...);
Tensor t = std::get<0>(v);
...
deallocate(t);
```
IR assumes that there is only one reference to `t` before `deallocate`, and once `deallocate` is executed there won't be any references, so the buffer which tensor held will be freed. But since `variant` 'beneath' still holds the reference to the same tensor, actual refcount was 2, so it only gets decremented to 1, and buffer still lives, so after some time there isn't any space left on the device.
- Inlined the result `ttnn::conv2d` inside `std::get`, so it's rvalue refrence and the …

Fix ResNet OOM issue in `ttnn-standalone`

---

test/python/golden/test_ttir_ops.py

No issue, just getting ops into CI
Due to `squeeze`/`unsqueeze` effectively being reshapes, they don't produce perf reports (#2371). Before we had as fine grained control over which flatbuffers were created, we needed to unconditionally skip these. Seeing as that issue is closed, and a tentative solution has been reached, I believe the following change to be safe and valid.
Since we can now selectively skip tests via pytest, we can just skip these tests whenever we need them for perf, or not include their flatbuffers in a perf run. These tests have been re-enabled, adding their PCC regression tests into CI. There is some discussion on the root issue of this, but wanted to at least get these into CI ASAP. We can discuss some more if this is premature or not.

Unskip `squeeze` & `unsqueeze` to CI test PCC

---

include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h
include/ttmlir/OpModel/TTNN/Conversion.h
include/ttmlir/OpModel/TTNN/MetalHeaders.h
lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
lib/Conversion/TTNNToEmitC/TTNNToEmitCPass.cpp
lib/OpModel/TTNN/Conversion.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
runtime/lib/ttnn/operations/data_movement/pad.cpp
runtime/lib/ttnn/operations/data_movement/permute.cpp
runtime/lib/ttnn/operations/data_movement/slice.cpp
runtime/lib/ttnn/operations/pool/pool2d.cpp
runtime/lib/ttnn/operations/reduction/reduction.cpp
test/unittests/TTNNToEmitC/TestEmitCConversion.cpp
third_party/CMakeLists.txt
tools/ttnn-standalone/ttnn-precompiled.hpp

This PR uplifts the third_party/tt-metal to the d81d323eb816723840691d5e4e3c7115e68e5080 (June 12)
- Update small_vector include and namespace after moved from metal API to tt_stl in metal change e573211
- Replace `tt::` namespace references with more specific `mlir::tt::` to disambiguate from `tt::stl::` namespace
- Update avgpool after new arg count_include_pad added in metal commit e132c7741d

Uplift third_party/tt-metal to d81d323eb816723840691d5e4e3c7115e68e5080 2025-06-18

---

include/ttmlir/Target/Common/types.fbs
lib/Dialect/TTCore/IR/TTCoreOpsTypes.cpp
runtime/include/tt/runtime/detail/ttmetal/ttmetal.h
runtime/include/tt/runtime/detail/ttnn/ttnn.h
runtime/include/tt/runtime/runtime.h
runtime/include/tt/runtime/utils.h
runtime/lib/runtime.cpp
runtime/lib/ttmetal/runtime.cpp
runtime/lib/ttnn/runtime.cpp
runtime/python/runtime/runtime.cpp
runtime/test/common/CMakeLists.txt
runtime/test/common/test_handle_integer_buffer_cast.cpp
runtime/test/python/ttnn/device_agnostic/test_runtime_api.py
runtime/tools/ttrt/ttrt/common/util.py

Added an `enum` to represent data types that are unsupported.
- int64
- uint64
- float64
- int16
- int8
- bool
Added utility function which returns the data type we should cast to.
- `getUnsupportedDataTypeAlias`
- This is based off of `toTTMLIRSupportedDataType` which is used in the `ElementTypeNormalization` pass.
Added runtime api for creating tensor from a buffer that includes data in an unsupported data type.
- `createOwnedHostTensorFromUnsupportedDataType`
- This will assume that the host buffer containing the data holds an unsupported data type and will cast all values inside to a supported data type (determined by `getUnsupportedDataTypeAlias`) and print a warning to the user that this is happening.
- I cannot create a version of this function which creates a borrowed tensor as we …

Add runtime api entry points to create runtime tensors from buffers containing unsupported data types

---

runtime/include/tt/runtime/perf.h
runtime/lib/common/perf.cpp
runtime/lib/ttnn/program_executor.cpp
runtime/python/runtime/runtime.cpp
runtime/tools/ttrt/ttrt/common/perf.py
runtime/tools/ttrt/ttrt/common/run.py
runtime/tools/ttrt/ttrt/common/util.py

[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/3706)
This PR adds support for insert custom metadata into the tracy profiler dumps from the compiler runtime. Different metadata can be inserted per op that is run, or program level metadata can be inserted for all ops.
eg.
```
"{'loop_number': 0, 'program_index': 0, 'disable_eth_dispatch': False, 'enable_program_cache': True, 'dump_device_rate': 1000}"
```
Also, this PR performs analysis on such results, to determine the host e2e duration, the TTNN api duration and the device fw duration. Results are dumped in run_results.json / perf_results.json file for whichever API is used.
eg.
```
"program_results": {
"program_index_0": {
"loop_0": {
"total_duration_ns": 1620766460,
"total_ttnn_api_duration_ns": 574167, …
```

#3706: Added support for custom metadata insertion in tracy profiler dumps and analysis of profiled results.

---

docs/src/ttnn-dialect-guidelines.md
include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h
include/ttmlir/Conversion/TTNNToEmitC/Utils.h
include/ttmlir/OpModel/TTNN/Conversion.h
lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
lib/OpModel/TTNN/Conversion.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
runtime/include/tt/runtime/detail/ttmetal/profiler.h
runtime/include/tt/runtime/detail/ttnn/utils.h
runtime/lib/ttnn/operations/data_movement/pad.cpp
runtime/lib/ttnn/operations/data_movement/permute.cpp
runtime/lib/ttnn/operations/data_movement/slice.cpp
runtime/lib/ttnn/operations/eltwise/binary/binary.cpp
runtime/lib/ttnn/operations/eltwise/binary/binary_composite.cpp
runtime/lib/ttnn/operations/kv_cache/update_cache.cpp
runtime/lib/ttnn/operations/pool/pool2d.cpp
runtime/lib/ttnn/operations/reduction/reduction.cpp
runtime/lib/ttnn/runtime.cpp
runtime/lib/ttnn/utils/utils.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
test/unittests/TTNNToEmitC/TestEmitCConversion.cpp
third_party/CMakeLists.txt
tools/ttnn-standalone/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 1a9ff3036e4298f30b644ffeeeb40812f5f4b89f (June 18)
- Distributed host buffer updates after metal commit 6ac48706e3
- Replace tt::stl namespace with ttsl after metal commit f94ddf80d4
- Update tt-logger include path after version bumped in commit f58bf76a68

Uplift third_party/tt-metal to 1a9ff3036e4298f30b644ffeeeb40812f5f4b89f 2025-06-19

---

runtime/include/tt/runtime/types.h
runtime/lib/binary.cpp

Currently, we only support loading and storing of flatbuffers from files on disk. Since this is not the primary way in which tt-xla serializes its binaries, we also need APIs for storing and loading it from memory, which this PR adds.

Adding serialization and deserialization of Flatbuffer to memory

---

include/ttmlir/Dialect/TTNN/IR/TTNNOpsAttrs.td
lib/Dialect/TTNN/IR/TTNNOpsAttrs.cpp
lib/OpModel/TTNN/Conversion.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Conversion/TestConversion.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

#3242
#3408
In TTNN it is possible to create a `MemoryConfig` that is L1 and sharded, but has an unspecified `shard_spec`. This means the tensor is sharded but the physical shard shape and grid are unspecified. Such `MemoryConfig`s cannot actually be used to allocate tensors. However, some ops such as `matmul` accept them as `output_memory_config` so callers can request a sharded output tensor while allowing the op to decide the actual shard layout.
The optimizer uses `TTNNLayoutAttr` to model the layout of TTNN tensors. This attribute requires a `GridAttr` and immediately computes the physical shard shape. There is no mechanism to model the unspecified `shardspec`. There is also no mechanism for the optimizer to signal to the OpModel to only partially translate the `TTNNLayoutAttr`. This …

[Optimizer] Enable getOpConstraint Queries with Partially Specified MemoryConfigs

---

runtime/include/tt/runtime/utils.h

Currenly, the tt-mlir uplift to tt-xla was broken due to an include of a header that was not copied over. Since that header is not needed, deleting it.

Deleted an include for fixing uplift to frontends

---

third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 6f08ca89a87b285ac64eee15f9e9c16235342b15
note for bisect: first commit in range fails due to build error that last commit fixes

Uplift third_party/tt-metal to 6f08ca89a87b285ac64eee15f9e9c16235342b15 2025-06-20

---

runtime/include/tt/runtime/perf.h
runtime/lib/common/CMakeLists.txt
runtime/lib/common/perf.cpp
runtime/lib/ttnn/program_executor.cpp
runtime/python/runtime/runtime.cpp
runtime/tools/ttrt/ttrt/common/run.py
third_party/CMakeLists.txt

Issue: https://github.com/tenstorrent/tt-mlir/issues/3788
This PR wraps existing tracy APIs and added a new op location API under perf::Env. There are now the following perf APIs exposed out of runtime.
```
perf_env.set_program_metadata
perf_env.tracy_log_op_location
perf_env.tracy_log_const_eval_program
perf_env.tracy_log_program_metadata
```
Each of these APIs can be called by the user before calling any individual TTNN api call. By default, they will be used by runtime from reading within the flatbuffer to extract the relevant information (or dynamically querying what the user has set). These entries will be appended onto the perf CSV file for each op.
Eg.
| LOC | CONST_EVAL_OP | PROGRAM_METADATA |
| ---  |  --- | --- |
| "loc("binary_ops.mlir.tmp.mlir"":9:14)" | true         | …

#3788: Added tracy APIs to log location, consteval and program metadata for each op.

---

include/ttmlir/Dialect/TTIR/IR/TTIROps.td
lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecompositionPass.cpp
lib/Dialect/TTIR/IR/TTIROps.cpp
test/python/golden/test_ttir_ops.py
test/ttmlir/Dialect/TTIR/Decomposition/select_decomposition_tests.mlir
test/ttmlir/Dialect/TTIR/select/select_tests_negative.mlir
test/ttmlir/Dialect/TTIR/select/select_tests_positive.mlir
tools/ttir-builder/builder.py

Closes #2488 
Closes #2496 
`select` was not passing in the `stride` argument due to #2488. This was causing the floating point exception seen in #2496.
Re-enabled passing the `stride` argument in, and some previous change fixed the issue seen in #2488. This argument fixes the floating point exception seen in #2496, and brings `select` golden testing into the CI

Fix `select` builder test

---

lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
runtime/lib/ttnn/operations/layout/to_layout.cpp
runtime/lib/ttnn/runtime.cpp
runtime/lib/ttnn/types/layout_converter.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the f578f4652e3e7950ac4e73aa70501e7bb137669f
- Remove device param from to_layout op after metal commit 67fb39c
- Follow up with issue https://github.com/tenstorrent/tt-mlir/issues/3897
- Skip op model conv tests due to hang after metal commit eb5db2e
- Follow up with issue https://github.com/tenstorrent/tt-mlir/issues/3901

Uplift third_party/tt-metal to f578f4652e3e7950ac4e73aa70501e7bb137669f 2025-06-23

---

include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
include/ttmlir/Dialect/TTNN/Transforms/Optimizer.h
lib/Dialect/TTNN/Analysis/DFShardingPolicy.cpp
lib/Dialect/TTNN/Transforms/Optimizer.cpp
test/ttmlir/Dialect/TTNN/const-eval/prep_conv2d.mlir
test/ttmlir/Dialect/TTNN/optimizer/conv2d_config_override.mlir
test/ttmlir/Dialect/TTNN/optimizer/multiple_add_with_loc.mlir
test/ttmlir/Dialect/TTNN/optimizer/output_layout_override.mlir
test/ttmlir/Dialect/TTNN/optimizer/partial_output_layout_override.mlir
test/ttmlir/Dialect/TTNN/optimizer/ttir_to_ttnn_pipeline.mlir
test/ttmlir/Silicon/TTNN/n150/optimizer/prep_conv2d_weights_const_eval.mlir
test/ttmlir/Silicon/TTNN/n150/optimizer/prepare_conv2d_weights.mlir

Optimizer controlled by single 'enable-optimizer' flag. If optimizer is enabled then MLA is ON. MLA can be disabled by specifying 'memory-layout-analysis-enabled=false'. I fixed every test that enables optimizer to disable MLA for now if it already didn't have it enabled/disabled explicitly.
Fixed L1 chain creation.
Fixes #3700
Fixes #3701

Make MLA on by default

---

env/activate
env/activate.fish
runtime/tools/ttrt/ttrt/common/perf.py

N/A
`tracy` module not visible in python.
```
cd tools/ttnn-standalone
TT_METAL_DEVICE_PROFILER=1 python -m tracy -r -v build/ttnn-standalone
```
returns
```
/opt/ttmlir-toolchain/venv/bin/python: No module named tracy
```
Add `${TT_METAL_HOME}/ttnn` to `$PYTHONPATH`, which contains the `tracy` module.
Edit:
A previous change removed `$TT_METAL_HOME` from `$PYTHONPATH` so I've added that back in as well, as it is needed by the tracy module when it's importing
```py
from tt_metal.tools.profiler.process_ops_logs import process_ops
```

Add $TT_METAL_HOME/ttnn to $PYTHONPATH

---

include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h
lib/Conversion/TTNNToEmitC/Utils.cpp
lib/OpModel/TTNN/Conversion.cpp
lib/OpModel/TTNN/SingletonDeviceContext.cpp
runtime/lib/ttnn/utils/utils.cpp
test/unittests/OpModel/TTNN/Conversion/TestConversion.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the cdc0135403f21b2661e6abacce368c56d1a354c9
- Remove references to ttnn.TensorMemoryLayout.SINGLE_BANK which was removed from metal in commit 0945ff2
- Follow up in https://github.com/tenstorrent/tt-mlir/issues/3909
- Disable program cache for op model to prevent llama from failing after metal commit b6d0eff
- Follow up in https://github.com/tenstorrent/tt-mlir/issues/3907

Uplift third_party/tt-metal to cdc0135403f21b2661e6abacce368c56d1a354c9 2025-06-24

---

include/ttmlir/Dialect/TTIR/Analysis/GenericInterchangeAnalysis.h
include/ttmlir/Dialect/TTIR/Transforms/Passes.td
include/ttmlir/Dialect/TTMetal/Pipelines/TTMetalPipelines.h
lib/Dialect/TTIR/Analysis/CMakeLists.txt
lib/Dialect/TTIR/Analysis/GenericInterchangeAnalysis.cpp
lib/Dialect/TTIR/Transforms/CMakeLists.txt
lib/Dialect/TTIR/Transforms/GenericApplyInterchange.cpp
lib/Dialect/TTIR/Transforms/GenericLowerDMAs.cpp
lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp
test/ttmlir/Dialect/TTIR/generic/generic_matmul_interchange.mlir

This commits implements a boilerplate pass that currently just accepts a pass override for programming
the interchange of a generic loop nest.
For example, the default matmul interchange looks like:
```
(m, n, k) -> (m, k)
(m, n, k) -> (k, n)
(m, n, k) -> (m, n)
```
This pass might choose a different interchange, such as
making the k dim the outermost loop, given interchange
(2, 0, 1):
```
(k, m, n) -> (m, k)
(k, m, n) -> (k, n)
(k, m, n) -> (m, n)
```

Support generic interchange

---

env/patches/shardy.patch

Docs build failing when StableHLO is enabled.
`ninja: error: '/opt/ttmlir-toolchain/src/shardy/shardy/dialect/sdy/transforms/export/Passes.td', needed by 'shardy/shardy/dialect/sdy/transforms/export/SdyTransformsExportPasses.md', missing and no known rule to make it`
Uppercase to lowercase in the patch file when building the environment.

fixing docs build

---

include/ttmlir/Conversion/TTIRToTTNN/Utils.h
include/ttmlir/Dialect/TTIR/Utils/Utils.h
include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
include/ttmlir/Dialect/TTNN/Transforms/Passes.td
include/ttmlir/Dialect/TTNN/Transforms/Workarounds/Decomposition/ReduceOpsRewritePattern.h
lib/Conversion/TTIRToTTIRDecomposition/TTIRToTTIRDecomposition.cpp
lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
lib/Dialect/TTIR/Transforms/EraseInverseOps/BroadcastCommutePatterns.cpp
lib/Dialect/TTIR/Transforms/EraseInverseOps/ElementwiseCommutePatterns.cpp
lib/Dialect/TTIR/Transforms/ExplicateTMs.cpp
lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
lib/Dialect/TTNN/Transforms/CMakeLists.txt
lib/Dialect/TTNN/Transforms/TTNNUniqueLocs.cpp
lib/Dialect/TTNN/Transforms/Workarounds/Decomposition/CumSumOpDimRewritePattern.cpp
lib/Dialect/TTNN/Transforms/Workarounds/Decomposition/CumSumOpRankRewritePattern.cpp
lib/Dialect/TTNN/Transforms/Workarounds/Decomposition/RepeatOpRewritePattern.cpp
lib/Dialect/TTNN/Transforms/Workarounds/TTNNWorkaroundsPatterns.cpp

Closes #3336
A pass should be added to `ttir-to-ttnn-backend-pipeline` to check if all ops have a unique `NameLoc`.
Op overrides (Conv2dConfig, OutputLayout, ...) are applied to ops using their `NameLoc`. If a ttir op is decomposed to multiple ttnn ops, they will initialy share the same location. This pass will enforce adding a suffix to locs of newly generated ttnn ops, so that the overrides are applied only to the targeted op.
E.g. `ttir.conv2d` generates `ttnn.prepare_conv2d_weights`, `ttnn.covn2d` and `ttnn.reshape`. Only `ttnn.conv2d` should have the same location (and overrides) as `ttir.conv2d`, while the locs of other ops should have an appropriate suffix added.
Added a new pass called `TTNNUniqueLocations` to check if name locations of ttnn ops are unique. If the condition is not …

Add unique locs pass

---

lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
lib/Dialect/TTIR/IR/TTIROps.cpp
lib/Dialect/TTIR/Transforms/TTIRFusing.cpp
test/ttmlir/Dialect/TTIR/fusing/kv_cache_fusing.mlir

We are looking to [support generative models](https://github.com/tenstorrent/tt-torch/issues/614)
To support generative models we need to enable KV-static cache fill/updates. Once we lower the module to stableHLO the cache update is a 20+ op pattern that start with a scatter op and can be traced all the way to a tensor containing the cache indices that need to be updated. We want to add a pattern matcher for scatter ops that represent a kv-cache fill/update and replace with a single Fill/UpdateCacheOp.
- Add a pattern matcher to TTIRFusing pass to determine if a scatter op can be replaced with a FillCacheOp or UpdateCacheOp
- Move conditions from ttir::ScatterOp::verify() into TTIRtoTTNN pass to allow kv-cache scattter ops to be rewritten into Cache ops
- Added test cases for FillCache …

Add fusing path to match/rewrite scatter op intoupdate/fill_cache

---

.github/workflows/issue-last-updated.yml

This change updates the GitHub Actions script for issue-last-updated to avoid failing the workflow  when issues like GraphQL errors or missing project item IDs occur.

fix: prevent workflow failure on GraphQL or project lookup errors

---

include/ttmlir/Dialect/TTCore/IR/TTCoreOpsTypes.td
include/ttmlir/Dialect/TTIR/IR/TTIROps.td
lib/Dialect/TTCore/IR/TTCoreOpsTypes.cpp
lib/Dialect/TTIR/Transforms/LowerToLayout.cpp
lib/Dialect/TTIR/Transforms/OptimizeTensorLayout.cpp
test/ttmlir/Dialect/TTIR/lower_to_layout.mlir

Currently we are limited on tensor size because we split all grid change and memory space change tolayouts into individual steps. 
This enables read/writes directly to/from host that are multicore. i.e. keep the grid change and mem space change as one op, when the host is involved.

D2M: Add support for multicore host read/write txs

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/Dialect/TTNN/IR/TTNNWorkaroundsPass.h
lib/Dialect/TTNN/IR/TTNNWorkaroundsPass.cpp
test/ttmlir/Silicon/TTNN/n150/simple_pad.mlir

https://github.com/tenstorrent/tt-mlir/issues/2889
tt-metal supports front padding for row-major layout only
update the workaround to only apply row-major layout in case of front padding.

Update workaround for ttnn.pad op

---

include/ttmlir/Conversion/TTIRToTTNN/Utils.h
include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/Dialect/TTNN/IR/TTNNTraits.h
include/ttmlir/Dialect/TTNN/IR/TTNNTraits.td
lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
lib/Conversion/TTIRToTTNN/Utils.cpp
lib/Dialect/TTNN/Transforms/Optimizer.cpp
lib/Dialect/TTNN/Transforms/Workarounds/Decomposition/RepeatOpRewritePattern.cpp
lib/Dialect/TTNN/Transforms/Workarounds/TTNNWorkaroundsPatterns.cpp
test/ttmlir/Dialect/TTNN/Traits/has_output_dtype_traits_negative.mlir
test/ttmlir/Dialect/TTNN/Traits/has_output_dtype_traits_positive.mlir
test/ttmlir/Dialect/TTNN/Transforms/Workarounds/add_integer_broadcasting_workaround.mlir
test/ttmlir/Dialect/TTNN/Transforms/Workarounds/binary_ops_workaround.mlir
test/ttmlir/Dialect/TTNN/Transforms/ttnn_create_input_gens_0.mlir
test/ttmlir/Dialect/TTNN/data_movement/data_type_cast/to_dtype_folding.mlir
test/ttmlir/Dialect/TTNN/data_movement/data_type_cast/typecast_folding.mlir
test/ttmlir/Dialect/TTNN/optimizer/insert_memreconfig_const_eval.mlir
test/ttmlir/Dialect/TTNN/test_remove_dead_values_pass.mlir
test/ttmlir/EmitC/TTNN/models/mnist_sharded.mlir

N/A
Recently we introduced the output_dtype attribute for binary ops in this PR:
https://github.com/tenstorrent/tt-mlir/pull/3934
However, we didn't add any verification regarding it.
Added a new trait on the binary ops to verify that the layout data type is in sync with output_dtype op attribute.

Adding verifier for output_dtype attribute

---

docs/CMakeLists.txt

The [docs](https://docs.tenstorrent.com/tt-mlir/autogen/md/Module/apis.html) generated by sphinx are showing up blank.
To the best of my knowledge, the docs weren't loading the `ttir_builder` python package because they were being built before the python packages. A dependency was added to correct that. 
Steps to reproduce error on main:
```
rm -rf build
cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang-17 -DCMAKE_CXX_COMPILER=clang++-17 -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DTTMLIR_ENABLE_RUNTIME=ON -DTT_RUNTIME_ENABLE_PERF_TRACE=ON -DTTMLIR_ENABLE_RUNTIME_TESTS=ON -DTTMLIR_ENABLE_STABLEHLO=ON -DTT_RUNTIME_DEBUG=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DTTMLIR_ENABLE_OPMODEL=ON
cmake --build build -- docs
```

Sphinx autogenerated docs dependency fix

---

include/ttmlir/Dialect/TTCore/Transforms/Passes.td
lib/Dialect/TTCore/Transforms/TTCoreRegisterDevice.cpp

TTCore dialect dependency was missing from the tablegen file. The pass simply crashed when it tried to print the generated IR with ``'mlir::tt::CPUDescAttr' because storage uniquer isn't initialized`.
Added the dependency in the tablegen file to fix this.

Add mising dialect dependencies for `TTCoreRegisterDevicePass`

---

.github/workflows/build-and-test.yml

/
`Ignore files` job in the CI was only checking if any files other than `./docs/*` have been **changed**, not including **deleted** ones in that list. 
That caused the `On PR` workflow to be skipped if your last commit only removed files.
We are now checking for deleted files as well when checking whether to run the `On PR` workflow.
We are now outputting the list of deleted files and checking deletions (in addition to changes) in files. The check is happening in the `build-image` job.

Check for deleted files as well in the CI

---

runtime/include/tt/runtime/detail/ttmetal/ttmetal.h
runtime/include/tt/runtime/detail/ttnn/ttnn.h
runtime/include/tt/runtime/runtime.h
runtime/lib/runtime.cpp
runtime/lib/ttmetal/runtime.cpp
runtime/lib/ttnn/runtime.cpp
runtime/python/runtime/runtime.cpp

We didn't have a runtime API to configure persistent kernel cache.
Added API to configure persistent kernel cache

Add runtime API to configure persistent kernel cache

---

runtime/include/tt/runtime/detail/ttnn/operations/utils.h
runtime/include/tt/runtime/detail/ttnn/utils.h
runtime/include/tt/runtime/workarounds.h
runtime/lib/common/system_desc.cpp
runtime/lib/common/workarounds.cpp
runtime/lib/ttnn/operations/ccl/collective_permute.cpp
runtime/lib/ttnn/operations/utils/utils.cpp
runtime/lib/ttnn/runtime.cpp
runtime/lib/ttnn/utils/utils.cpp
runtime/tools/ttrt/ttrt/common/run.py

Related to #4023
Untilize on device fails for various tt-torch models on blackhole
untilize on host for blackhole as a workarounds. Add blackholeWorkarounds flag to track various blackhole workarounds in runtime.
FYI @sshonTT

Add blackhole workarounds, untilize on host for blackhole

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

[#3940](https://github.com/tenstorrent/tt-mlir/issues/3940)
Adding constraints for `LinearOp`.
Added support for `getOpConstraints` and `getOpRuntime` for `LinearOp`

Add constraints API for LinearOp

---

lib/Dialect/TTIR/Transforms/TTIRFusing.cpp
test/ttmlir/Dialect/TTIR/fusing/pooling_pad_fusing.mlir

N/A
We may receive an IR which explicitly places padding for a pooling op on the pooling input. This can make it impossible to commute the reshape + permute that is inserted on the input of the op during `TTIRFlattenSlidingWindow`. Also, this is unnecessary. 
Add a pattern to `TTIRFusing` to fuse PadOp into PoolingOp

Add fusion pattern to fuse PadOp into PoolingOp padding attribute

---

include/ttmlir/Dialect/TTNN/Transforms/Workarounds/Decomposition/UpsampleOpRewritePattern.h
include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
lib/Dialect/TTNN/IR/TTNNWorkaroundsPass.cpp
lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
lib/Dialect/TTNN/Transforms/CMakeLists.txt
lib/Dialect/TTNN/Transforms/Optimizer.cpp
lib/Dialect/TTNN/Transforms/Workarounds/Decomposition/UpsampleOpRewritePattern.cpp
lib/Dialect/TTNN/Transforms/Workarounds/TTNNWorkaroundsPatterns.cpp
lib/Dialect/TTNN/Utils/TransformUtils.cpp
test/ttmlir/Dialect/TTNN/Transforms/Workarounds/upsample_sharding_workaround.mlir
test/ttmlir/Silicon/TTNN/n150/optimizer/upsample_layout_workaround.mlir
test/ttmlir/Silicon/TTNN/n150/simple_upsample.mlir

https://github.com/tenstorrent/tt-mlir/issues/3396
https://github.com/tenstorrent/tt-mlir/issues/4051
Commit from https://github.com/tenstorrent/tt-mlir/pull/3978 had to be reverted because of some friction between the way optmizer and TTNN workarounds treat workarounds.
- Reapply those changes
- Made some changes in optimizer necessary for this workaround to work correctly

Reapply "Support `UpsampleOp` in `bilinear` mode (#3978)"

---

lib/Conversion/TTIRToLinalg/TTIRToLinalg.cpp
test/python/golden/test_ttir_ops.py
test/ttmlir/Conversion/TTIRToLinalg/relu.mlir

https://github.com/tenstorrent/tt-mlir/issues/4062
There was no implementation of ttir.relu in linalg dialect.
Implemented ttir relu operation using linalg maxop by compering input and a zero and taking maximum. 
This way ttir.relu is lowered to linalg dialect.

Implemented ttir relu to linalg

---

include/ttmlir/Dialect/TTNN/Analysis/DFShardingPolicy.h
include/ttmlir/Dialect/TTNN/Analysis/L1ChainConfig.h
include/ttmlir/Dialect/TTNN/Analysis/MemoryLayoutAnalysisPolicy.h
include/ttmlir/Dialect/TTNN/Analysis/MemoryLayoutAnalysisProgressTracker.h
lib/Dialect/TTNN/Analysis/DFShardingPolicy.cpp
lib/Dialect/TTNN/Analysis/ShardSolver.cpp
lib/Dialect/TTNN/Transforms/Optimizer.cpp

Related to https://github.com/tenstorrent/tt-mlir/issues/3954
Until now we calculated L1 usage as sum of input tensor, CB peak usage and output tensor. However, given op can allocate more buffers for its internal usage (for example HaloOp result within Conv2d). This consumption is seen in the response of `OpModel::getOpConstraints` as tensor usage. Here I am changing, L1 Usage to be sum of input tensor, CB peak size and buffers peak size. Note that CBs and Buffers are exclusive in allocation tracker.

Fix L1 calc in ShardSolver & add progress tracker to MLA

---

lib/Dialect/TTIR/Transforms/Allocate.cpp
test/ttmlir/Dialect/TTIR/allocate/allocate.mlir
test/ttmlir/Dialect/TTIR/allocate/allocate_negative.mlir

To support ongoing dev/testing, make interim `ttir-allocator` changes so that it assigns DRAM addresses instead of just ignoring such allocs.
The allocator had originally used a single instance of `AllocationPlanner::Context` that was implicitly dedicated to L1. This has now been generalized into a per-memspace-array of contexts and the pass logic has been updated to do both L1 and DRAM as two independent problems.
Example:
```mlir
!memreftype_l1   = memref<1x1x4x4x!ttcore.tile<32x32, f32>, #ttcore.shard<1024x1024>, #ttcore.memory_space<l1>>
!memreftype_dram = memref<1x1x8x8x!ttcore.tile<32x32, f32>, #ttcore.shard<1024x1024>, #ttcore.memory_space<dram>>
func.func @allocate_mixed() -> (!memreftype_l1, !memreftype_dram, !memreftype_l1, !memreftype_dram, !memreftype_l1) {
%alloc_0 = …
```

extend default allocator L1 algorithm to DRAM memspace

---

docs/src/ttir-builder/ttir-builder.md
include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
lib/Conversion/TTIRToTTKernel/TTIRToTTKernel.cpp
lib/Dialect/TTKernel/IR/TTKernelOps.cpp
test/ttmlir/Conversion/TTKernelToEmitC/ttkernel.mlir
test/ttmlir/Translate/TTKernel/ttkernel_compute.mlir
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 81412069f02b01a483cc0fb29fec5c9bf28ac1ab
- Update untilize_init API to match tt-metal commit 46a339c6a5
- Removed output circular buffer param
- compute_kernel_hw_startup was already being called before untilize_init, so did not make that change

Uplift third_party/tt-metal to 81412069f02b01a483cc0fb29fec5c9bf28ac1ab 2025-07-18

---

.github/workflows/build-and-test.yml
test/python/golden/conftest.py

No Issue, QoL change
The `--allow-subset-mesh` flag allowed for generating tests on devices that match subsets of the intended program mesh. This behavior is desirable by default, so the flag is inverted and is now called `--require-exact-mesh`. 
- The flag was inverted
- The CI matrix has been updated to preserve behavior of exact mesh matching

Invert `--allow-subset-mesh` `pytest` flag

---

env/activate
env/activate.fish
lib/OpModel/TTNN/CMakeLists.txt
runtime/lib/common/system_desc.cpp
test/lit.cfg.py
test/unittests/lit.cfg.py
third_party/CMakeLists.txt

https://github.com/tenstorrent/tt-mlir/issues/1869
HAL now abstracts all hardware specific APIs. 
Codebase should no longer depend on ARCH specific include paths.
- Remove ARCH_NAME env var
- Remove ARCH based include paths
- Replace last remaining ARCH specific APIs with HAL API in system desc creation
- Existing tests [[pass in CI]](https://github.com/tenstorrent/tt-mlir/actions/runs/16371395757)

#1869  Remove ARCH specific includes and use HAL APIs instead

---

lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
lib/Conversion/TTNNToEmitC/TTNNToEmitCPass.cpp
test/ttmlir/EmitC/TTNN/other/const-eval-device.mlir
test/ttmlir/EmitC/TTNN/other/const-eval.mlir

x
`ttcore.ArgumentType` arg attrs would remain on FuncOp after TTNN->EmitC conversion, causing the translation (`ttmlir-translate --mlir-to-cpp`) to fail, citing "unregistered dialects".
Remove all arg attrs from `FuncOp`, and update tests to not use the hotfix (`--allow-unregistered-dialects`)

Remove arg attrs from FuncOp when going to EmitC

---

include/ttmlir/Dialect/TTNN/Transforms/Passes.td
include/ttmlir/Dialect/TTNN/Types/Types.h
lib/Dialect/TTNN/IR/TTNNOps.cpp
lib/Dialect/TTNN/Transforms/TTNNTraceHoistTransform.cpp
runtime/include/tt/runtime/detail/ttnn/types/types.h
runtime/lib/ttnn/types/types.cpp
test/ttmlir/Dialect/TTNN/trace/creation_no_consteval.mlir
test/ttmlir/Dialect/TTNN/trace/single_add_no_consteval.mlir

We should be skipping creation ops for trace since they're not supported. Conv verification was failing when conv ops are hoisted into trace functions if their weights are being prepared with `prepare_conv2d_weights` op. We were allocating device buffers for constants/params (Thanks @svuckovicTT  for catching this).
* Creation ops are now skipped in the trace hoist transform pass.
* When within a trace function, conv verifier will follow the function argument to the original location where the input is generated, and run the verification logic on the actual input instead of the function parameter.
* Only allocate separate buffers on device for inputs, for constants and parameters, use the original tensor directly.

Skip creation ops for trace capture, update conv verify logic, don't allocate empty slots for constants/params

---

lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp

We have some redundant looping around our copy/pack instructions because of how we generate those loop nests. This is a performance hit.
Add the affine loop coalescing pass to the ttmetal pipeline to optimize away these redundant loops.
Before:
```cpp
for %arg2 = %2 to %0 step %1  : !emitc.size_t {
%10 = expression : !emitc.size_t {
%11 = add %9, %arg2 : (!emitc.size_t, !emitc.size_t) -> !emitc.size_t
yield %11 : !emitc.size_t
}
for %arg3 = %2 to %0 step %1  : !emitc.size_t {
call_opaque "pack_tile"(%arg2, %7, %10) {template_args = [true]} : (!emitc.size_t, !emitc.opaque<"::tt::CB">, !emitc.size_t) -> ()
}
}
```
After:
```cpp
for %arg2 = %2 to %3 step %1  : !emitc.size_t {
%13 = div %arg2, %0 : (!emitc.size_t, !emitc.size_t) -> !emitc.size_t
%14 = add %12, %13 : (!emitc.size_t, …
```

D2M: Add affine loop coalescing optimization to ttmetal pipeline

---

include/ttmlir-c/TTKernelTypes.h
include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
include/ttmlir/Dialect/TTKernel/IR/TTKernelOpsTypes.td
lib/CAPI/TTKernelTypes.cpp
lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
python/TTKernelModule.cpp
test/pykernel/demo/eltwise_sfpu_demo.py
test/pykernel/demo/matmul_multicore_demo.py
test/pykernel/demo/matmul_singlecore_demo.py
test/pykernel/demo/vecadd_multicore_demo.py
test/pykernel/unit_tests.py
test/ttmlir/Conversion/TTKernelToEmitC/ttkernel.mlir
tools/pykernel/ast.py
tools/pykernel/op.py
tools/pykernel/types.py

[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/4069)
As described in issue.
- Added new ops `TensorAccessorArgs`, `TensorAccessor` constructors and member functions
- Added new ttkernel types for `TensorAccessor`
- ttkernel -> emitc conversion pass for new ops
- switched over both demos to use `TensorAccessor` instead of `InterleavedAddrGenFast`
- filecheck unit test for new ops
ToDo before push: 
Notes: 
- ~right now, you have to pass both `CTA` and `CRTA` offset, unlike in metal where you only need to pass `CTA`~
- currently setup so that `CTA_OFFSET` should be the # of cbs passed through `compile_time_args` when creating the kernel
- ~not able to use any member functions of `TensorAccessor`, continue investigating how we could do this.~
- ~eg: …

[PyKernel] Enable TensorAccessor

---

runtime/include/tt/runtime/detail/ttnn/types/types.h
runtime/lib/ttnn/operations/cache/load_cached.cpp
runtime/lib/ttnn/operations/mlir_native/func_call.cpp
runtime/lib/ttnn/operations/trace/capture_or_execute_trace.cpp
runtime/lib/ttnn/types/types.cpp

Current tensor pool only has API to insert ttnn tensors, causing us to unwrap consteval tensors before insertion. This causes version mismatches later on.
Add API to insert runtime tensors directly. This mostly solves the trace perf degradation seen on resnet.

Add insertRuntimeTensorAndValidate API to preserve tensor version info

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

#4067 
Adding constraints for `GreaterThanOp`.
Added support for `getOpConstraints` and `getOpRuntime` for `GreaterThanOp`.

Add constraints API for GreaterThan

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

#4067 
Adding constraints for `ExpOp`, `LogOp`, `TanhOp`.
Added support for `getOpConstraints` and `getOpRuntime` for `ExpOp`, `LogOp`, `TanhOp`.

Add constraints API for exp, log, and tanh

---

runtime/lib/runtime.cpp
runtime/lib/ttnn/runtime.cpp

closes https://github.com/tenstorrent/tt-mlir/issues/4242
Runtime provides 'getTensorDataBuffer' function to extract the data from ttnn::Tensor and return it as data vector. However, it assumes that the underlying tensor will always contain some data and assert otherwise. This assumption is not true in case of empty tensor.
Update the functionality to return empty data vector in case of empty 'ttnn::Tensor'

Return empty data vector

---

lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

I didn't create an issue since this was a quick fix.
@rpavlovicTT brought this issue up today. He was getting `segfault` with constraint APIs of `embeddingOp` when the output layout was `null`.
`embeddingOp` didn't handle the case where `outputLayout` is `nullptr`.
- This PR adds a fix to `embeddingOp`'s constraint APIs to handle `null` output layout.
- It also adds a UT that tests this case.

fix embeddingOp Constraint API to handle nullptr output layout

---

runtime/lib/ttnn/debug/CMakeLists.txt
runtime/lib/ttnn/operations/CMakeLists.txt
runtime/lib/ttnn/types/CMakeLists.txt
runtime/lib/ttnn/utils/CMakeLists.txt
runtime/test/ttnn/CMakeLists.txt
tools/ttnn-standalone/CMakeLists.txt

none
-mavx2 does not enable some additional x86 ISA features that can help performance. Using -march=x86-64-v3 ensures that all of the Haswell-era ISA features are used by the compiler.
Per the x86-64 psABI, here is the complete list of features mandated by x86-64-v3:
- AVX
- AVX2
- BMI1
- BMI2
- F16C
- FMA
- LZCNT
- MOVBE
- OSXSAVE
Change compiler flags in cmake

Switch -mavx -mavx2 to -march=x86-64-v3

---

runtime/tools/ttrt/ttrt/common/run.py

Closes #4228 
`ttrt run -h` was errring out due to unescaped `%` chars in a `help` str.
`%`s have been escaped

Escape `%` characters in  `ttrt` `argparse` help str

---

include/ttmlir/Dialect/TTNN/IR/TTNNOpModelInterface.td
include/ttmlir/OpModel/TTNN/Conversion.h
include/ttmlir/OpModel/TTNN/SingletonDeviceContext.h
include/ttmlir/OpModel/TTNN/TTNNOpConstraints.h
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
include/ttmlir/OpModel/TTNN/TTNNOpsModelCache.h
lib/Dialect/TTNN/Analysis/LegalTensorLayoutAnalysis.cpp
lib/Dialect/TTNN/Analysis/ShardSolver.cpp
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/Dialect/TTNN/Transforms/TTNNPrepareConv2dWeightsAndBias.cpp
lib/OpModel/TTNN/Conversion.cpp
lib/OpModel/TTNN/SingletonDeviceContext.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Conversion/TestConversion.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

https://github.com/tenstorrent/tt-mlir/issues/4245
Namespace `op_model::ttnn` clearly violates hierarchical order, as `op_model` belongs to `ttnn`, not vice-versa. This has led to the necessity to specify a fully qualified name for all types in `ttnn` namespace.
Changed the order to `ttnn::op_model`. Changed fully qualified names to unqualified (or partially qualified in case of types belonging to `ttcore` ns).
Thanks @rpavlovicTT for suggesting this change.

Rename namespace `op_model::ttnn` to `ttnn::op_model`

---

.github/CODEOWNERS
include/ttmlir/Conversion/TTNNToEmitPy/EmitPyConversion.h
include/ttmlir/Dialect/EmitPy/IR/EmitPyOps.td
include/ttmlir/Dialect/EmitPy/IR/EmitPyTypes.td
lib/Conversion/TTNNToEmitPy/TTNNToEmitPy.cpp
lib/Target/Python/TranslateToPython.cpp
test/ttmlir/Dialect/EmitPy/ttir_to_emitpy_pipeline_sanity.mlir

Previously, all TTNN to EmitPy op conversions required explicitly calling ```replaceOpWithNewOp``` within each ```OpConversionPattern```. This approach made it necessary to maintain numerous utility functions to correctly pass operands and attributes. As a result, support for some optional op attributes was previously missing due to this complexity.
- Introduced the ```EmitPyTTNNEmitter``` class (based on the ```EmitCTTNNEmitter``` design) as an abstraction layer to simplify and centralize rewriting of TTNN ops.
- Refactored the conversion patterns for currently supported TTNN ops to use the new emitter, improving code clarity and reducing repetitive code.
- Fully supported attributes of the currently covered ops.
- Emitted Python code and the EmitPy dialect now use keyword arguments for …

Refactor TTNN to EmitPy conversion using EmitPyTTNNEmitter

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

#4195 
Added constraints API for almost all unary eltwise ops.
The only ones pending are `cbrtOp` and `BitwiseNotOp`. I will add them in a later PR as they need the test files to be updated slightly.

Add constraints for most unary eltwise ops.

---

.gitignore

Add .claude/ directory to .gitignore
Adds the .claude/ directory to the project's gitignore file to prevent local Claude Code configuration files from being tracked in version control.

Adding claude local files to gitignore list

---

lib/Target/TTNN/TTNNToFlatbuffer.cpp

This PR updates the PermuteOp flatbuffer serialization to use getMemoryConfigIfNeeded(cache, op) instead of directly accessing op.getMemoryConfig(). The getMemoryConfigIfNeeded function:
1. First attempts to get the memory config from the op's explicit attribute
2. If that's null, derives the memory config from the output tensor's layout information

Fix PermuteOp flatbuffer serialization to respect memory layout changes

---

runtime/include/tt/runtime/detail/ttmetal/ttmetal.h
runtime/include/tt/runtime/workarounds.h
runtime/lib/common/workarounds.cpp
runtime/lib/ttmetal/executor.cpp
runtime/lib/ttmetal/executor.h
runtime/lib/ttmetal/executor_utils.h
runtime/lib/ttmetal/runtime.cpp
runtime/tools/ttrt/ttrt/common/run.py

https://github.com/tenstorrent/tt-mlir/issues/4179
Current D2M runtime uses APIs for single device computation. As a first step of enabling multi-device in D2M, we should use APIs for multi-devices (tt-mesh and tt-distributed).
Update D2M runtime using multi-device aware APIs such as meshBuffer and meshEvent. There exists some issue in mesh_event synchronization, so the return time event insertion is not enabled by default. It will be updated later once the issue (https://github.com/tenstorrent/tt-mlir/issues/4181) is resolved.

Initial implementation of multi-device aware D2M runtime 

---

lib/Dialect/TTNN/Transforms/Workarounds/Decomposition/ReduceScatterOpRewritePattern.cpp
lib/Dialect/TTNN/Transforms/Workarounds/TTNNWorkaroundsPatterns.cpp
test/ttmlir/Dialect/TTNN/ccl/all_reduce/all_reduce_positive.mlir

closes #4236 
here are two separate workaround implementations - one for Reduce Scatter and another for All Reduce - that contain almost identical logic. This duplication makes the codebase harder to maintain and increases the risk of inconsistencies.
Removed redundant workaround in All Reduce
- The special-case code that handled dim < 4 tensors inside the All Reduce workaround has been deleted.
- All Reduce is now transformed only by decomposing it into Reduce Scatter + All Gather, without altering tensor ranks or layouts.
- Centralized handling of dim < 4 Reduce Scatter
- Any dim < 4 tensors produced by the All Reduce decomposition are now handled exclusively by the existing Reduce Scatter workaround.
Updated Reduce Scatter workaround implementation
- Updated the implementation so that …

Remove duplicated workaround around reduce_scatter

---

lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
runtime/include/tt/runtime/detail/ttnn/ttnn.h
runtime/lib/ttnn/operations/data_movement/slice.cpp
test/python/golden/test_ttir_ops.py
test/ttmlir/Silicon/TTNN/n150/pooling/max_pool2d.mlir
test/ttmlir/Silicon/TTNN/n150/pooling/max_pool2d_unsupported.mlir
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the d78b2f9ae3d33c468d71c99ee5e8ab7f3606c89d
- Update implicit smallvec to span conversions after std span used in metal change 8549c9458a
- Follow up in https://github.com/tenstorrent/tt-mlir/issues/4312 to clean up emitc implementation
- Move MaxPool2D ops with non 1 dilation dims to unsupported testlist due to tt-metal commit a79ebb8
- Follow up in https://github.com/tenstorrent/tt-mlir/issues/4314 to shift left the dilation assertion to compile time
- Reset device in between tests for opmodel after metal commit 90cd6e4
- Update cbsize for logicalAnd op in opmodel tests after metal commit 662a1a3
- Update where op path after metal commit d7cba8cb92
- Follow up to investigate failure in https://github.com/tenstorrent/tt-mlir/issues/4313
Bisect …

Uplift third_party/tt-metal to d78b2f9ae3d33c468d71c99ee5e8ab7f3606c89d 2025-07-31

---

include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp

N/A
- During rebase https://github.com/tenstorrent/tt-mlir/pull/4230, I forgot to remove `outputShape` from `WhereOp`, which is a redundant parameter. Removing it could enable some future refactoring.
- After https://github.com/tenstorrent/tt-mlir/pull/4250, fully qualified names are not necessary, but they were added in https://github.com/tenstorrent/tt-mlir/pull/4271
- Removed `outputShape` from `WhereOp`
- Removed fully qualified names

`OpModel` cleanup for future refactoring

---

include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h

closes https://github.com/tenstorrent/tt-mlir/issues/4321
EmitC conversion generates same code for `ttnn::distributed::MeshDevice` and `ttnn::distributed::MeshDevice *` which causes compilation to fail.
Create a `ttnn::distributed::MeshDevice &` variable to access the `MeshDevice *ptr` and pass it to the TTNN ops.
Note: TTNN API has deleted `copy` and `move` constructors for `MeshDevice`; so other solutions requiring copy/move do not work.

[EmitC] Pass MeshDevice object properly to TTNN ops

---

.github/CODEOWNERS
docs/src/builder/stablehlo-builder.md
tools/builder/stablehlo/stablehlo_builder.py
tools/builder/stablehlo/stablehlo_utils.py

Issue: https://github.com/tenstorrent/tt-mlir/issues/4333
This PR adds shardy support into stablehlo builder. It allows users to generate stablehlo graphs with shardy ops and attribute indentations. For example
```
from builder.base.builder import Operand
from builder.stablehlo.stablehlo_builder import StableHLOBuilder
from builder.stablehlo.stablehlo_utils import build_stablehlo_module
shapes = [(32, 32), (32, 32)]
def model(in0: Operand, in1: Operand, shlo_builder: StableHLOBuilder):
tensor_sharding_attr = shlo_builder.tensor_sharding_attr(
mesh_name="mesh",
dimension_shardings=[
shlo_builder.dimension_sharding_attr(
axes=[shlo_builder.axis_ref_attr(name="x")],
is_closed=True,
),
shlo_builder.dimension_sharding_attr(
axes=[shlo_builder.axis_ref_attr(name="y")],
is_closed=False,
)
]
) …
```

#4333: Added support for shardy dialect in stablehlo builder.

---

runtime/tools/ttrt/ttrt/binary/__init__.py

`ttrt.binary` has an incorrectly named function. 
Corrected function name

ttrt read quick bug fix

---

runtime/tools/ttrt/ttrt/common/util.py
test/python/golden/conftest.py

Currently `ttrt` will run files in order they are created. Pytest will run tests sequentially based on ordering in test/python/golden/test_ttir_ops.py
Sorted ttrt runs alphabetically for easier debugging. Also sorted pytest.

sort the files for ttrt runs and pytest

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/Dialect/TTNN/IR/TTNNWorkaroundsPass.h
lib/Dialect/TTNN/IR/TTNNWorkaroundsPass.cpp
lib/Target/TTNN/TTNNToFlatbuffer.cpp
test/ttmlir/Dialect/TTNN/constant/positive/simple_constant_positive.mlir
test/ttmlir/Dialect/TTNN/quantization/simple_dequantize.mlir
test/ttmlir/Dialect/TTNN/quantization/simple_quantize.mlir
test/ttmlir/Dialect/TTNN/quantization/simple_requantize.mlir
test/ttmlir/Dialect/TTNN/simple_get_dimension_size.mlir
test/ttmlir/EmitC/TTNN/tensor/full.mlir
test/ttmlir/Silicon/StableHLO/n150/Constant/constant_i32.mlir
test/ttmlir/Silicon/StableHLO/n150/Constant/constant_i64.mlir
test/ttmlir/Silicon/StableHLO/n150/get_dimension_size_op.mlir
test/ttmlir/Silicon/TTNN/n150/eltwise/unary/get_dimension_size/get_dimension_size.mlir
test/ttmlir/Silicon/TTNN/n150/perf/test_perf_dequantize.mlir
test/ttmlir/Silicon/TTNN/n150/perf/test_perf_quantize.mlir
test/ttmlir/Silicon/TTNN/n150/perf/test_perf_requantize.mlir
test/ttmlir/Silicon/TTNN/n150/quantization/simple_dequantize.mlir
test/ttmlir/Silicon/TTNN/n150/quantization/simple_quantize.mlir
test/ttmlir/Silicon/TTNN/n150/quantization/simple_requantize.mlir

TTNN Full op supports int32 output.
Removed workaround and updated FileChecks in relevant tests. No builder test for Full, so nothing to update there.

Removing full workaround and updating tests

---

lib/Dialect/TTIR/Transforms/TTIRFusing.cpp
test/ttmlir/Dialect/TTIR/fusing/zero_maximum_to_relu.mlir

Currently in many cases we're expressing relu operations as zeros -> maximum.
Added fusion pattern to fuse zeros -> maximum into relu, with this hopefully all ops within resnet can be captured either in consteval or trace.

Add fusion pattern for zeros creation and maximum -> relu

---

test/pykernel/unit_tests.py
tools/pykernel/CMakeLists.txt
tools/pykernel/ast.py
tools/pykernel/kernel_types.py
tools/pykernel/op.py

[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/4160)
Currently, if we want to access member functions, we call the ttkernel op, so it lowers properly: 
```
noc_addr = tensor_accessor_get_noc_addr(...)
```
Instead, want to be do something like below in python and have it lower properly to the right ttkernel function
```
addr_gen = TensorAccessor(...)
noc_addr = addr_gen.get_noc_addr(...)
```
Both of the above will map to `ttkernel.tensor_accessor_get_nocc_addr` but the latter is just better..
- `PyKernelClassBase` as a base class for any future kernel types
- `TensorAccessor` to provide access to member functions used by TensorAccessor in kernels
- `ClassRegistry` as a way to map to the right PyKernelClass based on the mlir stored in the ast symbol table.
- …

[PyKernel] Attributes node implementation

---

include/ttmlir/Target/TTMetal/command.fbs
runtime/include/tt/runtime/workarounds.h
runtime/lib/common/workarounds.cpp
runtime/lib/ttmetal/executor.cpp
runtime/lib/ttmetal/runtime.cpp
runtime/tools/ttrt/ttrt/common/run.py

https://github.com/tenstorrent/tt-mlir/issues/4181
There was a bug in waiting ttmetal MeshEvent at return time, leading to hanging. It turns out that current wait() uses single device EventSynchronize while it is supposed to use distributed::EventSynchronize(). 
1. Fix bug in D2M wait() to use MeshEvent and distributed::EventSynchronize().
2. Remove some unnecessary commands as we migrate to MeshEvent from Event.

[D2M] Fix bug in wait() and remove unnecessary commands

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/Dialect/TTNN/IR/TTNNWorkaroundsPass.h
lib/Dialect/TTNN/IR/TTNNOps.cpp
lib/Dialect/TTNN/IR/TTNNWorkaroundsPass.cpp
test/ttmlir/Dialect/TTNN/Transforms/Workarounds/sort_workaround.mlir
test/ttmlir/Dialect/TTNN/sort/sort_tests_negative.mlir

closes https://github.com/tenstorrent/tt-mlir/issues/4405
ttnn::sort generates indices of type uint16. If ttir.sort generates indices with different type then runtime crashes due to mismatch in generated and expected data type.
Add datatype workaround for SortOp indices.

[TTNNWorkaround] SortOp indices

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
test/unittests/OpModel/TTNN/OpModelFixture.h

#4195
Added constraints for `CbrtOp` and `BitwiseNotOp`.
Testing in `TestOpModelLib.cpp`:
Both of these ops have different memory usage compared to the rest of the unary ops. In the case of `BitwiseNot` the memory numbers are doubled. For `Cbrt`, `expectedCbSize` becomes (*1.25 + 2048), and `expectedPeakSize` becomes 3x. Instead of refactoring the testing framework to be able to set these values, and given that we will eventually changes EQ to GE/LE (#4288), I added `EXPECT_EQ_OR_GE()` that uses GE given a flag. GE test is used for both `Cbrt` and `BitwiseNot`.
`BitwiseNot` only works with int32. Because of this, I created `CreateTiledLayoutInt32()` and `RunTestInt32()` to be used for `BitwiseNot` and in case any other future op is like this.

Add constraints for Cbrt and BitwiseNot

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
lib/Dialect/TTNN/IR/TTNNOps.cpp
test/ttmlir/Dialect/TTNN/data_movement/reshape/reshape_folding_test_ttnn.mlir

#4428 
TTIR Fusing and TTNN decompositions might create reshape operations that should have been folded. There is reshape op folding in TTIR, but there isn't reshape op folding in TTNN.
Added Reshape Op folding in TTNN and added a test file.

Add folder for TTNN Reshape Op #4428

---

test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 28a524e2c1c53c986b0c31884ba9d168a5021f7d
- Disable opmodel test for SoftmaxSharded after metal commit 89c8ab6

Uplift third_party/tt-metal to 28a524e2c1c53c986b0c31884ba9d168a5021f7d 2025-08-12

---

include/ttmlir/Dialect/TTNN/Transforms/Workarounds/Decomposition/ConcatOpReshapeRewritePattern.h
lib/Dialect/TTNN/Transforms/CMakeLists.txt
lib/Dialect/TTNN/Transforms/Workarounds/Decomposition/ConcatOpReshapeRewritePattern.cpp
lib/Dialect/TTNN/Transforms/Workarounds/TTNNWorkaroundsPatterns.cpp
test/ttmlir/Dialect/TTNN/Transforms/Workarounds/concat_workaround.mlir

closes https://github.com/tenstorrent/tt-mlir/issues/4425
ttnn::concat op crashes for 1D inputs
Add a reshape workaround for 1D inputs.

[TTNNWorkaround] ConcatOp with one dimensional input tensors

---

.github/CODEOWNERS

N/A
@sgholamiTT has made extensive contributions to op model and is very familiar with the code. I am currently the only reviewer/owner in a NA timezone and he will help distribute the workload

Add sgholamiTT as codeowner for op model

---

lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
lib/Dialect/TTIR/Transforms/TTIRFusing.cpp
test/ttmlir/Conversion/StableHLOToTTIR/unary/erf_mhlo_op.mlir
test/ttmlir/Dialect/TTIR/fusing/gelu_fusing.mlir

N/a
- torch-xla will provide calls to `erf` in the form `stablehlo.custom_call(@mhlo.erf)`. We do not lower this yet
- Gelu is provided in a multitude of forms. These are some eltwise operations surrounding a call to `erf` or `tanh`
- Lower `stablehlo.custom_call(@mhlo.erf)` to `ttir.erf`
- Add fusion pattern, capable of fusing a few different forms of `gelu` as they are presented from torch-xla and jax
- Add test for SHLO lowering
- Add tests for `gelu` fusion.
**NOTE**: The `erf` based version of `gelu` as it is provided from jax lowers `erf` as a polynomial approximation. Unlike torch-xla which conveniently provides `stablehlo.custom_call(@mhlo.erf)`. tt-xla currently has a monkeypatch to return `gelu` as a composite call, which is lowered properly, thereby bypassing this issue. So, …

Add conversion from `stablehlo.custom_call(@mhlo.erf)` to `ttir.erf`, add `gelu` fusion pattern

---

test/python/golden/test_ttir_ops_llmbox.py
test/python/golden/test_ttir_ops_n300.py
tools/builder/CMakeLists.txt
tools/builder/base/builder.py
tools/builder/base/builder_golden.py
tools/builder/base/sharded_tensor.py
tools/builder/ttir/ttir_builder.py

closes #4339
closes #4173
The TTIR builder cannot currently generate golden tensors for graphs that include CCL operations.
Introduced ShardedTensor — a class for multi-device tensors that:
- stores a List[torch.Tensor]
- provides access to a tensor on a specific device
- provides access to tensors grouped by cluster_axis
- supports most torch.* functions by applying them shard-wise
Updated TTIR golden library to work with ShardedTensor.
Removed ccl_proxy; replaced calls with op_proxy.
Updated multi-device test cases to use TTIR Builder generated goldens instead of pseudo goldens.

Generate golden tensors for graphs with CCL ops using the TTIR builder

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

#4198
Constraints for `min` and `max` reduction ops.
The ordering of tests in `TestOpModelLib.cpp` causes `min` `getOpRuntime()` to hang on the final test. As a temporary workaround, I added `SingletonDeviceContext::resetInstance();` before `getOpRuntime()`. We will eventually remove all resets (Issues: #4316, https://github.com/tenstorrent/tt-metal/issues/25772).

Add constraints for min, max reduction ops

---

lib/OpModel/TTNN/TTNNOpModel.cpp

There is a linker error in Debug build
```
ld.lld: error: undefined symbol: typeinfo for llvm::ErrorInfoBase
>>> referenced by TTNNOpModel.cpp
>>>        TTNNOpModel.cpp.o:(typeinfo for llvm::ErrorInfo<llvm::ErrorList, llvm::ErrorInfoBase>) in archive lib/OpModel/TTNN/libTTNNOpModelLib.a
>>> did you mean: vtable for llvm::ErrorInfoBase
>>> defined in: /opt/ttmlir-toolchain/lib/libLLVMSupport.a(Error.cpp.o)
clang++-17: error: linker command failed with exit co
```

Fix debug build

---

lib/Dialect/TTNN/IR/TTNNWorkaroundsPass.cpp
test/python/golden/test_ttir_ops.py

- Remove some binary op workarounds for Int32 after recent metal changes
- Operations that still do not support Int32 are tracked here: https://github.com/issues/created?issue=tenstorrent%7Ctt-metal%7C25112

Remove some binary op workarounds

---

third_party/CMakeLists.txt
tools/tt-alchemist/csrc/InstallComponents.cmake

This PR uplifts the third_party/tt-metal to the 795135f0c9fde96c4fed761e274cf8d5ca053247
- Add workaround to copy tt_stl optional_references header after metal commit 09aae44c70
- Follow up in https://github.com/tenstorrent/tt-mlir/issues/4601

Uplift third_party/tt-metal to 795135f0c9fde96c4fed761e274cf8d5ca053247 2025-08-21

---

test/python/golden/test_metal_dma.py

#4407 got merged on a rebase and I missed adding `pytestmark` to a file to denote frontends. This is a single line straightforward fix that repairs the functionality of the reporting infrastructure
`pytestmark` added to `test/python/golden/test_metal_dma.py`

Fix absence of `pytestmark` in new tests

---

.github/get-docker-tag.sh
CMakeLists.txt
env/CMakeLists.txt
env/patches/shardy_mpmd_pybinds.patch
lib/RegisterAll.cpp
python/CMakeLists.txt
test/python/golden/experimental/test_mpmd_ops.py
tools/builder/base/builder_utils.py
tools/builder/stablehlo/stablehlo_builder.py

Issue: https://github.com/tenstorrent/tt-mlir/issues/4427
This PR adds in mpmd build targets by modifying bazel build in shardy for MPMD directories. It also adds python bindings for the dialect (similar to shardy pybinds) under a patch file. It adds in experimental APIs in builder to build and create MLIR graphs with MPMD dialect. 
new builder APIS
```
def experimental_named_mesh_attr
def experimental_topology_attr
def experimental_user_origin_attr
def experimental_origin_attr
```
new builder utils
```
experimental_build_stablehlo_module
```
example test created
```
pytest -ssv /code/tt-mlir/test/python/golden/experimental/test_mpmd_ops.py
module {
func.func @multiple_meshes(%arg0: tensor<128x128xf32>, %arg1: tensor<128x128xf32>) -> tensor<128x128xf32> attributes {topology = …
```

#4427: Add MPMD shardy dialect build + generate pybinds and builder API support under experimental feature.

---

include/ttmlir/Target/TTMetal/types.fbs
lib/Target/TTMetal/TTMetalToFlatbuffer.cpp
runtime/lib/ttmetal/executor.cpp
runtime/lib/ttmetal/executor_utils.h

N/A
The TTMetal TTRT backend does not currently support DRAM interleaved buffers, and all DRAM buffers are assumed to be sharded. A partner wants to use DRAM interleaved buffers, and D2M will need to eventually support these buffers even if they are not the first choice.
- D2M memrefs are assumed to be DRAM interleaved if:
- the memory space is set to DRAM, and
- there is no `ShardLayoutAttr` (tt/ttcore.shard in the IR)
- For each DRAM interleaved buffer, create and serialize an `InterleavedBufferConfig` instead of a `ShardedBufferConfig` in `TTMetalToFlatbuffer`
- Modified the TTMetal flatbuffer schema to allow exactly one of `ShardedBufferConfig` or `InterleavedBufferConfig` for each serialized buffer
- Modified the TTMetal TTRT backend to check the type of `bufferConfig` in each buffer …

[D2M] Add Support for DRAM Interleaved Buffers in D2M Runtime

---

lib/Target/TTMetal/TTMetalToFlatbuffer.cpp

Eliminates crash stemming from flatbuffer including bogus CircularBufferConfig for sharded DRAM buffers

Generate null CircularBufferConfig for Sharded DRAM buffers

---

lib/Dialect/TTNN/Transforms/Passes.cpp
test/ttmlir/Dialect/TTNN/Transforms/ttnn_create_input_gens_0.mlir

Currently we are adding input generators for all top level functions including const-eval functions. After we run generators and lower to cpp we get below:
```cpp
::std::vector<::ttnn::Tensor> create_inputs_for_forward_const_eval_0() {
....
}
int32_t main() {
::std::vector<::ttnn::Tensor> v1 =
create_inputs_for_forward_const_eval_0();
::std::vector<::ttnn::Tensor> v2 = forward_const_eval_0(v1);
....
```
We have unnecessary definition and call to generator from `main` for each const-eval function. This PR skips processing of const eval functions for input generators.

Skip CreateInputGenerators for const eval funcs

---

include/ttmlir/Target/Common/types.fbs
include/ttmlir/Target/TTMetal/command.fbs
include/ttmlir/Target/TTNN/operations/ccl.fbs
include/ttmlir/Target/TTNN/types.fbs
lib/Target/TTNN/TTNNToFlatbuffer.cpp
runtime/include/tt/runtime/detail/ttmetal/ttmetal.h
runtime/lib/runtime.cpp
runtime/lib/ttmetal/CMakeLists.txt
runtime/lib/ttmetal/executor.cpp
runtime/lib/ttmetal/executor_utils.h
runtime/lib/ttmetal/meshshard_utils.cpp
runtime/lib/ttmetal/meshshard_utils.h
runtime/lib/ttmetal/runtime.cpp
runtime/lib/ttnn/operations/ccl/mesh_shard.cpp

[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/4640)
Current D2M runtime needs to support two things for multi-device computation.
1. Enable multi-device tensor in D2M runtime
2. Enable mesh_shard op in D2M runtime
This PR includes the support of multi-device tensor and mesh_shard operation support in D2M runtime.
This PR is the first one and following PR (#4641) will cover lowering of mesh_shard op in D2M pipeline. This feature depends on some ongoing changes in PR, so needed to be split into two PRs.
- Tests will be added once the D2M lowering of MeshShard op is enabled in following ticket https://github.com/tenstorrent/tt-mlir/issues/4641.

Enable multi-device tensor and mesh_shard op in D2M runtime

---

test/python/golden/test_ttir_ops_llmbox.py

None
Missed xfailing tests that were ND during last metal uplift PR #4609
Fails are showing up in unrelated CI runs for [[explorer uplift]](https://github.com/tenstorrent/tt-mlir/actions/runs/17317075464), [[D2M changes]](https://github.com/tenstorrent/tt-mlir/actions/runs/17307913600)
xfailed ND golden mismatches in builder tests
Failures are expected to be investigated as part of #4712 
- For ND validation, [[CI passes 5 times]](https://github.com/tenstorrent/tt-mlir/actions/runs/17321486198) after xfailing these tests

Mark ND builder test fails for matmul after metal uplift

---

include/ttmlir/Target/Common/types.fbs
include/ttmlir/Target/TTMetal/program.fbs
include/ttmlir/Target/TTNN/CMakeLists.txt
include/ttmlir/Target/TTNN/operations/generic_op.fbs
include/ttmlir/Target/TTNN/program.fbs
lib/Target/TTMetal/TTMetalToFlatbuffer.cpp
runtime/lib/ttmetal/executor_utils.h
runtime/lib/ttnn/runtime.cpp

[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/4519)
Definition of TTNN GenericOp Flatbuffer schema. Schema should align generic_op dialect definition and reflect ttnn proper and what's defined in `tt-metallium/program_descriptors`.
- new flatbuffer schema `TTNN/operations/generic_op.fbs`
- move `UnpackToDestMode` enum to `Common/types.fbs` and propagate changes through metal runtime
- `LOG_WARNING` in `ttnn/runtime.cpp` indicating generic_op runtime is not implemented yet
Follow up [issue/task](https://github.com/tenstorrent/tt-mlir/issues/4634) will be to implement the runtime for generic_op

TTNN Generic Op Flatbuffer schema

---

.github/CODEOWNERS

Moved catch-all TTIR Dialect codeowner lines (without changes) earlier in CODEOWNERs. 
The current CODEOWNERs effectively shadowed the rule to have `/test/ttmlir/Dialect/TTIR/generic/` owned by forge-developers-mlir-d2m.

Fix codeowners for D2M TTIR tests

---

runtime/lib/ttnn/operations/ccl/reduce_scatter.cpp
test/python/golden/test_ttir_llama_1x2_tp.py
test/python/golden/test_ttir_ops_llmbox.py
test/python/golden/test_ttir_ops_n300.py

closes #4712
`reduce_scatter_minimal_async` with a linear topology requires a `persistent_intermediate_buffer` that is twice the input tensor size.
Increased the persistent_intermediate_buffer size by 2×.
Fixes the low-PCC issue observed with new CCL op.

Double persistent_intermediate_buffer size for reduce_scatter_minimal_async

---

lib/Conversion/TTIRToTTIRGeneric/TTIRToTTIRGenericPass.cpp
lib/Conversion/TTIRToTTKernel/TTIRToTTKernelPass.cpp
runtime/include/tt/runtime/types.h
runtime/lib/ttmetal/executor.cpp
test/ttmlir/Silicon/TTMetal/n150/simple_constant.mlir

[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/4746)
Support lowering `ttir.constant` through the D2M flow.
- legalize `ttir.full` in `TTIRtoTTIRGenericPass`
- legalize `memref.global_op` and `memref.get_global_op` in TTIRtoTTKernelPass`
- fixed assert in runtime `executor.cpp`
- re-enabled `Silicon/TTMetal/n150/simple_constant.mlir` test to qualify changes

Support lowering constants through D2M

---

include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/OpModel/TTNN/MetalHeaders.h
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
lib/Dialect/TTNN/IR/TTNNOpModelInterface.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

#4198 
Added constraints for `ProdOp` and `ArgMaxOp`.
`getOpRuntime` for `ProdOp` is not supported because `"Writes are not supported during trace capture."`

Add constraints API for Prod and ArgMax

---

runtime/include/tt/runtime/detail/common/common.h
runtime/include/tt/runtime/detail/ttnn/ttnn.h
runtime/include/tt/runtime/detail/ttnn/utils.h
runtime/lib/ttnn/operations/CMakeLists.txt
runtime/lib/ttnn/operations/generic/generic_op.cpp
runtime/lib/ttnn/operations/generic/generic_op.h
runtime/lib/ttnn/program_executor.cpp
runtime/lib/ttnn/runtime.cpp
runtime/lib/ttnn/utils/utils.cpp

[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/4634)
Need runtime support for TTNN GenericOp
- Added `generic_op.cpp` with necessary conversions to create `ProgramDescriptor` and invoke the generic op
Follow up issue for E2E test: https://github.com/tenstorrent/tt-mlir/issues/4805

TTRT support for TTNN GenericOp

---

lib/Dialect/StableHLO/Transforms/UpdateGlobalToLocalShapes.cpp
test/ttmlir/Dialect/StableHLO/shardy/op_propagation_registry/slice.mlir

Issue: https://github.com/tenstorrent/tt-mlir/issues/4799
In shardy partitioner, we incorrectly use the output tensor shardings when updating the slice op attribute dictionary. We need to use the input sharding of this op, as well as update only the limit indices.

#4799: Fix bug when updating slice op attribute dictionary

---

lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
runtime/lib/ttnn/operations/eltwise/unary/unary.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
third_party/CMakeLists.txt

This PR uplifts the third_party/tt-metal to the 1c6f2b7a835ff8a9ca20d024cbf7e8cba4c53a69
- Replace accurate mode and update op model expected cbsize after tanh updated in metal commit e818062

Uplift third_party/tt-metal to 1c6f2b7a835ff8a9ca20d024cbf7e8cba4c53a69 2025-09-03

---

include/ttmlir/Dialect/TTNN/IR/TTNNOpsAttrs.td
include/ttmlir/Dialect/TTNN/Interfaces/TTNNKernelInterface.td
include/ttmlir/Target/Utils/MLIRToFlatbuffer.h
lib/Dialect/TTNN/IR/TTNNOpsAttrs.cpp
lib/Target/TTNN/TTNNToFlatbuffer.cpp

#4520 
Extend `translateTTNNToFlatbuffer` to support writing TTNNGeneric operation to Flatbuffer.
- Added `createOp` function for `GenericOp` op;
- Change `TTNN_CoreRangeAttr:$core_range` to `TTNN_CoreRangeSetAttr:$core_ranges`;
- Distinguish kernel `func.func`'s by the presence of `ttkernel.thread` attribute;
- Used `ttkernel::translateTopLevelKernelToCpp` to translate kernels to C++;
- Tested with `ttmlir-translate --ttnn-to-flatbuffer` and `ttrt read` the resulting Flatbuffers file for IR included in [D2M/TTNN Integration](https://docs.google.com/document/d/1SyJyK7yYPvMDzm0eBe89vrjhA5ZkIFc2_Lw2gOIarhY/edit?usp=sharing).

D2M: Support writing TTNNGeneric to Flatbuffer

---

runtime/tools/ttrt/test/test_d2m_perf_e2e.py

#4786 
We don't test the profiler e2e on d2m flatbuffers. This has left the profiler broken a bunch of times without us noticing. 
Add a ttrt pytest that will run the `ttrt perf` on a ttm flatbuffer, and then validate that there is coherent data in the tracy output files.

Add e2e pytest for d2m profiling flow

---

runtime/lib/ttnn/operations/ccl/reduce_scatter.cpp

partially resolve #4758
The argument `persistent_output_buffers` on `reduce_scatter_minimal_async`Op updated as `std::optional`.
We don't need to allocate intermediate/output persistent buffers.
Remove code blocks related to allocating persistent buffer for reduce_scatter_minimal_async from runtime.
Add descriptive comments about semaphores.

Remove hardcoded persistent buffer allocation code

---

lib/Dialect/TTIR/Transforms/GenericHWThreadSelection.cpp
lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp
test/ttmlir/Dialect/TTIR/generic/generic_hw_thread_selection.mlir

See https://github.com/tenstorrent/tt-mlir/issues/4621
In order to have fully streaming binary ops, we must merge >2 DMA regions onto 2 physical DMA regions we can implement on a BRISC/NCRISC pair.
- GenericHWThreadSelection has swapped positions in pipeline with GenericLowerDMAs
- DMA threads are merged _before_ lowering
- GenericHWThreadSelection merges all DMA regions according to following scheme
- First, input DMA regions are round-robin merged into DMA regions 0 and 1 to balance load
- Second, output DMA regions are always merged to ^datamovement1, to ensure they have access to NOC1
- **rationale**: Most streaming DMA writes will be to DRAM, where using NOC1 is very important to avoid congestion. Even if this results in two output threads sharing NOC1, that is still generally …

[D2M] DMA Region Merging

---

include/ttmlir/Dialect/TTKernel/IR/TTKernelOps.td
include/ttmlir/Dialect/TTKernel/IR/TTKernelOpsEnums.td
include/ttmlir/Dialect/TTKernel/IR/TTKernelOpsTypes.td
lib/Conversion/TTKernelToEmitC/TTKernelToEmitC.cpp
lib/Target/TTKernel/TTKernelToCpp.cpp
test/ttmlir/Conversion/TTKernelToEmitC/ttkernel.mlir

`unary_bcast_init` and `unary_bcast` ops are missing from `tt-mlir`.
Add broadcast a single tile from a CB. The tile is read from the CB and the broadcast result is stored in the provided DST register index. Broadcast along `rows` or `columns` or along both is supported.

Add `unary_bcast_init` and `unary_bcast_tile` ops

---

include/ttmlir/Dialect/TTCore/IR/TTCoreOps.td
include/ttmlir/Dialect/TTCore/Transforms/Passes.td
lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPass.cpp
lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
lib/Conversion/TTIRToTTNN/TTIRToTTNNPass.cpp
lib/Dialect/TTCore/Transforms/CMakeLists.txt
lib/Dialect/TTCore/Transforms/OptimizationBarrierFold.cpp
lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
test/ttmlir/Conversion/StableHLOToTTIR/optimization_barrier_op.mlir
test/ttmlir/Silicon/StableHLO/n150/optimization_barrier_op.mlir

Adding e2e (ttnn, ttir, and runtime) support for the `stablehlo.optimization_barrier` needed in training from` tt-xla`.
More details in: https://github.com/tenstorrent/tt-mlir/issues/4034
Fixes https://github.com/tenstorrent/tt-mlir/issues/4034

Adding support for stablehlo.optimization_barrier op

---

lib/Dialect/StableHLO/Utils/CMakeLists.txt
lib/Dialect/TTIR/Pipelines/CMakeLists.txt
lib/Dialect/TTNN/Transforms/CMakeLists.txt

N/A
Library dependencies were broken in multiple places. One example that exposes it is an `OptimizerTests` target in debug build mode. TBH, it's a miracle that we managed to get this far without catching it, but the two main reasons are:
- in release build `-ffunction-sections -Wl,--gc-sections` is used, so unused functions don't need to be resolved
- tools like `ttmlir-opt` and `ttmlir-translate` link all MLIR libraries

Fix library dependencies

---

tools/builder/base/builder_utils.py

The `ttir builder` does not produce TTIR dump for all test cases.
Pass  `test_base` to `build_ttir_module`.

[builder] pass test_base to build_ttir_module

---

lib/Dialect/TTNN/Analysis/L1InterleavedFallbackAnalysis.cpp
lib/Dialect/TTNN/Transforms/OptimizerPasses/Optimizer.cpp

When logging reasons for updates in L1IFA, some failing cases were unclear in the YOLO_v4 model.
Specifically, some `ttnn::toLayout` ops were added to `l1InterleavedLegalConfigs` but had no valid L1 Interleaved legal layout, so their map elements were empty.
This led to confusing update failures that were hard to locate.
The fix checks ahead and skips adding ops to the map if there are no configs for them.
An assertion is added when fetching configs to catch these cases early.
- No changes in behavior, just better code organization.
- No new/existing tests required, as this is a preventive change to make future errors easier to detect.

[L1IFA] Fix to skip empty config vector in relevant condition check

---

lib/OpModel/TTNN/TTNNOpModel.cpp
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp

Found bugs in OpModel lib where we missed that padding in pooling ops can be variant of array of 2 elements or array of 4 elements.

Fix padding in pooling ops to allow array of 4 elems

---

lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp

#4903 
This should've been affine LICM to begin with. It looked like the loop was removed, it was actually just fused :(
Replace affine loop coalescing pass w/ affine LICM pass.

D2M: replace affine loop coalescing w/ affine licm

---

lib/Dialect/TTNN/Analysis/L1InterleavedFallbackAnalysis.cpp

During recursive validation in L1 interleaved fallback analysis, `toLayoutOp` operations were causing failures because they have no valid configurations set in the OpModel system. Since `toLayoutOp` is inherently layout-agnostic and designed to handle any input layout, OpModel validation is unnecessary and inappropriate for these operations.
Added logic in `checkUpgradeToL1Interleaved` to skip OpModel validation for `toLayoutOp`. These operations are designed to handle layout transitions and don't impose constraints on their input layouts, making OpModel validation both unnecessary and problematic, so we upgrade the tensor based on producer's OpModel validation only.

[L1InterleavedFallbackAnalysis] Fixed error for toLayoutOp checking input tensor layout validity

---

README.md

https://github.com/tenstorrent/tt-forge/issues/327?issue=tenstorrent%7Ctt-forge%7C397
Add a DeepWiki badge to the TT-MLIR repo.
Grab the DeepWiki badge code from the DeepWiki Badge Maker and add it.

add deepwiki badge and deprecation note for tt-torch

---

docs/src/SUMMARY.md

The recently added doc for adding constraints/runtime APIs wasn't added to `SUMMARY.md`, so it wasn't properly built, which resulted in a broken link.

Fix doc link to constraints/runtime APIs

---

.github/Dockerfile.base

slack
Python installed is 3.11.0rc1 as it is install from ubuntu 22.04 repo
Fixed python installation to newest by fetching from deadsnakes apt repo

Fix python to be installed to fresh version 3.11

---

include/ttmlir/Conversion/Passes.h
include/ttmlir/Conversion/Passes.td
include/ttmlir/Conversion/TTNNToTTIR/TTNNToTTIR.h
include/ttmlir/Dialect/TTNN/Types/Types.h
include/ttmlir/Dialect/TTNN/Utils/Utils.h
lib/Conversion/CMakeLists.txt
lib/Conversion/TTNNToTTIR/CMakeLists.txt
lib/Conversion/TTNNToTTIR/TTNNToTTIRPass.cpp
lib/Conversion/TTNNToTTIR/TTNNToTTIRPatterns.cpp
lib/Dialect/TTNN/Utils/Utils.cpp
test/ttmlir/Conversion/TTNNToTTIR/binary_op.mlir
test/ttmlir/Conversion/TTNNToTTIR/skip_binary_op.mlir
test/ttmlir/Conversion/TTNNToTTIR/skip_unary_op.mlir
test/ttmlir/Conversion/TTNNToTTIR/unary_op.mlir

[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/4763)
Convert TTNN operations targged with `ttnn.hoist_generic_via_d2m` attribute to TTIR. Limit support to unary and binary element-wise operations. See [design doc](https://docs.google.com/document/d/1SyJyK7yYPvMDzm0eBe89vrjhA5ZkIFc2_Lw2gOIarhY/edit?tab=t.0).
- Add ConvertTTNNToTTIR pass;
- Add MLIR test for unary and binary op.

D2M/TTNN Integration: Convert TTNN to TTIR pass 

---

test/python/golden/conftest.py
tools/builder/base/builder_utils.py

There are a group of exception classes in builder utils to mark certain failure stages of tests that are needed for proper test reports. These have been reinstated to reraise any compilation errors that occur as these exceptions, so the test reported can pick up on them
A previous change removed these exceptions, breaking failure stage reporting
Exceptions have been re-added

Reinstate sentinel exceptions in builder

---

include/ttmlir/Dialect/TTIR/IR/TTIROps.td
include/ttmlir/Dialect/TTMetal/Pipelines/TTMetalPipelines.h
lib/Dialect/TTIR/IR/TTIROps.cpp
lib/Dialect/TTMetal/Pipelines/TTMetalPipelines.cpp
test/ttmlir/Conversion/TTIRToTTMetal/ttnn_metal_layout_cast.mlir

[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/4976)
Purely representational op that marks the conversion between ttnn and metal layouts.
- added `ttnn_metal_layout_cast_op`
- added `ttnn-mode` flag in `TTIRToTTMetalPipelineOptions`, where when true in one-shot-bufferize pass:
- no longer bufferize function parameters
- allow for unbufferized tensors (in this case, only `ttir.empty` with a ttnn layout attached)
- implemented `bufferize` 
- implemented basic `verifier`
- follow up issue to amend: https://github.com/tenstorrent/tt-mlir/issues/4977
- added mlir test case

D2M/TTNN Integration - `ttnn_metal_layout_cast` op

---

test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp

#4316 and [issue on metal](https://github.com/tenstorrent/tt-metal/issues/25772)
`getOpRuntime()` (sometimes in combination with `getOpConstraints()` )  hangs. We have used `resetInstance()` as a temporary workaround until issues are fixed on metal. We want to gradually remove these resets when tests can run without hangs.
Removed almost all `resetInstance()` from `TestOpModelLib.cpp` and `TestOpModelInterface.cpp`. Right now it seems only `Reshape` is causing an issue.
Ran CI tests 4 times. Offline testing with`--gtest_shuffle --gtest_repeat=2`.

Remove most device resets in OpModel tests

---

lib/Conversion/TTIRToTTIRGeneric/TTIRToTTIRGeneric.cpp
lib/Dialect/TTIR/Transforms/InsertDstRegisterAccess.cpp
test/ttmlir/Dialect/TTIR/Transforms/insert_dst_register_access_intermediate_results_thru_dst_in_place_intermediate.mlir

#5026 
If in a fused op, an intermediate op stored its results in place to dest register, it wouldn't be picked up by next op.
Check if op needs to allocate a new dest register or use the one already allocated.
Added a test to check these changes.

[D2M] Fused intermediate ops that store result in place use already allocated dest register tile

---

include/ttmlir/Conversion/TTNNToEmitC/EmitCConversion.h
include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/Target/TTNN/CMakeLists.txt
include/ttmlir/Target/TTNN/operations/tensor_serialization.fbs
include/ttmlir/Target/TTNN/program.fbs
lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
lib/Conversion/TTNNToEmitPy/TTNNToEmitPy.cpp
lib/Dialect/TTNN/IR/TTNNOps.cpp
lib/Dialect/TTNN/Interfaces/TTNNOpModelInterface.cpp
lib/Target/TTNN/TTNNToFlatbuffer.cpp
runtime/include/tt/runtime/detail/ttnn/ttnn.h
runtime/lib/ttnn/operations/CMakeLists.txt
runtime/lib/ttnn/operations/tensor_serialization/dump_tensor.cpp
runtime/lib/ttnn/operations/tensor_serialization/dump_tensor.h
runtime/lib/ttnn/operations/tensor_serialization/load_tensor.cpp
runtime/lib/ttnn/operations/tensor_serialization/load_tensor.h
runtime/lib/ttnn/program_executor.cpp
runtime/lib/ttnn/runtime.cpp
test/ttmlir/EmitC/TTNN/tensor_serialization/dump_load.mlir
test/ttmlir/Silicon/TTNN/n150/tensor_serialization/dump_load.mlir
tools/tt-alchemist/templates/cpp/local/ttnn-precompiled.hpp
tools/tt-alchemist/templates/cpp/standalone/ttnn-precompiled.hpp
tools/ttnn-standalone/ttnn-precompiled.hpp

https://github.com/tenstorrent/tt-mlir/issues/4965
https://github.com/tenstorrent/tt-mlir/pull/4909 has added a runtime support for these operations, but we need to model it on the TTNN dialect level. We have a use case for `load_tensor` in codegen paths.
Added support for these ops on the dialect level. In the runtime, I've added an implementation for ops execution that's unrelated to https://github.com/tenstorrent/tt-mlir/pull/4909, since these are pretty much direct calls to the `tt-metal` APIs.

Add `ttnn.load_tensor` and `ttnn.dump_tensor`

---

.github/Dockerfile.ird

None
GNU ftp server isn't stable and is causing CI failures.
Switch to the auto-select mirror url.
Also update GDB.

Update GDB and use GNU ftp mirror

---

include/ttmlir/Dialect/TTIR/IR/TTIRGenericRegionOps.td
lib/Conversion/TTIRToTTIRGeneric/TTIRToTTIRGeneric.cpp
lib/Conversion/TTIRToTTKernel/TTIRToTTKernel.cpp
test/ttmlir/Conversion/TTIRToTTIRGeneric/named_to_generic.mlir
test/ttmlir/Conversion/TTIRToTTKernel/get_dst_idx.mlir
test/ttmlir/Conversion/TTIRToTTKernel/single_tile_ops.mlir
test/ttmlir/Dialect/TTIR/Transforms/insert_dst_register_access_intermediate_results_thru_dst_in_place_intermediate.mlir
test/ttmlir/Silicon/TTMetal/n150/simple_eltwise.mlir

None
The FPU add/sub/mul ops are reading from the CBs and writing to the DST, makes it difficult/costly to fuse them even with other eltwise ops, blocking our op fusion & bcast work.
Switch to the SFPU variants, the FPU ones are still present in the TTKernel dialect, but are orphans now.
Fix an existing bug that leads to incorrect SSA ordering when the DST index is loop-dependent.
The comparison ops are decomposed into sub+cmpz, and will have two `init_sfpu` inserted. This is localized in the D2M comparison ops and is benign atm. The duplicates will be removed by the soon-to-land init hoisting work.

D2M: use SFPU for add/sub/mul

---

include/ttmlir/Dialect/TTCore/IR/TTCoreOpsTypes.td

We discovered that this interface shouldn't be applied to host layouts.

Remove DeviceLayoutInterface from HostLayoutAttr

---

include/ttmlir/Dialect/TTNN/Pipelines/TTNNPipelines.h
include/ttmlir/Dialect/TTNN/Transforms/Optimizer.h
include/ttmlir/Dialect/TTNN/Transforms/Passes.td
include/ttmlir/Dialect/TTNN/Validation/OpConstraintValidation.h
lib/Dialect/TTNN/Pipelines/TTNNPipelines.cpp
lib/Dialect/TTNN/Transforms/OptimizerPasses/OperationValidationAndFallback.cpp
lib/Dialect/TTNN/Transforms/OptimizerPasses/Optimizer.cpp
lib/Dialect/TTNN/Validation/OpConstraintValidation.cpp
test/unittests/Validation/TestOpConstraintValidation.cpp

This PR updates the default percentage of L1 memory considered usable in the Optimizer and related passes. Previously, the default was set to 80%; it is now increased to 100% (i.e., full L1 capacity). Specifically, both analyses in the Optimizer (L1IFA and MLA) now use the updated option value.
Additionally, the newer post-Optimizer validation pass now receives this usage cap as a pipeline option, rather than relying on a hardcoded value. This ensures that the validation logic aligns with the cap used in earlier passes. When the cap was set to 0.8, the validation pass would revert changes that utilized more memory, which significantly degraded performance for the Resnet model in particular. With the cap set to 1.0, such degradation is avoided, and performance improves.
While an …

Change default tensorL1UsageCap to 100% and Pass pipeline option cap to Validation pass

---

test/python/requirements.txt
tools/explorer/tt_adapter/src/tt_adapter/runner.py
tools/ttrt/requirements.txt

None
ttrt and tt-xla depend on different versions of pytorch.
Updating pytorch version in ttrt to the newer version tt-xla uses.
- Bump pytorch version from 2.5 to 2.7
- Update tt-explorer to run commands (ttrt, translate, opt) from mlir home dir for consistency

Bump pytorch version for ttrt and change explorer cmd path

---

include/ttmlir/Dialect/TTIR/IR/TTIROps.td
include/ttmlir/Dialect/TTNN/IR/TTNNOps.td
include/ttmlir/OpModel/TTNN/MetalHeaders.h
include/ttmlir/OpModel/TTNN/TTNNOpModel.h
include/ttmlir/Target/TTNN/operations/transformer.fbs
include/ttmlir/Target/TTNN/program.fbs
lib/Conversion/StableHLOToTTIR/StableHLOToTTIRPatterns.cpp
lib/Conversion/TTIRToTTNN/TTIRToTTNN.cpp
lib/Conversion/TTNNToEmitC/TTNNToEmitC.cpp
lib/Dialect/TTIR/IR/TTIROps.cpp
lib/Dialect/TTNN/IR/TTNNOps.cpp
lib/Dialect/TTNN/Interfaces/TTNNOpModelInterface.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
lib/Target/TTNN/TTNNToFlatbuffer.cpp
runtime/include/tt/runtime/detail/ttnn/ttnn.h
runtime/lib/ttnn/operations/CMakeLists.txt
runtime/lib/ttnn/operations/transformer/scaled_dot_product_attention.cpp
runtime/lib/ttnn/operations/transformer/scaled_dot_product_attention.h
runtime/lib/ttnn/operations/transformer/scaled_dot_product_attention_decode.cpp
runtime/lib/ttnn/program_executor.cpp
runtime/lib/ttnn/runtime.cpp
test/ttmlir/Conversion/StableHLOToTTIR/transformer/scaled_dot_product_attention.mlir
test/ttmlir/Conversion/StableHLOToTTIR/transformer/scaled_dot_product_attention_decode.mlir
test/ttmlir/EmitC/TTNN/transformer/scaled_dot_product_attention.mlir
test/ttmlir/Silicon/TTNN/n150/transformer/scaled_dot_product_attention.mlir
test/unittests/OpModel/TTNN/Lib/TestOpModelLib.cpp
test/unittests/OpModel/TTNN/Op/TestOpModelInterface.cpp
tools/ttnn-standalone/ttnn-precompiled.hpp

[#4265](https://github.com/tenstorrent/tt-mlir/issues/4265)
- We do not model `ttnn.transformer.scaled_dot_product_attention`
- We need this op to perform attention during prefill
- Bringup `scaled_dot_product_attention` through runtime, ttnn, ttir, and solo
- Add ttnn -> emitc conversion for op
- Add tests
- Also added sdpa decode shlo -> ttir tests

General SDPA op bringup

---

test/python/golden/test_ttir_ops.py
tools/builder/base/builder_golden.py
tools/builder/ttir/ttir_builder.py

#5099
TTIRBuilder ops currently use mixed argument styles - some DPS, some non-DPS.
Update dot_general, permute as non-DPS style.

TTIRBuilder - NonDPS style update - dot_general, permute

---

include/ttmlir/Dialect/TTCore/IR/TTCoreOpsTypes.td
test/ttmlir/Dialect/TTCore/tile_float_type_interface.mlir

The float type interface is introduced in order to support using the ttcore tile type in arith and math dialects, however, we don't currently need any upstream passes that reference this interface method hence we will leave it unimplemented for now.
Filed an issue for it's proper implementation if need be:
- #5124

Introduce FloatTypeInterface to ttcore.tile type

---

include/ttmlir/Target/TTMetal/program.fbs
lib/Dialect/D2M/Transforms/GenericRegionsToFuncs.cpp
lib/Target/TTMetal/TTMetalToFlatbuffer.cpp
runtime/include/tt/runtime/debug.h
runtime/lib/common/debug.cpp
runtime/lib/ttmetal/executor.cpp
runtime/lib/ttmetal/executor_utils.h
tools/ttrt/common/run.py

You can now specify somewhere to dump kernels to other than /tmp.
```bash
ttrt run --kernel-source-dir /my/path ...
```
You can also now use the location name (if it exists) as the kernel name.  This makes it possible to tag a particular kernel function with a location name and have the dumped artifact match exactly.

Custom load/store kernel dir

---

tools/tt-alchemist/templates/cpp/local/CMakeLists.txt

https://github.com/tenstorrent/tt-mlir/issues/5122
When trying to call:
```
tt-alchemist generate-cpp test/ttmlir/EmitC/TTNN/eltwise_binary/add.mlir --local -o add_cpp
cd add_cpp
./run
```
I'm getting a linking error:
```
[3/3] Linking CXX executable ttnn-local
FAILED: [code=1] ttnn-local 
: && /usr/bin/clang++ -O3 -DNDEBUG  CMakeFiles/ttnn-local.dir/ttnn-local.cpp.o -o ttnn-local -L/localdev/azecevic/tt-mlir/third_party/tt-metal/src/tt-metal/build/lib -Wl,-rpath,/localdev/azecevic/tt-mlir/third_party/tt-metal/src/tt-metal/build/lib  -ltt_metal  -ldevice  /localdev/azecevic/tt-mlir/third_party/tt-metal/src/tt-metal/build/lib/_ttnncpp.so && :
/usr/bin/ld: CMakeFiles/ttnn-local.dir/ttnn-local.cpp.o: undefined reference to symbol '_ZN4ttsl6detail4llvm15SmallVectorBaseIjE8grow_podEPvmm' …
```

Fix `tt-alchemist` solution linking error

---

tools/builder/base/builder_utils.py

While debugging a failing op in builder I had set the print_ir parameter to True but was not seeing the IR dump. This is because MLIR's IR printing happens at the C++ level and gets lost when the process crashes. So the only valid path to get IR is to provide `print_ir="/path/to/dir"` which prints IR to files. 
From MLIR docs:
> - IR printing is unsafe, e.g. when using `PassManager` with `PassManager.enable_ir_printing()` which calls thread-unsafe `llvm::raw_ostream`.
Sending the IR to a directory was not actually useful for my needs for debugging as a failing assert is not visible in that directory. Printing the IR to stdout was helpful but not always reproducible. I have added a note to this parameter to indicate its limited use for debugging IR.

adding more info on print_ir flag

---

runtime/lib/ttnn/operations/kv_cache/update_cache.cpp

Due to #1510, the update_cache op's updateIndex tensor must be returned to host and dissected to provide a uint32_t to TTNN.
This workaround does not work for a distributed tensor - for tensor parallel static cache update, the updateIndex may end up replicated across multiple devices, and ::ttnn::get_host_buffer explicitly asserts against this case.
This change uses the MeshComposer API to coalesce the replicated updateIndex into a single tensor and returns it to host. This continues to work if the updateIndex is not replicated as well.

Amend workaround for update cache op to extract a replicated updateIndex

---

include/ttmlir/Dialect/TTNN/Analysis/L1InterleavedFallbackAnalysis.h
include/ttmlir/Dialect/TTNN/Utils/Utils.h
lib/Dialect/TTNN/Analysis/L1InterleavedFallbackAnalysis.cpp
lib/Dialect/TTNN/Utils/Utils.cpp
test/ttmlir/Silicon/TTNN/n150/optimizer/l1_interleaved/simple_conv2d.mlir

This PR enhances the L1 interleaved fallback analysis by skipping reshape operation inputs/outputs that can be optimized to zero-cost view operations at runtime. The analysis now implements TTNN's reshape-to-view optimization logic to predict when reshapes would be converted to views if they stayed in DRAM, avoiding unnecessary L1 memory allocation for operations that didn't benefit from it or even caused perf degradation.
The new `checkReshapeSkip` function evaluates reshape operations using the same criteria as TTNN's runtime optimization:
- First checks if input and output tensors have identical shapes (no-op detection)
- For non-trivial reshapes, validates view optimization conditions:
- Last dimension preservation for memory layout compatibility  
- Memory layout consistency …

[L1InterleavedFallbackAnalysis] Improve perf by skipping L1 upgrades for reshape ops that can be optimized in runtime

---

lib/Dialect/D2M/Transforms/Allocate.cpp
test/ttmlir/Dialect/D2M/allocate/allocate.spill.mlir

Using mock stream buffer sizes of just 1 tiles exposes issues downstream that cause `test_metal_matmul.py` hangs
- Allocate.cpp logic has been reverted to invoke `device.getMemrefSizeBytes()` with shape equal to the data memref shape and making sure `includeBuffers` is set to `true` for buffer allocs (the latter got lost in a recent rebase on `main`)
- `test/ttmlir/Dialect/D2M/allocate/allocate.spill.mlir` has been disabled because no amount of spilling will make it pass when buffers are this large (2x the data size)
- [x ] New/Existing tests provide coverage for changes

reverting to sizing stream buffers the same as operand sizes

---

include/ttmlir/Dialect/TTCore/IR/TTCoreAttrInterfaces.td
include/ttmlir/Dialect/TTCore/IR/TTCoreOpsEnums.td
include/ttmlir/Dialect/TTCore/IR/TTCoreOpsTypes.td
include/ttmlir/Utils.h
lib/CAPI/TTCoreAttrs.cpp
lib/Conversion/D2MToTTMetal/D2MToTTMetal.cpp
lib/Conversion/TTIRToD2M/TTIRToD2M.cpp
lib/Dialect/D2M/IR/D2MOps.cpp
lib/Dialect/D2M/IR/D2MOpsInterfaces.cpp
lib/Dialect/D2M/Transforms/LowerToLayout.cpp
lib/Dialect/TTCore/IR/TTCoreOpsTypes.cpp
lib/Dialect/TTIR/IR/TTIROps.cpp
lib/Target/TTMetal/TTMetalToFlatbuffer.cpp
python/TTModule.cpp
test/python/golden/test_metal_dma.py
test/ttmlir/Dialect/D2M/bufferization/bufferization.mlir
test/ttmlir/Dialect/D2M/bufferization/view_map.mlir
tools/builder/base/builder.py
tools/builder/base/builder_utils.py

D2M x TTNN integration requires support for interleaved DRAM layouts (the only DRAM layout supported).
- A new layout attribute called `InterleavedLayoutAttr` conforming to `DeviceLayoutInterface` can be used as the layout attribute on a memref. 
- This behaves similarly to `ShardLayoutAttr`, but results in an interleaved-compatible affine map being generated by `DeviceAttr::getMemoryMap`
- Introduces a new interface in TTCoreAttrInterfaces called `BufferedDeviceLayoutInterface` that only InterleavedLayoutAttr and ShardLayoutAttr conform to
- Sole function in API is `getBuffers()` for now
- `MetalLayoutAttr` has a new enum parameter `TensorMemoryLayout` that closely matches the existing layout categorization used by TTNNLayoutAttr
- Layout can be either interleaved, width_sharded, …

[D2M] Interleaved DRAM layout support

---

runtime/include/tt/runtime/detail/ttnn/ttnn.h
runtime/include/tt/runtime/runtime.h
runtime/lib/runtime.cpp
runtime/lib/ttnn/runtime.cpp

Introducing function `bool hasLayout(Tensor t, Layout l)` to the runtime API. This function returns whether the provided tensor has the specified layout.
This is needed since the `toLayout()` function has a side-effect (dirtying of the tensor) regardless of whether or not the tensor is already in the correct (desired) layout - which affects the tensor cache for consteval. So, in FEs we would like to be able to know if the `toLayout()` is needed before we execute it - e.g. in scenarios where one tensor is used with multiple programs with different layouts.
Issue tenstorrent/tt-xla#953

[runtime] `hasLayout` API

---

lib/Dialect/TTIR/Transforms/TTIRFusing.cpp
lib/Dialect/TTNN/Transforms/TTNNFusing.cpp
lib/OpModel/TTNN/Conversion.cpp
lib/OpModel/TTNN/TTNNOpModel.cpp
test/ttmlir/Dialect/TTIR/fusing/relu6_fusing.mlir
test/ttmlir/Dialect/TTNN/fusing/conv2d_activation_fusing.mlir

[Link to Github Issue](https://github.com/tenstorrent/tt-mlir/issues/4631)
Mobilenet through torch-xla uses `minimum(relu(x), 6.0)` instead of a `relu6` op.
- Added `Relu6FusionPattern` that matches `minimum(relu(x), 6)` and converts to `relu6`
- Updated `TTNNConv2dWithActivation` to skip convs converted to matmul, as `relu6` is not supported for matmul in metal

Add fusing pattern for relu6

---

include/ttmlir/Dialect/TTCore/IR/Utils.h
lib/Dialect/D2M/IR/D2MOps.cpp
lib/Dialect/D2M/Transforms/Allocate.cpp

The stream layout previously didn't have a stringent enough verifier, which is now able to validate that shard shapes between the storage and the result type are equal.
There was one bit of fallout that was detected by an existing test `test/ttmlir/Dialect/D2M/allocate/generic_form_streams_matmul.mlir`. The subtest `matmul_multi_core_transpose` uses a view_layout op to transpose the input on the fly.  The allocator needed a small update to the stream_layout's storage memref type which must come from the post view's shape.  This is accomplished by reading the generic's operand type.

Update the stream_layout op's verifier

---

tools/ttrt/test/conftest.py

When running ttrt tests along with other tests it garbles tart-artifacts and make other tests fail.
Save existing ttrt-artifacts before test and restore after tests are finished.

Run ttrt tests with saving and restoring existing ttrt artifacts

---

include/ttmlir/Conversion/TTNNToEmitPy/EmitPyConversion.h
lib/Conversion/TTNNToEmitPy/TTNNToEmitPy.cpp

Part of https://github.com/tenstorrent/tt-mlir/issues/4930
The TTNNToEmitPy conversion pass was missing lowering patterns for many TTNN operations, preventing these operations from being converted to EmitPy dialect and subsequently to Python code. This limited the compiler's ability to generate executable Python code for a wide range of operations, including convolutions, pooling, normalization, slicing, and various element-wise operations.
Implemented comprehensive EmitPy conversion patterns for 20+ TTNN operations.

Adding emitPy op conversions

---

include/ttmlir/Dialect/D2M/Transforms/Passes.td
include/ttmlir/Dialect/TTNN/IR/TTNNOpsAttrs.td
include/ttmlir/Target/TTNN/operations/generic_op.fbs
lib/Conversion/D2MToTTNN/D2MToTTNN.cpp
lib/Dialect/D2M/Transforms/InsertStreams.cpp
lib/Dialect/TTNN/IR/TTNNOpsAttrs.cpp
lib/Target/TTNN/TTNNToFlatbuffer.cpp
runtime/lib/ttnn/operations/generic/generic_op.cpp
test/ttmlir/Conversion/D2MToTTNN/sanity.mlir
test/ttmlir/Dialect/D2M/allocate/allocate_cast.mlir

https://github.com/tenstorrent/tt-mlir/issues/5031
Right now for `ttnn-mode` we are always streaming both inputs and outputs since we can't alias buffers in the ttnn.generic op.
- wire the buffer pointer from `D2MToTTNN` pass to flatbuffer and mlir runtime the same way we pass tensor buffer address: as an index that will choose the correct tensor from `io_tensors`
- add `TTNN_KernelCBGlobalBufferAddressOfTensorAttr` to `TTNN_KernelCBAttr` as an optional
- add `KernelGlobalCBIndexOfTensor` to `generic_op.fbs`
- relevant changes to flatbuffer conversion and mlir runtime
- change `InsertStreams` pass to only insert streams for inputs that need to be streamed from DRAM.
- never stream output, but wired up `allowOutputSpilling` for the future when we could spill to DRAM.
- modified existing …

D2M/TTNN Integration - alias buffer in ttnn.generic op

---

lib/Conversion/TTNNToEmitPy/TTNNToEmitPy.cpp

Fixing lowering of concat_heads(decode) and nlp_create_qkv_decode into emitpy.

Fix emitpy lowering for llm ops
